Surface.fblits()
pygame-community/pygame-ce pull request #1831
Opened 2023-02-13 09:19 UTC by itzpr3d4t0r

2023-02-13 15:03 UTC, MyreMylar commented
looks like there is an actual linting fail here on `blit_test.py`. Needs a quick `black test/blit_test.py`.

2023-02-13 15:16 UTC, itzpr3d4t0r commented
> looks like there is an actual linting fail here on `blit_test.py`. Needs a quick `black test/blit_test.py`.

done

2023-02-16 00:19 UTC, Matiiss requested changes
Lovely idea, main function looks alright.

Mainly some minor inconsistencies in docs and names, also a possible issue with positional-only argument syntax in type stubs.

2023-02-16 00:19 UTC, Matiiss commented on test/blit_test.py
> +            print(f"Surface.fblits doreturn=0: {t1 - t0}")
"doreturn=0"?

2023-02-16 22:45 UTC, Matiiss commented on buildconfig/stubs/pygame/surface.pyi
> +            blend_flags: int = 0, /
Tested another branch with this syntax on 3.7.9 with mypy and it found no issues, the original issue I got this from was this: https://github.com/pygame/pygame/issues/3572

2023-02-17 07:45 UTC, Matiiss commented on buildconfig/stubs/pygame/surface.pyi
> +            blend_flags: int = 0, /
So, apparently I made some mistake while testing and this is in fact an issue still.

2023-02-17 10:11 UTC, itzpr3d4t0r commented on docs/reST/ref/surface.rst
> +      and a blend_flags parameter that applies to every surface being drawn. All surfaces are fully drawn.
basically in blits you can also pass a rect as "area" that defines which section of the original surface to draw. This isn't possible in fblits.

2023-02-17 10:26 UTC, itzpr3d4t0r commented on buildconfig/stubs/pygame/surface.pyi
> +            blend_flags: int = 0, /
no prob i removed that.

2023-02-17 11:15 UTC, itzpr3d4t0r commented
Don't merge this PR yet pls

2023-02-17 11:16 UTC, MyreMylar commented
> Don't merge this PR yet pls

I will not then :)

2023-02-17 11:17 UTC, itzpr3d4t0r commented
> > Don't merge this PR yet pls
> 
> I will not then :)

I'm doing refactors, adding comments and a change that should speed up gens but should be checked.

2023-02-19 23:21 UTC, Matiiss requested changes
Some minor docs stuff pretty much

2023-02-19 23:21 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +      fully(meaning that unlike `blit()` you cannot pass an "area" parameter to represent
there should be a space between "fully" and "("

2023-02-19 23:21 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +      object and dest is its destination position on this Surface. It draws each source surface
Inconsistencies with capitalizing Surface, it is not capitalized here at the end of the line

2023-02-19 23:21 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +      :rtype: None
Are both of these needed? Also for consistency rtype should also be in code quotes I guess or just remove the return type and just do ":returns: ``None``"? Just not sure if that "always" conditional is that necessary, or just leave ":rtype: ``None``"? It just feels a bit redundant IMO

2023-02-19 23:21 UTC, Matiiss commented on test/blit_test.py
> +            print(f"Surface.fblits: {t1 - t0}")
Oh, I suppose this was meant to be "Surface.fblits special_flags=0"?

2023-02-20 19:22 UTC, Matiiss approved these changes
LGTM, I ran the tests with prints and these single runs seemed a bit weird since python blits were almost always faster than fblits but I ran those functions multiple times in a loop in between the timers and there was about 33% of a speedup so that's nice 👍

2023-02-20 19:22 UTC, merged