transform.blur
pygame-community/pygame-ce pull request #1836
Opened 2023-02-13 09:28 UTC by yunline

# pygame.transform.blur

*This PR is cloned from [https://github.com/pygame/pygame/pull/3698](https://github.com/pygame/pygame/pull/3698).*

**2023-02-08T02:53:34Z** [yunline](https://github.com/yunline) wrote:
> # Add `blur` to transform module.
  > ```python
  > def box_blur(
  >     surface: Surface,
  >     radius: int,
  >     repeat_edge_pixels: Optional[bool] = True,
  >     dest_surface: Optional[Surface] = None
  > ) -> Surface: ...
  > 
  > def gaussian_blur( ... ) -> Surface: ...
  > def bokeh_blur( ... ) -> Surface: ...
  > ```
  > Inspired by #3659.
  > 
  > ![image](https://user-images.githubusercontent.com/31395137/216765287-551537bb-392e-4095-83f1-4c89266db11c.png)
  > ☑ Box Blur
  > ☑ Gaussian Blur
  > ☐ Bokeh Blur  

**2023-02-04T23:21:21Z** [novialriptide](https://github.com/novialriptide) wrote:
> Looks like you need to run `python setup.py format` to pass the linting test.  

**2023-02-06T01:41:11Z** [novialriptide](https://github.com/novialriptide) wrote:
> Blurring Better Call Saul is giving me weird results here... I'm not sure if this is normal
  > 
  > ### Result
  > ![image](https://user-images.githubusercontent.com/35881688/216862204-6a86c26f-e2cd-4b6d-8898-4b008c6d1ba9.png)
  > 
  > ### Original Image
  > ![maxresdefault](https://user-images.githubusercontent.com/35881688/216862632-73b64b42-b369-4f22-a310-3cb679e9b72a.jpg)
  > <details>
  > <summary>3d</summary>
  > 
  > ![saul-goodman-better-call-saul](https://user-images.githubusercontent.com/35881688/216862654-6dc2d6e4-ce25-4718-91d4-336f651913e8.gif)
  > 
  > </details>  

**2023-02-06T02:10:51Z** [yunline](https://github.com/yunline) wrote:
> > Blurring Better Call Saul is giving me weird results here... I'm not sure if this is normal
  > 
  > Fixed now, thanks for your testing.
  > ![image](https://user-images.githubusercontent.com/31395137/216866334-738cdcf3-e57f-4b03-8fd0-d7f09869b7d5.png)
  >   

**2023-02-06T03:52:35Z** [novialriptide](https://github.com/novialriptide) wrote:
> You can never go wrong with Saul's good looks. :)  

**2023-02-06T08:16:58Z** [yunline](https://github.com/yunline) wrote:
> > It takes about 220ms to process an image using this algorithm.
  > 
  > I optimized the algorithm and now it takes 75ms to process one image.
  > 
  > Image: 2048x2048 RGBA
  > CPU: AMD Ryzen7 6800H  

**2023-02-06T10:39:46Z** [itzpr3d4t0r](https://github.com/itzpr3d4t0r) wrote:
> I think that a blur function should be named depending on the blur algorithm it uses, so gaussian, bokeh etc.  

**2023-02-06T20:18:01Z** [yunline](https://github.com/yunline) wrote:
> New parameter `repeat_edge_pixels`
  > ![image](https://user-images.githubusercontent.com/31395137/217075438-517493c1-c7f6-4f22-97d0-5fbc75ee3cf0.png)  

**2023-02-08T02:50:03Z** [yunline](https://github.com/yunline) wrote:
> Gaussian blur √
  > ![image](https://user-images.githubusercontent.com/31395137/217415220-a22b746d-e600-4380-989e-96a4c4585d84.png)

2023-02-13 12:03 UTC, yunline commented
Relative issue #1796

2023-02-14 01:20 UTC, Matiiss requested changes
Looks great, some minor stuff should be fixed so the compiler doesn't complain, also docs and don't forget to run `python setup.py format` when you're done and before pushing so that the lint test can pass too.

2023-02-14 17:16 UTC, MyreMylar commented on buildconfig/stubs/pygame/transform.pyi
> +) -> Surface: ...
GitHub is telling me there is a missing new line here.

2023-02-14 17:20 UTC, MyreMylar reviewed
The most obvious thing missing is tests on the output of these two algorithms.

Tests would be particularly handy in this case as I expect a long term project we will embark on is to try and utilise SIMD techniques in the transform submodule in the same way we've been doing in the surface submodule. If we have tests verifying the output then a future SIMD version of these blurs would be able to test that what it is doing matches the current linear math version.

2023-02-17 18:44 UTC, oddbookworm commented
@yunline you should run `setup.py format` to pass the lint check

2023-02-19 23:38 UTC, Matiiss requested changes
Couple more doc and stub changes would be great

2023-02-19 23:38 UTC, Matiiss commented on buildconfig/stubs/pygame/transform.pyi
> +    repeat_edge_pixels: Optional[bool] = True,
It's just a `bool`, `Optional` means either `None` or the type given
`repeat_edge_pixels: bool = True`

2023-02-19 23:38 UTC, Matiiss commented on buildconfig/stubs/pygame/transform.pyi
> +    repeat_edge_pixels: Optional[bool] = True,
Same for this with `Optional`

2023-02-19 23:38 UTC, Matiiss commented on docs/reST/ref/transform.rst
> +   | :sl:`make surface blurry`
Based on other docs it should be sth like
"blur a surface using box blur"

2023-02-19 23:38 UTC, Matiiss commented on docs/reST/ref/transform.rst
> +   | :sl:`make surface blurry`
"blur a surface using gaussian blur"

2023-02-20 01:17 UTC, yunline commented on buildconfig/stubs/pygame/transform.pyi
> +    repeat_edge_pixels: Optional[bool] = True,
Done

2023-02-23 04:03 UTC, oddbookworm requested changes
Found a couple typos in the docs. Also, I noticed that the sample image `examples/data/lena.png` appears to be from the internet. I'd rather not deal with copyright infringement accusations, so can you point to the source you got the image from so we can look to see if it's fine to have in the repository?

2023-02-23 04:03 UTC, oddbookworm commented on docs/reST/ref/transform.rst
> +   Returns the blured surface using box blur algorithm.
typo, should be "blurred"

2023-02-23 04:03 UTC, oddbookworm commented on docs/reST/ref/transform.rst
> +   Returns the blured surface using gaussian blur algorithm.
typo, should be "blurred"

2023-02-23 04:48 UTC, yunline commented
> I'd rather not deal with copyright infringement accusations, so can you point to the source you got the image from so we can look to see if it's fine to have in the repository?

The lena.png is from https://github.com/mikolalysenko/lena.

2023-02-23 04:56 UTC, oddbookworm requested changes
Ok, I didn't realize this was a standard image in image processing. I'm fine with using it. Although I did stumble upon the [wikipedia](https://en.wikipedia.org/wiki/Lenna) entry, which states that the subject of the image does want the image to be retired and that the use of the image is now controversial. I'll approve it after the typo is fixed, but would like someone else to chime in on whether or not we should be using the image

2023-02-23 04:56 UTC, oddbookworm commented on docs/reST/ref/transform.rst
> +   Returns the blured surface using box blur algorithm.
this typo still exists

2023-02-23 05:01 UTC, yunline commented on docs/reST/ref/transform.rst
> +   Returns the blured surface using box blur algorithm.
sorry

2023-02-27 18:45 UTC, Matiiss approved these changes
LGTM
I tested with "peppers" (coloured) and "goldhill" images (courtesy of https://links.uwaterloo.ca/Repository.html) and it looked alright so I'm giving a greenlight for this. As for the image, I guess it can be changed to "peppers" since it's apparently the other commonly used test image and it's coloured too, so might as well use that instead I guess (or maybe "monarch").

Test code I used:
```py
import pygame


screen = pygame.display.set_mode((2000, 800))

color = pygame.image.load("my_tests/peppers3.tif").convert()
grayscale = pygame.image.load("my_tests/goldhill1.tif").convert()
print(grayscale.get_size())


# screen.blit(color, (0, 0))
# screen.blit(pygame.transform.box_blur(color, 10), (512, 0))
# screen.blit(pygame.transform.gaussian_blur(color, 10), (1024, 0))

screen.blit(grayscale, (0, 0))
screen.blit(pygame.transform.box_blur(grayscale, 10), (256, 0))
screen.blit(pygame.transform.gaussian_blur(grayscale, 10), (512, 0))

pygame.display.flip()

while not pygame.event.get(pygame.QUIT):
    pass
```

Output:
![image](https://user-images.githubusercontent.com/83066658/221654507-aba513dd-75c6-48e8-82a8-431a014dcdc8.png)
![image](https://user-images.githubusercontent.com/83066658/221654590-7688faf0-4077-4dcf-8762-70356559aa24.png)

2023-03-02 10:25 UTC, yunline commented
> I tested with "peppers" (coloured) and "goldhill" images (courtesy of https://links.uwaterloo.ca/Repository.html) and it looked alright so I'm giving a greenlight for this. As for the image, I guess it can be changed to "peppers" since it's apparently the other commonly used test image and it's coloured too, so might as well use that instead I guess (or maybe "monarch").

Sorry for missing your comment. The image is replaced now.

2023-03-04 15:12 UTC, MyreMylar approved these changes
LGTM 👍

2023-03-11 18:12 UTC, oddbookworm approved these changes
LGTM!

2023-03-11 18:13 UTC, merged