Surface.draw.polygons() function
pygame-community/pygame-ce pull request #1841
Opened 2023-02-13 09:35 UTC by itzpr3d4t0r

2023-02-15 06:25 UTC, MyreMylar commented
I'm pretty sure this one will be valuable for people wanting to draw polygons for 3D rendering (without using a GPU), but it could use a neat copy paste-able test program that shows how it is faster than a for loop of draw polygon.

Probably someone has already written a basic 3d model loading and drawing program we could adapt here.

2023-02-17 14:19 UTC, MyreMylar reviewed
As above. I want a convenient test program to compare old vs new.

2023-03-21 20:12 UTC, itzpr3d4t0r commented
@MyreMylar Could you re-review this PR? It changed a lot recently.

2023-04-27 08:49 UTC, Temmie3754 approved these changes
Code looks good to me and functions as expected on my system, thanks to the test I can confirm a consistent ~30% speedup for hollow polygons and ~20% for filled with no signs of memory leakage. Only change that is needed would be a versionadded comment for the docs for when its merged.

2023-05-29 09:09 UTC, MyreMylar requested changes
The speed up still works for me, looks like it got slightly faster 👍 

Apart from the little ordering mix-up pointed out in the line-by-line comments the main thing I also noticed that we haven't added this function to the draw tests.

For an example you can see what has been done for `draw.lines` by searching `draw.lines` and `draw_lines` in `draw_test.py`. Getting a bit of unit testing of this would be helpful in case somebody else decides to come and tweak it for performance later on and breaks something.

Great work!

2023-05-29 09:09 UTC, MyreMylar commented on docs/reST/ref/draw.rst
> +   :param draw_sequence: a sequence of (points, color, width) where:
```suggestion
   :param draw_sequence: a sequence of (color, points, width) where:
```

The original text appears to be wrong. The sequence is actually in the order:
`(color, points, width)`

2023-05-29 09:09 UTC, MyreMylar commented on docs/reST/ref/draw.rst
> +                 using a tuple ``(RGB[A])``
```suggestion
        - color: the color to draw the polygon with, the alpha value is optional if
                 using a tuple ``(RGB[A])``
                 
        - points: a sequence of 3 or more (x, y) coordinates that make up the vertices
                  of the polygon, each *coordinate* in the sequence must be a
                  tuple/list/:class:`pygame.math.Vector2` of 2 ints/floats,
                  e.g. ``[(x1, y1), (x2, y2), (x3, y3)]``
```

Swap the order of these explanations to match the correct sequence order.

2023-08-08 16:06 UTC, closed without merging