Added pg_IntFromObjEx(), pg_TwoIntsFromObjEx() and pg_IntFromSeqIndexEx()
pygame-community/pygame-ce pull request #1842
Opened 2023-02-13 09:38 UTC by itzpr3d4t0r

Added three new C API functions:
- pg_IntFromObjEx
- pg_IntFromSeqIndexEx
- pg_TwoIntsFromObjEx

2023-02-17 14:45 UTC, MyreMylar approved these changes
LGTM 👍 

I guess time will see if we get some good speed ups from these.

2023-02-18 11:16 UTC, MyreMylar commented
I get it going from (without this PR):

```
====||SEQUENCES||====
-) tup inside tup: 0.89526932 s
-) coll tup: 0.87893394 s
-) not coll tup: 0.8794718 s
-) coll list: 1.09282864 s
-) not coll list: 1.10122356 s
-) coll 2 args: 1.03318158 s
-) not coll 2 args: 1.06660838 s
-) coll unpack tuple 1->2: 1.11719524 s
-) not coll unpack tuple 1->2: 1.1178481 s
-) coll unpack list 1->2: 1.31008738 s
-) not coll unpack list 1->2: 1.24720098 s
______________
-) Mean time: 1.06725899

====||VECTORS||====
-) coll vector: 0.95589292 s
-) not coll vector: 0.90819832 s
______________
-) Mean time: 0.93204562
```

to (with this PR):

```
====||SEQUENCES||====
-) tup inside tup: 0.8181443 s
-) coll tup: 0.75252392 s
-) not coll tup: 0.74443626 s
-) coll list: 1.00662154 s
-) not coll list: 0.95291206 s
-) coll 2 args: 0.85712456 s
-) not coll 2 args: 0.85301936 s
-) coll unpack tuple 1->2: 1.01843844 s
-) not coll unpack tuple 1->2: 1.01575796 s
-) coll unpack list 1->2: 1.18465654 s
-) not coll unpack list 1->2: 1.18172594 s
______________
-) Mean time: 0.94412372

====||VECTORS||====
-) coll vector: 0.8472964 s
-) not coll vector: 0.85649714 s
______________
-) Mean time: 0.85189677

Process finished with exit code 0

```

Seems about 10% faster all over.

2023-03-21 14:54 UTC, itzpr3d4t0r commented
I'll be reverting the implementation in rect.collidepoint as an example because of the changes that were made to the rect module.

2023-08-08 09:29 UTC, MyreMylar approved these changes
I see no harm in adding these into the internal pygame API for other PRs and developers to use. In the previous example usage (now removed from this PR because of other changes to Rect) there was a demonstrated 10% performance improvement using these functions over current implementations.

If using them _doesn't_ turn out to provide a benefit long-term then developers won't use them and we could eventually clean them out of the developer API. Right now there seems to be a proven benefit and no change to our public facing API.

2023-08-18 16:14 UTC, yunline requested changes
Thank you for this PR. I have found some problems.

I use this test function:
```c
static PyObject*
int_cvt_test(PyObject* self, PyObject *arg) // METH_O
{   
    int val;
    if(!pg_IntFromObjEx(arg, &val, "This is an error msg.")){
        return NULL;
    }
    printf("Got value %d\n", val);
    Py_RETURN_NONE;
}
```
## Problems

-  ### `TypeError` if input object only has `__int__`

    A `TypeError` is raised if the input object has `__int__`or `__float__` method but doesn't have `__index__`method. (Such as `decimal.Decimal` and `fractionsFraction`)  
    <details>
    <summary>Code</summary>

    ```py
    class Num2:
        def __int__(self):
            return 1

    int_cvt_test(Num2())    # Should print "Got value 1"
    ```
    Current behavior:
    ```
    Traceback (most recent call last):
        File "x:\python\pygame_test\pgint.py", line 20, in <module>
            int_cvt_test(Num2())    # Got value 1
    TypeError: This is an error msg.
    ```
    </details>

    From python 3.10+, `PyLong_AsLong` would no longer use `__int__` to get the int value of object. This is the cause of the problem. In fact, this is also why you can't pass a float object to `PyLong_AsLong`.
    To check if object is able to be converted as int object, use [PyNumber_Check](https://github.com/python/cpython/blob/9bb576cb07b42f34fd882b8502642b024f771c62/Objects/abstract.c#L871).

- ### Some errors is still replaced with `TypeError`
    
    If any exception is raised inside of the `__index__()` method of the input object, a `TypeError` is always thrown out.
    <details>
    <summary>Code</summary>

    ```py
    class FooError(Exception):
        pass

    class Foo:
        def __index__(self):
            raise FooError("Fooooo.")

    int_cvt_test(Foo())    # Should raise "__main__.FooError: Fooooo."
    ```
    Current behavior:
    ```
    Traceback (most recent call last):
        File "x:\python\pygame_test\pgint.py", line 23, in <module>
            int_cvt_test(Foo())     # __main__.FooError: Fooooo.     
    TypeError: This is an error msg.
    ```
    </details>

    Those exceptions should have a higher priority than the customized `TypeError`.

- ### Float input should also be able to cause `OverflowError`

    <details>
    <summary>Code</summary>

    ```py
    int_cvt_test(1e44) # should raise OverflowError
    ```
    Current behavior:
    ```
    No error is raised.
    ```
    </details>

## Solution

I had written another version in #2405 before I found this PR.

In this version, you don't need to override any exception raised inside. (Override is not good)
Only when the input object can't pass the `PyNumber_Check`, will the `msg` argument be used.

I hope my code is helpful for you.

```c
static int
pg_IntFromObjEx(PyObject *obj, int *val, const char *msg)
{
    int tmp_val;
    PyObject *tmp_obj;
    SDL_bool do_decref = SDL_FALSE;

    if (PyLong_Check(obj)) {
        tmp_obj = obj;
    }
    else if (PyNumber_Check(obj)) {
        tmp_obj = PyNumber_Long(obj);
        if (!tmp_obj)
            return 0;

        do_decref = SDL_TRUE;
    }
    else {
        PyErr_SetString(PyExc_TypeError ,msg);
        return 0;  // Not a number type
    }

    tmp_val = PyLong_AsLong(tmp_obj);

    if (do_decref)
        Py_DECREF(tmp_obj);

    if (tmp_val == -1 && PyErr_Occurred()) {
        return 0;
    }
    *val = tmp_val;
    return 1;
}
```

2023-12-11 04:13 UTC, Starbuck5 commented
This PR is not ready for merge, so I'm marking it as a draft.

2024-02-29 00:45 UTC, yunline approved these changes
All problems I mentioned have been fixed. LGTM👍

2026-05-12 10:22 UTC, closed without merging