Translated README to Simplified Chinese.
pygame-community/pygame-ce pull request #1848
Opened 2023-02-13 10:06 UTC by yunline

![image](https://user-images.githubusercontent.com/31395137/218429021-1b4722cd-8b2b-4399-8cf8-c71203df24db.png)

2023-02-13 13:47 UTC, MyreMylar commented on readme/README_SC.rst
> +本发行版名为 **“pygame - Community Editio”** （简称 “pygame-ce”）。
missing an 'n' here at the end of **"pygame - Community Editio"**

2023-02-17 18:51 UTC, oddbookworm requested changes

2023-02-17 18:51 UTC, oddbookworm commented on readme/README_SC.rst
> +    :target: https://github.com/psf/black
All of these badges need to be retarged to `pygame-ce`. See the current README to look at how that's done. Also, the AppVeyorBuild badge needs to disappear because we are not using AppVeyor

2023-02-17 20:06 UTC, novialriptide commented
Can the file be renamed to `README.zh-cn.rst` to mimic this https://github.com/tiimgreen/github-cheat-sheet?

2023-02-18 04:59 UTC, oddbookworm commented
I see a problem in that the AppVeyor badge is gone, but it's not completely gone
![image](https://user-images.githubusercontent.com/49015102/219838842-936f416c-843a-4a2d-9841-d6bb7322f676.png)

2023-02-18 05:00 UTC, oddbookworm requested changes

2023-02-18 05:00 UTC, oddbookworm commented on docs/readmes/README.zh-cn.rst
> +|AppVeyorBuild| |PyPiVersion| |PyPiLicense|
The `|AppVeyorBuild|` part here is the cause of the problem I mentioned in my comment

2023-02-18 05:19 UTC, oddbookworm requested changes

2023-02-18 05:19 UTC, oddbookworm commented on docs/readmes/README.zh-cn.rst
> +刚接触pygame的初学者应该可以快速入门。pygame提供了大量教程与介绍，也提供了整个库的完整参考文档。你可以在 `docs page`_ 浏览文档。也可以在终端中运行``python -m pygame.docs``，在本地浏览文档。如果找不到本地文档，会自动打开在线文档。
One more small nitpick:
\`\`python -m pygame.docs\`\` -> \`python -m pygame.docs\`
(single set of backticks)

2023-02-18 05:19 UTC, oddbookworm commented on docs/readmes/README.zh-cn.rst
> +编译与安装的流程是高度自动化的。你要做的工作主要是pygame依赖的编译与安装。一旦完成，你就可以运行``setup.py``，它会尝试完成自动配置，编译，然后安装pygame。
same nitpick:
\`\`setup.py\`\` -> \`setup.py\`

2023-02-19 18:03 UTC, oddbookworm requested changes

2023-02-19 18:03 UTC, oddbookworm commented on README.rst
> +.. _简体中文: ./docs/readmes/README_SC.rst
This should be fixed since you renamed the other file

2023-02-23 04:10 UTC, oddbookworm commented
I'm honestly not sure how to review this. I can't read simplified chinese, so I can't vouch for the translation (not that I doubt it). The problem with that being inability to find errors and potential mistranslations. However, I did use google translate to get a rough approximation of the translation of this back into English and I was satisfied with the translated version. @Starbuck5 @MyreMylar @ankith26 I would appreciate some guidance on how to properly review this

2023-02-23 19:44 UTC, MyreMylar commented
> I'm honestly not sure how to review this. I can't read simplified chinese, so I can't vouch for the translation (not that I doubt it). The problem with that being inability to find errors and potential mistranslations. However, I did use google translate to get a rough approximation of the translation of this back into English and I was satisfied with the translated version. @Starbuck5 @MyreMylar @ankith26 I would appreciate some guidance on how to properly review this

My approach for translation PRs has been, like yours, to run them through google translate and just check if any rude swears come up (in case it is somebody trying to troll), but for the nuances of a language I don't speak I extend a certain amount of trust - assuming the PR otherwise seems genuine, and let the wider community act as the final guardians - because if a translation (or spelling or punction) is wrong, someone will come along and tell you about it pretty quick in my experience.

2023-02-24 05:24 UTC, oddbookworm approved these changes
Based on the conversation above and having read the version spat out from google translate back into English, I have no problem approving this (sorry, I only read and speak English)

2023-03-26 22:19 UTC, Starbuck5 approved these changes
I don't know how to have translations of things in a good way-- hand translations like this will struggle to stay up to date.

But this looks fine, so let's try it.

EDIT: probably should've done that as a squash and merge... but it'll be fine.

2023-03-26 22:19 UTC, merged