Suggested improvement to font_init
pygame-community/pygame-ce pull request #1853
Opened 2023-02-13 16:28 UTC by PurityLake

#1672 

This is a suggested solution to the Font class. It simply makes the font name and size arguments options with default values of "freesansbold.ttf" and 12 respectively.

This wouldn't be a breaking change as the default usual behavior still works, it just made the args optional instead of mandatory.

2023-02-14 14:31 UTC, MyreMylar reviewed
It seems like the first argument needs to nail down what it is called for this to work with keyword arguments

In the code it is called "font", in the typehints it is called "name", in the docs it is called "file_path".

2023-02-14 14:31 UTC, MyreMylar commented on src_c/font.c
> +static const int font_defaultsize = 12;
Should we make this default size a bit higher? The pygame default font is tiny at 12 (it comes out only about 6 pixels high for some reason):

![image](https://user-images.githubusercontent.com/13382426/218765350-14f386a8-43cf-4f8e-828e-09eca4923579.png)

This is it at 24 instead:
![image](https://user-images.githubusercontent.com/13382426/218765709-5e64a5b9-0f28-492d-a979-b8b335a6419e.png)

On the other hand, other fonts will be large at 24

2023-02-21 14:11 UTC, PurityLake commented
I will sort that out this evening

2023-02-21 18:43 UTC, PurityLake commented on src_c/font.c
> +static const int font_defaultsize = 12;
That is a good question, maybe 16 splitting the different between 12 and 24?

2023-02-23 04:24 UTC, oddbookworm requested changes
As Myre commented, the default font is super tiny at the default size
```
import pygame

pygame.init()

screen = pygame.display.set_mode((500, 500))

default_font = pygame.font.Font()
text1 = default_font.render("Hello World!", True, "red")

freesans_font = pygame.font.Font("freesansbold.ttf")
text2 = freesans_font.render("Hello World!", True, "red")

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            
    screen.fill("black")
    screen.blit(text1, (0, 0))
    screen.blit(text2, (0, 250))
    pygame.display.flip()
```
![image](https://user-images.githubusercontent.com/49015102/220821010-1aa33ec1-0acd-47f7-82b7-16a890a7e27c.png)

2023-02-23 04:24 UTC, oddbookworm commented on docs/reST/ref/font.rst
> +   be changed. If no arguments are given then the default font will be used and
Maybe add a note in the docs that the parameter name changed in 2.1.4?

2023-02-24 20:32 UTC, PurityLake commented on docs/reST/ref/font.rst
> +   be changed. If no arguments are given then the default font will be used and
I have added that detail now.

2023-02-24 20:33 UTC, PurityLake commented
I have updated the font size to 20, I feel 20 is quite big enough for it's purposes

2023-02-28 19:39 UTC, MyreMylar requested changes
Other than the type hints, this seems good.

Fix that and I will approve 👍

2023-02-28 19:39 UTC, MyreMylar commented on buildconfig/stubs/pygame/font.pyi
> +    def __init__(self, filename: Optional[FileArg], size: int) -> None: ...
```suggestion
    def __init__(self, filename: Optional[FileArg] = None, size: int = None) -> None: ...
```

2023-02-28 19:39 UTC, MyreMylar commented on buildconfig/stubs/pygame/font.pyi
> +    def __init__(self, filename: Optional[FileArg], size: int) -> None: ...
At the minute the type hints don't work because they are missing the default values.

2023-03-02 19:01 UTC, MyreMylar reviewed
Whoops looks like my last suggestion had the wrong default value for size, but upon reviewing I noticed it was still set to 12 all over the shop as well.

2023-03-02 19:01 UTC, MyreMylar commented on buildconfig/stubs/pygame/font.pyi
> +    def __init__(self, filename: Optional[FileArg] = None, size: int = None) -> None: ...
```suggestion
    def __init__(self, filename: Optional[FileArg] = None, size: int = 20) -> None: ...
```

2023-03-02 19:01 UTC, MyreMylar commented on src_c/doc/font_doc.h
> +#define DOC_PYGAMEFONTFONT "Font(filename=None, size=12) -> Font\nFont(filename, size) -> Font\nFont(pathlib.Path, size) -> Font\nFont(object, size) -> Font\ncreate a new Font object from a file"
```suggestion
#define DOC_PYGAMEFONTFONT "Font(filename=None, size=20) -> Font\nFont(filename, size) -> Font\nFont(pathlib.Path, size) -> Font\nFont(object, size) -> Font\ncreate a new Font object from a file"
```

2023-03-02 19:02 UTC, MyreMylar approved these changes

2023-03-02 19:09 UTC, MyreMylar commented on src_c/doc/font_doc.h
> + Font(filename=None, size=12) -> Font
```suggestion
 Font(filename=None, size=20) -> Font
```

2023-03-03 08:50 UTC, ankith26 commented on src_py/ftfont.py
> +    def __init__(self, file=None, size=-1):
shouldn't this be `size=20` too?

2023-03-03 13:20 UTC, PurityLake commented on src_py/ftfont.py
> +    def __init__(self, file=None, size=-1):
Yes it should, sorry, didn't think to change that

2023-03-04 12:13 UTC, MyreMylar commented on src_py/ftfont.py
> +    def __init__(self, file=None, size=-1):
```suggestion
    def __init__(self, file=None, size=20):
```

2023-03-04 22:35 UTC, oddbookworm approved these changes
LGTM!

2023-03-05 00:29 UTC, merged