Add docs status badge
pygame-community/pygame-ce pull request #1872
Opened 2023-02-16 07:31 UTC by novialriptide

2023-02-16 07:55 UTC, Starbuck5 commented
I don't really see the point of adding this sort of badge. It doesn't even link to the docs.

2023-02-16 20:25 UTC, MyreMylar commented
I guess we could make it link to the docs?

2023-02-16 20:25 UTC, MyreMylar requested changes
Make it link to the docs.

2023-02-23 04:28 UTC, oddbookworm submitted a review, later dismissed

2023-02-23 04:28 UTC, oddbookworm commented on README.rst
> +.. |DocsStatus| image:: https://img.shields.io/website?down_message=offline&label=docs&up_message=online&url=https%3A%2F%2Fpyga.me%2Fdocs%2F
should this target the docs so that clicking on the docs badge takes you there?

2023-03-04 15:04 UTC, MyreMylar commented on README.rst
> +
```suggestion
   :target: https://pyga.me/docs/
   
```

2023-03-04 15:06 UTC, MyreMylar commented on README.rst
> +|AppVeyorBuild| |DocsStatus| |PyPiVersion| |PyPiLicense|
```suggestion
|DocsStatus| |PyPiVersion| |PyPiLicense|
```

2023-03-04 15:07 UTC, MyreMylar commented on README.rst
> +|DocsStatus| |PyPiVersion| |PyPiLicense|
```suggestion
|DocsStatus| 
```

2023-03-04 15:08 UTC, MyreMylar approved these changes
LGTM 👍

2023-03-04 16:09 UTC, ankith26 approved these changes
Nice simple change, thanks! :cake:

2023-03-04 17:15 UTC, merged