Add "ABGR" format to pygame.image.fromstring
pygame-community/pygame-ce pull request #1875
Opened 2023-02-16 08:36 UTC by novialriptide

Ported from: https://github.com/pygame/pygame/pull/3674
Fixes: https://github.com/pygame/pygame/issues/3629

Looking at the SDL_PIXELFORMAT page (https://wiki.libsdl.org/SDL2/SDL_PixelFormatEnum), they have
```
SDL_PIXELFORMAT_RGBA32
SDL_PIXELFORMAT_ARGB32
SDL_PIXELFORMAT_BGRA32
SDL_PIXELFORMAT_ABGR32
```
Similarly, in pygame.image.fromstring, we support
```
RGBA
ARGB
BGRA
```
But with no `ABGR`

Somebody might need that support someday, and it seems like an obvious addition to what we support already.

2023-02-17 14:08 UTC, MyreMylar commented
Debian fail is:

```
====================================================================
  ERROR: test_frombuffer_ABGR (pygame.tests.image_test.ImageModuleTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/pygame/tests/image_test.py", line 1176, in test_frombuffer_ABGR
      argb_surf = pygame.image.frombuffer(abgr_buffer, (4, 4), "ABGR")
  pygame.error: Unknown pixel format
  
  ----------------------------------------------------------------------
  Ran 39 tests in 8.986s
  
  FAILED (errors=1, skipped=1)
  ----------------------------------------------------------------------
```

You might need to do something like this:

```
        try:
            # test if hardware supports ABGR surfaces
            pygame.Surface((64, 64), flags=pygame.SRCALPHA, masks=(0, 0xFF00, 0xFF0000, 0xFF000000))
        except pygame.error:
            pass
        else:
            argb_surf = pygame.image.frombuffer(abgr_buffer, (4, 4), "ABGR")
            self.assertEqual(argb_surf.get_at((0, 0)), pygame.Color(20, 10, 255, 200))
            self.assertEqual(argb_surf.get_at((1, 1)), pygame.Color(255, 255, 255, 127))
            self.assertEqual(argb_surf.get_at((2, 2)), pygame.Color(0, 0, 0, 79))
            self.assertEqual(argb_surf.get_at((3, 3)), pygame.Color(20, 200, 50, 255))
```

If I have those masks correct.

2023-02-20 05:52 UTC, novialriptide commented
> You might need to do something like this:

The Debian tests still fail when I insert that code into the tests. Also, I feel like that's a hacky sort of solution. There should be a better way.

2023-02-23 03:53 UTC, avaxar requested changes

2023-02-23 03:53 UTC, avaxar commented on src_c/image.c
> +        if (len != (Py_ssize_t)w * h * 4)
You haven't implemented the changes with the merging of #1863, implementing a `pitch` argument for every format.

2023-02-23 03:54 UTC, novialriptide commented on src_c/image.c
> +        if (len != (Py_ssize_t)w * h * 4)
Unfortunate

2023-03-01 17:26 UTC, closed without merging