Add `IS_CE` to constants
pygame-community/pygame-ce pull request #1900
Opened 2023-02-19 12:42 UTC by yunline

Issue: #1845

2023-02-19 12:45 UTC, yunline commented on buildconfig/stubs/pygame/__init__.pyi
> -from ._debug import print_debug_info as print_debug_info
Why are these changed???

2023-02-19 17:30 UTC, oddbookworm requested changes
In my testing, this worked great. `getattr(pygame, "IS_CE", False)` returned `True`. I think docs should be added for this feature however, which is the reason for the change request. Probably best to document it in https://github.com/pygame-community/pygame-ce/blob/main/docs/reST/ref/pygame.rst IMO

2023-02-19 18:07 UTC, MyreMylar commented
This also seems to be crashing the CI in the sphinx docs.

Perhaps we could just do a:

```
DEC_CONSTS(IS_CE, 1);
```

instead?

2023-02-20 02:07 UTC, yunline commented
> This also seems to be crashing the CI in the sphinx docs.
> 
> Perhaps we could just do a:
> 
> ```
> DEC_CONSTS(IS_CE, 1);
> ```
> 
> instead?

I doubt if the crash was caused by IS_CE.
And IS_CE should be a bool but DEC_CONSTS genetates an integer constant.

2023-02-20 17:26 UTC, MyreMylar approved these changes
Tested with:

```
import pygame


if getattr(pygame, "IS_CE", False):
    print("Running pygame CE")
else:
    print("Not running pygame CE")
```

And it works as it should.

2023-02-20 17:43 UTC, oddbookworm approved these changes
LGTM!

2023-02-20 17:43 UTC, merged