transform.grayscale and Color.grayscale
pygame-community/pygame-ce pull request #1907
Opened 2023-02-19 19:25 UTC by ScriptLineStudios

```python
pygame.transform.grayscale(surface: Surface, dest_surface: Optional[Surface] = None) -> Surface
pygame.Color.grayscale() -> Color
```

2023-02-22 07:55 UTC, Starbuck5 commented on docs/reST/ref/color.rst
> +      .. ## Color.grayscale ##
This needs a ..versionadded::2.1.4 tag.

2023-02-22 08:00 UTC, Starbuck5 commented on docs/reST/ref/color.rst
> +      Returns a Color which represents the grayscaled version of self using the luminosity formula which weights red, green and blue according to their wavelengths..
Rewrote this slightly for grammar and clarity:

> Returns a new Color object which represents the grayscaled version of self, using the luminosity formula, which weighs red, green, and blue according to their relative contribution to perceived brightness.

There should also be a space between the :sg: element and the description line. And the description lines shouldn't be more than 80 characters, you should break it if it's longer.

2023-02-22 08:00 UTC, Starbuck5 commented on docs/reST/ref/transform.rst
> +   .. ## pygame.transform.grayscale ##
This also needs a ..versionadded::2.1.4 tag.

2023-02-22 08:01 UTC, Starbuck5 commented on src_c/color.c
> +    {"grayscale", (PyCFunction)_color_grayscale, METH_VARARGS | METH_KEYWORDS,
Would this be METH_NOARGS since it only takes self?

2023-02-23 04:48 UTC, oddbookworm requested changes
I might be nitpicking here, but I'd like to see a couple of comments explaining why there are seemingly random numbers in the algorithm

2023-02-23 04:48 UTC, oddbookworm commented on src_c/color.c
> +        (Uint8)(0.299 * self->data[0] + 0.587 * self->data[1] +
This might be nitpicking, but I'd like to see some form of explanation here for why these specific numbers were used. Are they a standard thing somewhere? Maybe a comment would help giving an explanation for the existence of these "magic numbers"?

2023-02-23 04:48 UTC, oddbookworm commented on src_c/transform.c
> +            Uint8 grayscale_pixel = (Uint8)(0.299 * r + 0.587 * g + 0.114 * b);
Similar to my other comment, maybe just a quick explainer comment for these magic numbers

2023-02-23 05:00 UTC, Starbuck5 commented on src_c/color.c
> +        (Uint8)(0.299 * self->data[0] + 0.587 * self->data[1] +
It's from https://docs.opencv.org/3.4/de/d25/imgproc_color_conversions.html

2023-02-23 05:02 UTC, Starbuck5 approved these changes

2023-02-26 12:32 UTC, MyreMylar approved these changes
LGTM 👍 

I'm pretty sure we can do a couple of neat SIMD versions of this at some point in the future which should allow it to be used full screen in real time at a decent framerate for some fun desaturation effects.

2023-02-26 12:32 UTC, MyreMylar commented on docs/reST/ref/color.rst
> +      which weighs red, green, and blue according to their relative contribution to perceived brightness.
should "weighs" here be "weights" as in the other documentation?

2023-02-26 12:32 UTC, MyreMylar commented on src_c/color.c
> +        (Uint8)(0.299 * self->data[0] + 0.587 * self->data[1] +
You can also see these coefficients used as the PAL/NTSC ones in the 'luma coding' section of the wikipedia article on greyscale:

https://en.wikipedia.org/wiki/Grayscale

2023-02-28 19:44 UTC, MyreMylar commented
Moving this to 2.2 milestone.

2023-03-02 17:07 UTC, MyreMylar commented on docs/reST/ref/color.rst
> +      which weighs red, green, and blue according to their relative contribution to perceived brightness.
```suggestion
      which weights red, green, and blue according to their relative contribution to perceived brightness.
```

2023-03-04 07:24 UTC, merged