Rewrite stars.py
pygame-community/pygame-ce pull request #1909
Opened 2023-02-20 04:06 UTC by pycoinfu

Refactored the `stars.py` example: made it use OOP and less math; simplified the code

2023-02-20 04:12 UTC, pycoinfu commented
Just realized I forgot to bring the quote at the end back, not sure if it needs to be there though 😅

2023-02-20 05:04 UTC, yunline reviewed
Maybe define a class and pack `create_particle()`, `update_particles()` etc into it is better.
Like:
```python
class Particles:
    def __init__(self):
        self._particles=[]
        ...

    def create_particle(self, ... ):
        ...

    ...

    def mainloop(self):
        ...
```

2023-02-20 21:25 UTC, novialriptide requested changes

2023-02-20 21:25 UTC, novialriptide commented on examples/stars.py
> +pg.examples.stars
To stay consistent with the other examples, keep it like `""" pg.examples.stars`

2023-02-20 21:25 UTC, novialriptide commented on examples/stars.py
> +    """
Nitpick: I don't think this comment here is needed

2023-02-21 02:54 UTC, pycoinfu commented on examples/stars.py
> +    """
Thanks for the review 👍🏻

2023-02-21 05:23 UTC, novialriptide approved these changes
LGTM

2023-02-22 20:08 UTC, MyreMylar approved these changes
LGTM 👍 

I do have a couple of fun suggestions:

See below; adding some random colours to draw, and regaining the 'single pixel' look of the original by using draw line:
```
        self.colour_list = [(255, 210, 125),
                            (255, 163, 113),
                            (166, 168, 255),
                            (255, 250, 134),
                            (168, 123, 255)]

    def draw(self, display: pg.Surface):
        pg.draw.line(display, random.choice(self.colour_list),
                     self.pos, self.pos)
```

Also, add a density variable to make more stars:

```
        for _ in range(particle_densisty):
            create_particle(particles, spawn_point)
```

I liked a density of about 10.

2023-02-23 03:20 UTC, pycoinfu commented
> LGTM 👍
> 
> I do have a couple of fun suggestions:
> 
> See below; adding some random colours to draw, and regaining the 'single pixel' look of the original by using draw line:
> 
> ```
>         self.colour_list = [(255, 210, 125),
>                             (255, 163, 113),
>                             (166, 168, 255),
>                             (255, 250, 134),
>                             (168, 123, 255)]
> 
>     def draw(self, display: pg.Surface):
>         pg.draw.line(display, random.choice(self.colour_list),
>                      self.pos, self.pos)
> ```
> 
> Also, add a density variable to make more stars:
> 
> ```
>         for _ in range(particle_densisty):
>             create_particle(particles, spawn_point)
> ```
> 
> I liked a density of about 10.

Thanks for reviewing my PR 😄
I've implemented the suggestions, and it really does look better now!

2023-02-23 04:39 UTC, oddbookworm approved these changes
LGTM!

2023-02-23 04:40 UTC, merged