get_just_pressed and get_just_released
pygame-community/pygame-ce pull request #1912
Opened 2023-02-20 19:53 UTC by ScriptLineStudios

duplicate of my old pr - https://github.com/pygame/pygame/pull/3237

2023-02-26 17:22 UTC, oddbookworm requested changes
I'd be happy to approve this once you update the versionadded tags to 2.1.4

2023-02-26 17:22 UTC, oddbookworm commented on docs/reST/ref/key.rst
> +   .. versionadded:: 2.1.3
Should be 2.1.4

2023-02-26 17:22 UTC, oddbookworm commented on docs/reST/ref/key.rst
> +   .. versionadded:: 2.1.3
Should be 2.1.4

2023-03-08 08:46 UTC, robertpfeiffer commented
I really want this functionality merged, because it's something that exists in HaxeFlixel and Unity and everywhere. My main concern is what API/behaviour/guarantees this should give. I think as is, it wouldn't work in any of my games that get() different event types. I think the reset should only be triggered when `dopump` is true, or better yet, the reset code should live inside _pg_event_pump. You have my approval conditional on these changes.

I know this change will make the docs slightly more unwieldy, and I don't know how your code will interact with keyboard events introduced by pygame.event.post, but I think this is worth including now.

2023-03-12 16:59 UTC, MyreMylar reviewed
Updating the version strings

2023-03-12 16:59 UTC, MyreMylar commented on docs/reST/ref/key.rst
> +   .. versionadded:: 2.1.3
```suggestion
   .. versionadded:: 2.2.0
```

2023-03-12 16:59 UTC, MyreMylar commented on docs/reST/ref/key.rst
> +   .. versionadded:: 2.1.3
```suggestion
   .. versionadded:: 2.2.0
```

2023-03-13 03:32 UTC, oddbookworm approved these changes
LGTM!

2023-03-13 07:10 UTC, robertpfeiffer requested changes
I don't think resetting on pygame.event.get() only is a good idea, and resetting on pygame.event.get(pump=False) is a very bad idea. I think it should reset on calls to pump.

I like the idea in general, I like the API, but I think we need to talk about this a little more. I'd also be open to implementing the change myself.

2023-03-13 07:10 UTC, robertpfeiffer commented on src_c/event.c
> +            }
I think this should probably live in an event filter.

2023-03-13 07:10 UTC, robertpfeiffer commented on src_c/event.c
> +
And this should really live inside _pg_event_pump

2023-03-13 07:10 UTC, robertpfeiffer commented on src_c/key.c
> +
The external API looks good and sensible and I have no problem here

2023-05-15 07:08 UTC, Starbuck5 approved these changes
Directly pushed fixes for couple small issues I saw with it.

I like your changes @robertpfeiffer, this seems like a good use for an event filter.

This has got to be a record for the most people who've committed to a single PR branch?

2023-05-17 19:55 UTC, ankith26 commented on src_c/event.c
> +    SDL_FilterEvents(_pg_register_keys_just_pressed, NULL);
As a middle term goal, I'd like to move away from custom pump hacks (yes I know, my fault for putting some of it in the first place, but that was years ago at this point). I also had a WIP PR at some point to remove this function entirely (which I plan to revive at around SDL3 release time)

If this bit of code could be moved to the global event filter and still work as expected, that would be great. However not a PR blocker, I think.

As for why this should be a big deal, we are blocked on using stuff like `SDL_WaitEventTimeout` that implicitly call SDLs "vanilla pump". And `SDL_WaitEventTimeout` is a lot better than our current custom implementation (that is actually old SDL code - the newest actually waits for events, as opposed to repeated polling)

2023-05-17 19:56 UTC, ankith26 commented on src_c/key.c
> +    VIDEO_INIT_CHECK();
minor nitpick: This should be at the top of the function. If it's here, it leaks the tuple allocated above in the exit condition

2023-05-18 04:31 UTC, Starbuck5 commented
@ankith26 Thanks for taking a look at this.

About your reviews on this PR, you should push those changes directly. Scriptline seems busy right now, and more focused on their recent PRs. Plus, we've got a record to set with the committers on this branch!

2023-08-14 13:36 UTC, MyreMylar commented
This has developed a small conflict. Looks like it could be ready to go for 2.4.0 with a tiny bit of love as it already has three approvals.

2023-09-11 07:31 UTC, ankith26 requested changes
Some reviews (mostly notes to self) that I will address when I get back to this PR later today

2023-09-11 07:31 UTC, ankith26 commented on src_c/event.c
> +char released_keys[SDL_NUM_SCANCODES];
```suggestion
static char pressed_keys[SDL_NUM_SCANCODES] = { 0 };
static char released_keys[SDL_NUM_SCANCODES] = { 0 };
```

2023-09-11 07:31 UTC, ankith26 commented on src_c/key.c
> +get_just_pressed()
```suggestion
get_just_pressed(PyObject *self, PyObject *_null)
```

2023-09-11 07:31 UTC, ankith26 commented on src_c/key.c
> +get_just_released()
```suggestion
get_just_released(PyObject *self, PyObject *_null)
```

2023-09-11 07:31 UTC, ankith26 commented on src_c/key.c
> +        key_elem = PyBool_FromLong(pressed_keys[i]);
```suggestion
        key_elem = PyBool_FromLong(pressed_keys[i]);
        if (!key_elem) {
            Py_DECREF(key_tuple);
            return NULL;
        }
```

2023-09-11 07:31 UTC, ankith26 commented on src_c/key.c
> +        key_elem = PyBool_FromLong(released_keys[i]);
```suggestion
        key_elem = PyBool_FromLong(released_keys[i]);
        if (!key_elem) {
            Py_DECREF(key_tuple);
            return NULL;
        }
```

2023-09-11 16:37 UTC, ankith26 approved these changes
I have pushed some changes, and now this PR looks good to go for me.

I also wrote a little test script to validate that my changes don't break anything, here is it for anyone else interested in testing things out
```py
import pygame

win = pygame.display.set_mode((500, 500))

letters = [pygame.K_a + i for i in range(26)]

while True:
    cur_pressed = set()
    cur_released = set()
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            raise SystemExit

        if event.type == pygame.KEYDOWN:
            cur_pressed.add(event.key)

        if event.type == pygame.KEYUP:
            cur_released.add(event.key)
    
    for i in letters:
        if (i in cur_pressed) != pygame.key.get_just_pressed()[i]:
            raise RuntimeError(f"{i}")

        if (i in cur_released) != pygame.key.get_just_released()[i]:
            raise RuntimeError(f"{i}")

    pygame.time.wait(10)
```
Just run this script and spam letters randomly. There should be no error raised if the implementation is alright.

I'll wait for someone else to merge this PR though, because the last change (as of now) is mine

2023-09-16 04:38 UTC, Starbuck5 approved these changes

2023-09-16 07:14 UTC, merged