Color swizzling
pygame-community/pygame-ce pull request #1926
Opened 2023-02-22 19:13 UTC by ScriptLineStudios

Closes #1919

2023-02-22 21:21 UTC, gresm commented
Should color swizzling also support different color types like ``hsla`` or ``hsva``

2023-02-22 22:50 UTC, oddbookworm requested changes
This overall looks good, but there are some problems that keep it from compiling

2023-02-22 22:50 UTC, oddbookworm commented on src_c/color.c
> +                self->data[RED] = PyLong_AsLong(PySequence_GetItem(val, RED));
Compiler complains about implicit typecasting here, should cast to `Uint8`

2023-02-22 22:50 UTC, oddbookworm commented on src_c/color.c
> +                    PyLong_AsLong(PySequence_GetItem(val, GREEN));
see above about casting

2023-02-22 22:50 UTC, oddbookworm commented on src_c/color.c
> +                    PyLong_AsLong(PySequence_GetItem(val, BLUE));
see above about casting

2023-02-22 22:50 UTC, oddbookworm commented on src_c/color.c
> +                    PyLong_AsLong(PySequence_GetItem(val, ALPHA));
see above about casting

2023-02-22 22:50 UTC, oddbookworm commented on src_c/color.c
> +        Uint8 data[len];
This doesn't really work. Compiler tries to figure out what size this is at compile time, but fails and errors out

2023-02-22 23:40 UTC, oddbookworm commented on src_c/color.c
> +        Uint8 data[len];
I fixed it in my local, so here's what I did to get it to compile (you don't have to do it this way, but you can try it if you want):
```
    if (len == 3 || len == 4) {
        Uint8* data = malloc(sizeof(Uint8) * len);
        res = pgColor_New(data);
        ((pgColorObject *)res)->data[ALPHA] = 255;
        free(data);
    }
```

2023-02-23 20:12 UTC, gresm commented
It would be nice if there were some sort of macro helper functions in ``pgcompact.h`` (or more appropriate header file for that matter) for values swizzling? Why rewrite everything from scratch that was already written for vectors and colors when new class (like Rect) get value swizzling, when the idea is usually very similar?

2023-02-24 14:52 UTC, ScriptLineStudios commented
closing as discussed here: https://discord.com/channels/772505616680878080/772940667231928360/1078546221708349530

2023-02-24 14:52 UTC, ScriptLineStudios commented
closing as discussed here: https://discord.com/channels/772505616680878080/772940667231928360/1078546221708349530

2023-02-24 14:52 UTC, closed without merging