Implement FRect
pygame-community/pygame-ce pull request #1944
Opened 2023-02-26 10:26 UTC by yunline

- [x] Merge from https://github.com/pygame/pygame/pull/3230. 
- [x] Solve merge conflicts.
- [ ] Write tests.
- [ ] Fix bugs.

2023-02-27 05:19 UTC, pmp-p reviewed
why pgcompat.c instead of pgcompat_rect.c and an inclusion in rect.c ?

2023-02-28 07:07 UTC, pmp-p commented
FRect is still not correctly registered in static build

2023-02-28 07:43 UTC, pmp-p commented
need to include "pgcompat_rect.c" here and i think it's good https://github.com/pygame-community/pygame-ce/blob/b3f2781e521e7fdc80765a288b274c0165fb7b80/src_c/static.c#L196

2023-02-28 07:45 UTC, pmp-p requested changes
just need inclusion or pgcompat_rect.c in static.c

2023-02-28 11:17 UTC, yunline commented
Close and reopen to rerun the CI

2023-02-28 12:51 UTC, pmp-p approved these changes

2023-03-04 11:02 UTC, pmp-p approved these changes

2023-03-12 17:42 UTC, Emc2356 commented
love seeing this PR being continued

2023-03-12 18:05 UTC, MyreMylar commented
I think this will need a squash and merge.

2023-03-14 07:31 UTC, yunline commented
Close and reopen to rerun the CI

2023-03-14 07:31 UTC, yunline commented
Close and reopen to rerun the CI

2023-03-14 07:31 UTC, yunline commented
Close and reopen to rerun the CI

2023-03-15 08:04 UTC, Starbuck5 commented on src_c/rect.c
> +        PyFloat_FromFloat(self->r.h));
This memory leaks the python float objects, since they get created with a refcount of 1 and never get the refcount decremented.

Another location in pygame that has floats as part of the repr (`clock_str` in time.c) uses PyOS_snprintf. Maybe that's the way to go here?

Also I'm not sure where this got added it, but `PyFloat_FromFloat` is a weird macro to have-- It shouldn't be named as  a python macro if it's our thing and not a backcompat thing.

2023-03-15 08:11 UTC, Starbuck5 commented on src_c/include/_pygame.h
> +#include "../pgcompat.h"
Seems like a suspicious change

2023-03-15 10:15 UTC, yunline commented on src_c/include/_pygame.h
> +#include "../pgcompat.h"
https://github.com/yunline/pygame-ce/commit/4496f37e9e050a247e8c605b5f9d93d2db4b8189
It seems this is to solve a CI problem. I'll try to change it back。

2023-03-19 08:27 UTC, Starbuck5 commented on docs/reST/ref/rect.rst
> +since version 2.1.4 there is another class called FRect that serves the same
2.2

2023-03-19 08:45 UTC, Starbuck5 commented
I'm questioning the documentation strategy you've implemented for this. I see you changed it so the docs are in the normal "rect" module rather than the faux Rect "class module." But then in the new module documentation you only have documentation for "Rect," with FRect in a comment. If FRect is going to be in a comment anyway, why change the module structure?

My suggestion is to keep the docs structured the way they were before, add a nice `..versionchanged` comment in there, and add some "FRect" constructors into the Rect class `sg` or `sl` or whatever it's called.

2023-03-20 08:10 UTC, Starbuck5 approved these changes

2023-03-20 08:18 UTC, Starbuck5 commented
I'm not merging this just this second because
- I want to give it another day or two for reviews.
- Is there a good way to clean up the commit history? Squashing together related commits and things? Doing a squash and merge on this seems unfair to the amount of effort that went into the changes, and puts me as an equal author to yunline and Emc, which isn't fair. Nice squashes might be impossible because of merge commits in history?

2023-03-20 10:09 UTC, novialriptide commented
We should try rebasing this pull request first to remove the merge commits.

2023-03-20 21:35 UTC, dr0id approved these changes
LGTM (after a quick skim through the code)

2023-03-21 01:36 UTC, Starbuck5 commented
Rebasing something this old is pretty risky. I’m okay merging it as is.

2023-03-21 08:17 UTC, merged