`pygame.font.SysFont` - Warn user if no font was found
pygame-community/pygame-ce pull request #1973
Opened 2023-03-03 18:04 UTC by Sjmarf

See issue #1970 

When a non-existent font is passed to `pygame.font.SysFont`, Pygame uses a default font instead and doesn't raise an error. I've added a warning (not an error) that is shown when the user does this.
`The system font 'non-existent font' couldn't be found. Using the default font instead.`
`None of the specified system fonts (non-existent font, non-existent font2) could be found. Using the default font instead.`

The changes have been formatted with Black. Let me know if you would prefer a different error message, if if there's anything else you'd like me to change :)

Here's some test code:

```py
import pygame

pygame.font.init()

# Shows the following warning:
# The system font 'non-existent font' couldn't be found. Using the default font instead.
pygame.font.SysFont("non-existent font",40)
pygame.font.SysFont(bytes("non-existent font",'utf-8'),40)

# Shows the following warning:
# None of the specified system fonts (non-existent font, non-existent font2) could be found. Using the default font instead.
pygame.font.SysFont(("non-existent font","non-existent font2"),40)
pygame.font.SysFont((bytes("non-existent font",'utf-8'),"non-existent font2"),40)

# No warning is shown for any of the following:
pygame.font.SysFont("arial",40)
pygame.font.SysFont(("arial","comic sans"),40)
pygame.font.SysFont(("non-existent font", "arial"),40)
pygame.font.SysFont(bytes("arial",'utf-8'),40)
pygame.font.SysFont((bytes("non-existent font",'utf-8'), 'arial'),40)
pygame.font.SysFont(None,40)
```

2023-03-03 21:41 UTC, Matiiss commented
I feel like this should be implemented in the existing loop, if a font is not found, you just add it to a list and if it never `break`s out of the loop and enters the `else` block, then you just already have a list of fonts that you can add to the warning.

2023-03-03 22:07 UTC, Sjmarf commented
I'm working on some unit tests right now. 

Would your suggested change be faster though? We've already got a list of fonts, and if we fail to find _any_ of those fonts, we can just use that same list in the warning. Granted, I have to loop through the list again to convert `bytes` objects to `str`. But that extra loop only runs if none of the available fonts load - which only occurs in a small portion of cases.

2023-03-04 03:35 UTC, Python-ZZY commented
font.SysFont is not a good idea.
i think font.Font will be better because you dont have to worry the font wasnt found.
It supports a font file path as an argument and will throw an error if the font is not found

2023-03-04 08:14 UTC, Sjmarf commented
In the current implementation, `font.SysFont` uses a default font if the font isn’t found. Are you suggesting that we should make `font.SysFont` raise an error if the font isn’t found, instead of falling back to a default? That would cause back-compat issues, though…

2023-03-04 13:01 UTC, Sjmarf commented
@Matiiss I seem to remember you saying that Pygame should still warn the user if they pass a tuple of font-names, but some of the fonts couldn't be loaded. Currently, it only warns the user if _none_ of the fonts could be loaded. But now I can't see that comment anymore? Is that still the plan, or no? Or am I just remembering wrong? 

If not, then I don't see how your suggested change would be an improvement? We've already got a list of fonts, and if we fail to find any of those fonts, we can just use that same list in the warning. Granted, I have to loop through the list again to convert `bytes` objects to `str`. But that extra loop only runs if none of the available fonts load - which only occurs in a small portion of cases.

2023-03-04 19:03 UTC, Matiiss commented
> @Matiiss I seem to remember you saying that Pygame should still warn the user if they pass a tuple of font-names, but some of the fonts couldn't be loaded. Currently, it only warns the user if _none_ of the fonts could be loaded. But now I can't see that comment anymore? Is that still the plan, or no? Or am I just remembering wrong?
> 
> If not, then I don't see how your suggested change would be an improvement? We've already got a list of fonts, and if we fail to find any of those fonts, we can just use that same list in the warning. Granted, I have to loop through the list again to convert `bytes` objects to `str`. But that extra loop only runs if none of the available fonts load - which only occurs in a small portion of cases.

Yeah, I'm not sure what I was thinking yesterday... this should be fine I guess

2023-03-04 21:45 UTC, Sjmarf commented
Ah, no worries! Happens to us all sometimes 😄

2023-03-04 22:14 UTC, Sjmarf commented
I think I'm happy with my code now 👍

2023-03-05 00:02 UTC, Matiiss requested changes

2023-03-05 00:02 UTC, Matiiss commented on src_py/sysfont.py
> +                    f"None of the specified system fonts ({', '.join(name)}) "
Probably would be great if the font names could be also separated from the rest of the text by single quotes like so
```py
f"... fonts ('{'\', \''.join(name)}') "
```
so that it looks a bit neater and is a bit clearer

2023-03-05 00:02 UTC, Matiiss commented on src_py/sysfont.py
> +                    f"The system font {single_name} couldn't be "
Same here, but simpler I guess
```py
"... font '{single_name}' ..."
```

2023-03-05 14:42 UTC, Sjmarf commented on src_py/sysfont.py
> +                    f"None of the specified system fonts ({', '.join(name)}) "
Done 👍

2023-03-07 20:14 UTC, Matiiss approved these changes
LGTM, works as I'd expect 👍

2023-03-12 07:30 UTC, Starbuck5 commented on src_py/sysfont.py
> +        else:
So it looks like this block has different name parsing logic than the block above.

Perhaps the whole thing should be refactored so it parses into a list of string font names once, then looks through that list to try to find the font, then raises the warning with the names it has.

2023-03-16 11:42 UTC, Sjmarf commented on src_py/sysfont.py
> +        else:
Sure 👍

2023-03-18 15:06 UTC, dr0id commented on src_py/sysfont.py
> +                warnings.warn(
I wonder if the warning should be documented in the docs.

2023-03-18 15:09 UTC, dr0id reviewed
Should freetype also emit a warning if a font is not found?

2023-03-19 21:56 UTC, Sjmarf commented
> Should freetype also emit a warning if a font is not found?

My understanding was that the `freetype` SysFont just calls the `font` SysFont anyway - so I don't need to change anything over there. Correct me if I'm wrong, though.

2023-03-29 18:15 UTC, MyreMylar approved these changes
LGTM 👍

2023-03-29 18:16 UTC, merged