Change font.c to compare with SDL_ttf instead of SDL itself
pygame-community/pygame-ce pull request #1991
Opened 2023-03-06 02:06 UTC by simplyrohan

Fixes: #1987
Compares SDL_ttf version to 2.22.0, as requested by @Starbuck5.

2023-03-06 02:39 UTC, oddbookworm requested changes
The comment above the code should also be edited to be consistent with the change

2023-03-06 02:39 UTC, oddbookworm commented on src_c/font.c
>     So, this is a compat patch for that behavior
You should probably edit the comment just above to reflect the correction as well

2023-03-06 02:42 UTC, simplyrohan commented on src_c/font.c
>     So, this is a compat patch for that behavior
Done

2023-03-06 07:49 UTC, Starbuck5 commented on src_c/font.c
> +/*  There is a bug in SDL_ttf up to 2.22.0 (the current release version as of
2.22.0 is the next release version as of writing.

2023-03-08 02:40 UTC, simplyrohan commented on src_c/font.c
> +/*  There is a bug in SDL_ttf up to 2.22.0 (the current release version as of
I think I fixed this with my latest commit...

2023-03-08 02:44 UTC, oddbookworm commented on src_c/font.c
> +/*  There is a bug in SDL_ttf up to 2.22.0 (the current release version as of
No, the comment says that 2.22.0 is the current release, not the next minor release

2023-03-11 03:37 UTC, simplyrohan commented on src_c/font.c
> +/*  There is a bug in SDL_ttf up to 2.22.0 (the current release version as of
Alright, hope this wraps it up

2023-03-11 07:33 UTC, Starbuck5 approved these changes
Thanks!

2023-03-11 17:09 UTC, oddbookworm approved these changes
LGTM! Thanks for fixing my mistake 😅

2023-03-11 17:10 UTC, merged