Added keyword arguments to `Font.render`
pygame-community/pygame-ce pull request #2000
Opened 2023-03-08 01:53 UTC by PurityLake

Refers to #1990 

Added keyword argument options for the arguments in `Font.render`

2023-03-08 02:09 UTC, PurityLake commented
Oddly enough, despite the docs saying `wraplength` is an arg to `Font.render` it was never passed on to the C implementation.

Also the C implementation didn't receive the `antialias` argument.

2023-03-08 02:12 UTC, Starbuck5 commented
That’s not what ftfont is.
Ftfont is “font” on the freetype API.

2023-03-08 03:22 UTC, PurityLake commented
Ah apologies, will rectify that mistake

2023-03-10 08:02 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +         of the respective names.
version changed = 2.2.0

"all arguments can be passed by keyword arguments  of the respective names" is more grammatically correct.

Viewing kwargs notices in other places, it could be something like "2.2.0 now supports keyword arguments"

2023-03-10 08:08 UTC, Starbuck5 commented on src_c/font.c
> +                             "background", "wraplength", NULL};
If we're ever going to change these, now would be the time.

Fygame.freetype has `fgcolor` and `bgcolor` instead of `color` and `background` (As kwargs already).

Opinions?

2023-03-11 11:52 UTC, PurityLake commented on src_c/font.c
> +                             "background", "wraplength", NULL};
fgcolor/bgcolor would make more sense, yes. I can make that change and adjust the docs and other places the parameter names are mentioned

2023-03-13 20:15 UTC, MyreMylar approved these changes
LGTM 👍

2023-03-14 04:04 UTC, Starbuck5 commented on test/font_test.py
> +        # this test should only be run with FontTest not FtFontTest
Why? Ftfont should be changed so that you use the keywords with the same names.

2023-03-14 12:48 UTC, PurityLake commented on test/font_test.py
> +        # this test should only be run with FontTest not FtFontTest
Fair point

2023-03-18 14:32 UTC, dr0id requested changes
Thinking about the parameter names I find `color` and `background` more understandable than `fgcolor` and `bgcolor`. Reading this I would wonder what `fgcolor` is. 

Maybe `textcolor` and `backgroundcolor` would be nicer (but longer) and would need a change in Font and in Freetype.

2023-03-18 14:32 UTC, dr0id commented on docs/reST/ref/font.rst
> +      | :sg:`render(text, antialias, fgcolor, bgcolor=None, wraplength=0) -> Surface`
below in the text 
`The color argument is the color of the...`  

Update `color` it is now `fgcolor`.

2023-03-18 14:32 UTC, dr0id commented on docs/reST/ref/font.rst
> +      | :sg:`render(text, antialias, fgcolor, bgcolor=None, wraplength=0) -> Surface`
same for the 'bgcolor' change, in the text below `background` is still used.

2023-03-19 08:26 UTC, Starbuck5 commented
> Maybe textcolor and backgroundcolor would be nicer (but longer) and would need a change in Font and in Freetype.

We can't change freetype since it already has those as kwargs. What about `color` and `bgcolor` ?

2023-03-19 16:31 UTC, MyreMylar commented
> > Maybe textcolor and backgroundcolor would be nicer (but longer) and would need a change in Font and in Freetype.
> 
> We can't change freetype since it already has those as kwargs. What about `color` and `bgcolor` ?

`color` and `bgcolor` would match the names used in classic HTML tags.

2023-04-05 07:44 UTC, Starbuck5 commented
@PurityLake This looks to be nearly done, just needs a bit of sprucing up.

It seems we've come to a consensus on the kwarg names being `color` and `bgcolor`, so that needs to be updated in the docs/types/code/test.

The versionchanged needs to be updated to 2.3.0, since that's the next version now.

After those changes I think this is good to go.

2023-05-16 07:12 UTC, Starbuck5 commented on test/font_test.py
> +from pygame._freetype import STYLE_DEFAULT
Looks like an extraneous bit of some local test got included?

2023-05-16 07:15 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      | :sg:`render(text, antialias, color, bgcolor=None, wraplength=0) -> Surface`
You haven't updated `background`  in the description of the method below. It should be explaining the `bgcolor` argument now.

2023-05-17 03:20 UTC, Starbuck5 approved these changes

2023-05-17 03:21 UTC, merged