Fix issue with converting surfaces to 8 bit surfaces with palettes
pygame-community/pygame-ce pull request #2031
Opened 2023-03-17 14:08 UTC by Temmie3754

This resolves issue https://github.com/pygame/pygame/issues/2477 by checking if the new surface needs a palette and creating the default one for it if it does.

2023-03-18 01:16 UTC, yunline requested changes

2023-03-18 01:16 UTC, yunline commented on src_c/surface.c
> +                        SDL_AllocPalette(default_palette_size - 1);
`-1` here is not needed.

2023-03-18 01:16 UTC, yunline commented on src_c/surface.c
> +                                         default_palette_size - 1);
Also here.

2023-03-19 01:41 UTC, yunline approved these changes
LGTM

2023-03-19 16:08 UTC, MyreMylar commented on src_c/surface.c
> +                    format.palette = palette;
should we be using:
```
SDL_SetSurfacePalette()
```

here and then freeing our allocation with:

```
SDL_FreePalette()
```

?

2023-03-19 16:19 UTC, MyreMylar reviewed
Is there are chance you are leaking memory here for the all white palette? The SDL functions for setting the surface palette are careful to destroy/free (the functions have recently been renamed) any existing palettes before assigning a new one.

It looks like here you might potentially be just replacing the all white palette with the default palette leaving a dangling allocation for the old white palette.

On a wider scale it might be cool if this conversion function actually generated an appropriate 8 bit palette for the image being converted using something like the [Median cut](https://en.wikipedia.org/wiki/Median_cut) algorithm. See [here ](https://github.com/jkirkwin/gifgen/blob/master/palettize/median_cut.cpp) for one example. This would be beyond the scope of this PR though.

2023-03-19 23:43 UTC, Temmie3754 commented
Thanks for catching that, it does indeed look as if there is a memory leak, I'll work on fixing that.

2023-03-29 16:26 UTC, MyreMylar commented on src_c/surface.c
> +                    format.palette = surf->format->palette;
```suggestion
                    SDL_SetPixelFormatPalette(format, surf->format->palette);
```

2023-03-29 16:26 UTC, MyreMylar commented on src_c/surface.c
> +                    format.palette = palette;
```suggestion
                    SDL_SetPixelFormatPalette(format, palette);
```

2023-03-29 16:28 UTC, MyreMylar commented on src_c/surface.c
> +                    format.palette = palette;
Just added these suggestions to minimise risk of memory leaking on the format's _old_ palette.

2023-05-28 00:13 UTC, Starbuck5 commented on src_c/surface.c
> +                    format.Bmask, format.Amask))) {
Can't you use format.format here?

2023-05-28 00:15 UTC, Starbuck5 commented
This should get a unit test to make sure the issue doesn't regress in the future.

2023-06-03 17:52 UTC, Temmie3754 commented on src_c/surface.c
> +                    format.Bmask, format.Amask))) {
No since format.format doesn't get updated to match bpp and masks so it needs to get the correct enum value from the masks and bpp.

2023-06-03 18:29 UTC, Temmie3754 commented
Added a unit test

2023-06-05 05:54 UTC, Starbuck5 approved these changes
Thanks!

2023-06-05 05:55 UTC, merged