fixed banding bug with draw.circle
pygame-community/pygame-ce pull request #2032
Opened 2023-03-18 20:05 UTC by oddbookworm

When `draw.circle` is fed a circle centered to the left of the screen's left edge, a band appears across the entire screen. I tracked it to [this commit](https://github.com/pygame-community/pygame-ce/commit/046efe181375a9f0078f07c880ac7b2e304e0e01). I fixed the bug and added a test case to prevent regression.

Test code:
```python
import pygame

screen = pygame.display.set_mode((500, 500))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            
    screen.fill("black")
    pygame.draw.circle(screen, "white", (-1, 250), 10)
    pygame.display.flip()
```
Result on current `main`:
![broken](https://user-images.githubusercontent.com/49015102/226135338-1fe72cec-faec-4f38-89e1-227fd266351f.png)

Result after this PR:
![fixed](https://user-images.githubusercontent.com/49015102/226135411-ab255830-7114-4c04-9cdb-5619badc19e3.png)

2023-03-18 20:15 UTC, Matiiss requested changes
This needs a test for when center is greater than surface width so it doesn't make a trail to the left.

2023-03-19 11:09 UTC, dr0id commented on src_c/draw.c
`MIN(x, xmin)` on line 2045: xmin is always INT_MAX no? Can x be ever bigger than xmin?

2023-03-19 15:47 UTC, oddbookworm commented
> I assume the bug was introduced in [c88a1d8](https://github.com/pygame-community/pygame-ce/commit/c88a1d8f7b31099cec84dc5cb7aeebdada783e83). Or was it introduced by [ef2399e](https://github.com/pygame-community/pygame-ce/commit/ef2399ecfd7e5b1d2b4560458f6ec393b3a634fe)?

It was introduced in [c88a1d8](https://github.com/pygame-community/pygame-ce/commit/c88a1d8f7b31099cec84dc5cb7aeebdada783e83). If I go back one commit to [f5a7a9a](https://github.com/pygame-community/pygame-ce/commit/f5a7a9a0458b4452fa5f59aef5d39d5370228b41), then the problem does not appear

> Does your fix re-introduce the original problem described by @novialriptide in [pygame/pygame#3143](https://github.com/pygame/pygame/issues/3143)?

No. The behavior from novial's test code is exactly as expected. Pure black screen.

2023-03-19 16:15 UTC, oddbookworm commented on src_c/draw.c
You are correct. I removed the redundant logic associated with the `xmin` variable. Tests still pass on my local, performance isn't significantly affected in my testing, and everything still seems to work as expected.

2023-03-19 17:23 UTC, dr0id commented on test/draw_test.py
> +            # pixel at the center should be black, not white
suggestion: this comment would be helpful as assert message in case the test should fail ( assertion methods have a `msg=` in the kw args). This would remove the comment but still provide the information.

2023-03-19 17:36 UTC, dr0id approved these changes
LGTM

2023-03-19 17:38 UTC, dr0id approved these changes
LGTM

2023-03-19 17:51 UTC, MyreMylar approved these changes
LGTM 👍  fixes the issue and I can't see any other related issues with fully or partially offscreen circles.

2023-03-20 07:18 UTC, Matiiss approved these changes
LGTM 👍

2023-03-20 07:23 UTC, merged