pygame.window.Window
pygame-community/pygame-ce pull request #2070
Opened 2023-03-28 13:44 UTC by yunline

#2069

2023-04-02 02:11 UTC, novialriptide reviewed
I don't see anything that's out of the ordinary so far.

2023-04-02 02:11 UTC, novialriptide commented on buildconfig/stubs/pygame/window.pyi
> +    def set_icon(self,icon:Surface) -> None: ...
We should discuss having these as properties instead of getter/setter methods to make pygame-ce more "pythonic".

2023-04-02 02:11 UTC, novialriptide commented on src_c/window.c
> +    char *title = "pygame";
See review above.

2023-04-02 02:11 UTC, novialriptide commented on src_c/window.c
> +        "title", "size", "position", "fullscreen", "fullscreen_desktop", NULL};
In the docs, we should maybe find a better name for `fullscreen` and `fullscreen_desktop`? Even though these are the official names for SDL. 

My guess with the difference between `SDL_WINDOW_FULLSCREEN` and `SDL_WINDOW_FULLSCREEN_DESKTOP` is that `SDL_WINDOW_FULLSCREEN` acts as "Full Screen" while `SDL_WINDOW_FULLSCREEN_DESKTOP` acts as "Full Screen Windowed" like in Overwatch 2. Maybe name it like that? I'd like @Starbuck5's opinion.

2023-04-02 04:28 UTC, yunline commented on buildconfig/stubs/pygame/window.pyi
> +    def set_icon(self,icon:Surface) -> None: ...
#2091

2023-04-02 06:54 UTC, yunline commented on src_c/window.c
> +        "title", "size", "position", "fullscreen", "fullscreen_desktop", NULL};
Notice: `fullscreen` and `fullscreen_desktop` are now a part of `**flags`, they are removed from `kwids`.

2023-04-06 09:38 UTC, robertpfeiffer requested changes
I can't stress enough how much I appreciate the time you put into this, I just think we need to get this right before we release it.

Also the docs should probably be proofread by a native English speaker to make it sound less awkward.

2023-04-06 09:38 UTC, robertpfeiffer commented on docs/reST/ref/window.rst
> +   :param bool opengl: Create a window with support for an OpenGL context. You will still need to create an OpenGL context separately.
We have the option, when creating new API, to use an Enum or something like that.

2023-04-06 09:38 UTC, robertpfeiffer commented on docs/reST/ref/window.rst
> +   :param bool fullscreen: Create a fullscreen window using the window size as the resolution (videomode change).
This naming convention is unfortunate. I'd rather have the default fullscreen be the modern option, and

2023-04-06 09:38 UTC, robertpfeiffer commented on docs/reST/ref/window.rst
> +   :param bool fullscreen_desktop: Create a fullscreen window using the current desktop resolution
So this one would be just fullscreen, and the other would be hard_fullscreen or legacy_fullscreen.

2023-04-06 09:38 UTC, robertpfeiffer commented on docs/reST/ref/window.rst
> +   :param bool vulkan: Create a window with support for Metal.
Typo, this should be Vulkan first and then metal

2023-04-06 09:38 UTC, robertpfeiffer commented on docs/reST/ref/window.rst
> +
Needs warning about platform support?

2023-04-06 09:38 UTC, robertpfeiffer commented on docs/reST/ref/window.rst
> +
Needs warning because creating a window directly is preferred to mixing set_mode and window.

2023-04-06 09:38 UTC, robertpfeiffer commented on src_c/cython/pygame/_sdl2/video.pyx
> +    def from_window(cls,window):
Shouldn't this be a borrowed window then?

2023-04-06 09:38 UTC, robertpfeiffer commented on src_c/window.c
> +{
Will this clash with event handling in display.c or events?

2023-04-06 11:04 UTC, yunline commented on src_c/window.c
> +{
I think it won't
test code ↓
```python
import pygame
import sys

sf_disp=pygame.display.set_mode((640,480),pygame.RESIZABLE)
pygame.display.set_caption("display module")
win=pygame.window.Window("window module",position=(100,100),resizable=1)
sf_win=win.get_surface()
while 1:
    print("disp:%s  win:%s"%(sf_disp,sf_win))
    for event in pygame.event.get():
        if event.type==pygame.WINDOWCLOSE:
            sys.exit()
```

2023-04-06 11:09 UTC, yunline commented on src_c/cython/pygame/_sdl2/video.pyx
> +    def from_window(cls,window):
Should add a `is_new_window` attribute and modify the `destroy()`. Currently if the window is destroyed using video module, the `_window_list` in window module would not change. Gonna fix this later.

2023-04-06 12:58 UTC, robertpfeiffer commented on src_c/cython/pygame/_sdl2/video.pyx
> +    def from_window(cls,window):
What's the difference between your idea and using is_borrowed?

2023-04-06 12:59 UTC, robertpfeiffer commented
after this is merged, but before the next release, we'd need to make pygame.display aware of window

2023-04-06 13:02 UTC, yunline commented on src_c/cython/pygame/_sdl2/video.pyx
> +    def from_window(cls,window):
Solved

2023-04-06 13:24 UTC, yunline commented on src_c/cython/pygame/_sdl2/video.pyx
> +    def from_window(cls,window):
> What's the difference between your idea and using is_borrowed?

Window should be removed from `_window_list` after destroyed.
if we simply set the `is_borrowed` to True, when destroying the window, the window will still exist in _window_list but no longer usable.

2023-04-07 02:59 UTC, JiffyRob reviewed
Hello.  @robertpfeiffer You stated that you;d like a native English speaker to go over the docs.  Here I am!

To start with, in `docs/reST/ref/window.rst`:
 - `get_windows`:
   - The phrase "returns a tuple include all windows" is grammatically incorrect.  I'd recommend replacing "include" with "including"
   - On a similar vein, in the sentence "Notice the window created by display module will never present in the tuple until you use `Window.from_existing_window` to get the window object," you should add a "the" before "display module" and "be" before present.
   - In the Window class you should decide whether to add periods at the end of parameter descriptions.  I don't see periods in the other classes' parameters, but I don't know what policy is on that (or if there is one).
   - The above also applies to parameters of methods inside the `Window` class
   - In `Window.set_position`, you don't need the second "as" (though it can be left and still be valid English)
   - Does `Window.set_position` set the center of the screen or the top-left?  This is a general thing I'm noticing about these docs - there are not a lot of them, and a bit of fleshing out would probably be in order.
   - In `Window.get_surface` you might want to change "get" to "return".  That way it is consistent with `pygame.display.get_surface()` and more descriptive.
   - In `Window.get_foreign` you use `returns` instead of `get` or `return`.  Is there a standard for this, too?  I personally prefer this over "get" or "return", but consistency could be better...?
   - In `Window.get_wm_info` you can combine the first and second sentences.  Additionally, you might want to say "returns a dictionary with keys of ... and values of ..." or something similar, instead of talking about formatting later on.

2023-04-07 08:04 UTC, Starbuck5 requested changes
@yunline I've been happy to see your work on this module and this functionality, it's definitely important and cool.

That being said, I believe this is not the best approach to get this successfully developed and merged.

I see this as two (main) huge changes:
- Rewrite of the Window class from _sdl2.video into C
- New `window` module and API

As I learned in the past, when I rewrote _sdl2.video into C and no one would review the PR, making the PRs smaller is very important for the development process.

I think the best way to start with these changes is with "just" a rewrite of _sdl2.video.Window into C, emulating the exact behavior and API of the old class. Then we can do the fancy stuff, debating where Window goes, working on interop with display, adding new API.

Let me know what you think.

2023-04-15 22:13 UTC, narilee2006 commented
Will pygame.Window work? later?

2023-05-11 07:34 UTC, Starbuck5 commented
This PR is superseded for now by #2114.

But new features in this PR might want to be upstreamed later.

I'm converting this to a draft for now because this shouldn't be being reviewed right now. (B/c #2114 should be reviewed instead).

2023-06-19 06:56 UTC, Starbuck5 commented
@yunline Should this PR be closed?

2023-06-19 07:07 UTC, yunline commented
> @yunline Should this PR be closed?

ok

2023-06-19 07:07 UTC, closed without merging