Create Surface.get_frect method
pygame-community/pygame-ce pull request #2071
Opened 2023-03-29 05:38 UTC by durkisneer1

- Surface.get_frect()
- Implement FRect documentation

Fixes #2066

2023-03-31 11:34 UTC, Matiiss requested changes

2023-03-31 11:34 UTC, Matiiss commented on test/surface_test.py
Should add more tests for various keyword arguments to make sure those are set properly and test that the initial position is at (0, 0)

2023-03-31 11:46 UTC, novialriptide commented on test/surface_test.py
> +        self.assertEqual(frect.size, size)
small nitpick: maybe check if the position is also `(0,0)`.

2023-04-01 10:11 UTC, novialriptide commented on test/surface_test.py
> +        size = (16, 16)
instead of the size being integers, could you make them into floats instead?

2023-04-01 19:04 UTC, VantaTree commented on docs/reST/ref/surface.rst
> +      example would be ``mysurf.get_frect(center=(100, 100))`` to create a
make it: ``mysurf.get_frect(center=(100.0, 100.0))``  instead, might be better.

2023-04-02 01:58 UTC, novialriptide commented on test/surface_test.py
> +        size = (16.0, 16.0)
I meant something like `16.65` or something like that.

2023-04-05 07:51 UTC, Starbuck5 commented on docs/reST/ref/surface.rst
> +      :ref:`Surface.get_rect`
This reference doesn't work, it generates a warning when I build the docs. It would need to be a `:meth:` tag instead of a ref tag, had to see what other pygame doc rst did.

Iirc, this was supposed to be a link in the text `.get_rect()` above.  So replace \`\`.get_rect()\`\` with :meth:\`Surface.get_rect\`

2023-04-10 05:14 UTC, Starbuck5 approved these changes

2023-04-10 06:44 UTC, Matiiss commented on test/surface_test.py
Also test whether the correct exceptions are raised if, for example, `centre` is used instead of `center` or `aljdsfjdsa` instead of something sensible.

Test that using `center` actually sets the `center` of the rect properly.

2023-04-10 06:56 UTC, Matiiss approved these changes
LGTM, congrats on the first PR (otherwise, thanks for contributing again, much appreciated)

2023-04-10 06:57 UTC, merged