mouse.get/set_relative_mode()
pygame-community/pygame-ce pull request #2076
Opened 2023-03-30 08:04 UTC by yunline

Issue: #2073

2023-05-25 17:51 UTC, zoldalma999 commented on docs/reST/ref/mouse.rst
> +   SDL2 docs: *"While the mouse is in relative mode, the cursor is hidden,
Instead of just quoting the sdl2 docs, you should probably write up something that explains it. Or at least remove the part that mentions sdl. Most people will probably not know what it is, and this would just confuse them.

2023-05-25 17:51 UTC, zoldalma999 commented on docs/reST/ref/mouse.rst
> +   ``True`` will exit relative mouse mode.
The arg being named "enable" and passing in True to exit it seems weird. Probably naming it something like disable would be better

2023-05-25 17:51 UTC, zoldalma999 commented on src_c/mouse.c
> +    }
This would probably be cleaner as 
```c
int mode = PyObject_IsTrue(arg);
if (mode == -1) {
    return NULL;
}
```
and cast mode if there is a compiler warning

2023-05-26 00:26 UTC, yunline commented on docs/reST/ref/mouse.rst
> +   ``True`` will exit relative mouse mode.
But it says ‘Calling pygame.mouse.set_visible’, not calling this function.

2023-05-26 00:34 UTC, yunline commented on docs/reST/ref/mouse.rst
> +   SDL2 docs: *"While the mouse is in relative mode, the cursor is hidden,
Docs are copied from here https://github.com/pygame-community/pygame-ce/blob/e077dc7cd08be3b4f2946dc82aa603ab6573b0ef/docs/reST/ref/sdl2_video.rst?plain=1#L113-L128

2023-05-27 13:56 UTC, zoldalma999 commented on docs/reST/ref/mouse.rst
> +   SDL2 docs: *"While the mouse is in relative mode, the cursor is hidden,
I know that you copied it from there, I saw it. But I also think that this would be the proper place to change it, since you are moving the implementation anyway, especially since _sdl2.video docs are not final, while these ones are supposed to be.

2023-05-27 13:57 UTC, zoldalma999 commented on docs/reST/ref/mouse.rst
> +   ``True`` will exit relative mouse mode.
Right, I misread that. Thanks for pointing it out!

2023-05-30 00:47 UTC, yunline commented on docs/reST/ref/mouse.rst
> +   SDL2 docs: *"While the mouse is in relative mode, the cursor is hidden,
I removed "SDL". Is that ok?

2023-06-03 04:18 UTC, zoldalma999 commented on docs/reST/ref/mouse.rst
> +   SDL2 docs: *"While the mouse is in relative mode, the cursor is hidden,
Yep, thank you!

2023-06-03 04:19 UTC, zoldalma999 approved these changes
Looks good to me!

2023-10-08 18:54 UTC, MyreMylar requested changes
OK, so there are a couple of things that come up because `SDL_SetRelativeMouseMode()` also hides the cursor and locks the mouse to the window.

As the event grab also locks the key events to the window I think it is fine that `pygame.event.get_grab()` doesn't return true while the mouse is in relative mode. 

However - `mouse.get_visible()` really should be false while we are in relative mode as the mouse cursor is not visible and this function does nothing else.

Anyway, it would be an easy fix, except these functions just got updated in the main branch for SDL3 so:

1. Please merge main into this PR.
2. If still needed (as the functions might have changed) please change line 218 of `mouse.get_visible()` to something like:
```
result = (PG_CursorVisible() || SDL_GetRelativeMouseMode());
``` 

so that `pygame.mouse.get_visible()` returns False while in relative mode.

Test program:

```python
import pygame


display_surf = pygame.display.set_mode((1280, 800))
display_surf.fill((255, 255, 255))


pygame.init()

clock = pygame.time.Clock()

running = True

mouse_state_changed = False

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN and event.key == pygame.K_r:
            if pygame.mouse.get_relative_mode():
                pygame.mouse.set_relative_mode(False)
            else:
                pygame.mouse.set_relative_mode(True)
            mouse_state_changed = True

        if event.type == pygame.KEYDOWN and event.key == pygame.K_v:
            if pygame.mouse.get_visible():
                pygame.mouse.set_visible(False)
            else:
                pygame.mouse.set_visible(True)
            mouse_state_changed = True

        if event.type == pygame.KEYDOWN and event.key == pygame.K_g:
            if pygame.event.get_grab():
                pygame.event.set_grab(False)
            else:
                pygame.event.set_grab(True)
            mouse_state_changed = True

    if mouse_state_changed:
        print("mouse relative mode:", pygame.mouse.get_relative_mode())
        print("mouse visible:", pygame.mouse.get_visible())
        print("events grabbed:", pygame.event.get_grab(), "\n")
        mouse_state_changed = False

    pygame.display.flip()

    clock.tick(60)
```

2023-11-19 11:25 UTC, MyreMylar commented on src_c/mouse.c
> +    result = (PG_CursorVisible() || SDL_GetRelativeMouseMode());
```suggestion
    result = (PG_CursorVisible() && !SDL_GetRelativeMouseMode());
```

2023-11-19 11:36 UTC, MyreMylar approved these changes

2023-11-19 11:40 UTC, MyreMylar commented on test/mouse_test.py
> +        visible = pygame.mouse.get_visible()
```suggestion

    def test_set_relative_mode(self):
        """Tests that set_relative_mode hides the cursor."""
        pygame.mouse.set_visible(True)
        pygame.mouse.set_relative_mode(True)  # sets the mouse invisible
        visible = pygame.mouse.get_visible()
```

2023-11-19 11:57 UTC, MyreMylar commented on test/mouse_test.py
> +        self.assertEqual(pygame.mouse.get_relative_mode(), False)
```suggestion
    @unittest.skipIf(
        os.environ.get("SDL_VIDEODRIVER", "") == "dummy",
        "mouse.set_relative_mode requires non-null video driver",
    )
    def test_set_relative_mode(self):
        """Tests that set_relative_mode hides the cursor."""
        pygame.mouse.set_visible(True)
        pygame.mouse.set_relative_mode(True)  # sets the mouse invisible
        visible = pygame.mouse.get_visible()
        self.assertEqual(visible, False)
        pygame.mouse.set_relative_mode(False)  # sets the mouse visible
        visible = pygame.mouse.get_visible()
        self.assertEqual(visible, True)

    @unittest.skipIf(
        os.environ.get("SDL_VIDEODRIVER", "") == "dummy",
        "mouse.set_relative_mode requires non-null video driver",
    )
    def test_get_relative_mode(self):
        """Tests that get_relative_mode correctly reports the relative mode"""
        pygame.mouse.set_relative_mode(True)
        self.assertEqual(pygame.mouse.get_relative_mode(), True)
        pygame.mouse.set_relative_mode(False)
        self.assertEqual(pygame.mouse.get_relative_mode(), False)
```

2023-11-19 14:17 UTC, merged

2023-11-19 17:36 UTC, ankith26 commented on docs/reST/ref/mouse.rst
> +   .. ## pygame.mouse.set_relative_mode ##
I know I'm late and the PR has been merged already, but this is missing version added tags. Can open a new PR to fix this

2023-11-19 18:02 UTC, MyreMylar commented on docs/reST/ref/mouse.rst
> +   .. ## pygame.mouse.set_relative_mode ##
https://github.com/pygame-community/pygame-ce/pull/2573