Rect swizzling
pygame-community/pygame-ce pull request #2110
Opened 2023-04-10 09:04 UTC by ScriptLineStudios

Rect swizzling similar to Vector and Color swizzling

2023-04-12 01:52 UTC, oddbookworm requested changes

2023-04-12 01:52 UTC, oddbookworm commented on test/rect_test.py
> +            c.rr = (10.3421784, 10.3421784)
Another copy/paste error?

2023-04-12 01:52 UTC, oddbookworm commented on test/rect_test.py
> +            c.rgb = (256, 256, 256)
Copy/Paste error? `c` is a `Rect`, so it doesn't have these properties in the first place

2023-04-12 01:52 UTC, oddbookworm commented on docs/reST/ref/rect.rst
> +   the creation of new color objects with the corresponding swizzled attributes
copy/paste error? "color"

2023-04-12 01:52 UTC, oddbookworm commented on src_c/rect.c
> +    if (len == 4) {
Like with swizzling colors, I'm not a fan of having a different return type in special cases. I think it should just return a tuple even when 4 values are requested

2023-05-20 06:37 UTC, Matiiss commented on src_c/rect.c
> +    if (len == 4) {
For `Vector3` swizzling two values returns a `Vector2` though and three values return a `Vector3`, also despite them being different types they can both be iterated over, the only loss here is immutability (but Vectors have it very similar).

2023-06-20 06:55 UTC, Starbuck5 commented on test/rect_test.py
> +    def test_swizzle_get(self):
No test that a 4 element swizzle returns a Rect?

2023-06-20 07:01 UTC, Starbuck5 commented
I'm assuming you got most of the implementation by checking the vector code, that should be good. Before adding this, I'd like to hear a use case for why this should be added.

2023-08-14 13:45 UTC, MyreMylar commented
> I'm assuming you got most of the implementation by checking the vector code, that should be good. Before merging this, I'd like to hear a use case for why this should be added.

I'm also struggling to think of a reason I would use this. I guess flipping coordinates around with rectangles is just less common in game development? 

If anybody out there has a use case for this then I am totally open to hearing it.

2023-09-05 09:12 UTC, Matiiss commented
The only somewhat useful case I can think of would be if the swizzling returned a `pygame.Vector2` when swizzling two values. That way you could get the center of the rect as a vector like so:
```py
center_vec = rect.xy + rect.wh / 2
```
compared to
```py
center_vec = pygame.Vector2(rect.center)
```
So yeah... not a very strong argument, especially given that we could add `_v` attributes to the rects, like `center_v` that would achieve the same thing

2023-10-12 20:19 UTC, closed without merging

2023-10-12 20:20 UTC, MyreMylar commented
No clear uses cases for this, seem to have emerged. In a search I can't find any other game or graphic library that has added swizzling to geometry other than vectors I'm going to move that we close this PR. 

Thankyou for the work put into this @ScriptLineStudios, but I think it is not a good idea for us to add new functions that it seems like nobody will use as it just creates more code to maintain in the future and complicates the public API for pygame.

If I'm wrong, please re-open this with a compelling use case or demand for this feature and I'd be happy for it to go in.