vector2 support for Surface.get_at and set_at
pygame-community/pygame-ce pull request #2111
Opened 2023-04-10 14:36 UTC by ScriptLineStudios

the ability to use vector2's to specify coordinates for surface set_ats and get_ats

2023-04-12 01:33 UTC, oddbookworm requested changes
I think you should edit the typestub info in [buildconfig/stubs/pgyame/surface.pyi](https://github.com/pygame-community/pygame-ce/blob/main/buildconfig/stubs/pygame/surface.pyi) so that linters don't throw a fit when using a `Vector2` in these methods. Also, adding documentation for this new functionality would be a good idea IMO. Maybe make sure to mention that any floating point values will be truncated, not rounded

2023-04-15 21:45 UTC, novialriptide commented
`Vector2`s are not `Sequence[int]` as @oddbookworm has mentioned. I'm not entirely sure if this PR should go through as stuff like this becomes valid.
```python
import pygame
a = pygame.Surface((50,50))
a.set_at(pygame.Vector2(50,50.5), (25,25,25))
a.set_at((50,50.5), (25,25,25))
```
whereas before, this would've thrown an error
```python
import pygame
a = pygame.Surface((50,50))
a.set_at((50,50.5), (25,25,25))
```
```
TypeError: 'float' object cannot be interpreted as an integer
```
If we favor introducing this, we can mention in the docs that we now support float values for `get_at()` and `set_at()`.

2023-04-15 21:56 UTC, narilee2006 commented
I agree

2023-04-18 04:53 UTC, Starbuck5 commented
> this got me thinking that I'm not entirely sure if this PR should go through as stuff like this becomes valid

Many things in pygame support floats now, and didn't always. Transform.scale used to need integer dimensions, for example. I think it's perfectly fine to have integer things accept floats and just truncate them.

But you're right, this can be documented and hinted as support for a 2-sequence of floats.

2023-04-19 03:59 UTC, Starbuck5 commented on src_c/surface.c
> +                     "position must be a sequence containing 2 integers");
Not really, since they can be floats.

`position must be a sequence of two numbers` ?

2023-04-30 08:32 UTC, Starbuck5 commented on src_c/surface.c
> +                     "position must be a sequence containing 2 integers");
Missed this one with the `position must be a sequence of two numbers` action.

2023-04-30 08:36 UTC, Starbuck5 commented on buildconfig/stubs/pygame/surface.pyi
>      def get_at_mapped(self, x_y: Sequence[int]) -> int: ...
I don't think this is right.

In the code get_at_mapped is changed too. Also it's not just a sequent of ints or a Vector, it supports floats. See how `transform.scale` hints itself. It uses https://github.com/pygame-community/pygame-ce/blob/main/buildconfig/stubs/pygame/_common.pyi#L18

2023-04-30 09:00 UTC, Starbuck5 commented
Also I'm curious what kind of performance impact this has. on get_at/set_at.

2023-05-25 07:50 UTC, Starbuck5 commented on docs/reST/ref/surface.rst
> +      .. note:: Any floating point values given in the specified pixel coordiante will be truncated.
I feel like it's much important to say that it supports floats now than the specific way it gets from floats to ints.

I would just give it a `versionchanged:: 2.3.0 now can accept float coordinates (and hence Vectors2)` or something.

2023-05-25 07:51 UTC, Starbuck5 commented on buildconfig/stubs/pygame/surface.pyi
> +    def set_at(self, x_y: Union[Tuple[float, float], Sequence[float], Vector2], color: ColorValue) -> None: ...
Rather than copy the value of the Coordinate value I linked, you can import it into the type stub file and use it here directly, like how the Surface typestubs do it.

2023-05-25 07:52 UTC, Starbuck5 commented on docs/reST/ref/surface.rst
> +      either be given as Sequence or as a Vector2. If the Surface has no per
"The pixel can either be given as Sequence or as a Vector2"

Vector2s are sequences
Also I don't think the average person reading these docs knows what a sequence is

I would drop this sentence addition.

2023-06-05 18:27 UTC, ScriptLineStudios commented on src_c/surface.c
changed it :+1:

2023-07-01 04:27 UTC, Starbuck5 commented on buildconfig/stubs/pygame/surface.pyi
> +from pygame.math import Vector2
Now that you're using Coordinate this Vector2 is an unneeded import?

2023-07-01 04:29 UTC, Starbuck5 commented on docs/reST/ref/surface.rst
> +      .. versionchanged:: 2.3.0 now can accept both float coordinates and Vector2s
2.3.1 now (several other locations too)

2023-07-01 04:32 UTC, Starbuck5 commented on docs/reST/ref/surface.rst
> +      If the pixel position is outside the area of the Surface an
Since these have the same content there shouldn't be a change in the diff.

2023-07-01 04:41 UTC, Starbuck5 commented on src_c/surface.c
> +        return RAISE(PyExc_ValueError, "Argument must be a sequence type");
The sequence_check is done in pg_TwoIntsFromObj. Relevant in the other method too.

2023-07-01 04:53 UTC, Starbuck5 commented
I did some performance testing, and set_at with this PR is 1.5% faster now! (This is pretty low, it could be a fluke)
But this means that there isn't a big performance regression here we're not noticing. 

I'm not sure whether pg_TwoIntFromObj or that PyArg_ParseTuple is more expensive, but METH_O is less expensive than METH_VARARGS so maybe that helps it.

2023-07-11 09:29 UTC, ScriptLineStudios commented on src_c/surface.c
> +        return RAISE(PyExc_ValueError, "Argument must be a sequence type");
done!

2023-07-16 21:00 UTC, oddbookworm approved these changes
LGTM!

2023-07-21 05:15 UTC, ankith26 commented on buildconfig/stubs/pygame/surface.pyi
>      def get_at_mapped(self, x_y: Sequence[int]) -> int: ...
```suggestion
    def get_at_mapped(self, x_y: Coordinate) -> int: ...
```

2023-07-21 05:17 UTC, ankith26 requested changes
The docs, tests and stubs for `get_at_mapped` aren't updated yet

2023-07-22 09:05 UTC, Starbuck5 approved these changes
Looks good!

Thanks for working on this. Getting stuff supporting floats when appropriate is a good initiative throughout the pygame-ce API.

2023-07-22 09:53 UTC, merged