Add dark theme for documentation
pygame-community/pygame-ce pull request #2122
Opened 2023-04-19 18:49 UTC by Notenlish

This commit adds dark theme to pygame-ce documentation. It uses localStorage in js to save the theme that the user chose and sets the class of the body tag based on that. The theme.conf file now has dark versions of some settings. It also has some modifications to the way docs are generated in makeref.py, I had to do this because I couldnt figure out a better way for it. There probably is a better way to do it but i don't know how.

2023-04-24 07:05 UTC, Starbuck5 commented
I took a small look at this tonight.

I was surprised to see that the scroll bar design had changed, and that the quick start header is now in the middle of the page on the docs main page.

2023-04-24 10:45 UTC, Notenlish commented
The scrollbar could be kept the default one, I'm not sure if it fits the theme

2023-04-25 07:44 UTC, Starbuck5 commented
>  The scrollbar could be kept the default one, I'm not sure if it fits the documentation theme

What documentation theme? Specifically "dark mode" or just in general?

I'd rather use the built in scroll bar than this very custom looking thing. Looking at Github light vs dark, they both use the normal scroll bar, but the colors of it change slightly.

2023-04-26 19:20 UTC, Notenlish commented
Reverted the scrollbar

2023-04-30 08:51 UTC, Starbuck5 commented on docs/reST/themes/classic/script.html
> +console.log("hi from script.js");
Can't have this in production 😄

2023-04-30 08:55 UTC, Starbuck5 commented
Scrollbar back how it was, thanks.

I'm trying to minimize the changes in this PR to make it just about the dark mode so it is focused and easy to review :)

Next up: the searchbar. I'd rather you keep it how it was-- shorter height, text search button instead of icon. With how tall it is now it distorts the whole top row of the top bar. I'm thinking you did this to match the height of the svg icon you got? The svg should be scaled down.

2023-05-01 08:15 UTC, Notenlish commented on docs/reST/themes/classic/script.html
> +console.log("hi from script.js");
I couldn't figure out how to put it in an external file while also having it named "script.js". The pathto() function adds ".html" to the filename. I tried to change it but couldnt figure out how it works. Would it be better to put it directly inside the html?

2023-05-01 08:19 UTC, Starbuck5 commented on docs/reST/themes/classic/script.html
> +console.log("hi from script.js");
I'm referring to the console.log

2023-05-06 18:09 UTC, Notenlish commented on docs/reST/themes/classic/script.html
> +console.log("hi from script.js");
oh sorry 😅 didnt notice that, fixed

2023-05-06 18:10 UTC, Notenlish commented
> Scrollbar back how it was, thanks.
> 
> I'm trying to minimize the changes in this PR to make it just about the dark mode so it is focused and easy to review :)
> 
> Next up: the searchbar. I'd rather you keep it how it was-- shorter height, text search button instead of icon. With how tall it is now it distorts the whole top row of the top bar. I'm thinking you did this to match the height of the svg icon you got? The svg should be scaled down.

Should I change the search icon back to the text or keep it?

2023-05-09 15:46 UTC, gresm commented on buildconfig/makeref.py
> +        return Exception
Few issues: 
1. Why do you print ``Exception`` class into the console. Maybe you want to re-raise it again?
2. ``return Exception`` Again, why?
3. This part probably was intended to be for debugging reasons, but instead it hides the error.

2023-05-09 15:51 UTC, gresm requested changes
buildconfig/makeref.py fails to include js files, so no extra widgets are working...

2023-05-09 15:51 UTC, gresm commented on buildconfig/makeref.py
> +        target = r"{}".format(f'{rst_build_dir}\script.html')
Wrong backslashes: use ``/``. This script has to work on different operating systems.

2023-05-09 15:51 UTC, gresm commented on buildconfig/makeref.py
> +        return returncode
If the ``add_js_files()`` would fail, it still would return error code 0.

2023-05-09 15:53 UTC, gresm commented on buildconfig/makeref.py
> +        target = r"{}".format(f'{rst_build_dir}\script.html')
Actually, those backslashes are unnecessary.

2023-05-09 17:49 UTC, gresm commented
For proper sphinx way of including JavaScript files see [this](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file).

2023-05-13 20:11 UTC, Notenlish commented
> For proper sphinx way of including JavaScript files see [this](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file).

I'll try and do it

2023-05-14 06:28 UTC, novialriptide reviewed
I like this pull request a lot! I just have a few nitpicks about it.

In the future, we should probably instate a formatter like Prettier or something.

2023-05-14 06:28 UTC, novialriptide commented on buildconfig/makeref.py
> +        print("---")
Remove the `---` prints

2023-05-14 06:28 UTC, novialriptide commented on buildconfig/makeref.py
> +def add_js_files():
Could you add a brief docstring to explain what this method is doing?

2023-05-14 06:28 UTC, novialriptide commented on docs/reST/themes/classic/elements.html
> +			<svg class="theme-icon" data-theme="light-theme" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
If possible, could you put these svg files into its own file?

2023-05-14 06:28 UTC, novialriptide commented on docs/reST/themes/classic/theme.conf
> +dark_searchbarbgcolor= #292929
Code quality nitpick: Could you put a space before and after `=`?

2023-05-21 07:31 UTC, Starbuck5 commented on buildconfig/makeref.py
> +import shutil
There are a lot of pointless changes in this file in this PR. It should be left how it was before with whitespace.

2023-05-21 07:31 UTC, Starbuck5 commented on docs/reST/_static/script.js
> +});
Needs a blank line at the end.

2023-05-21 07:32 UTC, Starbuck5 commented on buildconfig/makeref.py
> +                    return Exception
Looks resolved?

2023-05-21 07:32 UTC, Starbuck5 commented on buildconfig/makeref.py
> +        return Exception
Looks resolved?

2023-05-21 07:34 UTC, Starbuck5 commented on buildconfig/makeref.py
> +        returncode = subprocess.run(subprocess_args).returncode
I don't understand why this is changed.

2023-05-22 18:50 UTC, Matiiss commented
Fixes https://github.com/pygame-community/pygame-ce/issues/1710

2023-05-25 08:07 UTC, Starbuck5 commented on docs/reST/themes/classic/elements.html
> +				</svg>
Since the other two svgs were moved out into files, it seems like this one should as well.

2023-05-25 08:20 UTC, Starbuck5 commented on docs/reST/themes/classic/elements.html
This PR changes the shape of the header sections by "inflating" the top bar, because the icons are taller than the previous content.

To minimize this effect, I think the icons should go down to 24x24 or a similar size.

2023-05-26 08:43 UTC, Starbuck5 approved these changes
Ok.

IDK why you switched the buttons. I think it made more sense before. If you're in light mode you click moon to go to dark mode, and vice versa.

Why have two identical SVGs one labeled dark one labeled light. Just use one.

You have a merge conflict to resolve, let people in the discord know if you need help with that.

Also, I'm still a bit skeptical of the dark mode colors themselves. But that shouldn't prevent this from getting merged and going out a bit experimental at first.

With all that in mind, I'm approving it anyway. Thanks for working on this!

2023-05-26 10:45 UTC, Notenlish commented
> Why have two identical SVGs one labeled dark one labeled light. Just use one.

I wasn't sure if the colors of the icons should be the same for both themes.

2023-05-27 08:05 UTC, Starbuck5 commented
> I wasn't sure if the colors of the icons should be the same for both themes.

I believe it's conventional to define the shape of an icon in the svg file and the color in the css. So it would be one svg file anyways.

2023-05-31 10:26 UTC, Matiiss commented on docs/reST/ext/boilerplate.py
> +    app.add_js_file("script.js", loading_method="defer")
This maybe could use a different loading method or a different approach that lets the dark theme load before displaying the page to the user

2023-05-31 14:32 UTC, MyreMylar commented
This 'colour_value' text seems much larger than I would expect:

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/e5c80777-019d-4441-88bc-ba12ef2ad210)

2023-05-31 14:36 UTC, MyreMylar commented on docs/reST/ext/boilerplate.py
> +    app.add_js_file("script.js", loading_method="defer")
Does this cause the brief flash of green I see when switching between pages?

2023-05-31 14:40 UTC, MyreMylar approved these changes
Looks pretty good. I think I would probably prefer some more pastel-y variations on the current colours which seem a little 80's teletext to me (old UK resident reference).

Noticed one area where the styling changes made a particular word really pop out - see comment above - which can probably be fixed in the documentation itself. Overall 👍  

I won't merge yet as there were some questions about the theme caching/loading which it might be nice to resolve, but none of it is crucial. No need to make the perfect the enemy of the good.

2023-05-31 17:04 UTC, Notenlish commented on docs/reST/ext/boilerplate.py
> +    app.add_js_file("script.js", loading_method="defer")
Fixed it

2023-05-31 17:12 UTC, Matiiss approved these changes
For the purposes of this PR as noted by Starbuck:
LGTM 👍 
Thanks for the PR

2023-05-31 17:12 UTC, merged