`_sdl2.video` docs rewrite, minor method signature changes
pygame-community/pygame-ce pull request #2128
Opened 2023-04-23 23:30 UTC by Mega-JC

(based on #2092)

This commit effectively rewrites all the documentation of the `pygame._sdl2.video` module, by either adding new information for undocumented content, or extracting information from existing docstrings in the codebase. Along with the documentation changes, some function signatures were modified to adhere to the snake case naming convention described in PEP 8.

2023-04-30 08:06 UTC, Starbuck5 commented on src_c/cython/pygame/_sdl2/video.pyx
> +        Get or set the window title. An empty string means that no title is set.An empty string means that no title is set.
2nd sentence duplicated.

2023-04-30 08:08 UTC, Starbuck5 commented on src_c/cython/pygame/_sdl2/video.pyx
> +        """Get the unique window ID
Why not leave the "read-only" note?

2023-04-30 08:13 UTC, Starbuck5 commented on src_c/cython/pygame/_sdl2/video.pyx
> +        textures to be drawn unto.
Target textures aren't technically supported on all platforms. Some old renderers that SDL2 might use don't support it.

2023-04-30 08:19 UTC, Starbuck5 commented on docs/reST/ref/sdl2_video.rst
The other doc files usually keep the line length down to 79-80 if not too inconvenient.

2023-04-30 08:24 UTC, Starbuck5 commented on docs/reST/ref/sdl2_video.rst
> +   operations is preferred where possible.
This last sentence makes it sound like batching is something you have to worry about yourself, when it's handled automatically by SDL.

2023-04-30 20:17 UTC, Mega-JC commented on src_c/cython/pygame/_sdl2/video.pyx
> +        """Get the unique window ID
Good catch, will add them back in a bit

2023-04-30 20:21 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
I was a bit unsure about how to approach line lengths, in some cases tying to split things up ended up breaking the intended reStructuredText formatting. I'll see what I can do though.

2023-04-30 21:23 UTC, Mega-JC commented on src_c/cython/pygame/_sdl2/video.pyx
> +        textures to be drawn unto.
I tried to be a bit more clearer in my latest change

2023-04-30 21:24 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   operations is preferred where possible.
Removed that bit

2023-05-01 07:00 UTC, Starbuck5 approved these changes
Looks good.

Thanks for this!

2023-05-12 20:35 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   | :sg:`get_drivers() -> Generator[RendererDriverInfo, None, None]`
I think that `RendererDriverInfo` should be immediately followed by `get_drivers` to maintain some continuity in the docs since `get_drivers` returns a generator that yields `RendererDriverInfo`s
And after them I guess it doesn't matter as much, just don't put `messagebox` after `get_grabbed_window`.

2023-05-12 23:38 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   | :sg:`get_drivers() -> Generator[RendererDriverInfo, None, None]`
I made some further changes related to this.

2023-05-13 14:19 UTC, Matiiss requested changes

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   rotate and resize when drawn unto a :class:`Renderer`
`unto` seems a bit weird in this context (seems a bit incorrect too), it's also old, what about `onto`? (and this same word in like 10 different places all over the docs should be fixed then)

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   Creates an Image.
Is this a remnant of whatever was before? Otherwise it seems like it's in a weird place in the generated html.

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: origin
Is this actually callable? Should need a signature then

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
>  .. class:: Image
Setters/getters usually precede methods

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   Creates a 2D rendering context for a window.
Is this a remnant of whatever was before? Otherwise it seems like it's in a weird place in the generated html.

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
>  .. class:: Renderer
Setters/getters and methods are kinda mashed together, as per other docs setters/getters should precede methods

2023-05-13 14:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +      .. warning:: This is a very slow operation, and should not be used frequently.
This warning could be added to all the other methods on this page that contain _slow operation, use sparingly_

2023-05-15 22:19 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   Creates a 2D rendering context for a window.
This is intentional and is a more formal description of the `:sl:` field. It also maps better to the preexisting docstrings.

2023-05-15 22:20 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +      .. warning:: This is a very slow operation, and should not be used frequently.
I've decided to turn all of them into `.. note::`s instead.

2023-05-15 22:29 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   Creates an empty texture.
[It's intentional.](https://github.com/pygame-community/pygame-ce/pull/2128#discussion_r1194417360)

2023-05-15 22:29 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   Creates an Image.
[It's intentional.](https://github.com/pygame-community/pygame-ce/pull/2128#discussion_r1194417360)

2023-05-15 22:40 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +      If :func:`pygame.mouse.set_visible` was called with ``True`` the input
https://github.com/pygame-community/pygame-ce/blob/2.2.1/src_c/mouse.c#L165-L198

2023-05-15 22:40 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   rotate and resize when drawn unto a :class:`Renderer`
typo.

2023-05-15 22:53 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: origin
fixed.

2023-05-15 22:54 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   Creates a window.
[It's intentional.](https://github.com/pygame-community/pygame-ce/pull/2128#discussion_r1194417360)

2023-05-16 10:48 UTC, yunline commented on src_c/doc/sdl2_video_doc.h
> +#define DOC_SDL2_VIDEO_WINDOW "Window(title="pygame", size=(640, 480), position=None, fullscreen=False, fullscreen_desktop=False, **kwargs) -> Window\npygame object that represents a window"
Double quotation mark here is causing error at compile time

2023-05-16 10:52 UTC, yunline requested changes

2023-05-16 10:52 UTC, yunline commented on src_c/doc/sdl2_video_doc.h
> +#define DOC_SDL2_VIDEO_WINDOW "Window(title="pygame", size=(640, 480), position=None, fullscreen=False, fullscreen_desktop=False, **kwargs) -> Window\npygame object that represents a window"
Double quotation mark here is causing error at compile time

2023-05-17 04:03 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +                           (X11 only, >= SDL 2.0.5)
Line 70 in this snapshot of code should end with a period for sure, I guess you weren't adding them to those ending with parentheses (though then again line 68 ends with a period)

2023-05-17 04:11 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +      If :func:`pygame.mouse.set_visible` was called with ``True`` the input
Looking at https://github.com/pygame-community/pygame-ce/blob/2.2.1/src_c/mouse.c#LL184C41 I see that calling set_visible with `True` would disable the relative mouse mode

2023-05-17 04:19 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: origin
So, I looked at the source and it is a property, so it should be `.. attribute:: origin` (https://github.com/pygame-community/pygame-ce/blob/main/src_c/cython/pygame/_sdl2/video.pyx#L937-L951)

2023-05-17 04:21 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +   .. staticmethod:: from_surface
`from_surface` should probably get its warning/note about being slow back

2023-05-17 15:38 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   .. staticmethod:: from_surface
There was no note to begin with.

2023-05-17 15:42 UTC, Mega-JC commented
Alright, I took another good look at the changes made in this PR, and took some time to address all the complaints. Should have done that earlier, but I think it the PR should be ready now.

2023-05-17 16:56 UTC, Matiiss commented on docs/reST/ref/sdl2_video.rst
> +      If :func:`pygame.mouse.set_visible` was called with ``True`` the input
Will be looked into in a future PR

2023-05-17 16:57 UTC, Matiiss approved these changes
LGTM (apart from that minor thing that's out of the scope of this PR)

2023-05-17 17:03 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: origin
Fixed again.

2023-05-17 18:11 UTC, Mega-JC commented on docs/reST/ref/sdl2_video.rst
> +      If :func:`pygame.mouse.set_visible` was called with ``True`` the input
It's now been clarified (after some Discord back-and-forth testing).

2023-05-18 02:33 UTC, Starbuck5 commented
This has the approvals to merge, but the cython should be regenerated to sync the default window title change. And to be sure that's safe the branch should be rebased against main to not wipe out any existing cython changes since the inception of this branch.

Also the commit history of the branch is a lot at this point, it could "squash and merge"d or Mega could squash down some commits into each other.

2023-05-18 08:54 UTC, Mega-JC commented
All done and completed, Squash and Merge sounds good.

2023-05-20 06:35 UTC, Starbuck5 commented
> Edit: Seems like recompilation with Python 3.11 was needed, CI is happy now.

Since Cython is a code generator, the only relevant thing is the version of Cython.

I didn't like how the Cython version changed in your regen, and how every file was regenerated (even ones that shouldn't have any change), so I changed the Cython regen commit a bit.

But now if I squash and merge we'll both be equal authors on this PR, from a commit perspective. Which isn't accurate. I'd like you to squash the first 14 commits into 1 or several commits authored exclusively by you, then we can do a normal merge.

2023-05-21 16:09 UTC, Mega-JC commented
Alright, commits have now been squashed down to 2.

2023-05-21 21:08 UTC, merged