basic functionality
pygame-community/pygame-ce pull request #2160
Opened 2023-05-14 17:52 UTC by Notenlish

Thanks to starbuck, matt and other people who helped me

2023-05-14 18:11 UTC, oddbookworm requested changes
You should also make sure to add typestub info to `font.pyi`

2023-05-14 18:11 UTC, oddbookworm commented on docs/reST/ref/font.rst
> +      | :sg:`render_to(text, antialias, color, surf_to_render, dest_pos, background=None, wraplength=0) -> Surface`
The args here and the args you're parsing in the code are not in the same order, they should be

2023-05-14 18:11 UTC, oddbookworm commented on src_c/font.c
> +font_render_to(PyObject *self, PyObject *args)
As @Matiiss suggested in discord, you'll want some input validation here. Like checking that a surface is valid before blitting to it (using the `SURF_INIT_CHECK` macro would be helpful here)

2023-05-14 18:13 UTC, oddbookworm commented
Using this test code:
```py
import pygame
pygame.init()

screen = pygame.display.set_mode((500, 500))

surf = pygame.Surface((50, 50), pygame.SRCALPHA)
font = pygame.font.Font()

font.render_to(surf, (0, 0), "Hello World!", True, "blue")

screen.blit(surf, (100, 100))
pygame.display.flip()

input()
```
I got this result:
![image](https://github.com/pygame-community/pygame-ce/assets/49015102/c6ea999b-3491-4149-8dee-896481b5206e)

2023-05-14 18:15 UTC, Matiiss commented
The function should also accept keyword arguments.

2023-05-14 18:49 UTC, Matiiss commented
And this needs tests too.

2023-05-18 19:12 UTC, Matiiss requested changes

2023-05-18 19:12 UTC, Matiiss commented on src_c/font.c
> +    Py_RETURN_NONE;
Instead of returning None this should return what `pgSurface_Blit` returns (which is a Rect)

2023-07-27 17:48 UTC, Notenlish commented
Closing the pr as I'm not going to work on it

2024-08-05 20:26 UTC, Notenlish commented
```cmd
Installing collected packages: urllib3, pytz, MarkupSafe, idna, charset-normalizer, certifi, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, requests, Pygments, Jinja2, imagesize, docutils, babel, alabaster, Sphinx
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Successfully installed Jinja2-3.0.3 MarkupSafe-2.0.1 Pygments-2.14.0 Sphinx-5.3.0 alabaster-0.7.13 babel-2.11.0 certifi-2024.7.4 charset-normalizer-2.0.12 docutils-0.18.1 idna-3.7 imagesize-1.4.1 pytz-2024.1 requests-2.27.1 snowballstemmer-2.2.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 urllib3-1.26.19
Pygame-ce requires Python3 version 3.7 or above.
```

How can I change the python version?

2024-08-12 17:20 UTC, Notenlish commented
big thanks to @bilhox for the segfault fix

2025-01-05 12:46 UTC, zoldalma999 commented
IIRC Notenlish has said that he does not want to work on this PR, so I'll close it. Maybe @Matiiss or @damusss can fix it up sometime and make a new PR (assuming we still want this API)?

2025-01-05 12:46 UTC, closed without merging

2025-03-09 02:36 UTC, Matiiss commented
_Do_ we still want this API?

2025-03-09 17:49 UTC, Notenlish commented
> _Do_ we still want this API?
I still think people would like this, someone just needs to work on the pr