Raise an error when source and destination surfaces are the same (in `box_blur` and `gaussian_blur`).
pygame-community/pygame-ce pull request #2161
Opened 2023-05-15 06:15 UTC by yunline

Continue from #2103
Fix #2102

2023-05-18 05:33 UTC, Matiiss requested changes
This should probably have a note in the docs that passing the calling surface as destination surface would raise an exception. Otherwise looks good to me.

2023-05-18 09:46 UTC, Matiiss approved these changes
LGTM 👍

2023-05-20 06:40 UTC, Starbuck5 commented on src_c/transform.c
> +    if (retsurf->pixels == src->pixels) {
Is this a viable way of testing that surfaces have the same data?

Like I believe subsurfaces might have a `->pixels` pointer within the existing surface data region.

Could it test if the pixels regions overlap? Like something around `if (retsurf->pixels <= src->pixels && src->pixels <= retsurf->pixels + retsurf->pitch * retsurf->h) {}`

I'm not telling you to do this, this is a genuine question.

2023-05-20 07:31 UTC, Matiiss commented on src_c/transform.c
> +    if (retsurf->pixels == src->pixels) {
My understanding is that since pixel addresses are compared no two different surfaces would have the same pixel address, right? So, only the same surface would succeed that check. As for subsurfaces, they also pass that check and an exception is raised. Which makes sense as that's still the same surface under the hood.

2023-05-20 07:36 UTC, Starbuck5 commented on src_c/transform.c
> +    if (retsurf->pixels == src->pixels) {
As I suspected, subsurfaces do have different addresses:

```py
>>> import pygame
pygame-ce 2.3.0.dev3 (SDL 2.26.4, Python 3.9.5)
>>> a = pygame.Surface((500,50))
>>> b = a.subsurface((10,10,100,30))
>>> b
<Surface(100x30x32)>
>>> a
<Surface(500x50x32)>
>>> a._pixels_address
1743672180768
>>> b._pixels_address
1743672200808
>>>
```

2023-05-20 07:40 UTC, yunline commented on src_c/transform.c
> +    if (retsurf->pixels == src->pixels) {
> As I suspected, subsurfaces do have different addresses:

Yes, but they are in different size, which will be caught by here:
https://github.com/pygame-community/pygame-ce/blob/2a21a5db2ba5b4180f948fd952b8423221e6a552/src_c/transform.c#L3152-L3155

2023-05-21 07:40 UTC, Starbuck5 commented on src_c/transform.c
> +                     "Source and destination surfaces are overlapping.");
The fact that they're overlapping is not a good error message, imo.

"Blur routines do not support dest_surfaces that share pixels with the source surface. Likely the surfaces are the same, one of them is a subsurface, or they are sharing the same buffer."

^ Something like this?

I tried to put it in words that would make sense with the context of the pygame API.

2023-05-21 07:43 UTC, Starbuck5 approved these changes
Left some error message feedback to resolve before merge, otherwise looks good.

2023-05-21 09:43 UTC, merged