Re-allow destsurf scale w/ diff but compatible pixelformats
pygame-community/pygame-ce pull request #2172
Opened 2023-05-18 05:10 UTC by Starbuck5

Fixes #2116

2023-05-25 17:22 UTC, ankith26 commented on src_c/transform.c
> +        stretch_result_num = SDL_SoftStretch(src, NULL, modsurf, NULL);
As I understand, this modified `modsurf`. But `modsurf` is freed, and this function actually returns `retsurf`?

2023-05-25 17:26 UTC, Starbuck5 commented on src_c/transform.c
> +        stretch_result_num = SDL_SoftStretch(src, NULL, modsurf, NULL);
Mod surf and retsurf use the same pixel buffer.

2023-05-25 17:40 UTC, ankith26 commented on src_c/transform.c
> +        stretch_result_num = SDL_SoftStretch(src, NULL, modsurf, NULL);
Oh, I assumed the pixel buffer would be copied. But yeah, shared pixel buffer makes sense

2023-05-25 17:41 UTC, ankith26 approved these changes
cool fix, thankss :star2:

2023-05-28 00:51 UTC, Temmie3754 requested changes
Whilst this does solve the case of RGBX sources it does not fix BGRA cases (and possibly others) which the method prior to 2.2.1 handled fine so it will likely need to be modified to support those as well.

2023-05-28 00:55 UTC, Starbuck5 commented
What kind of BGRA cases?

If you're trying to scale a BGRA surface onto a RGBA surface it should fail. It "worked" before but would produce incorrect output.

2023-05-28 01:06 UTC, Temmie3754 approved these changes
Cases where the destination format was BGRA which would result in altered colours in the old method.
Though if that was unintentional behaviour of the old function then everything else should be good to go.

2023-05-28 01:16 UTC, Starbuck5 commented
My thought is that it’s better to explicitly fail in that case rather than give such weird output.

2023-05-28 01:23 UTC, Temmie3754 commented
It likely is, I can't see many scenarios where someone would intentionally make use of the scaling methods to also change the displayed colour at the same time, there's a greater chance someone would accidentally cause that problem when scaling which the error message would help with.

2023-05-28 02:18 UTC, merged