add stylename property to freetype font
pygame-community/pygame-ce pull request #2175
Opened 2023-05-18 13:27 UTC by dr0id

partial PR as requested in this PR #2132

2023-05-19 06:32 UTC, narilee2006 commented on src_c/font.c
> +    {"stylename", (getter)font_getter_style_name, NULL,
`style_name` instead?

2023-05-20 10:02 UTC, dr0id commented on src_c/font.c
> +    {"stylename", (getter)font_getter_style_name, NULL,
@narilee2006  renamed

2023-05-21 06:53 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      Read only. Returns the font's style name.
It would be nice to give some example outputs to contextualize what a style name is. 

I wonder if there's a complete list of style names in freetype? (Nope: https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_facerec)

From testing I got things like `Regular`, `Narrow`, `Bold`.

2023-05-21 06:56 UTC, Starbuck5 commented on src_c/_freetype.c
> +        return stylename ? PyUnicode_FromString(stylename) : 0;
If stylename is NULL, the method returns NULL?

That will raise a Python SystemError because it will be returning NULL without setting an error.

But it raises the question of what to return if the Font doesn't have a stylename-- `None`? empty string?

2023-05-21 06:56 UTC, Starbuck5 commented on src_c/_freetype.c
> +    return PyObject_Repr((PyObject *)self);
I don't get this line.

2023-05-21 07:03 UTC, Starbuck5 commented on src_c/font.c
> +    const char *font_name = TTF_FontFaceStyleName(font);
In SDL_ttf:  https://github.com/libsdl-org/SDL_ttf/blob/SDL2/SDL_ttf.c#L3030, this is the same as the freetype call you make in freetype.

So it should also be NULL checked the way the other one is.

Also we technically support down to SDL_ttf 2.0.11 right now, and this function was added in SDL_ttf 2.0.12. We might as well just raise the dependency version. (You can do that in this PR, the dep versions are in the README)

2023-05-21 07:04 UTC, Starbuck5 commented
Thanks for the PR!

One additional thing I noticed is that this should have some small unit tests added.

2023-05-23 19:38 UTC, dr0id commented on src_c/_freetype.c
> +    return PyObject_Repr((PyObject *)self);
I think it returns just the string repr() of self.

2023-05-23 19:38 UTC, dr0id commented on src_c/_freetype.c
> +        return stylename ? PyUnicode_FromString(stylename) : 0;
done

2023-05-23 19:38 UTC, dr0id commented on docs/reST/ref/font.rst
> +      Read only. Returns the font's style name.
updated

2023-05-23 19:38 UTC, dr0id commented
I have added a test for the new property

2023-05-28 00:43 UTC, Starbuck5 commented on src_c/_freetype.c
> +    return PyObject_Repr((PyObject *)self);
I mean why it's there. You're emulating the other getter I guess? I still wonder why it's there at all.

2023-05-28 00:48 UTC, Starbuck5 commented on src_c/font.c
> +    return font_style_name ? PyUnicode_FromString(font_style_name) : NULL;
If font_style_name is NULL this will return NULL, which will cause Python to have a SystemError because you've returned NULL without an exception set.

2023-05-28 00:49 UTC, Starbuck5 commented on src_c/font.c
> +    const char *font_name = TTF_FontFaceStyleName(font);
Dependency version still needs to be updated.

2023-05-30 19:27 UTC, dr0id commented on src_c/font.c
> +    return font_style_name ? PyUnicode_FromString(font_style_name) : NULL;
might this be the reason why the name property returned 0 instead of NULL? I have been copying that method. Not sure what or which error I should set.

2023-05-30 19:29 UTC, dr0id commented on src_c/_freetype.c
> +    return PyObject_Repr((PyObject *)self);
yes, I copied from the name getter. I dunno, ask the original author? But I agree, its probably not a good idea. Should it raise an exception instead (same as in the NULL case?)?

2023-05-30 19:33 UTC, dr0id commented on src_c/font.c
> +    const char *font_name = TTF_FontFaceStyleName(font);
updated

2023-05-30 19:43 UTC, dr0id commented on src_c/font.c
> +    return font_style_name ? PyUnicode_FromString(font_style_name) : NULL;
Maybe I should just return an empty string as I do in the freetype code.

2023-06-21 20:13 UTC, dr0id commented
@Starbuck5 @narilee2006 @novialriptide @ankith26  
updated, please review again

2023-07-08 08:34 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      .. versionadded:: 2.3
2.3.1 now, same with the other versionadded.

2023-07-08 08:36 UTC, Starbuck5 commented on src_c/_freetype.c
> +    return PyObject_Repr((PyObject *)self);
Yes, raising an exception there seems like the best idea.

2023-07-08 08:48 UTC, Starbuck5 commented on src_c/font.c
> +    }
I think this error checking is unnecessary. TTF_FontFaceStyleName doesn't mention any error condition, and on SDL2_ttf's side it's just a direct access into the freetype font face struct.

2023-07-08 08:55 UTC, Starbuck5 commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
I've just noticed this will segfault if you quit the font module. Also font_getter_name will as well.

```py
import pygame
pygame.init()
a = pygame.Font(None, 32)
pygame.font.quit()
a.style_name
```

Honestly this is such an edge case I'd be fine merging this without fixing it, especially because it seems like a pain to fix it. Just as long as we open an issue to track it and come back deliberately.

2023-07-13 18:55 UTC, dr0id commented on src_c/font.c
> +    }
if you say so, removed

2023-07-13 18:59 UTC, dr0id commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
hmm, why should 'a' (in your example) still be a valid pointer after 'pygame.font.quit()'? Which code part does 'own' the pointer? The module code or the users code?

I agree, it is probably an edge case, not sure how often it will happen.

2023-07-13 19:04 UTC, zoldalma999 commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
Isn't this just #1506 again? The linked PR does add a check for this to some functions, but probably all of them need it (or most anyway).

2023-07-23 19:43 UTC, dr0id commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
@zoldalma999 thanks for the hint. Yes it looks like it would be the same, will implement it the same way then.

2023-07-25 19:58 UTC, dr0id commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
@Starbuck5 @zoldalma999 
would these kind of tests make sense?

```
    def test_font_method_should_raise_exception_after_quit(self):
        methods = [
            ("get_ascent", tuple()),
            ("get_bold", tuple()),
            ("get_descent", tuple()),
            ("get_height", tuple()),
            ("get_italic", tuple()),
            ("get_linesize", tuple()),
            ("get_strikethrough", tuple()),
            ("get_underline", tuple()),
            ("metrics", ("any text",)),
            ("render", ("hello", True, "white")),
            ("size", ("any text",)),
            # ("set_bold", (True,)),
            # ("set_direction", ("is it text",)),
            # ("set_italic", (True,)),
            # ("set_script", ("is it other text",)),
            # ("set_strikethrough", (True,)),
            # ("set_underline", (True,)),
        ]
        font = pygame_font.Font(None, 10)
        actual_names = [n for n in sorted(dir(font)) if callable(getattr(font, n)) and not n.startswith("__")]
        expected_names = [n for n,a in sorted(methods)]
        self.assertEqual(len(expected_names), len(actual_names)-6, msg=f"ensure all methods are checked {expected_names} != {actual_names}")

        for name, args in methods:
            with self.subTest(name=name):
                # arrange
                font = pygame_font.Font(None, 16)
                pygame_font.quit()
                pygame_font.init()

                # act / assert
                self.assertRaises(pygame.error, getattr(font, name), *args)
                # self.assertRaises(pygame.error, font.render, "hello", True, "white")


    def test_font_property_should_raise_exception_after_quit(self):
        properties = [
            ("align", 1),
            ("bold", True),
            ("italic", True),
            ("name", None),
            ("strikethrough", True),
            ("style_name", None),
            ("underline", True),
        ]

        font = pygame_font.Font(None, 10)
        actual_names = [n for n in sorted(dir(font)) if not callable(getattr(font, n)) and not n.startswith("__")]
        expected_names = [n for n,a in sorted(properties)]
        self.assertEqual(len(expected_names), len(actual_names), msg=f"ensure all methods are checked {expected_names} != {actual_names}")

        for name, arg in properties:
            with self.subTest(name=name):
                # arrange
                font = pygame_font.Font(None, 16)
                pygame_font.quit()
                pygame_font.init()

                # act / assert
                self.assertRaises(pygame.error, getattr, font, name) # read
                if arg is not None:
                    self.assertRaises(pygame.error, setattr, font, name, arg) # write
```

Which gives me 13 FAILS like

```
======================================================================
FAIL: test_font_method_should_raise_exception_after_quit (__main__.FontTypeTest) (name='get_underline')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\Python310\lib\site-packages\pygame\tests\font_test.py", line 794, in test_font_method_should_raise_exception_after_quit
    self.assertRaises(pygame.error, getattr(font, name), *args)
AssertionError: error not raised by get_underline

======================================================================
FAIL: test_font_property_should_raise_exception_after_quit (__main__.FontTypeTest) (name='align')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\Python310\lib\site-packages\pygame\tests\font_test.py", line 820, in test_font_property_should_raise_exception_after_quit
    self.assertRaises(pygame.error, getattr, font, name) # read
AssertionError: error not raised by getattr
```

 and following do segfault:

```
            # ("set_bold", (True,)),
            # ("set_direction", ("is it text",)),
            # ("set_italic", (True,)),
            # ("set_script", ("is it other text",)),
            # ("set_strikethrough", (True,)),
            # ("set_underline", (True,)),
```

2023-07-25 20:04 UTC, dr0id commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
this should probably also work for ftfont....hmm will need different expected lists I guess

2023-07-26 04:04 UTC, Starbuck5 commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
If you'd like to add these tests it should probably be in a separate PR.

You could add the tests and then mark them expected to fail in unittest. It might make more sense to open an issue that's like "validate properties of font after de-init" and put that forward as starter code for the issue.

2023-07-26 18:57 UTC, dr0id commented on src_c/font.c
> +font_getter_style_name(PyObject *self, void *closure)
ok, I will add them in another PR (uff). But first I would like to finish this one.

2023-07-26 19:32 UTC, dr0id commented on src_c/_freetype.c
> +    return PyObject_Repr((PyObject *)self);
returning an exception, not sure if I have done it right.

2023-07-26 19:34 UTC, dr0id commented
@Starbuck5 @zoldalma999 @narilee2006 
updated, I would like to finish this PR within this week.

2023-07-26 20:19 UTC, ankith26 commented on buildconfig/stubs/pygame/freetype.pyi
> +    style_name: str
since this is a property that is only `get`-able, it should be typed as that. Same above too.

Maybe this mistake is a common theme in this file, in that case you might as well leave your changes as is, and the typing stuff can be fixed together in a future PR

2023-07-26 20:19 UTC, ankith26 commented on docs/reST/ref/freetype.rst
> +      .. versionadded:: 2.3
outdated now

2023-07-27 05:04 UTC, dr0id commented on buildconfig/stubs/pygame/freetype.pyi
> +    style_name: str
after looking into it for 10 minutes I still don't see what should be changed. Can you give me an example or explicit pointers what you expect? Could not find an example either in pygame (maybe I have overlooked it).

2023-07-27 05:45 UTC, dr0id commented on docs/reST/ref/freetype.rst
> +      .. versionadded:: 2.3
updated to 2.3.1

2023-07-27 15:44 UTC, ankith26 commented on buildconfig/stubs/pygame/freetype.pyi
> +    style_name: str
I'll go ahead and resolve this (to be fixed in future work along with the rest of the file)

2023-07-27 16:03 UTC, ankith26 requested changes

2023-07-27 16:03 UTC, ankith26 commented on src_c/font.c
> +    return PyUnicode_FromString(font_style_name);
`font_style_name` can be `NULL` when unknown. Just like `freetype`, we should return an empty string in that case. Passing `NULL` to `PyUnicode_FromString` may lead to a segfault.

The same fix should also be applied to the above function.

Additionally, a small addition to the docs that state that these parameters can be empty stings too would also be nice

2023-07-27 19:26 UTC, dr0id commented on src_c/font.c
> +    return PyUnicode_FromString(font_style_name);
returning "" now if the style_name is null

2023-07-28 04:40 UTC, ankith26 commented on test/font_test.py
> +        self.assertNotEqual(f.style_name, "")
This isn't right anymore. Maybe this line could be replaced with `self.assertIsInstance(f.style_name, str)`

2023-07-28 04:40 UTC, ankith26 commented on src_c/_freetype.c
> +        return PyUnicode_FromString(name ? name : "");
actually, this change isn't required in freetype I think, only font. `_PGFT_Font_GetName` is already returning `""` when it has to, but it is also returning `NULL` when it is actually setting exceptions

2023-07-28 04:40 UTC, ankith26 commented on src_c/_freetype.c
> +        return PyUnicode_FromString(stylename ? stylename : "");
same review as `_ftfont_getname` applies here

2023-07-29 05:02 UTC, dr0id commented on test/font_test.py
> +        self.assertNotEqual(f.style_name, "")
this is still valid since following code
`f = pygame.font.Font(None, 10)
print(f.style_name)
`
prints 'Bold' for me.

But I can add the instance check.

2023-07-29 05:04 UTC, dr0id commented on src_c/_freetype.c
> +        return PyUnicode_FromString(name ? name : "");
but returning 0 is a bad choice if a string is expected?

2023-07-29 05:09 UTC, dr0id commented on src_c/_freetype.c
> +        return PyUnicode_FromString(name ? name : "");
I see, the error is already set, so what should I return then? 
NULL? might cause a segfault, no? 
0? is not a string

I have difficulties testing this because it does not happen.

2023-07-29 05:10 UTC, dr0id commented on src_c/_freetype.c
> +        return PyUnicode_FromString(name ? name : "");
changed back to original code

2023-07-29 05:11 UTC, dr0id commented on src_c/_freetype.c
> +        return PyUnicode_FromString(stylename ? stylename : "");
see comments on _ftfont_getname

2023-07-29 05:37 UTC, ankith26 approved these changes
LGTM, thanks for the PR :+1:

2023-07-29 07:00 UTC, Starbuck5 approved these changes
Let's get this merged!

2023-07-29 07:02 UTC, merged