Minor documentation updates
pygame-community/pygame-ce pull request #2183
Opened 2023-05-20 06:54 UTC by Starbuck5

2023-05-20 07:51 UTC, Matiiss requested changes

2023-05-20 07:51 UTC, Matiiss commented on docs/reST/ref/music.rst
>     Function :func:`set_pos` calls underlining SDL_mixer function
Could change "underlining" to "underlying"

2023-05-20 07:51 UTC, Matiiss commented on docs/reST/ref/music.rst
> +   better positioning support than earlier ones. A :code:`pygame.error`is
This seemingly didn't get generated correctly
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/92faff27-6273-4fc3-8afc-6db5cf2f992e)

2023-05-20 07:59 UTC, Starbuck5 commented on docs/reST/ref/music.rst
>     Function :func:`set_pos` calls underlining SDL_mixer function
Good idea.

2023-05-20 08:00 UTC, Starbuck5 commented on docs/reST/ref/music.rst
> +   better positioning support than earlier ones. A :code:`pygame.error`is
Good catch. I generated and then spaced out the lines to fit the line limit, that's how that slipped though.

I also noticed now that there are two other pygame.errors expressed on this page as `exc` instead of `code`, so I switched to use that strategy.

2023-05-20 08:10 UTC, Matiiss approved these changes
LGTM 👍

2023-05-21 01:30 UTC, yunline approved these changes
LGTM

2023-05-21 07:55 UTC, novialriptide approved these changes
So far so good. I didn't know `docs/README.md` existed tbh... lol 💀

2023-05-21 07:55 UTC, novialriptide commented on docs/README.md
> +- install Sphinx (`pip install Sphinx`)
Maybe capitalize the rest of the sentences in these steps.

2023-05-21 08:10 UTC, Starbuck5 commented on docs/README.md
> +- install Sphinx (`pip install Sphinx`)
Capitalize the rest of them? None of them are capitalized.

2023-05-22 06:19 UTC, Matiiss commented on docs/README.md
> +- Fork the pygame repository, download and navigate to it in the terminal
`pygame-ce` ?
also add command for how to do that: `git clone https://github.com/pygame-community/pygame-ce`

2023-05-22 19:52 UTC, MyreMylar approved these changes
LGTM 👍

2023-05-22 19:52 UTC, merged