Update README.fr.rst
pygame-community/pygame-ce pull request #2187
Opened 2023-05-21 17:17 UTC by jd-develop

Fix several things :
* replace incorrect punctuation marks with the official French ones (`"` to `«` and `»`, `'` to `’`)
* fix syntax and grammar errors
* replace « oeil » with « œil »
* replace « librarie » with « librairie »
* add NBSPs (no-break spaces) when necessary

2023-05-21 17:51 UTC, bilhox commented
Thank you for your changes, I'm the one who wrote the french readme and I noticed my grammatical mistakes but completely forgot to update it.

I have a project of french pygame documentation, if you're interested you can ask me in the pygame discord.

2023-05-21 21:24 UTC, Starbuck5 approved these changes
Seems like Lody is okay with it, so I'll approve.

@bilhox I think there is potential to have docs translations in the official docs, if it's something you'd like to look into: https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

2023-05-22 06:05 UTC, novialriptide approved these changes
I failed french in high school. LGTM!

2023-05-22 06:05 UTC, novialriptide commented on docs/readmes/README.fr.rst
> +Il utilise la librairie « Simple DirectMedia Layer » (SDL) et plusieurs autres librairies
`« Simple DirectMedia Layer » (SDL)` should have a link leading to the SDL website

2023-05-25 20:52 UTC, Grimmys requested changes
Bunch of suggestions.

Some are quick spelling fixes.
Some other are "bigger" fixes that could be handle (by me if you want) in another PR if you think it's not related.
And a lot of them are just me nitpicking on informal versus formal speech, you can ignore them if you disagree with my view.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
>  plus régulières, des améliorations et des correctifs, mais aussi une modèle de gouvernance plus
_modèle_ is a masculine word (https://www.larousse.fr/dictionnaires/francais/mod%C3%A8le/51916), so it should be _un modèle_.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +lançant cette commande ``python -m pygame.docs`` dans votre terminal. Si la documentation
I would replace _en
lançant cette commande ``python -m pygame.docs``_ by _en
exécutant la commande ``python -m pygame.docs``_.

_lançant_ is fine as well, but looks a bit less specific, more informal. But that's personal I guess.
The important fix is _la_ instead of _cette_.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +n’est pas trouvé localement, cela va lancer le site web.
_trouvée_ instead of _trouvé_.
_cela lancera_ instead of _cela va lancer_.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
>  La documentation en ligne reste à jour avec la version de pygame en cours de
Shouldn't it be _pygame-ce_ instead of _pygame_?
Just asking.
English translation of the current version: _The online documentation stays up-to-date with the pygame version under development on GitHub_.

Btw, guess it should be _GitHub_ instead of _github_.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Chose particulièrement intéressante : vous avez à votre disposition un dossier
Would replace _Chose particulièrement intéressante_ by _Un point particulièrement intéressant_.

But that's nitpicking, I just find it less informal.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
>  Si vous voulez utiliser des features en cours de développement,
_features_ could be translated as _fonctionnalités_

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
>  Build grâce au code source
In every places in this paragraph, I would replace _grâce au_ by _depuis le_.

Even if every native French should be able to get what _grâce au code source_ means, this formulation doesn't make sense to me.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +partie du travail sera de compiler et installer toutes les dépendances de
I think it should be _d'installer_

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Plus d’informations à propos de l’installation et de la compilation disponibles
It should be _... de la compilation sont disponibles_

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
>  Très grands remerciemments à toutes les personnes commentant la documentation,
_remerciements_

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Ceci veut en quelque sorte dire que vous êtes habilité à utiliser pygame
Again, I think everywhere in this paragraph, it should be _pygame-ce_ instead of _pygame_.

I don't know what is in the English version, but we are talking about the license here.
_pygame_ and _pygame-ce_ may have different licenses, so I think it's important to not mix them up when talking about this kind of stuff.

2023-05-25 20:52 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Pygame est une librairie multi-plateforme, libre et open-source
Ok, I'm going to be that annoying guy, but it is theoretically supposed to be _bibliothèque_ and not _librairie_.

BUT I know the word _librairie_ is already used in a lot a lot of places in this README, so it may not be so easy to catch all the places AND even if _librairie_ is wrong, everybody is making the mistake of using it (even me).
So we are in this kind of tricky situation: it's technically the wrong term, but this wrong term might be used even more often than the correct one.

Even Wikipedia is mentioning the mistake: https://fr.wikipedia.org/wiki/Biblioth%C3%A8que_logicielle
"Le mot « librairie » est souvent utilisé à tort pour désigner une bibliothèque logicielle. Il s'agit d'un [anglicisme](https://fr.wikipedia.org/wiki/Anglicisme) fautif dû à un [faux-ami](https://fr.wikipedia.org/wiki/Faux-ami) (library)."
Translation: "The word « librairie » is often wrongly used to designate a bibliothèque (logicielle). It's an anglicism coming from the faux-ami library."

Up to us to decide if we want to stick to correctness or rather to usage.

2023-05-26 05:22 UTC, jd-develop commented
Thank you for your suggestions!
I'll fix it ASAP

2023-05-26 06:56 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  Ceci est un fork du projet initial par ses principaux anciens développeurs,
In the English readme :

It is a fork of the upstream pygame project by its **former** core developers, and was created after impossible challenges prevented them from continuing development upstream.

So… I don’t think *ancien* should be removed :shrug:

2023-05-26 07:01 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +partie du travail sera de compiler et installer toutes les dépendances de
Je suis pas sûr : ici « installer » est le sujet de « est », et le COD « l’ » correspond à Pygame. Ici, on peut remplacer la phrase par « Installer pygame […] est assez automatisé. », ce serait plus clair

2023-05-26 07:06 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Cette distribution se nomme **« pygame - Community Edition »** (« pygame-ce » pour faire plus court).
fixed :+1:

2023-05-26 07:06 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +le développement du projet initial. Cette nouvelle distribution a pour but d’offrir des mises à jours
fixed :+1:

2023-05-26 07:06 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  plus régulières, des améliorations et des correctifs, mais aussi une modèle de gouvernance plus
fixed :+1:

2023-05-26 07:06 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +lançant cette commande ``python -m pygame.docs`` dans votre terminal. Si la documentation
fixed :+1:

2023-05-26 07:19 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +n’est pas trouvé localement, cela va lancer le site web.
fixed :+1:

2023-05-26 07:20 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  La documentation en ligne reste à jour avec la version de pygame en cours de
Nope, pygame-ce is installed under the name of « pygame » ^^

2023-05-26 07:26 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Chose particulièrement intéressante : vous avez à votre disposition un dossier
fixed :+1:

2023-05-26 07:26 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  Si vous voulez utiliser des features en cours de développement,
fixed :+1:

2023-05-26 07:26 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  Build grâce au code source
fixed :+1:

2023-05-26 07:26 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Plus d’informations à propos de l’installation et de la compilation disponibles
fixed :+1:

2023-05-26 07:26 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  Très grands remerciemments à toutes les personnes commentant la documentation,
fixed :+1:

2023-05-26 07:26 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Ceci veut en quelque sorte dire que vous êtes habilité à utiliser pygame
fixed :+1:

2023-05-26 08:18 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Pygame est une librairie multi-plateforme, libre et open-source
Well, well well…

First, this is super easy to catch every occurence of « librairie » and replace it by « bibliothèque ».

I agree with you : libriairie is the wrong term but everybody uses it. I personally prefer replacing it by « bibliothèque ». What do you think, and what do the other people reading this think ?

2023-05-26 08:20 UTC, bilhox commented on docs/readmes/README.fr.rst
>  La documentation en ligne reste à jour avec la version de pygame en cours de
I agree with Grimmys, it should be ``pygame-ce`` for the GitHub repository.

2023-05-26 09:11 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  La documentation en ligne reste à jour avec la version de pygame en cours de
OK, I'll fix it then

2023-05-26 11:18 UTC, Grimmys commented on docs/readmes/README.fr.rst
>  La documentation en ligne reste à jour avec la version de pygame en cours de
Right, but good to know `pygame-ce` is installed as `pygame`. It may explain why it should still be `pygame` in some cases then.

2023-05-26 11:23 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +partie du travail sera de compiler et installer toutes les dépendances de
Pardon, je parlais du second _installer_ !
Dans la première phrase, c'est correct tu as raison.
Mais dans la seconde :

_La majeure partie du travail sera de compiler et **d'**installer_

2023-05-26 11:25 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +partie du travail sera de compiler et installer toutes les dépendances de
Aaah oui, bien vu. Je corrige ça de ce pas

2023-05-26 11:28 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Pygame est une librairie multi-plateforme, libre et open-source
I'm always in favor of having a more formal and correct speech, so I would prefer to replace it by  « bibliothèque ».
Everybody should be able to understand what it means.

2023-05-26 11:29 UTC, jd-develop commented on docs/readmes/README.fr.rst
>  La documentation en ligne reste à jour avec la version de pygame en cours de
Fixed ^^

2023-05-26 11:41 UTC, bilhox commented on docs/readmes/README.fr.rst
> +Pygame est une librairie multi-plateforme, libre et open-source
I agree with Grimmys, it should be "bibliothèque".

2023-05-26 11:44 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Pygame est une librairie multi-plateforme, libre et open-source
alright, I just fixed it

2023-05-26 11:50 UTC, jd-develop commented on docs/readmes/README.fr.rst
> +Il utilise la librairie « Simple DirectMedia Layer » (SDL) et plusieurs autres librairies
Added it :+1:

2023-05-26 11:55 UTC, Grimmys approved these changes

2023-05-26 12:16 UTC, merged