Bump SDL_image to 2.7.0
pygame-community/pygame-ce pull request #2198
Opened 2023-05-26 11:06 UTC by yunline

Continue from #2182
To support animation

2023-05-27 02:27 UTC, yunline commented
![](https://github.com/pygame-community/pygame-ce/assets/31395137/e0f5ec5d-9d2e-4204-b96b-6e626748d64b)

2023-06-03 19:52 UTC, oddbookworm commented
```python
>>> pygame.print_debug_info()
Platform:               Windows-10-10.0.22621-SP0
System:                 Windows
System Version:         10.0.22621
Processor:              AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
Architecture:           Bits: 64bit     Linkage: WindowsPE
Driver:                 Display Not Initialized

Python:                 CPython
pygame version:         2.3.0.dev3
python version:         3.11.1

SDL versions:           Linked: 2.26.4  Compiled: 2.26.4
SDL Mixer versions:     Linked: 2.6.3   Compiled: 2.6.3
SDL Font versions:      Linked: 2.20.2  Compiled: 2.20.2
SDL Image versions:     Linked: 2.7.0   Compiled: 2.7.0
Freetype versions:      Linked: 2.11.1  Compiled: 2.11.1
```

2023-06-03 19:52 UTC, oddbookworm commented
Seems to work perfectly locally

2023-06-03 19:52 UTC, oddbookworm approved these changes

2023-06-03 19:54 UTC, oddbookworm commented
I'll test further on other OS's at some point today

2023-07-01 02:09 UTC, Starbuck5 commented on .github/workflows/build-windows.yml
> +      - name: Install CMake
According to this page (https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) Cmake is already installed.

2023-07-01 02:12 UTC, Starbuck5 commented on buildconfig/Setup.SDL2.in
> -imageext src_c/imageext.c $(SDL) $(IMAGE) $(PNG) $(JPEG) $(DEBUG)
I'd rather not split this into win/non-win versions.

Jpeg is not used directly by imageext anymore (removed by me a while back), it's just vestigial in buildconfig. So it should work to only link libpng both places.

2023-10-08 19:35 UTC, MyreMylar requested changes
Looks like this needs a bit of love to keep up with main, and some adjustments from @Starbuck5's feedback. I think @ankith26 should also look it over as I know they are doing stuff with windows dependencies at the moment.

2023-12-10 16:53 UTC, MyreMylar commented
Seems like this is superseded by moving to version 2.8.0 in this PR: https://github.com/pygame-community/pygame-ce/pull/2596

2023-12-11 10:39 UTC, ankith26 reviewed
We will be moving away from the old python buildconfig, and on windows we still want to keep deps precompiled and not compiled at any pygame dev machines.

This PR did some nice work, but we are on SDL_image 2.8.0 on main, doing things differently than this PR. Thanks for the work anyways.

2023-12-11 10:39 UTC, closed without merging

2023-12-12 06:35 UTC, Starbuck5 commented
Yes, thank you yunline for working on tackling this important item. I just wasn't sure what the right strategy was.