Added multiline to the TextInput example.  I also rewrote the code.
pygame-community/pygame-ce pull request #2209
Opened 2023-05-30 23:10 UTC by NaturePixels

Added multiline to the TextInput example.  I also rewrote the code of the TextInput example, since i thought that it was too messy.

2023-05-31 00:08 UTC, oddbookworm requested changes
Thanks for the PR! I went through and added some comments in places I noticed some things I didn't like, and I'd like to see these things addressed. Once they're addressed or otherwise explained, I'd be happy to re-review this PR

2023-05-31 00:08 UTC, oddbookworm commented on examples/textinput.py
> -    FONT_NAMES = [
Why'd you get rid of the multiple fonts? As the comment here mentions, Arial is not necessarily the best choice of font to use for something that can be non-English, and I don't want to lose any functionality of the example

2023-05-31 00:08 UTC, oddbookworm commented on examples/textinput.py
> -        """
Put docstrings in your methods. It helps explain the code, and this is for everyone after all, not everyone has the skill to parse through code and get at what the function is doing, so giving a brief description of the function's purpose is a good idea.

2023-05-31 00:43 UTC, novialriptide commented on examples/textinput.py
There shouldn't be a big block of empty newlines here.

2023-05-31 00:43 UTC, novialriptide commented on examples/textinput.py
> +        #Handles the events
All of the comments in `handle_events()` can be removed; they are not necessary.

2023-05-31 00:48 UTC, NaturePixels commented on examples/textinput.py
what do you mean by newlines?

2023-05-31 00:49 UTC, oddbookworm commented on examples/textinput.py
https://github.com/pygame-community/pygame-ce/blob/76f2363c85f765ff0ddfaef67058226c6bfec513/examples/textinput.py#L9-L11

2023-05-31 17:02 UTC, Matiiss requested changes

2023-05-31 17:02 UTC, Matiiss commented on examples/textinput.py
> +                                    self.text += "<"
This absolutely not what the example is about, you're supposed to use `TEXT...` events like `TEXTINPUT` (what this example is about as can be inferred from the name `textinput.py`)

2023-06-01 00:14 UTC, NaturePixels commented on examples/textinput.py
> +                                    self.text += "<"
already changed. Now the code uses the TEXTINPUT event.

2023-06-01 00:30 UTC, yunline commented on examples/textinput.py
> -os.environ["SDL_IME_SHOW_UI"] = "1"
Input method menu is not shown because this line is removed.

2023-06-01 00:33 UTC, yunline commented on examples/textinput.py
> -    FONT_NAMES = [
I'v tested it and seems that Chinese characters are not rendered correctly
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/69ce73ca-6795-4bd3-9d49-4c5598277b03)

2023-06-01 00:36 UTC, yunline commented on examples/textinput.py
> +        self.chat_list = []
`self.chat_list` is assigned twice, why?

2023-06-01 00:38 UTC, yunline commented on examples/textinput.py
> +        self.chat_list = []
It seems you never use `self.chat_list`, so I think maybe it should be removed.

2023-06-01 00:42 UTC, yunline commented on examples/textinput.py
> +                for i, chr in enumerate(self.text):
Don't use `chr` as name of a variable. `chr` has already been the name of a built-in function

2023-06-01 00:46 UTC, NaturePixels commented on examples/textinput.py
> +        self.chat_list = []
but i do use chat_list

2023-06-01 00:47 UTC, oddbookworm requested changes
You need to address or respond to all review comments.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> -    FONT_NAMES = [
@NaturePixels This needs to be fixed.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> -""" pygame.examples.textinput
Not fixed.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> -class TextInput:
Not addressed.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> -        """
Not addressed.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> +pygame.init()
Not addressed.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> +        self.screen = pygame.display.set_mode((700, 500))
Not addressed.
Edit: You put them below. That defeats the point. Put them above this line and actually use them *everywhere* you need the screen size.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> +    def update(self):
Not fixed. Your functions are still really long.

2023-06-01 00:47 UTC, oddbookworm commented on examples/textinput.py
> -os.environ["SDL_IME_SHOW_UI"] = "1"
@NaturePixels Put this back or explain why it was removed.

2023-06-01 00:47 UTC, NaturePixels commented on examples/textinput.py
> +        self.chat_list = []
i never used `self.char_list` though

2023-06-01 00:48 UTC, oddbookworm commented on examples/textinput.py
This hasn't been fixed.

2023-06-01 00:48 UTC, oddbookworm commented on examples/textinput.py
> +            y_pos = self.input_img.get_height() + 40
Not addressed.

2023-06-01 00:49 UTC, oddbookworm commented on examples/textinput.py
> +            if y_pos > 500:
Not addressed.

2023-06-01 00:50 UTC, oddbookworm commented on examples/textinput.py
> +                "> " + self.text + ["|", ""][int(time.time() * 2 % 2)],
Now it's even harder to read. I'd suggest finding a better way to construct this string (maybe consider using f-strings and using intermediate variables to improve clarity)

2023-06-01 00:53 UTC, NaturePixels commented on examples/textinput.py
> -    FONT_NAMES = [
Oh

2023-06-01 00:55 UTC, NaturePixels commented on examples/textinput.py
> -    FONT_NAMES = [
Ok ill try to do all of the stuff you guys said, but only tomorrow. Its getting late.

2023-06-01 17:24 UTC, NaturePixels commented
@oddbookworm I removed it because i remade the code from scratch, so i didn't know that it was important.

2023-06-01 17:46 UTC, NaturePixels commented
@yunline Now test it again. If there are any bugs let me know.

2023-06-01 17:59 UTC, robertpfeiffer commented on examples/textinput.py
> -    FONT_NAMES = [
> I'v tested it and seems that Chinese characters are not rendered correctly ![image](https://user-images.githubusercontent.com/31395137/242443414-69ce73ca-6795-4bd3-9d49-4c5598277b03.png)

I think this is a font issue even with the original version. I wanted to address this ages ago, but I didn't want to package unifont (or another font that covers most languages and 99.9% of the world) because it's too big. Maybe we should add a command line optiopn for font selection?

2023-06-01 18:02 UTC, robertpfeiffer commented on examples/textinput.py
> -os.environ["SDL_IME_SHOW_UI"] = "1"
> Input method menu is not shown because this line is removed.

Isn't this automatically shown when setting the IME rect? At least that happens when I input kanji on X11 with fcitx.

2023-06-01 19:52 UTC, Sjmarf commented on examples/textinput.py
> +                                    self.text += "<"
Why all this manual shift-key logic, by the way? `event.unicode` does this for you

2023-06-01 21:31 UTC, NaturePixels commented on examples/textinput.py
> -        """
@oddbookworm What do you mean by "not adressed"?

2023-06-02 02:59 UTC, yunline commented on examples/textinput.py
> -os.environ["SDL_IME_SHOW_UI"] = "1"
> Isn't this automatically shown when setting the IME rect? At least that happens when I input kanji on X11 with fcitx.

It's not shown on Windows if the environ is not set.

2023-06-02 03:02 UTC, yunline commented on examples/textinput.py
> -os.environ["SDL_IME_SHOW_UI"] = "1"
@NaturePixels The comments above this line shouldn't be removed too

2023-06-02 03:04 UTC, yunline commented on examples/textinput.py
> -        print("Using font: " + self.font.name)
Why not print font name?

2023-06-02 03:10 UTC, yunline commented on examples/textinput.py
> +                ">" + self.text + ["|", ""][int(time.time() % 2)], False, (25, 255, 100)
Please enable the anti aliasing here. 
**No Anti Aliasing:**
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/158ddaa1-284f-491e-89c9-34d324fd885a)
**With Anti Aliasing:**
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/4d566e90-ae7d-43da-880c-40695dfe6244)

2023-06-02 03:14 UTC, yunline commented on examples/textinput.py
> +                msg_imgs.append(self.small_font.render(msg, False, (25, 255, 100)))
Please enable the anti aliasing here.

2023-06-02 09:27 UTC, NaturePixels commented on examples/textinput.py
> +                msg_imgs.append(self.small_font.render(msg, False, (25, 255, 100)))
Added antialiasing.

2023-06-02 09:43 UTC, yunline commented on examples/textinput.py
> +                msg_imgs.append(self.small_font.render(msg, False, (25, 255, 100)))
> Added antialiasing.

You have modified another one, but this one is not modified.

2023-06-02 16:08 UTC, NaturePixels commented on examples/textinput.py
> +                msg_imgs.append(self.small_font.render(msg, False, (25, 255, 100)))
@yunline ok

2023-06-02 16:46 UTC, NaturePixels commented on examples/textinput.py
> +                msg_imgs.append(self.small_font.render(msg, False, (25, 255, 100)))
> > Added antialiasing.
> 
> You have modified the other one, but this one is not modified.

Fixed.

2023-06-02 21:21 UTC, Notenlish requested changes
```py
import pygame
from pygame.locals import *
import os
import time
import sys
```
The sys module is not used, did you forgot to remove it?

2023-06-02 23:31 UTC, NaturePixels commented on examples/textinput.py
> -class TextInput:
I don't think that i should use more than a Game class, because now the code is smaller than before, so the game class is smaller now.

2023-06-02 23:57 UTC, oddbookworm commented on examples/textinput.py
> -class TextInput:
It doesn't matter how little code there is. The whole point is separation of responsibility. Also, `Game` is not a very good name for this class. It's not a game.

2023-06-02 23:58 UTC, NaturePixels commented on examples/textinput.py
> -class TextInput:
ok. ill fix it.

2023-06-03 00:01 UTC, yunline commented on examples/textinput.py
> -        pygame.key.set_text_input_rect(input_rect)
These 3 lines shouldn't be removed. Now the IME menu is not at the right place.
**Before Remove:**
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/cddab63b-8625-471e-bab6-615c0bd386a7)

**After Remove:**
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/46c4d017-43fe-4c17-a29d-1f4163b3edaf)

2023-06-03 00:03 UTC, oddbookworm requested changes

2023-06-03 00:03 UTC, oddbookworm commented on examples/textinput.py
> +        self.screen = pygame.display.set_mode((700, 500))
Don't resolve comments unless they're addressed. This is the second one that hasn't been addressed fully. You're still using numbers here

2023-06-03 00:03 UTC, oddbookworm commented on examples/textinput.py
> -        """
It's not addressed. You haven't fully documented your methods. Docstrings are not regular comments, they actually matter when it comes to documenting your code. Put some effort into writing a good description

2023-06-03 00:03 UTC, oddbookworm commented on examples/textinput.py
> +    def update(self):
Not fixed. You can't ignore review comments and just mark them resolved because you disagree with them. That's disrespectful to the person who left the comment. If you disagree with my comments, then justify why you disagree.

2023-06-03 00:10 UTC, yunline requested changes
- This new example doesn't support to use the arrow keys to move the cursor.
- Doesn't support to use the enter key on the keypad  to make a new line.

2023-06-03 00:13 UTC, NaturePixels commented
> * This new example doesn't support to use the arrow keys to move the cursor.
> * Doesn't support to use the enter key on the keypad  to make a new line.

Now it supports the enter key on the keypad.

2023-06-03 00:25 UTC, oddbookworm requested changes

2023-06-03 00:25 UTC, oddbookworm commented on examples/textinput.py
> +pygame.init()
I missed unresolving this one.

2023-06-03 00:25 UTC, oddbookworm commented on examples/textinput.py
> +    def update(self):
Did you mark this as resolved again?

2023-06-03 00:26 UTC, NaturePixels commented
@oddbookworm no

2023-06-03 05:32 UTC, narilee2006 reviewed
I have some comments !

2023-06-03 05:32 UTC, narilee2006 commented on examples/textinput.py
> -        self, prompt: str, pos, screen_dimensions, print_event: bool, text_color="white"
Should there be types for `pos` and `screen_dimensions` ?

2023-06-03 05:32 UTC, narilee2006 commented on examples/textinput.py
> +    def get_fonts(self):
`def get_fonts(self) -> None:` ?

2023-06-03 05:32 UTC, narilee2006 commented on examples/textinput.py
> -    def update(self, events) -> None:
`events: List[...]` ?

2023-06-03 11:57 UTC, NaturePixels commented on examples/textinput.py
> -        pygame.key.set_text_input_rect(input_rect)
what do i do to make the ime menu show?

2023-06-03 11:57 UTC, NaturePixels commented on examples/textinput.py
> -        pygame.key.set_text_input_rect(input_rect)
like, what keys do i press?

2023-06-03 12:14 UTC, yunline commented on examples/textinput.py
> -        pygame.key.set_text_input_rect(input_rect)
> what do i do to make the ime menu show?

Install an IME then use `Win+Space` to switch (on Windows 10+)

2023-08-14 09:18 UTC, MyreMylar commented
Two months on this one with no activity/response to reviews. 

Just noting that we will eventually close small PRs like this with no progression (they can always be re-opened later if needed) so that other users can have a go at solving the same problems. 

As a general guideline three months of no activity seems a reasonable time frame for an admin closure. There is no penalty/stigma for closing and then later re-opening of PRs on Github, it just helps us keep our open PR list clean so we can see what is in progress for upcoming releases of pygame-ce 👍

2023-08-14 09:21 UTC, MyreMylar reviewed
As above - will close this PR September 4th if there is no further progression in next 3 weeks.

2023-09-30 05:41 UTC, Starbuck5 commented
I will go ahead and close under MyreMylar's rationale above. 🙂

2023-09-30 05:41 UTC, closed without merging