Add new C API `pg_GetPkgdataResource`
pygame-community/pygame-ce pull request #2222
Opened 2023-06-02 09:41 UTC by yunline

fixes #2221

2023-06-18 06:27 UTC, narilee2006 commented
What is pg_GetPkgdataResource ?

2023-07-07 07:08 UTC, yunline commented
> Do these changes provide any benefits that I'm missing? I can see that it makes the code a bit cleaner

You are right. It just cleans up some code.

2023-07-22 10:14 UTC, Starbuck5 commented on src_c/display.c
> +        PyObject *icon_fileobj = pg_GetPkgdataResource(icon_defaultname);
This isn't a "file object," I believe, so the variable is misleadingly named.

2023-07-22 10:16 UTC, Starbuck5 commented on src_c/image.c
> +pgImage_LoadBasic(PyObject *fileobj)
Same comment about `fileobj`

2023-08-22 02:26 UTC, yunline commented on src_c/image.c
> +pgImage_LoadBasic(PyObject *fileobj)
I don't think this one is misleading.
`fileobj` can be a str filename or a file-like object.

2023-08-22 02:26 UTC, yunline commented on src_c/display.c
> +        PyObject *icon_fileobj = pg_GetPkgdataResource(icon_defaultname);
fixed

2023-09-29 12:28 UTC, ankith26 requested changes

2023-09-29 12:28 UTC, ankith26 commented on src_c/base.c
> +    goto get_resource_end;
this is a redundant `goto`, even without it, control is going to flow into the block below

2023-09-29 12:28 UTC, ankith26 commented on src_c/window.c
> +    PyObject *icon = pgImage_LoadBasic(icon_path_obj);
Needs check for `icon_path_obj` being `NULL` (and exit early with error forward) and if it is not `NULL` it needs to be `DECREF`d after `pgImage_LoadBasic` finishes

2023-09-29 12:28 UTC, ankith26 commented on src_c/display.c
> +        state->icon = pgImage_LoadBasic(icon_path_obj);
same as above review (except here maybe just ignore the error and don't even call `pgImage_LoadBasic` in that case)

2023-10-12 17:07 UTC, MyreMylar commented
This could use merging with main as the conflicts are making the diff hard to understand now.

2023-10-12 17:09 UTC, MyreMylar requested changes
Please merge with main and resolve the conflicts, to make it easier to review.

2023-11-07 07:49 UTC, yunline commented
It‘s not worth to create two C APIs and just simplify code a little bit.
The simplifying works will contunue in #2552

2023-11-07 07:49 UTC, closed without merging