add sidebar + sort modules
pygame-community/pygame-ce pull request #2225
Opened 2023-06-02 15:15 UTC by NOTMEE12

I will add sidebar (maybe also make it look better).
Also I feel that sorting by `Most Usefull stuff`, `Advanced stuff`, is not the best sorting, so I will sort modules by Usecase (`pygame.display` will go to `Window` section, etc.)

2023-06-03 10:59 UTC, NOTMEE12 commented
mockup of what I want to get:
![image](https://github.com/pygame-community/pygame-ce/assets/103068655/c1965445-68c9-47f1-8a7d-f368e5c8eafc)

2023-06-04 19:39 UTC, NOTMEE12 commented
I shall close that pr, bc many people didn't agree with the mockup design + I don't have time

2023-06-08 18:20 UTC, Notenlish commented
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/71cfad0d-16a4-4088-84be-4b37cbd34ca7)
why are you adding '▼' into the text itself? You should add it as a seperate element because: 
A) It wont appear as text when you hold down the mouse
B) Cleaner implementation

![image](https://github.com/pygame-community/pygame-ce/assets/71970100/97e38096-9039-48e1-bc6c-ff414dd90837)
Secondly, you should make the width of the sidebar fixed, not based on the window width. Because it just leads to the sidebar getting narrower when you make the window narrower. Instead it should ideally have more or less a fixed width. If the window is too narrow, It should work like how the godot docs handles it.

Thirdly, I dont think that making the sidebar have a gradient for background makes sense. 

Also, the sidebar shouldn't change width when hovering over it. It just makes it distracting.

2023-06-10 20:13 UTC, Notenlish requested changes
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/3574db11-39c7-4d33-b3c4-581ea0e42aa3)

Fix the div with the class "related" taking up sidebar's space

2023-06-10 20:15 UTC, Notenlish requested changes
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/72b520eb-1503-432e-b11f-0d2a84b8c74a)

Fix this(screenshot from iphone 12 pro screen resolution)

2023-06-10 20:16 UTC, Notenlish requested changes
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/bb4244ca-a4a5-42fe-9de0-388a3298714a)

Can you replace the icon, doesn't fit well. It's too big and the white outline doesn't really make sense)

2023-06-10 20:19 UTC, Notenlish requested changes
```css
    transition-property: all;
    transition-duration: 2s;
    transition-timing-function: bezier;
    transition-delay: 0.1s;
```

I think you should get rid of the transition

2023-06-10 20:23 UTC, Notenlish requested changes
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/59261240-1c95-453c-9a8e-93fbc77a1d6a)

Add `cursor: pointer;` for hovering over that part

2023-06-10 20:26 UTC, Notenlish requested changes
```css
div.header > div {
    /* border: {{ theme_headerborder }}; */
    border-collapse: collapse;
    background-color: {{ theme_headerbgcolor }};
    background-image: linear-gradient(to bottom, {{ theme_headerbgcolor}}, {{ theme_bgcolor }});
}
.dark-theme div.header > div {
    background-color: {{ theme_dark_headerbgcolor }};
    border: {{ theme_dark_headerborder }};
    background-image: linear-gradient(to bottom, {{ theme_dark_headerbgcolor }}, {{ theme_dark_bgcolor }});
}
div.header .logo {
    background-color: {{ theme_logobgcolor }};
    background-image: linear-gradient(to bottom, {{ theme_logobgcolor }}, {{ theme_headerbgcolor }});
    padding: 0.3em;
    /* border-right: 3px solid black; */
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
}
.dark-theme div.header .logo {
    background-color: {{ theme_dark_logobgcolor }};
    background-image: linear-gradient(to bottom, {{ theme_dark_logobgcolor}}, {{ theme_dark_headerbgcolor }});
    border: none;
}
```

Get rid of background-image. I don't think a gradient is needed, just using a color should be fine.

2023-06-10 20:38 UTC, Notenlish requested changes
```js
function toggleSectionVisibility(section, message){
	document.getElementById(section).hidden = ! document.getElementById(section).hidden;
	if (document.getElementById(section).hidden === true){ // show
		items = localStorage.getItem('hidden');
		if (items !== null){
			if (!(items.includes(section))){
				items = items + section + '|';
			}
			localStorage.setItem('hidden', items);
		} else {
			localStorage.setItem('hidden', section + '|');
		}
		document.getElementById(section[0]).innerHTML = document.getElementById(section[0]).innerHTML.replace('▼', '▲');
	} else {  // hide
		items = localStorage.getItem('hidden');
		if (items !== null){
			if (items.includes(section)){
				items = items.replace(section + '|', '');
			}
			localStorage.setItem('hidden', items);
		}
		document.getElementById(section[0]).innerHTML = document.getElementById(section[0]).innerHTML.replace('▲', '▼');
	}
}

function toggleChecked(classname){
    if (window.innerWidth <= 1100) {
        el = document.getElementsByClassName(classname)[0];
        console.log(el.id);
        if (el.id !== 'clicked') {
            el.id = 'clicked';
            htmlElement.classList.add('clicked');
        } else {
            el.id = null;
            htmlElement.classList.remove('clicked');
        }
    }
}
```
Do we have to save the hidden/closed tabs in localStorage? I don't think resetting hidden parts would create any inconvenience for the user.

2023-06-10 20:40 UTC, Notenlish requested changes
```js
function toggleSectionVisibility(section, message){
    ...
}
```

`message` argument isn't used

2023-06-10 20:41 UTC, NOTMEE12 commented
> ![image](https://user-images.githubusercontent.com/71970100/244893147-72b520eb-1503-432e-b11f-0d2a84b8c74a.png)

How did you get that. What are the steps to replicate this?

2023-06-10 20:44 UTC, Notenlish requested changes
```css
	box-shadow: 20px 10px 15px 0px rgba(0, 0, 0, 0.2);
	margin: 0;
	top: 0;
	height: 100vh;
	transition-property: all;
```

use `100%` instead of `100vh`

2023-06-11 01:35 UTC, cool-dev-guy commented
> ![image](https://user-images.githubusercontent.com/71970100/244893224-bb4244ca-a4a5-42fe-9de0-388a3298714a.png)
> 
> Can you replace the icon, doesn't fit well. It's too big and the white outline doesn't really make sense)

What about using unicode?`<p>&#8801; </p>` for hamburger menu?
eg :  
# &#8801;

2023-06-11 01:38 UTC, cool-dev-guy commented
> ```css
> 	box-shadow: 20px 10px 15px 0px rgba(0, 0, 0, 0.2);
> 	margin: 0;
> 	top: 0;
> 	height: 100vh;
> 	transition-property: all;
> ```
> 
> use `100%` instead of `100vh`

Is it working,cuz if the body&html is not `100%` it cant take the entire window size.

2023-06-17 06:24 UTC, novialriptide commented on docs/reST/_static/sections.js
> +function toggleSectionVisibility(section, message){
Could you make your tab spaces four spaces instead?

2023-06-17 07:17 UTC, NOTMEE12 commented on docs/reST/_static/sections.js
> +function toggleSectionVisibility(section, message){
I replaced tabs with four spaces just now

2023-06-22 20:06 UTC, Notenlish requested changes
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/9bc15034-d65f-4cd8-9ade-7fac25153312)
It's hard to see the sidebar in light theme

2023-06-22 20:06 UTC, Notenlish commented on docs/reST/themes/classic/static/pygame.css_t
> +    border-radius: 20px;
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/5162da6c-dceb-4157-bb0e-ffabe858a031)
border-radius seems to be supported pretty much everywhere, why do you use -mox-border-radius and :-webkit-border-radius ?

2023-06-23 16:17 UTC, NOTMEE12 commented on docs/reST/themes/classic/static/pygame.css_t
> +    border-radius: 20px;
should I remove it?

2023-06-24 13:26 UTC, NOTMEE12 commented on docs/reST/themes/classic/static/pygame.css_t
> +    /* background-image: linear-gradient(to bottom, {{ theme_logobgcolor }}, {{ theme_headerbgcolor }}); */
I removed all of the unnecesary comments.

2023-06-26 06:52 UTC, NOTMEE12 commented on docs/reST/themes/classic/static/pygame.css_t
> +    width: 40vh;
tbh I don't know why I did that. now it is `40%`

2023-10-12 17:33 UTC, MyreMylar requested changes
Thanks for having a go at doing this.

My three thoughts when looking it over:

1. I don't like the extra scroll bar that I get on the left hand side when all the submodule sections are open at the same time. I think that a) the submodules should perhaps start closed, only expanding when you click on the category and b) all the other sections should close when you expand one of them. This is how the default read the docs theme works, you can experiment with it in [the Pygame GUI docs here](https://pygame-gui.readthedocs.io/en/latest/
).
2. The upwards pointing arrow icons on the drop downs are confusing, generally I think the convention is that the arrows point to the right until expanded and then point down.
3. I like the idea of broad categorisations for grouping the submodules, but since they are being changed from the classic trio of 'Most useful', 'Advanced' and 'Other'. There needs to be a bit of debate over the broad categories here. For instance, I would call the one labelled 'Music' here 'Sound' because it covers sound effects as well as playing music or midi tracks. The drawing section has too much stuff in it - including some very rarely used submodules alongside frequently used ones. time does seem to belong under window, and we also have a new submodule and class on the way called 'window' and Window. I'd be tempted to seperate out font and freetype into a section called 'Text'. 'touch' should definitely be in the input section. 'BufferProxy', 'PixelArray', 'pixelcopy' and surfarray could all go in the 'Other' bucket imho. I'm sure there are other changes that could be made but those would be a decent start, and many others will have opinions.

2023-10-12 17:39 UTC, MyreMylar commented
What I'm talking about with the drop down arrows btw (I've slightly edited a screenshot of the docs built on this PR):

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/720f907c-646e-4166-a6a2-6915eaf1df20)


You'll have to click though on the image to make out the arrows.

2023-10-13 15:42 UTC, NOTMEE12 commented
> 1. I don't like the extra scroll bar that I get on the left hand side when all the submodule sections are open at the same time. I think that a) the submodules should perhaps start closed, only expanding when you click on the category and b) all the other sections should close when you expand one of them. This is how the default read the docs theme works, you can experiment with it in [the Pygame GUI docs here](https://pygame-gui.readthedocs.io/en/latest/).

You mean that:
- all sections should closed by default
- only one section can be open at a time


> 2. The upwards pointing arrow icons on the drop downs are confusing, generally I think the convention is that the arrows point to the right until expanded and then point down.

replace that with an arrow pointing to the right. Ok got it.

> 3. I like the idea of broad categorisations for grouping the submodules, but since they are being changed from the classic trio of 'Most useful', 'Advanced' and 'Other'. There needs to be a bit of debate over the broad categories here. For instance, I would call the one labelled 'Music' here 'Sound' because it covers sound effects as well as playing music or midi tracks. The drawing section has too much stuff in it - including some very rarely used submodules alongside frequently used ones. time does seem to belong under window, and we also have a new submodule and class on the way called 'window' and Window. I'd be tempted to seperate out font and freetype into a section called 'Text'. 'touch' should definitely be in the input section. 'BufferProxy', 'PixelArray', 'pixelcopy' and surfarray could all go in the 'Other' bucket imho. I'm sure there are other changes that could be made but those would be a decent start, and many others will have opinions.

So here:
- "Music" change to "Sound"
- `font` and `freetype` to section "Text".
- `touch` to the "input" section.
- readd the "Other" section and put in it some not frequently used modules (like `BufferProxy`, `PixelArray`, `pixelcopy`)

Did I get everything right?

2023-10-15 14:56 UTC, MyreMylar commented
Thanks for sorting out the arrows 👍 

> * all sections should closed by default
> * only one section can be open at a time

Correct. It should eliminate the double scrollbar issue and will also make things less cluttered when you first arrive.

> So here:
> 
> * "Music" change to "Sound"
> * `font` and `freetype` to section "Text".
> * `touch` to the "input" section.
> * readd the "Other" section and put in it some not frequently used modules (like `BufferProxy`, `PixelArray`, `pixelcopy`)
> 
> Did I get everything right?

Yep pretty much - though the 'Other' section is still there at the minute (at least on the latest version of this branch) so no need to readd it:

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/d189c4c7-826c-499a-98f6-d04c66491331)

I think the grouping of submodules is a good idea, I just expect the exact organisation of submodules to take up the most time in getting this PR merged as I expect everyone with a stake in pygame-ce will have an opinion on it 😄

2023-10-15 17:53 UTC, NOTMEE12 commented
hmmm... Yes the `input` section.

Now that I think about it, it should contain:
- touch
- controller
- joystick
- key

Which would leave the "events" section with only one item in it being the "event"

Should it be that way?

2023-10-15 18:56 UTC, zoldalma999 commented
I am not sure whether I agree with this PR or not. On one hand I like the new sections, as they make more sense than just how useful they are (which is arbitrary anyway). And the looks of the side panel isn't bad either.

On the other hand, I don't like that now you can't see all the modules at a glance, and modules are one more click away (I used the top bar a fair amount, and this makes it a bit more "effort")

Anyway this is what I came up with for the sections:

<details>
<summary>Sections</summary>

```
essential (/core?)
-----
display
event
time
pygame (This could be in other?)
Surface (I put it in Surface manipulation, but it fits here too. Same with Rects)


Useful types (needs a better name, but I think it makes sense to put these together)
-----
Color
math
Rect
Mask


input
-----
key
mouse
joystick
controller
touch
camera (with a bit of a stretch, probably would go to other instead)


sound
-----
mixer
music
midi
sndarray


drawing and text
-----
draw
gfxdraw
font
freetype


surface manipulation
-----
Surface
transform
image
PixelArray
pixelcopy
surfarray
BufferProxy


system info
-----
system
scrap
cursors


experimental
-----
for not yet released modules (video, touch, controller, geometry, window) could
be here? Anything that has progress but is not yet ready to be released fully


other
-----
sprite
locals
version
examples
tests
```
</details>

2023-12-16 07:45 UTC, MyreMylar commented
Looks like I can't resolve merge conflicts or merge with main on this PR - probably because it is from NOTMEE12's main branch.

I'm going to switch it to draft due to the inability to fix it up and lack of agreement on the website changes.

2025-01-05 12:57 UTC, zoldalma999 commented
Seems like this PR has been superseded by #2924.

2025-01-05 12:57 UTC, closed without merging