Update README.fr.rst (fix typos, ``pygame`` => ``pygame-ce`` ...)
pygame-community/pygame-ce pull request #2228
Opened 2023-06-04 18:09 UTC by bilhox

Hi,

Again, I propose a PR to fix some typos, some ``pygame`` got updated to ``pygame-ce``, and finally, some sentences got a bit changed to look more natural.

Should be reviewed by @Grimmys

2023-06-04 18:12 UTC, oddbookworm requested changes

2023-06-04 18:12 UTC, oddbookworm commented on docs/readmes/README.fr.rst
> +Si vous venez de commencer avec Pygame, vous devriez être capable de vous y lancer assez
The convention is that `pygame` is generally uncapitalized except at the beginning of a sentence

2023-06-04 18:12 UTC, oddbookworm commented on docs/readmes/README.fr.rst
> +changements ou des ajouts à Pygame lui-même, alors vous serez dans l’obligation
same comment about capitalization

2023-06-04 18:22 UTC, bilhox commented on docs/readmes/README.fr.rst
> +Si vous venez de commencer avec Pygame, vous devriez être capable de vous y lancer assez
Do you know how to edit the text from github directly ?

2023-06-04 18:33 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +la plus intuitive possible.
In my opinion, everything should be change to masculine instead.

We don't say "rendre l'écriture de programmes la plus simple possible", but "le plus simple possible", so I think it should be the same in this case: _rendre l'écriture de programmes le plus intuitif possible._.
Though I'm lacking the grammar rule to prove my point, so maybe I'm just wrong.

2023-06-04 18:33 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +et ajoutant du nouveau contenu dans le wiki sur pygame.org et sur pyga.me .
Looks like there is a space before the final dot.
But maybe just a GitHub rendering issue.

Also, why not providing the URLs?

2023-06-04 18:33 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +| SDL_gfx  | (Optionel, vendored in)|
If we decide to translate "Optional", shouldn't we translate "vendored in" as well?

Suggestion for translation: _déjà incluse_, _fourni avec (pygame)_.
Ok, not easy to find something suitable lol.

2023-06-04 18:33 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Si vous venez de commencer avec Pygame, vous devriez être capable de vous y lancer assez
If you move to the file from your repository, you should have the option to edit the file at the top

2023-06-04 18:33 UTC, Grimmys commented
No blocker on my side, just suggestions.

2023-06-04 18:34 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +Si vous venez de commencer avec Pygame, vous devriez être capable de vous y lancer assez
Link to the file in your repo: https://github.com/bilhox/pygame-ce/blob/bd4be11f9cd9376106cf82c8b9bb825cc958fcdf/docs/readmes/README.fr.rst

2023-06-04 18:37 UTC, bilhox commented on docs/readmes/README.fr.rst
> +la plus intuitive possible.
it's "la écriture", so it must be "la plus intuitive", no ?

2023-06-04 18:39 UTC, bilhox commented on docs/readmes/README.fr.rst
> +| SDL_gfx  | (Optionel, vendored in)|
yes, I was waiting for your opinion about this word, because I didn't know what it means.
I'll change it by this word ig.

2023-06-04 18:55 UTC, bilhox commented on docs/readmes/README.fr.rst
> +Si vous venez de commencer avec Pygame, vous devriez être capable de vous y lancer assez
fixed

2023-06-04 18:56 UTC, bilhox commented on docs/readmes/README.fr.rst
> +la plus intuitive possible.
fixed (not changed)

2023-06-04 18:56 UTC, bilhox commented on docs/readmes/README.fr.rst
> +et ajoutant du nouveau contenu dans le wiki sur pygame.org et sur pyga.me .
fixed

2023-06-04 18:56 UTC, bilhox commented on docs/readmes/README.fr.rst
> +| SDL_gfx  | (Optionel, vendored in)|
fixed

2023-06-04 19:17 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +| SDL_gfx  | (Optionel, vendored in)|
Je n'avais jamais vu l'expression "vendored in" non plus pour être honnête, je pense que ça a le même sens que "provided".

En gros, ça veut dire que la dépendance est incluse dans le package pygame-ce quand tu le télécharges.

2023-06-04 19:19 UTC, bilhox commented on docs/readmes/README.fr.rst
> +| SDL_gfx  | (Optionel, vendored in)|
Ok, donc je peux laisser "fourni avec" ?

2023-06-04 19:23 UTC, oddbookworm commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
Why are we linking to the original docs?

2023-06-04 19:29 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
It's for the thanks:

"[...] et ajoutant du nouveau contenu dans le wiki de `pygame`_ et sur `pygame-ce`_. "

Meaning:

"[...] and thanks to the people adding new content in pygame and pygame-ce wikis", with links to them.

If we don't want to link to the original docs, then should we remove the thanks for pygame as well?

2023-06-04 19:33 UTC, oddbookworm commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
That's fair, and I'm fine with it. However, I want to be careful about slight content changes between the versions of the readmes as well. I'm fine with it, as long as all versions of the readme stay consistent with each other

2023-06-04 20:19 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
I definitely agree with you, I was starting to think about this issue as well.

But then, what should be the process?
We should always have the English original version in sight next to the translation changes when reviewing them, and if we want to suggest change meaningful for both versions, it should first be applied to the English one?

2023-06-04 20:37 UTC, oddbookworm commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
The more translations we have, the harder this will be to manage. I'm not sure what the best approach would be. Ideally, they'd all be changed at the same time so they're all always in sync, but that's just not feasible

2023-06-06 17:07 UTC, bilhox commented
I added a warning about french README content.
Is there anything left to do ?

2023-06-17 06:42 UTC, novialriptide commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
I didn't read the `README (English)` too much, but I don't think we should deviate from the original source too much.

2023-06-17 08:54 UTC, bilhox commented on docs/readmes/README.fr.rst
> +.. _pygame: https://www.pygame.org/docs/
Okay then should I make the same changes to the english readme ? (replacing specific ``pygame`` to ``pygame-ce``, and make pygame(-ce) links redirecting to the docs instead of main page)

2023-06-18 08:36 UTC, Starbuck5 commented
Here's the policy I envision for updating the READMEs.
- Non-English READMEs are just trying to follow the English README's content.
- Whoever updates the English README has the responsibility to mark all other READMEs as out of date (in English)
- Translators see the README is out of date and update and update it (they can check the git history on the English README to find what changed). Or they don't, and maybe after a view years of that the Non-English README will be removed for lack of maintenance.

So you want to make a content change to the README?
You need to make it to the English README, then mark all other READMEs as out of date.

In your case, you can make the update to the English README and the French README then mark all other READMEs as out of date.

2023-07-11 08:40 UTC, Starbuck5 commented
@bilhox lets move this forward.

Content changes you've made to the French README should be added to the English README, and you should mark each other translation as out of date.

2023-07-11 08:44 UTC, bilhox commented
Hello,

Okay (I forgot about this PR sorry 😅), shall I also add the policy you envisaged in your last message, directly in the readme ?

2023-07-11 08:46 UTC, Starbuck5 commented
I don't think it's necessary to explain the README update policy in the README. We could have a README-README for that 😄

Don't worry about it in this PR.

2023-07-11 09:38 UTC, yolowex commented
> Okay, I added what you wanted. I updated the english README, and warned people ni the french readme that it could be out of date. For the korean (I guess ?) and persian readme, @yolowex and @yunline shall update them.

Sure thing, thanks for the tag

2023-07-15 09:59 UTC, Starbuck5 commented on docs/readmes/README.fr.rst
> +---------------------------------------------------------------------------------------------------
Why mark this README out of date? Did you make different changes to the English one and the French one?

If you change the English source and also the French translation, it's every other README that's out of date.

2023-07-15 11:32 UTC, Grimmys commented on docs/readmes/README.fr.rst
> +---------------------------------------------------------------------------------------------------
No, it is not saying that this README is out of date, but that it **might** be at any point in time.

It's more like a safeguard, warning people that they should not 100% trust the content of translation README files.

I think it's the policy you were talking about and then said it should not be added in the README file itself, maybe they just mixed up what you explained.

2023-07-15 12:25 UTC, bilhox commented on docs/readmes/README.fr.rst
> +---------------------------------------------------------------------------------------------------
> Why mark this README out of date? Did you make different changes to the English one and the French one?
> 
> If you change the English source and also the French translation, it's every other README that's out of date.

I updated also the English README (just added some web-links as I did in the French README).
As he said grimmys, the message says it could be out dated" (maybe I'll make it smaller).
Concerning other READMEs, yunline and yolowex got pinned in a message I sent a couple days ago, so they can change their README.

2023-07-16 08:09 UTC, Starbuck5 commented on docs/readmes/README.fr.rst
> +---------------------------------------------------------------------------------------------------
What's the point of having translated READMEs if we just put generic disclosures that they could be out of date at the top?
Especially since we actually know it's not out of date right now.

2023-07-16 08:54 UTC, bilhox commented on docs/readmes/README.fr.rst
> +---------------------------------------------------------------------------------------------------
So basically, the best I can do is removing this text in the French README, and mark each other README translation as out of date ?

2023-08-03 19:59 UTC, bilhox commented
Ready for reviews

2023-08-14 08:14 UTC, MyreMylar commented on README.rst
> +.. _pygame wiki: https://www.pygame.org/docs/
```suggestion
.. _pygame wiki: https://www.pygame.org/wiki/
```

2023-08-14 08:17 UTC, MyreMylar commented on docs/readmes/README.fr.rst
> +.. _wiki de pygame: https://www.pygame.org/docs/
```suggestion
.. _wiki de pygame: https://www.pygame.org/wiki/
```

2023-08-14 08:26 UTC, MyreMylar approved these changes
Overall these changes seem fine to me.

I suggest removing the links to both the old and new pygame wikis at the top of the links list as both are targeted more towards in-depth developers of pygame rather than average pygame enjoyers and we already have a link to the compilation part of the most recent wiki.

2023-08-14 08:26 UTC, MyreMylar commented on README.rst
> +.. _Old pygame wiki: https://www.pygame.org/wiki/
I fixed the links to these wikis - but I'm not sure we actually need to highlight them at the top of the links list like this.

We also already have a link to the compilation wiki page below. My suggestion is actually to clear out these links.

2023-08-14 14:19 UTC, bilhox commented on README.rst
> +.. _Old pygame wiki: https://www.pygame.org/wiki/
My bad, they're supposed to point to pygame/pygame-ce docs, not the wiki

2023-08-14 14:29 UTC, bilhox commented on docs/readmes/README.fr.rst
> +.. _wiki de pygame-ce: https://pyga.me/docs/
Shall I remove them then ?

2023-08-27 09:41 UTC, Starbuck5 approved these changes
Still doesn't have the warning message in the other readmes to tell translators to update, but at this point I just want to merge this in to resolve the conversation.

2023-08-27 09:41 UTC, merged