WIP: vector lerp and smoothstep
pygame-community/pygame-ce pull request #2254
Opened 2023-06-15 19:46 UTC by robertpfeiffer

2023-06-16 08:18 UTC, Starbuck5 commented on src_c/math.c
> +    PyMem_Free(self->coords);
Coords is not dynamic memory anymore on pygame-ce main.

It doesn't need to be allocated or freed, it can't be allocated or freed. See #2174

2023-06-16 08:26 UTC, robertpfeiffer commented on src_c/math.c
> +    PyMem_Free(self->coords);
Can you guess I wrote this in March and rebased it? Sorry to cause you trouble.

2023-06-18 07:00 UTC, Starbuck5 commented
I'm surprised that these functions do vectors and numbers. It seems reasonable to have the module functions just do numbers and the vector methods do vectors. There's already a way to lerp two vectors together, with vector.lerp.

2023-10-12 20:47 UTC, MyreMylar commented
I agree with Starbuck. We should add a `.smoothstep()` method to the two vector classes and then have scalar/number only versions at the submodule function level. 

That way there is one clear way to do it with either type of thing.

2023-10-14 08:01 UTC, MyreMylar requested changes
As commented above. Please make the module level functions for scalars only, and - if you like add the vector code for smoothstep as a method for the Vector classes.

This is to keep it consistent with the already existing `Vector2.lerp()` & `Vector3.lerp()`.

It has been a long ass time, for me to get around to reviewing this so also happy to take this over if you don't want to make any changes.

2023-11-05 20:25 UTC, dr0id commented on docs/reST/ref/math.rst
> +   and ``b``. The third parameter determines how far between ``a`` and
please add an explanation for the range of the `third parameter`

2023-11-05 20:26 UTC, dr0id commented on docs/reST/ref/math.rst
> +   Returns a Vector or number which is a smooth interpolation between ``a``
what is a smooth interpolation?

2023-11-05 20:27 UTC, dr0id commented on docs/reST/ref/math.rst
> +   and ``b``. The third parameter determines how far between ``a`` and
also here, define the range of the parameter I guess its `[0, 1]`

2023-11-05 20:29 UTC, dr0id commented on src_c/math.c
> +        t = t * t * (3.0f - 2.0f * t);
`(3.0f - 2.0f * t);`  this part needs some explanation I guess. Otherwise I wonder why 3 -2 = 1 => `1.0f * t` should be different than just `t`

2023-11-05 20:34 UTC, dr0id commented on docs/reST/ref/math.rst
> +   and ``b``. The third parameter determines how far between ``a`` and
maybe even write the formula: `a * value + (1-value) * b`
looking at this I would suggest to rename value to `t`

2023-11-05 20:39 UTC, dr0id commented on docs/reST/ref/math.rst
> +   and ``b``. The third parameter determines how far between ``a`` and
maybe also include the formula? like `a * t + (1-t) * b where t = t*t*(3 - 2*t) if t in [0, 1]`

suggestion: rename value to t

2023-11-26 12:06 UTC, MyreMylar approved these changes

2023-11-26 12:06 UTC, MyreMylar commented
Tidied this up a bit to respond to reviews.

2023-11-26 15:08 UTC, Matiiss approved these changes
Code looks great, seems to run fine, these are wonderful additions. Although I'm not sure why the vector methods don't use `METH_FASTCALL` too, but that can be changed later if necessary.

2023-11-26 16:55 UTC, merged