Improved `blits()` docs
pygame-community/pygame-ce pull request #2263
Opened 2023-06-19 20:06 UTC by itzpr3d4t0r

Follows #2259. This one aims to improve the `Surface.blits()` method docs.
Before:
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/4f3b160b-662b-48a1-8dff-33394f99abde)

After:
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/22bfbf48-3a51-4a35-a348-98997fb7c2d8)

2023-07-01 04:42 UTC, oddbookworm requested changes
I don't see any problems with this other than the comment I left

2023-07-01 04:42 UTC, oddbookworm commented on docs/reST/ref/surface.rst
> -      .. versionaddedold:: 1.9.4
I feel like this should be kept

2023-07-08 08:19 UTC, Matiiss reviewed
Looks pretty cool.
One more thing that should be changed is on line 136 it should probably be `doreturn=True` in the signature instead of `1`, since, well, `True` is more Pythonic.

2023-07-08 08:19 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +
Since you're indicating that what is below are notes, what about using bullet points instead of `Note:`? It would be sort of less repetitive and not as "noisy" IMO.

2023-07-08 08:19 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +          The ``doreturn`` parameter is a bool that controls the method's return value.
This is a bit repetitive of what you describe it does above in the parameter section, it's just longer, so it might as well be removed? Because it gets explained again in the Return section too.

2023-07-08 08:20 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +          The ``doreturn`` parameter is a bool that controls the method's return value.
Talking about `doreturn`

2023-07-08 09:48 UTC, itzpr3d4t0r commented on docs/reST/ref/surface.rst
> +
The thing is that imho doing so makes notes less readable and too compact:
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/788764ab-e6f0-4825-a69b-b2ddc630b80c)
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/d91a2ac1-c811-4d2f-a7b6-c95a75dba2d7)
So there's repetition but it's more readable.

2023-07-08 09:50 UTC, itzpr3d4t0r commented on docs/reST/ref/surface.rst
> +          The ``doreturn`` parameter is a bool that controls the method's return value.
I agree that there's repetition there but i don't think i should remove it, instead i'm trying to significantly shorten the return description and make the parameter description more dense.

2023-07-08 09:51 UTC, itzpr3d4t0r commented on docs/reST/ref/surface.rst
> -      .. versionaddedold:: 1.9.4
I've readded the tag

2023-07-09 10:14 UTC, Matiiss commented on docs/reST/ref/surface.rst
> +
Would it be possible to add space between bullet points?

2023-07-10 09:15 UTC, itzpr3d4t0r commented on docs/reST/ref/surface.rst
> +
Ok found a way to achieve that:
![image](https://github.com/pygame-community/pygame-ce/assets/103119829/9dd0f827-9921-45f2-9b0e-f0e723e9d702)
Already pushed the changes

2023-07-10 10:34 UTC, Matiiss approved these changes
LGTM

2023-08-14 09:24 UTC, MyreMylar approved these changes
LGTM 👍

2023-08-14 09:26 UTC, MyreMylar approved these changes
LGTM 👍 

Documentation seems clearer.

2023-08-14 09:27 UTC, merged