Enabling users to set the soundfont on midi playback
pygame-community/pygame-ce pull request #2274
Opened 2023-06-27 16:27 UTC by AlexanderGroeger

This PR adds a new `set_soundfont` function to the `pygame.mixer.music` module. This new feature allows game developers to leverage to pay a lower cost for storing music in their game by using smaller midi-formatted music tied with any soundfont they choose. 

**Technical Notice**
This PR relies on SDL_mixer's [Mix_SetSoundFonts](https://wiki.libsdl.org/SDL2_mixer/Mix_SetSoundFonts) function. At the initial commit, tests showed that setting the soundfont before loading and playing a MID file did not yield using the specified soundfont but instead fell back on the system default soundfont. This needs to be addressed before a merge will contribute anything.

2023-06-29 03:14 UTC, Starbuck5 commented
For the two failing runs you asked about clarification about:
- The code needs to be linted. Run `python setup.py format` after installing clang-format and black.
- Type stubs need to be added for this new API. See buildconfig/stubs/pygame/

2023-06-29 03:17 UTC, Starbuck5 commented on src_c/music.c
> +    Py_BEGIN_ALLOW_THREADS;
The BEGIN/END allow threads in these functions are unnecessary. They are very quick SDL functions based on the source, so there's no need to release the GIL for them.

2023-06-29 03:27 UTC, Starbuck5 commented on src_c/music.c
> +music_set_soundfont(PyObject *self, PyObject *arg)
This function doesn't have the SDL_mixer functionality of passing NULL to un-set soundfont settings.

Additionally, would it be better to accept a list (sequence) of strings rather than a semicolon separated list? It would make the implementation more complex, but it seems more Python-normal.

2023-06-29 03:29 UTC, Starbuck5 commented on src_c/music.c
> +music_set_soundfont(PyObject *self, PyObject *arg)
Implementation idea for joining strings into semicolon separated list.

Use PyUnicode_FromString to make a python string (";")
Use PyObject_CallMethod on the semicolon string to call string.join

Difficult part is error handling and making sure to avoid leaking objects by messing up reference counting.

2023-06-29 03:34 UTC, Starbuck5 commented on docs/reST/ref/music.rst
> +   not Windows 11. Other operation systems have not been tested.
*operating systems

Also Windows 11 is too specific, just say Windows. The SDL_mixer binary is the same for all Windows.

2023-06-29 03:35 UTC, Starbuck5 commented
As well as the type stubs the CI complained about, this PR also needs an entry into the pygame-ce test suite. See the tests/ directory.

2023-06-30 18:25 UTC, Starbuck5 commented on docs/reST/ref/music.rst
> +   .. versionaddedold:: 2.3.1
Versionaddedold is for pre-fork things. This should be versionadded.

2023-06-30 18:32 UTC, Starbuck5 commented on test/mixer_music_test.py
> +    def todo_test_set_soundfont(self):
These should be real tests rather than todo tests, since they're new.

For example, you could test that if you set soundfont and then get soundfont they're the same. (self.assertEqual the things)
You could could test that invalid arguments raise an error. (using self.assertRaises)
You could test that return types match expected.

2023-07-01 04:14 UTC, Starbuck5 commented on docs/reST/ref/music.rst
> +   not Windows 11. Other operation systems have not been tested.
Still says "operation systems" several places, which is a typo.

2023-07-01 04:15 UTC, Starbuck5 commented on test/mixer_music_test.py
> +    def todo_test_set_soundfont(self):
They also need to be renamed so they'll run, and because they're not "to do" if you've done them.

methods starting with test_ get run, so these won't run at all I believe.

2023-07-01 04:16 UTC, Starbuck5 commented on test/mixer_music_test.py
> +        # because this requires the memory is full
What?

2023-07-01 14:07 UTC, AlexanderGroeger commented on test/mixer_music_test.py
> +        # because this requires the memory is full
SDL_Mixer can only raise this error is there is no memory left to set the soundfont paths. See [Return Value](https://wiki.libsdl.org/SDL2_mixer/Mix_SetSoundFonts)

2023-07-05 16:01 UTC, ankith26 reviewed
First of all, thanks for contributing to pygame-ce! :cake: 

Left a couple of typing related reviews. Also I'd like to discuss the API a bit more? Should we go with SDL's semicolon-separated style? I wouldn't mind making the API more pythonic and having the users deal with sequences of strings

2023-07-05 17:30 UTC, AlexanderGroeger commented on buildconfig/stubs/pygame/mixer_music.pyi
> +def get_soundfont() -> str: ...
My pleasure. I like pygame-ce. I have been digging through source code to solve my Raspberry Pi 4 Optimizations discord help post, and while waiting for it to be resolved, I found something interesting to work on.

Thank you for correcting these stubs. I haven't done _that part_ of programming much.

In regards to the first inquiry, @Starbuck5 also brought this up consideration (on Discord I think?). My main reasons against passing a list of strings are two-fold: I wasn't comfortable with the programming of list arguments, and the API (intentionally) suggests there is only 1 soundfont, which ultimately only 1 will be used by SDL_Mixer because it uses the first valid soundfont file in the list of semi-colon-separated filepaths. I'm still unsure why this extra functionality would be helpful or ever used by developers, so I didn't want them to even bother thinking about it or being confused about how setting multiple soundfonts works internally, nevertheless, this fact is documented under `pygame.mixer.music.set_soundfont.`

2023-07-08 08:22 UTC, Starbuck5 commented on test/mixer_music_test.py
> +        # because this requires the memory is full
I read it as `There is no reasonable way to call this function, so it raises pgExc_SDLError`

You meant it as `There is no reasonable way to call this function that results in it raising pgExc_SDLError`

2023-07-09 19:52 UTC, ankith26 commented on test/mixer_music_test.py
> +    def todo_test_set_soundfont(self):
This review thread isn't resolved yet, the functions still have the `todo_` prefix that need removing, as mentioned above. The tests themselves look good so far, maybe for good measure we can throw in some typeerror/valueerror validator subtests?

2023-07-09 20:46 UTC, AlexanderGroeger commented on test/mixer_music_test.py
> +    def todo_test_set_soundfont(self):
Okay. Forgot about this. I think commit [cc8058b](https://github.com/pygame-community/pygame-ce/pull/2274/commits/cc8058bd9719b3cfcc49e3386af2b22682f08d6a) addresses this.

2023-07-11 08:24 UTC, Starbuck5 commented on docs/reST/ref/music.rst
> +   not Windows 11. Other operation systems have not been tested.
This is not resolved.

2023-07-11 12:43 UTC, AlexanderGroeger commented
> Question: why is this in mixer.music? Does this not apply to midi added as sounds (I'm on Windows so I can't test)? If it applies to all midi I'd think it should go in the mixer music.

I'm not sure what you're asking. It is in mixer.music, and you're suggesting it should go in mixer music....

2023-07-11 16:28 UTC, Starbuck5 commented
Sorry I mistyped. I meant why does it not go in mixer.

2023-07-11 20:47 UTC, AlexanderGroeger commented
I hadn't considered this. I tested `mixer.Sound` with the soundfont selected and confirmed it works on Raspbian. I can move the new API over to the mixer instead of within its music submodule.

2023-07-22 01:57 UTC, oddbookworm commented on src_c/_pygame.h
> +#define Py_IsNone(x) x == Py_None
```suggestion
#define Py_IsNone(x) (x == Py_None)
```

2023-07-22 01:57 UTC, oddbookworm commented on src_c/mixer.c
> +    const char *string_path = "";
```suggestion
    char *string_path = "";
```

2023-07-22 01:57 UTC, oddbookworm commented on src_c/mixer.c
> +    const char *paths;
```suggestion
    char *paths;
```

2023-07-22 01:59 UTC, oddbookworm commented on src_c/music.c
> +
If moving to mixer, please get rid of the music versions

2023-07-22 19:32 UTC, oddbookworm commented on src_c/mixer.c
> +    char *paths;
I guess you should put the `const` back...

2023-07-23 16:23 UTC, oddbookworm requested changes
Overall, looks good. I just have a few (mostly minor) nitpicks

2023-07-23 16:23 UTC, oddbookworm commented on src_c/doc/music_doc.h
> +#define DOC_MIXER_MUSIC_GETSOUNDFONT "get_soundfont() -> paths\nget the soundfont for playing midi music"
This documentation should be removed because it's no longer in `mixer.music`. I think `python setup.py docs --fullgeneration` should handle that for you and you just need to commit the result

2023-07-23 16:23 UTC, oddbookworm commented on docs/reST/ref/mixer.rst
> +   support for a that operation system.
grammar nitpick: "for a that operation system" -> "for that operating system"

2023-07-23 16:23 UTC, oddbookworm commented on docs/reST/ref/music.rst
> +
docs in `mixer.music` are unneeded because it no longer exists there

2023-07-23 16:23 UTC, oddbookworm commented on src_c/mixer.c
> +        return NULL;
I understand that braces aren't needed here because it's a single line, but I still suggest adding them to be more explicit

2023-07-23 16:23 UTC, oddbookworm commented on src_c/mixer.c
> +        paths_set = Mix_SetSoundFonts(string_path);
Same comment about braces

2023-07-23 16:23 UTC, oddbookworm commented on src_c/mixer.c
> +        return RAISE(pgExc_SDLError, SDL_GetError());
Same comment about braces

2023-07-23 16:23 UTC, oddbookworm commented on src_c/mixer.c
> +        return PyUnicode_FromString(paths);
same comment about braces

2023-07-23 16:23 UTC, oddbookworm commented on test/mixer_test.py
> +        self.assertEqual(mixer.get_soundfont(), "test1.sf2;test2.sf2")
Where you assert that `set_soundfont` returns `None` is a bit redundant. If it doesn't return `None`, then an error was raised and the test is failed anyway. I think you can just use the function

2023-07-23 18:51 UTC, itzpr3d4t0r commented on src_c/_pygame.h
> +#endif
Instead of having a separate macro that will later need to be removed, why couldn't you just put `path != Py_None` where you have the `!Py_IsNone(path)`?

2023-07-23 18:57 UTC, oddbookworm commented on src_c/_pygame.h
> +#endif
That was actually my suggestion. That macro is defined for python 3.10+ and I was going to do a followup PR using this macro and potentially some similar ones in many places throughout the codebase. Specifically, `Py_IsNone`, `Py_IsTrue`, and `Py_IsFalse` rather than the direct comparisons everywhere in the codebase. When 3.10 becomes our minimum supported version, it would be super simple just to remove 3 macros rather than do the PR then to update the code

2023-07-23 19:02 UTC, oddbookworm commented on src_c/_pygame.h
> +#endif
Maybe the true/false ones wouldn't be as useful because there aren't really many places we expect a boolean literal, but I know there are a large number of instances of `___ == Py_None` or `___ != Py_None` in the codebase that can be cleaned up this way

2023-07-23 19:10 UTC, itzpr3d4t0r commented on src_c/_pygame.h
> +#endif
Alright, was just curious, your explaination makes sense.

2023-07-26 04:22 UTC, Starbuck5 commented on src_c/mixer.c
> +    }
Rewritten with less nesting:

```
if (PyUnicode_Check(path)) {
    string_path = PyUnicode_AsUTF8(path);
}
else if (!Py_IsNone(path) {
    PyErr_SetString
}
```

2023-07-26 04:22 UTC, Starbuck5 commented on src_c/mixer.c
> +     DOC_MIXER_SETSOUNDFONT},
Could be `METH_O` instead of varargs, since it's just one arg.

2023-07-26 04:25 UTC, Starbuck5 commented on docs/reST/ref/mixer.rst
> +.. function:: set_soundfont
These docs look good. But I do think it seems heavy on "implementation detail" mentions about SDL_mixer.

2023-07-26 13:27 UTC, AlexanderGroeger commented on src_c/mixer.c
> +     DOC_MIXER_SETSOUNDFONT},
This change fails the test `TypeError: pygame.mixer.set_soundfont() takes exactly one argument (0 given)`

2023-07-26 13:28 UTC, AlexanderGroeger commented on src_c/mixer.c
> +    }
[4d35782](https://github.com/pygame-community/pygame-ce/pull/2274/commits/4d3578287f8ae553421917b56278cef44df570dc)

2023-07-26 13:40 UTC, AlexanderGroeger commented on docs/reST/ref/mixer.rst
> +.. function:: set_soundfont
[1560c3a](https://github.com/pygame-community/pygame-ce/pull/2274/commits/1560c3ac3c1007de226cc0d81a953cc1672fb261)

2023-07-26 16:19 UTC, AlexanderGroeger commented
One final note here. Perhaps we can learn something from this [issue](https://github.com/pygame/pygame/issues/2980) to get soundfonts working on windows.

2023-07-28 06:23 UTC, Starbuck5 commented on src_c/mixer.c
> +     DOC_MIXER_SETSOUNDFONT},
Ah, ok. Doesn't work because it's also supposed to take 0 args.

2023-07-28 06:26 UTC, Starbuck5 commented on docs/reST/ref/mixer.rst
> +.. function:: set_soundfont
That isn't really what I was concerned about.

Each function has an entire (short) paragraph saying exactly what function this refers to in SDL_mixer
Each function makes sure to tell the user the soundfont setting is stored in SDL_mixer

IMO this is unnecessary information.

2023-07-28 11:49 UTC, AlexanderGroeger commented
I tried including fluidsynth in the windows build config but didn't have the compiling experience or intuition to make the SDL_Mixer use soundfonts on windows, so I'd prefer to wrap up this PR and make an issue regarding this.

2023-07-28 12:17 UTC, ankith26 commented on docs/reST/ref/mixer.rst
> +   are missing. If ``path`` is an empty string or not specified, any specified soundfont paths
```suggestion
   are missing. If ``path`` is an empty string or the default (``None``), any specified soundfont paths
```
minor update to the wording, basically to mention that ``None`` is allowed, and gives same behavior as the empty string

2023-07-29 05:46 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada: 

PS: to the person merging this, please squash and merge this PR

2023-07-29 08:54 UTC, Starbuck5 approved these changes
Nice work getting this up to be fully ready!

2023-07-29 09:01 UTC, merged