Fixed Rect and FRect typing to use setters and getters
pygame-community/pygame-ce pull request #2297
Opened 2023-07-08 15:33 UTC by oddbookworm

dickerdackel (Discord) pointed out that rect positioning properties have lint problems with anything except a tuple, but the code accepts more. So, this PR is to fix that issue for both `Rect` and `FRect`. I also updated `size`

2023-07-08 17:36 UTC, zoldalma999 commented on buildconfig/stubs/pygame/rect.pyi
> +        """The bottom left corner of the rect. Floats will be truncated to ints"""
We don't leave documentation in stub files

Also, minor nitpick, there is a space after the function name here. Same goes for the FRect version

2023-07-09 00:31 UTC, oddbookworm commented on buildconfig/stubs/pygame/rect.pyi
> +        """The bottom left corner of the rect. Floats will be truncated to ints"""
fixed

2023-07-09 19:43 UTC, ankith26 approved these changes
LGTM, thanks for the PR :cake:

2023-07-09 20:40 UTC, ankith26 requested changes

2023-07-09 20:40 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
>      right: int
Actually I just remembered, these should technically be properties too. Even in plain ol' `Rect`, you are allowed to do something like `rect_obj.right = 8.6` and this doesn't error, but the argument is truncated/rounded

2023-07-09 21:48 UTC, oddbookworm commented on buildconfig/stubs/pygame/rect.pyi
>      right: int
Pretty big commit incoming due to a conversation between us on Discord

2023-07-10 11:22 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
>      @overload
A few lines above, `scale_by` function should return `Self` and not `Rect`

2023-07-10 11:22 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[RectTuple[_N], _V], values: bool = ...
I don't get why this is being changed. I guess `RectValue` is correct here? I don't see the need for `RectTuple[_N]`, it's just a narrower-than-needed type

2023-07-10 11:22 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> -    ) -> Tuple[_K, "Rect"]: ...
I don't get why this overload is being removed. According to the code, this is a valid signature

2023-07-10 14:14 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[RectTuple[_N], _V], values: bool = ...
Yeah, but I'd still prefer it to be a `RectValue`. The user could still have a custom sequence-like object that is hashable (that isn't a tuple - weird usage, I'm not saying this would be common). As for non-hashable types that can pass under `RectValue`, I'm pretty sure mypy catches that error anyways, regardless of what the key is type'd as

2023-07-11 12:29 UTC, oddbookworm commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[RectTuple[_N], _V], values: bool = ...
Discussed in Discord (if you can even call it an actual discussion):
I’m still not a fan of leaving this as possibly accepting a nonhashable type, but I agree with you that it can be more closely looked at sometime in the future.

2023-07-11 16:11 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +    ) -> Tuple[_K, RectValue]: ...
Not really your PRs issue, but I also noticed another fix you can do while you are at fixing this section. The return value of `collidedict` is allowed to be `None`, so wrap it in an `Optional`

2023-07-11 16:20 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
>      @overload
This is not really your PRs fault, but if you want to fix it, there's a small issue in `scale_by` typing here. The `y` argument should be optional (so, something like `y: float = ...` should do)

2023-07-11 16:41 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[_K, RectValue], values: bool = False
AFAIK there is no convenient way to properly convey "use this overload if this flag is falsey else use the next one" so next the best option we got RN is to actually leave this as `values: bool` as this somewhat conveys that the above overload is default, and not this.

2023-07-12 13:41 UTC, oddbookworm commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[_K, RectValue], values: bool = False
I think I have found a solution, but I'd welcome feedback. Adding a new commit with the solution included

2023-07-12 14:12 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +RectLike = TypeVar("RectLike", bound=RectValue, covariant=True)
This is useful, I guess it would be useful in more places in this file, now that you've added this. One place I can think of is `Sequence[RectValue]` should actually be `Sequence[RectLike]`. While you are at it, maybe also change the naming a bit would help to not confuse `RectValue` and `RectLike`. Typically typevars are prefixed with an underscore, and another convention in the python ecosystem is to suffix covariant typevars with `_co`

2023-07-13 01:21 UTC, oddbookworm commented on buildconfig/stubs/pygame/rect.pyi
> +RectLike = TypeVar("RectLike", bound=RectValue, covariant=True)
How's the new version?

2023-07-13 01:23 UTC, oddbookworm commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[_K, RectValue], values: bool = False
I wasn't able to come up with a better solution for general "truthiness". And honestly, I don't see it being a huge problem, I can't imagine many scenarios where an explict bool wouldn't be the cleanest option anyway

2023-07-13 11:48 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +RectLike = TypeVar("RectLike", bound=RectValue, covariant=True)
LGTM

2023-07-13 11:53 UTC, ankith26 commented on buildconfig/stubs/pygame/rect.pyi
> +        self, rect_dict: Dict[_K, RectValue], values: bool = False
Fair enough

2023-07-13 11:59 UTC, ankith26 approved these changes
I like how this PR started with one area improvement and quickly spiralled into all round general improvements. 
Thanks a lot! :sunglasses: 

PS to the person merging this: Please squash and merge this PR

2023-07-13 20:10 UTC, zoldalma999 approved these changes
Looks good to me! Thanks!

2023-07-13 20:12 UTC, merged