Add `get_surface()` for Window class
pygame-community/pygame-ce pull request #2350
Opened 2023-07-26 08:23 UTC by yunline

```py
import pygame
from pygame._sdl2 import video

pygame.init()

win = video.Window()
sf = win.get_surface()
sf.fill((255,0,0))
win.update_from_surface()
sf.fill((255,255,255))
win.update_from_surface((100,100,100,100),(300,300,100,100))

while 1:
    pygame.event.get()
```
<details>

<summary>Screenshot</summary>
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/3b350958-089a-47f9-af2c-d05b3bf9b854)
</details>

2023-08-27 08:59 UTC, Starbuck5 commented on docs/reST/ref/sdl2_video.rst
> +      .. versionaddedold:: 2.4.0
Should be `versionadded`. `versionaddedold` is for pygame, versionadded is for pygame-ce

2023-10-02 05:52 UTC, Starbuck5 commented on src_c/window.c
> +    }
If it's borrowed shouldn't the surface be managed by the display.c event watch?

2023-10-02 05:58 UTC, Starbuck5 commented on src_c/window.c
> +        self->surf->surf = NULL;
Does the surface need SDL_FreeSurface here?

2023-10-02 05:59 UTC, Starbuck5 commented on src_c/window.c
> +        self->surf->surf = NULL;
Actually if you don't NULL it here the natural pygame surface dealloc will take care of it, right?

2023-10-02 06:03 UTC, Starbuck5 commented on src_c/window.c
> +    }
Same here shouldn't you decref the pygame surface object and let that handle the internal SDL_Surface?

2023-10-02 06:07 UTC, Starbuck5 commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: update_from_surface
There's a real question of what we want to expose here.

Updating with rects is a niche use case, and we moved all the examples to use "flip" instead of "update"-- so should we continue that here and only expose the simpler functionality under the name "flip" ?

We could add both flip and update here.

And on names-- my first thought on "update_from_surface" is that we should just call it "update," but maybe update from surface is better.

Just starting this as a discussion.

2023-10-02 11:02 UTC, zoldalma999 commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: update_from_surface
I don't think we should expose `display.update` like partial screen updates. It is hard to actually do for the user, and does not have much speedups.

2023-10-11 20:38 UTC, MyreMylar commented on docs/reST/ref/sdl2_video.rst
> +   .. method:: update_from_surface
I tested this a bit here in #2514

In short, the passing the rect_list adds almost nothing practically performance-wise to CPU rendering. I don't think we should look to duplicate it into the future.

2023-10-13 03:11 UTC, yunline commented on src_c/window.c
> +        self->surf->surf = NULL;
> Does the surface need SDL_FreeSurface here?

According to [SDL wiki](http://wiki.libsdl.org/SDL2/SDL_GetWindowSurface): "This surface will be freed when the window is destroyed. Do not free this surface."

> Actually if you don't NULL it here the natural pygame surface dealloc will take care of it, right?

I set the internal surface to NULL to make the pygame surface invalid, since the internal surface has been freed by SDL. 
If users want to operate on this surface they will get an error.
```py
win = Window()
sf = win.get_surface()
win.destroy()
sf.fill((0,0,0))
```
```
Traceback (most recent call last):
  File "x:\python\pygame_test\window_surface.py", line 11, in <module>
    sf.fill((0,0,0))
pygame.error: Surface is not initialized
```

2023-10-13 03:25 UTC, yunline commented on src_c/window.c
> +    }
fixed

2023-10-15 05:15 UTC, Starbuck5 commented on src_c/window.c
> +        self->surf->surf = NULL;
Okay, the behavior looks good, thanks for the additional context.

Can some of that be added there as a comment, I feel its hard to understand all the ramifications there.

2023-10-15 15:17 UTC, MyreMylar requested changes
Overall this works great on windows OS and lets me use the window class to do familiar CPU blitting and drawing.

I agree that we should remove the list of rects overload from `update_from_surface()` however. The realistic speed ups from this functionality on most modern platforms are too minor, and too niche, to justify continuing it and the confusion it brings when users try to use it to speed up their games. They put a bunch of effort in to maintain an accurate list of sections of the screen that have changed this loop, only to then find that it in many cases it actually makes the program run slower because they have more than 15 or so moving objects in their application and the per-rectangle-cost of updating has exceeded the saving from the reduced area updated. 

See #2514 for more discussion.

2023-10-16 19:01 UTC, MyreMylar commented on test/window_test.py
> +        win.size = (100, 100)
do we need to do a `pygame.event.pump()` here to make sure the event watch handler is triggered?

2023-10-26 07:17 UTC, yunline commented on test/window_test.py
> +        win.size = (100, 100)
Auto resize event watch is deleted when `pygame.quit()` is called.
This is the cause of this bug,
So I set the event watch when `pygame.init()` and the bug should be fixed now.

2023-10-26 07:19 UTC, ankith26 commented on src_c/window.c
> -    SDL_AddEventWatch(_resize_event_watch, NULL);
Just commenting because I feel this change could be independent of this PR. I think it could fix another one of those init+quit+init issues.

But I would prefer moving this to the display specific init function instead, instead of messing with `base.c`. The diff would also be much less I reckon

2023-10-26 07:31 UTC, ankith26 commented on src_c/window.c
> -    SDL_AddEventWatch(_resize_event_watch, NULL);
My bad, I assumed the changes were happening in `display.c` but I now see they are in `window.c`. My suggestion would still be along similar lines, create an "init-quit hook" (see what `display.c` does) for window, and set/unset this filter from there.

2023-10-26 19:19 UTC, MyreMylar approved these changes

2023-10-27 06:56 UTC, MyreMylar approved these changes

2023-10-28 04:57 UTC, ankith26 commented on src_c/window.c
> +     "auto quit for _window module"},
Yes these hooks look good, but I think they should be called from the display init/quit hook instead of the base pygame init/quit function (like how event and time are handled right now). This is so that if someone only does `pygame.display.init()` instead of the full `pygame.init()` we would still want the window hooks to run, as they are related

2023-10-31 08:24 UTC, yunline commented on src_c/window.c
> +     "auto quit for _window module"},
fixed

2023-11-01 20:19 UTC, MyreMylar approved these changes

2023-11-19 10:13 UTC, Starbuck5 approved these changes
Let's get this in. Thanks yunline!

Note from testing: window resize doesn't work properly when using a borrowed window--
```py
import pygame
from pygame._sdl2 import Window

pygame.init()

screen = pygame.display.set_mode((500,500))
window = Window.from_display_module()

window_screen = window.get_surface()
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_1:
                window.size = (500,500)
            if event.key == pygame.K_2:
                window.size = (700,700)

    window.update_from_surface()
pygame.quit()
```

After this is merged I have several things I'd like to do myself on this. I want to change `update_from_surface()` to `flip()`, I'd like to write some things in the docs about how it's analogous to set_mode and flip(), and I'd like to add a standalone window software rendering example.

The way forward on this is getting this PR merged. @yunline I'm leaving it to you to merge-- I think some of the commits could be squashed down, but it's up to your discretion.

2023-11-19 10:41 UTC, merged