Added `Window.(min|max)imum_size`
pygame-community/pygame-ce pull request #2364
Opened 2023-07-30 22:58 UTC by Matiiss

Ported this SDL2 functionality:
- https://wiki.libsdl.org/SDL2/SDL_SetWindowMinimumSize
- https://wiki.libsdl.org/SDL2/SDL_GetWindowMinimumSize
- https://wiki.libsdl.org/SDL2/SDL_SetWindowMaximumSize
- https://wiki.libsdl.org/SDL2/SDL_GetWindowMaximumSize

Some code to play with:
```py
import pygame
import pygame._sdl2 as pg_sdl2  # noqa

WIDTH, HEIGHT = 640, 360
FPS = 60

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT), flags=pygame.RESIZABLE)
clock = pygame.Clock()

window = pg_sdl2.Window.from_display_module()
window.minimum_size = (WIDTH / 2, HEIGHT / 2)
window.maximum_size = (WIDTH * 2, HEIGHT * 2)
print(window.minimum_size)
print(window.maximum_size)

running = True
while running:
    dt = clock.tick(FPS) / 1000
    screen.fill("black")
    
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            running = False
    
    pygame.display.flip()
```

As for the tests, I'm not sure, probably one option is adding those after this gets merged https://github.com/pygame-community/pygame-ce/pull/2230
But also the underlying API would fail silently anyways. (still can check that setting values means they can be retrieved using same API)

2023-07-31 00:53 UTC, yunline requested changes

2023-07-31 00:53 UTC, yunline commented on src_c/window.c
> +    if (!out)
We don't need to check if out is NULL here. You can directly return out.

2023-07-31 00:53 UTC, yunline commented on src_c/window.c
> +    if (!out)
You can directly return out here.

2023-07-31 01:13 UTC, yunline commented
```py
window.minimum_size = (640,481)
window.maximum_size = (640,480)
print(window.minimum_size) # (640, 481)
print(window.maximum_size) # (0, 0)

window.maximum_size = (640,480)
window.minimum_size = (640,481)
print(window.minimum_size) # (0, 0)
print(window.maximum_size) # (640, 480)
```

Currently, if maximum_size < minimum_size, it returns (0, 0), which is weird.
Let's raise an error if user is trying to set an invalid value.

2023-07-31 21:46 UTC, Matiiss commented
> ```python
> window.minimum_size = (640,481)
> window.maximum_size = (640,480)
> print(window.minimum_size) # (640, 481)
> print(window.maximum_size) # (0, 0)
> 
> window.maximum_size = (640,480)
> window.minimum_size = (640,481)
> print(window.minimum_size) # (0, 0)
> print(window.maximum_size) # (640, 480)
> ```
> 
> Currently, if maximum_size < minimum_size, it returns (0, 0), which is weird. Let's raise an error if user is trying to set an invalid value.

Yeah, I suppose raising an exception here should make it easier for users to debug this issue if it ever arises, although I suppose it could also just be documented instead (it is now too, kind of, docs now mention that an error will be raised and why) and the code could raise a warning?

2023-07-31 21:47 UTC, Matiiss commented
Also speaking of that `if (!out)` redundancy, `window_set_size` has it too, could that be handled in this PR too or new PR?

2023-08-01 01:13 UTC, yunline commented
> although I suppose it could also just be documented instead (it is now too, kind of, docs now mention that an error will be raised and why) and the code could raise a warning?

In SDL3, `SDL_SetWindowMaximumSize()` returns an `int` instead of `void`, and sets an error when maximum is smaller than minimum. So I think it's necessary to raise an exception than a warning.

https://github.com/libsdl-org/SDL/blob/8f00d7856d2ddaf08349c24726471a2d952570f9/src/video/SDL_video.c#L2767-L2771

2023-08-01 11:26 UTC, yunline approved these changes
LGTM

2023-08-03 08:17 UTC, Starbuck5 commented on buildconfig/stubs/pygame/_sdl2/video.pyi
> +    def maximum_size(self, value: Coordinate) -> None: ...
I feel like the point of making them properties is so that you can type the getter/setter differently.

But the getter is not returning Coordinate, it's returning a Tuple of ints.

2023-08-03 10:04 UTC, Matiiss commented on buildconfig/stubs/pygame/_sdl2/video.pyi
> +    def maximum_size(self, value: Coordinate) -> None: ...
Yes, indeed. Also that then makes sense for them to be properties since they're typed differently.

2023-08-14 10:25 UTC, MyreMylar approved these changes
LGTM. These sorts of functions are pretty useful for GUI apps with resizable windows.

2023-08-14 10:26 UTC, MyreMylar commented
Conflicts need resolving. Merge after 2.3.2.

2023-08-21 05:36 UTC, Starbuck5 commented
> Merge after 2.3.2.

Main is on 2.4 already, so we can merge as soon as @Matiiss resolves the conflicts. Scanned through it myself and everything looks good.

2023-08-21 05:36 UTC, Starbuck5 approved these changes

2023-08-21 21:22 UTC, merged