made capitalization and periods more consistent across math document
pygame-community/pygame-ce pull request #2368
Opened 2023-07-31 22:38 UTC by ehjohnson154

Updated capitalization and periods to more closely adhere to proper grammar. All italic descriptions and non-italic sentences are treated closer to English and have had capitals and periods added where needs be.

2023-08-01 01:01 UTC, oddbookworm requested changes
You also need to regenerate the documentation headers that are generated from the `math.rst` file. Run `python setup.py docs --fullgeneration` and commit the changed C header file as well. You will need some basic setup done to generate docs, such as installing sphinx via `pip` (and I'm not sure what else offhand)

2023-08-01 20:59 UTC, Matiiss requested changes
Thanks for the PR, lovely to see new contributors 😁
Here are a couple of changes you should make to your PR though:

- You apparently skipped `clamp`: 
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/ef656244-152c-49e8-b71b-f933445d0931)
and `Vector3`:
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/65f78cff-77ce-425c-8df4-4d166226b250)
and `Vector3.move_towards_ip`:
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/3a99cf33-1d67-427a-9387-dbf159129d93)
and `Vector3.epsilon`:
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/751d9e27-e6c6-4afe-b161-70a4e558499c)

- Also since this is about consistency, it appears that sometimes _v_ in _vector_ is capitalized and sometimes it's not, it probably should not be capitalized in descriptions and summaries. It's also sometimes referred to as `Vector2` **in descriptions** and that should also probably be changed to a plain _vector_. (Do not change it on the `:sg:` lines).

- In all the `rotate` methods the period should be inside the parentheses for "_(Note that due to pygame's inverted y coordinate system, the rotation will look clockwise if displayed)._".

- Here the sentences _Please leave clamp_magnitude feedback with authors_ should probably end with an exclamation mark. Although the whole experimental note might be removed, but not sure about it yet.

- Also something should be done about that bullet list in `epsilon`, I think.

- There're also these inconsistencies (not entirely sure what to do about them, perhaps, just add a description to the ones lacking it or remove it from the ones that have it because they mostly just reiterate the summary, except for `Vector2.cross`, so maybe for Vector2 it may stay as is, but for Vector3 you might as well remove the description from `Vector3.cross`):
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/017cce71-e75d-43f0-a64d-2958e5b8764f)
![image](https://github.com/pygame-community/pygame-ce/assets/83066658/99c11180-3998-4a3d-b522-890f6c28b508)

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>        theorem: ``vec.magnitude() == math.sqrt(vec.x**2 + vec.y**2)``
Line 102 should end in a period, so `... theorem: ``...``.`

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>        Pythagorean theorem: ``vec.length() == math.sqrt(vec.x**2 + vec.y**2)``
Same thing here, line 123 should end with a period, after the theorem explanation

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: rotate
Period should be inside the parentheses.

Referring to "_(Note that due to pygame's inverted y coordinate system, the rotation will look clockwise if displayed)._".

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: rotate_rad
Period should be inside the parentheses.

Referring to "_(Note that due to pygame's inverted y coordinate system, the rotation will look clockwise if displayed)._".

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: rotate_ip
Period should be inside the parentheses.

Referring to "_(Note that due to pygame's inverted y coordinate system, the rotation will look clockwise if displayed)._".

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: rotate_rad_ip
Period should be inside the parentheses.

Referring to "_(Note that due to pygame's inverted y coordinate system, the rotation will look clockwise if displayed)._".

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: angle_to
The sentence _Example demonstrating the angle returned_ should probably be moved to before the image and end with a colon, otherwise it should end with a period.

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: clamp_magnitude_ip
The sentence _If only one argument is passed, it is taken to be the max_length_ should end with a period, same thing in `clamp_magnitude`

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>        theorem: ``vec.magnitude() == math.sqrt(vec.x**2 + vec.y**2 + vec.z**2)``
Again missing a period after the theorem line.

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>        ``vec.length() == math.sqrt(vec.x**2 + vec.y**2 + vec.z**2)``
Again missing a period after the theorem line.

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>        Returns a new vector that points in the direction as if self would bounce
There's a typo in the description where _of_ should change to _off_ in _bounce of a surface_.

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: move_towards
Since the method name contains _towards_ it makes sense for summaries and descriptions to use the same spelling, so check for that in Vector2 _towards_ methods too.

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>        Returns the projected vector. This is useful for collision detection in finding the components in a certain direction (e.g. in direction of the wall).
_in direction of **a** wall_

2023-08-01 20:59 UTC, Matiiss commented on docs/reST/ref/math.rst
>     .. method:: clamp_magnitude_ip
_It is taken to be the max_length_ should end with a period, same for `clamp_magnitude`

2023-08-14 10:55 UTC, MyreMylar reviewed
It should be noted that currently most of these :sl: slug lines are not capitalised and do not end with a period across the entirety of the pygame documentation.

e.g.:

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/2ebf68c2-fe0b-4688-a4c1-693d595bca79)

Not making a judgement either way on what is better, but we should probably be consistent with out capitalisation and periods across all documentation pages for these lines.

I'd lean towards proper capitalisation and full stops/periods everywhere, but that is my preference.

2023-10-15 04:09 UTC, Starbuck5 commented
I'm going to go ahead and close this, since it's been inactive for a long time, and as Myre points out this makes the math modules docs less consistent with the rest of the docs. If you'd like to try again on this in the future feel welcome.

I also agree the rest of the docs could change in this regard.

It seems like Matiiss did a deep proofread of this entire module document and had ideas for improvement that were added as feedback to this PR even though they were unrelated to the actual content of the PR? How about you make that a standalone PR @Matiiss.

2023-10-15 04:09 UTC, closed without merging