added mixer.Channel.get_id
pygame-community/pygame-ce pull request #2369
Opened 2023-08-01 04:00 UTC by oddbookworm

2023-08-02 08:49 UTC, Starbuck5 commented
@oddbookworm circleci is failing for you but it's passing on main. After scratching my head for a second on this, I believe it's because it's pulling the circleci config from YOUR main branch, rather than the PR branch or pygame-ce's main branch.

@ankith26 tagging for visibility. I haven't thought about mitigation yet, but presumably we'd want circleci to use the config of the PR branches themselves, is there a way to have that?

2023-08-02 11:59 UTC, oddbookworm commented
Alright, I pulled in the most recent merges to both my own `main` and the PR branch

2023-08-03 08:22 UTC, Starbuck5 commented on docs/reST/ref/mixer.rst
> +      ..versionadded:: 2.3.1
How is this function intended to be used?

The version added is 2.4.0 .

2023-08-04 17:11 UTC, ankith26 commented
> I haven't thought about mitigation yet, but presumably we'd want circleci to use the config of the PR branches themselves, is there a way to have that?

Yes I'd like that too, but unfortunately there's nothing much we can do about it AFAIK.

2023-08-14 10:28 UTC, MyreMylar commented on docs/reST/ref/mixer.rst
> +      ..versionadded:: 2.3.1
```suggestion
      ..versionadded:: 2.4.0
```

2023-08-14 10:34 UTC, MyreMylar approved these changes
LGTM 👍 

It's not earth shattering as users could already keep track of their own channel IDs mapping to channels if they wanted, but might make it slightly easier to find out/debug which channel a sound is playing on with a simple number.

2023-08-14 18:51 UTC, ankith26 requested changes
Since this is new API, how about considering making this a read-only property instead? Fewer characters to type and also pythonic

2023-08-14 23:29 UTC, oddbookworm commented
> Since this is new API, how about considering making this a read-only property instead? Fewer characters to type and also pythonic

I'll push a commit soon for this

2023-08-15 01:02 UTC, oddbookworm commented
force push to fix a half-complete commit

2023-08-15 07:25 UTC, ankith26 approved these changes
LGTM, thanks for the PR :+1:

2023-08-15 07:36 UTC, MyreMylar approved these changes
LGTM 👍

2023-08-19 16:17 UTC, merged