Fix caution visual bug for dark theme
pygame-community/pygame-ce pull request #2418
Opened 2023-08-23 16:22 UTC by Notenlish

Old:
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/84f85e60-9337-483d-8c26-74cff21dccc1)
New:
![image](https://github.com/pygame-community/pygame-ce/assets/71970100/34a43e3b-8a11-4ae2-9bef-bbc8dae9ae72)

reported by @yunline

2023-08-23 16:35 UTC, Notenlish commented
https://github.com/pygame-community/pygame-ce/issues/2417

2023-08-24 02:25 UTC, yunline requested changes
Thanks for your fix.
However, there are 2 bugs mentioned in the issue, and you just fixed one of them.
The another one is in https://pyga.me/docs/tutorials/en/move-it.html
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/ece46df0-d2fe-4e55-a112-966ee7edf842)
![image](https://github.com/pygame-community/pygame-ce/assets/31395137/e1ca60c4-dc4e-4738-a638-c6678cdb571b)

2023-08-24 07:01 UTC, Starbuck5 commented
@yunline It's fine for this PR to only fix one of the problems, as long as the original issue doesn't get closed.

2023-08-25 07:50 UTC, Starbuck5 commented on docs/reST/themes/classic/theme.conf
> +dark_cautionbgcolor         = rgb(255 25 25 / 30%)
Opacity in the css? This is single-handedly bringing pygame-ce into the future :) /s

2023-08-25 07:59 UTC, novialriptide commented on docs/reST/themes/classic/theme.conf
> +dark_cautionbgcolor         = rgb(255 25 25 / 30%)
Should be a hex value. `/ 30%` shouldn't be here as well.

2023-08-25 08:22 UTC, Starbuck5 commented on docs/reST/themes/classic/theme.conf
> +dark_cautionbgcolor         = rgb(255 25 25 / 30%)
I think it's fine for it to have opacity. It looks good in the output.

2023-08-26 10:50 UTC, rethanon commented
Just wanted to point out that we already have a color we use for a warning in the _sdl2 docs, should we try to be consistent and use the same color?
![image](https://github.com/pygame-community/pygame-ce/assets/54457966/b2475372-bc3d-424d-90a7-17928f349109)

2023-08-26 11:00 UTC, rethanon commented
Which I guess does lead to the question, rather than just apply changes to the dark mode, could we apply the background color/text color universally like we have for the above warning in sdl2_video?

2023-10-08 10:50 UTC, MyreMylar commented on docs/reST/themes/classic/static/pygame.css_t
> +
```suggestion
.dark-theme div.caution {
    background-color: {{ theme_dark_cautionbgcolor }};
    border: 1px solid;
    border-color: {{ theme_dark_cautionbordercolor }};
}

```

2023-10-08 10:50 UTC, MyreMylar commented on docs/reST/themes/classic/theme.conf
> +dark_cautionbgcolor         = rgb(255 25 25 / 30%)
```suggestion
dark_cautionbgcolor         = rgb(255 25 25 / 30%)
dark_cautionbordercolor     = rgb(255 60 60)
```

2023-10-08 10:53 UTC, MyreMylar commented
I think it is fine for us to have different colours for Warning and Caution boxes.

I applied the suggestions from the earlier comments so we can get this merged.

Caution boxes in the dark theme now look like this:

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/b662976a-7530-4e06-9b74-43300a304a46)

2023-10-08 10:54 UTC, MyreMylar approved these changes
LGTM now.

2023-10-08 10:54 UTC, merged