Optimize vector parsing in math.c
pygame-community/pygame-ce pull request #2443
Opened 2023-09-10 02:25 UTC by Starbuck5

2023-09-10 08:15 UTC, dr0id commented on src_c/math.c
> +// occurred. If 0 is returned, the error flag will not normally set. Callers
```suggestion
// occurred. If 0 is returned, the error flag will not normally be set. Callers
```

2023-09-10 08:15 UTC, dr0id commented on src_c/math.c
> +            }
what happens here in the else case?

2023-09-10 08:34 UTC, Starbuck5 commented on src_c/math.c
> +            }
It proceeds down to check if it’s a Python sequence and parse that out.

2023-09-10 08:41 UTC, dr0id commented on src_c/math.c
> +            }
ah, must have missed that

2023-09-10 15:42 UTC, ankith26 commented on src_c/math.c
> +        tmp = PySequence_GetItem(obj, i);
if you want to squeeze a little more performance, can use [`PySequence_ITEM`](https://docs.python.org/3/c-api/sequence.html#c.PySequence_ITEM) here. I'm not sure how much it will improve things, but it definitely won't downgrade performance

2023-09-10 15:42 UTC, ankith26 commented on src_c/math.c
> +    }
Could also experiment with adding list/tuple fastpaths before the generic sequence handling

2023-09-10 18:10 UTC, Starbuck5 commented on src_c/math.c
> +        tmp = PySequence_GetItem(obj, i);
Good idea

2023-09-10 18:12 UTC, Starbuck5 commented on src_c/math.c
> +    }
I’m more concerned about getting the happy path (vector arg) faster than about getting other things faster. That’s a good future suggestion but I don’t want to go for it in this PR.

2023-09-10 19:16 UTC, itzpr3d4t0r commented on src_c/math.c
> +    }
Then i think you should somehow get rid of those memcpy calls for the happy path.

2023-09-10 21:10 UTC, Starbuck5 commented on src_c/math.c
> +    }
I actually did make an attempt on that— it would only work sometimes because sometimes a copy is actually needed— but I found it was actually slower in my initial testing

2023-09-11 04:12 UTC, Starbuck5 commented on src_c/math.c
> +// occurred. If 0 is returned, the error flag will not normally set. Callers
Fixed, thanks.

2023-09-11 04:14 UTC, Starbuck5 commented on src_c/math.c
> +        tmp = PySequence_GetItem(obj, i);
Done. Benchmark results updated. It went from 18% -> 20% faster for sequences, although it also went from 7% -> 5.5% for vectors (showing volatility of the benchmarks instead of an actual slowdown, I think).

My current benchmark results are averages of 4 runs of main versus 4 runs of this PR.

2023-09-11 09:52 UTC, itzpr3d4t0r requested changes
Nice PR. I'm sure we can build on it further in the future, the whole module is full of places we can work on.
I'd like to suggest you use mean(timeit.repeat(...)) with a high repeat number for benchmarking instead of a single timeit that accumulates runtimes. This is because it yields smoother and better results overall since outliers won't count towards increasing the times in a suboptimal way.

2023-09-11 09:52 UTC, itzpr3d4t0r commented on src_c/math.c
> +        Py_DECREF(tmp);
Should be XDECREF here.

2023-09-11 09:52 UTC, itzpr3d4t0r commented on src_c/math.c
> +        if (tmp != NULL) {
Could just be `if (tmp)`

2023-09-12 03:39 UTC, Starbuck5 commented on src_c/math.c
> +        if (tmp != NULL) {
I prefer it written out explicitly.

2023-09-12 03:40 UTC, Starbuck5 commented on src_c/math.c
> -    }
> code that was actually more performant than the current one

That's not what the benchmarks say.

2023-09-12 04:09 UTC, Starbuck5 commented
> I'd like to suggest you use mean(timeit.repeat(...)) with a high repeat number for benchmarking instead of a single timeit that accumulates runtimes. This is because it yields smoother and better results overall since outliers won't count towards increasing the times in a suboptimal way.

I swapped out my timeit.timeit call with `min(timeit.repeat(statement, globals=globals, repeat=1000, number=1000)) * 1000` and got the following results:

<details>
<summary>Results</summary>

```
vec2_1.move_towards(vec2_2, 4): 0.16205 (6.774% faster)
vec2_1.move_towards(vec2like, 4): 0.1976 (14.809% faster)
vec2_1.move_towards_ip(vec2_2, 4): 0.14465 (6.269% faster)
vec2_1.move_towards_ip(vec2like, 4): 0.1703 (19.088% faster)
vec3_1.move_towards(vec3_2, 4): 0.165325 (7.212% faster)
vec3_1.move_towards(vec3like, 4): 0.20437500000000003 (18.987% faster)
vec3_1.move_towards_ip(vec3_2, 4): 0.145225 (9.658% faster)
vec3_1.move_towards_ip(vec3like, 4): 0.18039999999999998 (22.124% faster)
vec2_1.cross(vec2_2): 0.080625 (12.029% faster)
vec2_1.cross(vec2like): 0.1172 (22.653% faster)
vec3_1.cross(vec3_2): 0.09242500000000001 (11.555% faster)
vec3_1.cross(vec3like): 0.1359 (27.034% faster)
vec2_1.angle_to(vec2_2): 0.1089 (13.037% faster)
vec2_1.angle_to(vec2like): 0.144625 (23.872% faster)
vec3_1.angle_to(vec3_2): 0.10072500000000001 (16.428% faster)
vec3_1.angle_to(vec3like): 0.141625 (24.285% faster)
vec3_1.rotate(34, vec3_2): 0.1841 (5.674% faster)
vec3_1.rotate_ip(34, vec3_2): 0.16610000000000003 (5.504% faster)
vec2_1 + vec2_2: 0.05325 (2.473% faster)
vec2_1 + vec2like: 0.093575 (21.349% faster)
vec2_1 * vec2_2: 0.041475 (4.983% faster)
vec2_1 * vec2like: 0.08097499999999999 (24.797% faster)
vec2_1 * 2.3: 0.07072500000000001 (-12.934% faster)
vec3_1 + vec3_2: 0.053875 (18.556% faster)
vec3_1 + vec3like: 0.097925 (31.521% faster)
vec3_1 * vec3_2: 0.042475 (24.455% faster)
vec3_1 * vec3like: 0.08814999999999999 (32.94% faster)
vec3_1 * 2.3: 0.06772500000000001 (1.24% faster)

Average change = 14.87 %
```
</details>

I'm happy to see it shows a higher speedup, with a +14.87% average now.

2023-09-12 04:14 UTC, Starbuck5 commented
@itzpr3d4t0r 

> And a side note.
Generally speaking, the idea of having 2 pointers, one with a stack allocated array in the case of a sequence being passed and a single pointer that switches between the array and an actual vector's coords memory address is a valid optimization across the whole module. It avoids having to use memcpy in the vector case, which is probably what matters most.

You've suggested this in 4 separate comments on this PR, I replied when you brought it up in Ankith's thread: https://github.com/pygame-community/pygame-ce/pull/2443#discussion_r1320861904. My initial testing actually found the code was slower without the memcpy, somehow-- maybe the compiler is optimizing a fixed side memcpy away? Assuming this PR gets merged, you can try this yourself and maybe show a speedup and maybe make a follow up PR.

2023-09-12 04:14 UTC, Starbuck5 commented on src_c/math.c
> -    }
Replied to memcpy bit in https://github.com/pygame-community/pygame-ce/pull/2443#issuecomment-1714934403

2023-09-12 04:14 UTC, Starbuck5 commented on src_c/math.c
>      }
Replied to memcpy bit in https://github.com/pygame-community/pygame-ce/pull/2443#issuecomment-1714934403

2023-09-12 04:53 UTC, Starbuck5 commented on src_c/math.c
> +        Py_DECREF(tmp);
Good point, thanks

2023-09-12 10:12 UTC, itzpr3d4t0r approved these changes

2023-09-12 12:33 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada: 

Left a review for your consideration, resolve at will

2023-09-12 12:33 UTC, ankith26 commented on src_c/math.c
> +                            "Wrong internal call to pg_VectorCoordsFromObj.");
Not a big deal but just pointing this out, this error never actually makes it to the end user. Every caller of this function sets a new error message.

2023-09-14 03:39 UTC, Starbuck5 commented on src_c/math.c
> +                            "Wrong internal call to pg_VectorCoordsFromObj.");
Vector_generic_math doesn't set an error, it also won't forward this. So this will be a systemerror type internal fault (user visible) if it fires from vector_generic_math

2023-09-14 04:58 UTC, merged

2023-09-14 04:58 UTC, Starbuck5 commented
Alright @itzpr3d4t0r now it's on you: further optimizations 😄 📈