Strip the leading SDL_ from the pixel format name
pygame-community/pygame-ce pull request #2477
Opened 2023-09-30 13:01 UTC by MyreMylar

Fixes issue #1741.

I'm not sure this is the best way to strip 4 characters from a C string, so please let me know.

2023-09-30 13:30 UTC, ankith26 requested changes
A one-line change to achieve this could be passing `pixel_format_name + 4` directly instead of the copying to new memory. This of course, assumes that `pixel_format_name` is a non-null pointer and the string has atleast 4 chars (which should be checked, either way)

2023-09-30 13:37 UTC, ankith26 commented
```c
if (!strncmp(pixel_format_name, "SDL_", 4)) {
    pixel_format_name += 4
}
```
(untested code)
This should do maybe?

2023-09-30 14:20 UTC, zoldalma999 commented
The vidinfo type also has a getter, defined a bit above the str function. This currently does not even return a value for pixel format, so I think this could be an opportunity to fix that (and of course, strip "SDL_" off there as well).

2023-09-30 14:27 UTC, ankith26 commented
> ps: [SDL_GetPixelFormatName will always return a string starting with "SDL_"](https://github.com/libsdl-org/SDL/blob/SDL2/src/video/SDL_pixels.c#L88C13-L88C35)

Yeah I realised that too as I made my comment, but then it's safer (more future-proof) this way and does no harm.

2023-09-30 20:11 UTC, MyreMylar commented
> The vidinfo type also has a getter, defined a bit above the str function. This currently does not even return a value for pixel format, so I think this could be an opportunity to fix that (and of course, strip "SDL_" off there as well).

Should work now:

```
import pygame

pygame.init()
print(pygame.display.Info().pixel_format)
```

Output:
```
pygame-ce 2.4.0.dev1 (SDL 2.26.5, Python 3.11.1)
PIXELFORMAT_RGB888
```

2023-09-30 20:49 UTC, zoldalma999 approved these changes
Looks good to me!

2023-10-01 10:35 UTC, ankith26 commented on buildconfig/stubs/pygame/display.pyi
> +    pixel_format: str
This change needs to be documented too

2023-10-05 19:55 UTC, MyreMylar commented
Documented the `pixel_format` attribute and fixed that attribute documentation block while I was in there. Before it was formatted as python code and had an unnecessarily messy horizontal scrollbar.

👍

2023-10-07 05:47 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada:

2023-10-07 05:47 UTC, merged