Remove the unused Surface param from convert alpha docs
pygame-community/pygame-ce pull request #2486
Opened 2023-10-01 16:56 UTC by MyreMylar

It does nothing at all.

fixes #1753

2023-10-01 17:19 UTC, zoldalma999 commented
Apart from changing the docs, we could also remove the stubs for it and deprecate it in code. That would also close #493. Unless we want to add this functionality back?

2023-10-08 08:39 UTC, MyreMylar commented
> Apart from changing the docs, we could also remove the stubs for it and deprecate it in code. That would also close #493. Unless we want to add this functionality back?

Pretty sure we don't want this back.

I've added the deprecation warnings.

2023-10-09 10:11 UTC, Temmie3754 approved these changes
No longer appears in docs, stubs and appropriate depreciation warning displays

2023-10-09 16:07 UTC, ankith26 requested changes
Also a small and simple test that tests the deprecation warning would also be nice

2023-10-09 16:07 UTC, ankith26 commented on docs/reST/ref/surface.rst
>        the converted surface.
A note here of the deprecation would be nice

2023-10-09 18:50 UTC, MyreMylar commented on docs/reST/ref/surface.rst
>        the converted surface.
👍 added a `versionchanged` note.

2023-10-09 18:52 UTC, MyreMylar commented
> Also a small and simple test that tests the deprecation warning would also be nice

Added a test for the deprecation warning, and removed a few places in the test that were now triggering it as they were passing in the surface argument (which has done nothing for years).

2023-10-15 11:45 UTC, zoldalma999 commented on test/surface_test.py
> +import pygame
this seems accidental

2023-10-15 11:46 UTC, zoldalma999 approved these changes
Apart from a minor nitpick, this looks good to me

2023-10-15 12:54 UTC, MyreMylar commented on test/surface_test.py
> +import pygame
```suggestion
```

2023-10-15 12:56 UTC, MyreMylar commented on test/surface_test.py
> +import pygame
oops, thanks 👍 

Fixed.

2023-10-15 13:05 UTC, ankith26 approved these changes
LGTM now, thanks for the PR :tada:

2023-10-27 14:26 UTC, merged