Fix issue #2446: rotozoom keeps the colorkey flag.
pygame-community/pygame-ce pull request #2491
Opened 2023-10-02 11:59 UTC by igordsm

Issue #2446 reported that using rotozoom looses the colorkey information and provided code to reproduce the issue. We modified `rotozoomSurface` to copy colorkey from `src` to `rz_dst` and added a test to `test/transform_test.py`.

**Before**:
![image](https://github.com/pygame-community/pygame-ce/assets/221446/fe812f98-8a0a-4f80-8959-96a07f0e35c2)

**After**:

![image](https://github.com/pygame-community/pygame-ce/assets/221446/81aee906-f7cf-4845-8949-55279413ecdb)

2023-10-02 16:07 UTC, ankith26 requested changes
Hello, thanks for contributing to pygame-ce! :tada: :cake: 

This seems like a nice fix, but we have CI failing on lint errors. To fix that run `setup.py format` and commit resulting changes (make sure you have the appropriate tools like `black`/`clang-format` installed)

2023-10-02 16:13 UTC, ankith26 commented on src_c/transform.c
> +    }
This block of code should be outside the thread macros. This is because we cannot call python API when the GIL is released. Also, after setting the error, the function must return `NULL`

2023-10-05 18:50 UTC, MyreMylar commented on src_c/transform.c
> +            break;                                                            \
```suggestion
#define SURF_GET_AT(p_color, p_surf, p_x, p_y, p_pixels, p_format, p_pix)    \
    switch (p_format->BytesPerPixel) {                                       \
        case 1:                                                              \
            p_color = (Uint32) *                                             \
                      ((Uint8 *)(p_pixels) + (p_y) * p_surf->pitch + (p_x)); \
            break;                                                           \
        case 2:                                                              \
            p_color =                                                        \
                (Uint32) *                                                   \
                ((Uint16 *)((p_pixels) + (p_y) * p_surf->pitch) + (p_x));    \
            break;                                                           \
        case 3:                                                              \
            p_pix =                                                          \
                ((Uint8 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x) * 3);   \
            p_color = (SDL_BYTEORDER == SDL_LIL_ENDIAN)                      \
                          ? (p_pix[0]) + (p_pix[1] << 8) + (p_pix[2] << 16)  \
                          : (p_pix[2]) + (p_pix[1] << 8) + (p_pix[0] << 16); \
            break;                                                           \
        default: /* case 4: */                                               \
            p_color =                                                        \
                *((Uint32 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x));     \
            break;                                                           \
```

2023-10-05 18:51 UTC, MyreMylar commented on src_c/transform.c
> +            break;                                                            \
```suggestion
#define SURF_SET_AT(p_color, p_surf, p_x, p_y, p_pixels, p_format,       \
                    p_byte_buf)                                          \
    switch (p_format->BytesPerPixel) {                                   \
        case 1:                                                          \
            *((Uint8 *)p_pixels + (p_y) * p_surf->pitch + (p_x)) =       \
                (Uint8)p_color;                                          \
            break;                                                       \
        case 2:                                                          \
            *((Uint16 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x)) =    \
                (Uint16)p_color;                                         \
            break;                                                       \
        case 3:                                                          \
            p_byte_buf =                                                 \
                (Uint8 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x) * 3; \
            *(p_byte_buf + (p_format->Rshift >> 3)) =                    \
                (Uint8)(p_color >> p_format->Rshift);                    \
            *(p_byte_buf + (p_format->Gshift >> 3)) =                    \
                (Uint8)(p_color >> p_format->Gshift);                    \
            *(p_byte_buf + (p_format->Bshift >> 3)) =                    \
                (Uint8)(p_color >> p_format->Bshift);                    \
            break;                                                       \
        default:                                                         \
            *((Uint32 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x)) =    \
                p_color;                                                 \
            break;                                                       \
```

2023-10-05 18:51 UTC, MyreMylar commented on src_c/transform.c
> +            break;                                                            \
```suggestion
#define SURF_SET_AT(p_color, p_surf, p_x, p_y, p_pixels, p_format,       \
                    p_byte_buf)                                          \
    switch (p_format->BytesPerPixel) {                                   \
        case 1:                                                          \
            *((Uint8 *)p_pixels + (p_y) * p_surf->pitch + (p_x)) =       \
                (Uint8)p_color;                                          \
            break;                                                       \
        case 2:                                                          \
            *((Uint16 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x)) =    \
                (Uint16)p_color;                                         \
            break;                                                       \
        case 3:                                                          \
            p_byte_buf =                                                 \
                (Uint8 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x) * 3; \
            *(p_byte_buf + 2 - (p_format->Rshift >> 3)) =                \
                (Uint8)(p_color >> p_format->Rshift);                    \
            *(p_byte_buf + 2 - (p_format->Gshift >> 3)) =                \
                (Uint8)(p_color >> p_format->Gshift);                    \
            *(p_byte_buf + 2 - (p_format->Bshift >> 3)) =                \
                (Uint8)(p_color >> p_format->Bshift);                    \
            break;                                                       \
        default:                                                         \
            *((Uint32 *)(p_pixels + (p_y) * p_surf->pitch) + (p_x)) =    \
                p_color;                                                 \
            break;                                                       \
```

2023-10-05 19:18 UTC, MyreMylar requested changes
Just added a note here about an RLE thing that likely needs fixing in general across the whole of `transform.c` before we add another version of it in here.

We probably also need to make some tests for it based on the first post in #1668 just to check if it still is, or isn't a problem, as SDL has likely changed since this issue was first posted.

2023-10-05 19:18 UTC, MyreMylar commented on src_c/rotozoom.c
> +                SDL_SetSurfaceRLE(rz_dst, SDL_TRUE) != 0) {
IMHO we shouldn't be using this pattern in `transform.c` of always enabling RLE whenever a source surface has a color key. RLE no longer always works in all circumstances.

See this issue: https://github.com/pygame-community/pygame-ce/issues/1668

Instead I think we should check the source surface to see if it already has RLE, and if so, then enable it for the destination. That should isolate any RLE & source alpha bugs to when we are initially creating surfaces and when calling `Surface.set_alpha()`.

Slightly complicating this, is that the function to get a surface's RLE is one of the one's being renamed in SDL3. It is currently called: `SDL_HasSurfaceRLE()` but is going to be called `SDL_SurfaceHasRLE()` in SDL3.

In short I think we need to make something like what this PR has added for `SDL_ConvertSurface()` in `_pygame.h` but with `PG_SurfaceHasRLE()` as the name and then use it here something like:

```C
    if (SDL_GetColorKey(src, &colorkey) == 0) {
        if (SDL_SetColorKey(rz_dst, SDL_TRUE, colorkey) != 0) {
            SDL_FreeSurface(rz_dst);
            return NULL;
        }
        if(PG_SurfaceHasRLE(src) && SDL_SetSurfaceRLE(rz_dst, SDL_TRUE) != 0) {
            SDL_FreeSurface(rz_dst);
            return NULL;
        }
    }
```

2023-10-07 07:10 UTC, MyreMylar commented
This will also need to merge in the latest main branch to pick up the grub-efi fix.

2023-10-26 10:30 UTC, MyreMylar commented on src_c/rotozoom.c
> +            if (PG_SurfaceHasRLE(src) && SDL_SetSurfaceRLE(rz_dst, SDL_TRUE) != 0) {
```suggestion
            if (PG_SurfaceHasRLE(src) &&
                SDL_SetSurfaceRLE(rz_dst, SDL_TRUE) != 0) {
```

2023-10-26 10:30 UTC, MyreMylar commented on src_c/rotozoom.c
> +            if (PG_SurfaceHasRLE(src) && SDL_SetSurfaceRLE(rz_dst, SDL_TRUE) != 0) {
```suggestion
            if (PG_SurfaceHasRLE(src) &&
                SDL_SetSurfaceRLE(rz_dst, SDL_TRUE) != 0) {
```

2023-10-26 10:37 UTC, MyreMylar approved these changes
LGTM. Can confirm it fixes the issue and works with RLE and non-RLE colorkey surfaces. Thank you for the contribution!

👍 🎉

2023-10-26 10:44 UTC, MyreMylar commented on src_c/_pygame.h
> +#define PG_SurfaceHasRLE(src) SDL_SurfaceHasRLE(src)
```suggestion
#define PG_SurfaceHasRLE SDL_SurfaceHasRLE
```

2023-10-26 10:44 UTC, MyreMylar commented on src_c/_pygame.h
> +#define PG_SurfaceHasRLE(src) SDL_HasSurfaceRLE(src)
```suggestion
#define PG_SurfaceHasRLE SDL_HasSurfaceRLE
```

2023-10-26 11:36 UTC, MyreMylar commented on src_c/_pygame.h
> +#define PG_SurfaceHasRLE SDL_HasSurfaceRLE
```suggestion
#if SDL_VERSION_ATLEAST(2, 0, 14)
#define PG_SurfaceHasRLE SDL_HasSurfaceRLE
#else
// vendored in until our lowest SDL version is 2.0.14
SDL_bool
PG_SurfaceHasRLE(SDL_Surface *surface)
{
    if (surface == NULL) {
        return SDL_FALSE;
    }

    if (!(surface->map->info.flags & SDL_COPY_RLE_DESIRED)) {
        return SDL_FALSE;
    }

    return SDL_TRUE;
}
#endif

```

2023-10-26 11:49 UTC, MyreMylar commented on src_c/_pygame.h
> +// vendored in until our lowest SDL version is 2.0.14
```suggestion
// vendored in until our lowest SDL version is 2.0.14
#include "_blit_info.h"
#define SDL_COPY_RLE_DESIRED 0x00001000

```

2023-10-26 11:52 UTC, MyreMylar commented
I realised while investigating the failing test that the function now known as `SDL_SurfaceHasRLE` that was renamed for SDL 3, was also only added to SDL 2 in version 2.0.14 so we are still 5 patch versions behind in our lowest supported SDL to use it. notably our wheels are ahead of this version so that's why I wasn't seeing this error locally.

I've just added a patch commit to vendor this function in for the case where SDL is less that 2.0.14. Not the most elegant solution (if it eventually works), but it should hold up OK as the function itself is super basic and we can delete it eventually when our bottom end catches up with our current  main target.

2023-10-26 12:04 UTC, MyreMylar commented on src_c/_pygame.h
> +#include "_blit_info.h"
```suggestion
struct SDL_BlitMap
{
    SDL_Surface *dst;
    int identity;
    SDL_blit blit;
    void *data;
    SDL_BlitInfo info;

    /* the version count matches the destination; mismatch indicates
       an invalid mapping */
    Uint32 dst_palette_version;
    Uint32 src_palette_version;
};
```

2023-10-26 12:25 UTC, MyreMylar commented on src_c/_pygame.h
> +};
```suggestion
typedef struct {
    int width;
    int height;
    Uint8 *s_pixels;
    int s_pxskip;
    int s_skip;
    Uint8 *d_pixels;
    int d_pxskip;
    int d_skip;
    SDL_PixelFormat *src;
    SDL_PixelFormat *dst;
    Uint8 src_blanket_alpha;
    int src_has_colorkey;
    Uint32 src_colorkey;
    SDL_BlendMode src_blend;
    SDL_BlendMode dst_blend;
} SDL_BlitInfo;

struct SDL_BlitMap {
    SDL_Surface *dst;
    int identity;
    SDL_blit blit;
    void *data;
    SDL_BlitInfo info;

    /* the version count matches the destination; mismatch indicates
       an invalid mapping */
    Uint32 dst_palette_version;
    Uint32 src_palette_version;
};
```

2023-10-26 12:55 UTC, MyreMylar commented on src_c/rotozoom.c
> +#include "_pygame.h"
```suggestion
#include "_pygame.h"

#if !SDL_VERSION_ATLEAST(2, 0, 14)
SDL_bool
PG_SurfaceHasRLE(SDL_Surface *surface)
{
    if (surface == NULL) {
        return SDL_FALSE;
    }

    if (!(surface->map->info.flags & SDL_COPY_RLE_DESIRED)) {
        return SDL_FALSE;
    }

    return SDL_TRUE;
}
#endif
```

2023-10-26 13:22 UTC, MyreMylar commented
Getting that to compile via Github web version interactions required a few compromises... I'm planning to do another PR on the topic of Surface RLE flags for the whole transform module once this gets merged, so I can almost certainly clean this up a bit in that PR.

2023-10-28 04:05 UTC, ankith26 commented on src_c/_pygame.h
> +#define PG_SurfaceHasRLE SDL_SurfaceHasRLE
This line should be removed?

2023-10-28 04:05 UTC, ankith26 commented on src_c/_pygame.h
> +};
I don't why these two structs are being vendored in? Just vendoring in `SDL_COPY_RLE_DESIRED` should be enough, unless I'm missing something

2023-10-28 06:12 UTC, MyreMylar commented on src_c/_pygame.h
> +#define PG_SurfaceHasRLE SDL_SurfaceHasRLE
No, that is there for SDL 3 compatibility as they have renamed `SDL_HasSurfaceRLE` to `SDL_SurfaceHasRLE`.

2023-10-28 06:18 UTC, MyreMylar commented on src_c/_pygame.h
> +};
I tried not including the structs (you can see the series of commits) the compiler that goes down this route using SDL 2.0.10 errors on line 24 below when getting the pointer to `map` unless both of these structs are defined. 

They are not public structs as they are part of the SDL internals so to use them at all we have to vendor them in temporarily as well. The versions of SDL this applies to (2.0.9 to 2.0.13) are already released so their struct internals won't be changing so I don't see any long term harm from having them here until it comes time to remove them when the bottom end of our SDL support moves up.

2023-10-28 11:51 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada:

2023-10-28 11:56 UTC, ankith26 commented
Noticed the original commit has many co-authors, so thank you all! Unless anyone minds, I'd like to squash-and-merge this PR but I will leave the co-author tags intact.

2023-10-28 13:14 UTC, MyreMylar commented
Absolutely squash and merge away. Igor did 99% of the work here. I was
just wrestling with the compiler to get it over the line.

On Sat, Oct 28, 2023 at 12:56 PM Ankith ***@***.***> wrote:

> Noticed the original commit has many co-authors, so thank you all! Unless
> anyone minds, I'd like to squash-and-merge this PR but I will leave the
> co-author tags intact.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pygame-community/pygame-ce/pull/2491#issuecomment-1783789574>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADGDGGUP2WZ557IVUA44OODYBTXIJAVCNFSM6AAAAAA5PJ3OU2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBTG44DSNJXGQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-10-28 13:42 UTC, merged