Fix issue #2109: Added requested tests
pygame-community/pygame-ce pull request #2492
Opened 2023-10-02 13:32 UTC by JorasOliveira

Added the requested tests for both pygame.Surface.get_rect and pygame.Surface.get_frect functions.

For both methods test:
 - [X] whether using correct keyword argument(s) sets the appropriate rect attribute
- [X]  that when using multiple different kwargs, only the last one is applied
 - [X] that appropriate exceptions are raised when using kwarg names that don't match rect attributes (like centre instead of center)

For Rect:
- [X]  add the difference between current get_rect and get_frect tests to get_rect (test position and instance type)

2023-10-02 16:04 UTC, ankith26 commented
requesting matt's review as they are the OP of the original issue

2023-10-03 18:53 UTC, MyreMylar reviewed
Just a couple of spots to resolve the CI test fails on PyPy 👍

2023-10-03 18:53 UTC, MyreMylar commented on test/surface_test.py
> +            surf.get_rect(centre=(100, 100))
```suggestion
        if not IS_PYPY:
            with self.assertRaises(AttributeError):
                surf.get_rect(centre=(100, 100))
```

2023-10-03 18:53 UTC, MyreMylar commented on test/surface_test.py
> +            surf.get_rect(centre=(100, 100))
This test doesn't work on PyPy because pypy doesn't raise an attribute error when passed incorrect attribute names to `PyObject_SetAttr()`.

You could also add a comment as to why we are skipping this particular bit of test for PyPy.

2023-10-03 22:22 UTC, JorasOliveira commented on test/surface_test.py
> +            surf.get_rect(centre=(100, 100))
will implement the changes tomorrow!

2023-10-03 23:52 UTC, Matiiss commented on test/surface_test.py
> +            surf.get_rect(centre=(100, 100))
And don't forget that `get_frect` has the same issue

2023-10-05 18:41 UTC, MyreMylar commented on test/surface_test.py
> +        if not IS_PYPY: #PyPy doesn't raise an AttributeError, so for PyPy we can just skip it.
```suggestion
        if (
            not IS_PYPY
        ):  # PyPy doesn't raise an AttributeError, so for PyPy we can just skip it.
```

2023-10-05 18:42 UTC, MyreMylar commented on test/surface_test.py
> +        if not IS_PYPY: #PyPy doesn't raise an AttributeError, so for PyPy we can just skip it.
```suggestion
        if (
            not IS_PYPY
        ):  # PyPy doesn't raise an AttributeError, so for PyPy we can just skip it.
```

2023-10-05 18:43 UTC, MyreMylar approved these changes
LGTM 👍

2023-10-05 19:20 UTC, MyreMylar commented on test/surface_test.py
> +
```suggestion

```

2023-10-05 19:21 UTC, MyreMylar commented on test/surface_test.py
> +                surf.get_rect(centre=(100, 100))
```suggestion
                surf.get_rect(centre=(100, 100))

```

2023-10-05 19:22 UTC, MyreMylar commented on test/surface_test.py
> +                surf.get_rect(centre=(100, 100))
```suggestion
                surf.get_rect(centre=(100, 100))

```

2023-10-06 16:14 UTC, Matiiss requested changes
> that when using multiple different kwargs, only the last one is applied

That basically means that there should be a test something like
```py
....get_rect(center=(5, 5), center=(10, 10))
```
where you test that center is indeed at (10, 10).

Also should test that if a positional argument is passed, it raises a `TypeError` and that it raises a `TypeError` when the value can't be assigned to the rect, for example
```py
....get_rect(5)
....get_rect(center=5)
....get_rect(center="5")
```

2023-10-07 07:11 UTC, MyreMylar commented
Try merging the latest main branch into this PR branch to fix the CI errors.

2023-10-16 11:16 UTC, JorasOliveira commented
> > that when using multiple different kwargs, only the last one is applied
> 
> That basically means that there should be a test something like
> 
> ```python
> ....get_rect(center=(5, 5), center=(10, 10))
> ```
> 
> where you test that center is indeed at (10, 10).

I get a syntaxError when I tried do this test, the gef_rect and get_frect functions don't allow repeated keywords. I'll add a test for the syntaxError

2023-10-16 18:43 UTC, Matiiss requested changes

2023-10-16 18:43 UTC, Matiiss commented on test/surface_test.py
> +                surf.get_rect(center="5")
I don't think this will test all the functions and it shouldn't be under `if not IS_PYPY:`
you can also do this instead
```py
self.assertRaises(TypeError, surf.get_rect, 5)
self.assertRaises(TypeError, surf.get_rect, center=5)
self.assertRaises(TypeError, surf.get_rect, center="5")
```

2023-10-16 18:44 UTC, Matiiss commented on test/surface_test.py
> +                surf.get_rect(center="5")
Same for `get_frect`

2023-10-20 06:54 UTC, Matiiss approved these changes
LGTM, thanks for the PR 🎉

2023-10-20 06:54 UTC, merged