Remove blend from draw.aaline
pygame-community/pygame-ce pull request #2550
Opened 2023-11-06 09:22 UTC by MightyJosip

Already done in #2506, but there was still some stuff that used blend argument. I also removed check for bounding rect, since it is done later in the code

2023-11-06 17:38 UTC, MyreMylar commented
Looks like this needs running through the linters.

2023-11-06 21:22 UTC, MyreMylar approved these changes
LGTM 👍

2023-11-07 05:24 UTC, dr0id approved these changes
LGTM

2023-11-07 11:13 UTC, ankith26 requested changes

2023-11-07 11:13 UTC, ankith26 commented on src_c/draw.c
> -            return original_color;
I'm not sure if this check should be removed. Because at this point we want this check to have already happened. I can imagine the below line can segfault for unchecked input at this stage

2023-11-07 20:17 UTC, MightyJosip commented on src_c/draw.c
> -            return original_color;
Tried to reproduce segfault but wasn't able to. But anyways I will add it back just in case

2023-11-09 17:23 UTC, ankith26 approved these changes
LGTM, thanks for the PR :crown:

2023-11-09 17:23 UTC, merged