Support collide_mask as collided argument in spritecollide
pygame-community/pygame-ce pull request #2569
Opened 2023-11-15 19:43 UTC by ZeroWave022

This PR attempts to fix #2568 by making the type of the `collided` argument of `pygame.sprite.spritecollide`, `pygame.sprite.spritecollideany` and `pygame.sprite.groupcollide` more strict/precise.
It also adds the `pygame.sprite.collide_mask` return type as one of the possible return types besides a boolean.

2023-11-16 07:28 UTC, ankith26 requested changes
Thanks for the PR! :partying_face: 

left a few reviews

2023-11-16 07:28 UTC, ankith26 commented on buildconfig/stubs/pygame/sprite.pyi
> +    group: AbstractGroup[_TSprite2],
These changes are probably not needed? The issue is in the `collided` keyword argument

2023-11-16 07:28 UTC, ankith26 commented on buildconfig/stubs/pygame/sprite.pyi
> +        Callable[[_TSprite, _TSprite2], bool | Optional[Tuple[int, int]]]
I think a better fix is to replace `bool | Optional[Tuple[int, int]]]` (which was previously `bool`) with `Any`. This is because in python (almost) any object can be interpreted as a boolean.

2023-11-16 08:55 UTC, ZeroWave022 commented on buildconfig/stubs/pygame/sprite.pyi
> +    group: AbstractGroup[_TSprite2],
We can leave it as `_HasRect`, but I thought it'd be good to use the same type for sprite/group, as the collided argument. After all, the two first arguments are used when collided is called

https://github.com/pygame-community/pygame-ce/blob/acdb21fc937e22a378d4f2ae0d707685ee051084/src_py/sprite.py#L1699-L1703

Whatever we end up using, the collided callback needs two `_TSprite`s to fix the issue (as far as I can understand)

2023-11-16 08:55 UTC, ZeroWave022 commented on buildconfig/stubs/pygame/sprite.pyi
> +        Callable[[_TSprite, _TSprite2], bool | Optional[Tuple[int, int]]]
I agree. I was thinking myself that this wasn't the most elegant solution, so I'll commit the change in a sec

2023-11-16 18:34 UTC, ankith26 commented on buildconfig/stubs/pygame/sprite.pyi
> +    group: AbstractGroup[_TSprite2],
`_HasRect` should be a more generic type than `_TSprite`, so passing a `_TSprite` where `_HasRect` is expected should work

2023-11-16 20:12 UTC, ZeroWave022 commented on buildconfig/stubs/pygame/sprite.pyi
> +    group: AbstractGroup[_TSprite2],
I've pushed a commit to change this back. Feel free to resolve this conversation if it looks good to you

2023-11-17 13:56 UTC, ankith26 approved these changes
This PR is almost ready to go, approving but leaving a minor review for your consideration. Thanks again! :cake:

2023-11-17 13:56 UTC, ankith26 commented on buildconfig/stubs/pygame/sprite.pyi
> +    collided: Optional[Callable[[_TSprite, _TSprite2], Any]] = None,
The function argument types here need not change, and same above as well

2023-11-17 15:23 UTC, ZeroWave022 commented on buildconfig/stubs/pygame/sprite.pyi
> +    collided: Optional[Callable[[_TSprite, _TSprite2], Any]] = None,
collide_mask expects two sprites with image and rect or mask and rect:
https://github.com/pygame-community/pygame-ce/blob/26be6b50ff262adcf581d6c508dd77ce827fa551/buildconfig/stubs/pygame/sprite.pyi#L270-L274

`_HasRect` is not strict enough, so leaving it as the function argument will make mypy complain again

2023-11-17 16:00 UTC, ankith26 commented on buildconfig/stubs/pygame/sprite.pyi
> +    collided: Optional[Callable[[_TSprite, _TSprite2], Any]] = None,
Oh yeah, just remembered that `Callable` is contravariant in its arguments. So this change is good, it makes the type hint more generic by being more specific

2023-11-18 10:31 UTC, MyreMylar approved these changes
LGTM 👍

2023-11-18 10:32 UTC, merged