Multiline more examples
pygame-community/pygame-ce pull request #2588
Opened 2023-11-23 12:12 UTC by gresm

Resolves one sub-task from  #2206

This PR:
 - examples/textinput.py - now uses multi-line font rendering
 - examples/textinput.py - fix visual errors with text looking weird
 - examples/vgrade.py - PEP 8 exists

2023-11-23 15:33 UTC, oddbookworm requested changes
Looks like reasonable changes, just one small nitpick about type hinting

2023-11-23 15:33 UTC, oddbookworm commented on examples/textinput.py
> +        fps: int = 50,
Looks like you're missing a couple of type hints here

2023-11-23 20:48 UTC, gresm commented on examples/textinput.py
> +        fps: int = 50,
Thanks, didn't catch this because this is actually the code from before my changes (it appeared in diff because I've black on it...).

2023-11-24 23:22 UTC, oddbookworm commented on examples/textinput.py
> +        text_color="white",
another minor nitpick:
spaces around "="

2023-11-25 10:28 UTC, MyreMylar commented on examples/textinput.py
> +        text_color="white",
```suggestion
        text_color = "white",
```

2023-11-25 10:29 UTC, MyreMylar approved these changes
seems fine 👍

2023-11-25 12:02 UTC, gresm commented on examples/textinput.py
> +        text_color="white",
@MyreMylar https://pep8.org/#other-recommendations
![image](https://github.com/pygame-community/pygame-ce/assets/78505251/ca388e6c-53ad-47ce-b75b-39494995e02b)

2023-11-25 12:10 UTC, gresm commented on examples/textinput.py
> +        text_color="white",
Here I disagree, text_color should be a valid pygame color-like object, but the annotation for it is a bit verbose (in ._common.pyi is defined like ``Union[int, str, Sequence[int]]``), so I don't see much value in adding annotations here, as it doesn't improve code readability and when annotations are missing, according to PEP 8, there shouldn't be any spaces (also running black on the code should also remove them, so the checks will fail).

2023-11-25 18:30 UTC, Matiiss commented on examples/textinput.py
> +        text_color="white",
The way to deal with verbose type annotations is to alias them, so something like `Color: TypeAlias = Union[int, str, Sequence[int], pygame.Color]` and use that for the type hint, then you'd need to add the spaces around which is what Andrew probably meant, if you add the type hint, you need spaces.

2023-11-25 18:43 UTC, gresm commented on examples/textinput.py
> +        text_color="white",
I prefer to leave it like this until a proper API is exposed.

2023-12-06 07:44 UTC, Starbuck5 commented on examples/textinput.py
>          # Freetype
But it's not using freetype anymore?

2023-12-06 07:45 UTC, Starbuck5 commented on examples/textinput.py
> +from __future__ import annotations
Why?

2023-12-06 07:48 UTC, Starbuck5 commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
The modern type hint style doesn't work on 3.8, which we still support.

```
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> def a(x: int, y: tuple[int, int]):
...     print(x, y)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

```
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> def a(x: int, y: tuple[int, int]):
...     print(x, y)
...
>>> a
<function a at 0x000001921B3AF040>
```

2023-12-06 20:31 UTC, gresm commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
Invalid concern: see [``__future__`` imports](https://docs.python.org/3/library/__future__.html).
```py
>>> from __future__ import annotations
>>> import sys
>>> def a(lst: list[str]):
...     print(*lst)
>>> print(sys.version)
>>> a(["a", "b", "c"])
3.8.0b4 (default, Sep  2 2019, 08:08:37) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
a b c
```

2023-12-06 20:43 UTC, gresm commented on examples/textinput.py
>          # Freetype
@Starbuck5 done

2023-12-10 06:42 UTC, Starbuck5 commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
I would rather use the old style than use a future import that has been stalled with no definite direction for several years now.

2023-12-11 09:32 UTC, gresm commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
Well, examples need to have the code refactored, as they use different style conventions. I personally use the ``__future__`` import, but I would use the chosen one for this project, if such style existed. I understand why you dislike ``__future__.annotations``, but I have nothing against it. We are missing a consistent code-styling guide ( it doesn't have to be a formal document of any kind, coherent code base would be enough) and because of that, we are having this discussion about what convention is correct.

2023-12-12 06:47 UTC, Starbuck5 commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
I agree that lots of the examples could use improvement.

I'm not sure what styling guide would go in depth enough to prescribe whether a future import is allowed.

I would like you to make your type annotations compatible with Python 3.8 without this future import.

2023-12-12 12:09 UTC, gresm commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
Understandable, I can do that.

2023-12-12 12:17 UTC, gresm commented on examples/textinput.py
> +        screen_dimensions: tuple[int, int],
@Starbuck5 done

2023-12-13 08:52 UTC, Starbuck5 approved these changes
Looks good, thanks!

2023-12-13 08:53 UTC, merged