Subclassing Sounds + Channels.
pygame-community/pygame-ce pull request #2590
Opened 2023-11-24 12:06 UTC by gresm

Fixes #2589
(Or at least it should)

2023-11-25 09:36 UTC, MyreMylar approved these changes
LGTM 👍

2023-11-25 18:43 UTC, ankith26 approved these changes
LGTM, thanks for the PR :partying_face:

2023-11-26 08:38 UTC, ankith26 requested changes
Okay on a relook, maybe this PR also needs a little docs addition in the `Channel` class saying that it is now subclassable?

2023-11-30 20:19 UTC, MyreMylar approved these changes
LGTM 👍

2023-12-03 19:24 UTC, Starbuck5 commented on test/mixer_test.py
> +    def test_subclass(self):
Nitpick on this testing, won't unittest mark it as failed if an unexpected Exception occurs without needing to explicitly try/except it?

2023-12-04 23:03 UTC, gresm commented on test/mixer_test.py
> +    def test_subclass(self):
I was sure that it was implemented this way, but when searching through code-base, I see I was wrong, I'll fix it when I'll be able to.

2023-12-06 20:42 UTC, gresm commented on test/mixer_test.py
> +    def test_subclass(self):
@Starbuck5 done

2023-12-10 06:38 UTC, merged