Add window example
pygame-community/pygame-ce pull request #2626
Opened 2023-12-23 09:41 UTC by Starbuck5

Task for #2603

2023-12-23 11:46 UTC, ankith26 requested changes
Nice work on the example! :sunglasses: 
Seeing this example in action has gotten me more interested in `Window` :smile: as it demonstrates new cool stuff and also serves as a good way to test things in action

I added a couple of reviews, some reviews for the example, and also a few API reviews that I noticed while playing around with the example.

2023-12-23 11:46 UTC, ankith26 commented on examples/window.py
> +main_window = pygame.Window("demo window", (500, 500), resizable=True)
could the main window also be `always_on_top`?

Another trivial note, how about setting an icon with `set_icon`?

2023-12-23 11:46 UTC, ankith26 commented on examples/window.py
> +                    win.size += pygame.Vector2(WIN_GROW_SPEED, WIN_GROW_SPEED)
might also be a good idea to cap it to some upper bound? Perhaps using the `maximum_size` property?

2023-12-23 11:46 UTC, ankith26 commented on examples/window.py
> +                    pass
How about adding a `event.window.focus()` here?

2023-12-23 11:46 UTC, ankith26 commented on examples/window.py
> +n.) minimize main window
In addition to maximise/minimise, could also two keys for add/remove full screen?

2023-12-23 11:46 UTC, ankith26 commented on examples/window.py
> +                windows_and_surfaces.append((win, win.get_surface()))
## API comment
This has gotten me thinking about the API. As a user, I think it would be much neater if we could do something like `win.surface` and not have to explicitly track the output of `win.get_surface`. Even helps conceptually to show that "this surface instance is a special window-surface tied to the window"

2023-12-23 11:56 UTC, ankith26 commented on examples/window.py
> +                    win.position += pygame.Vector2(WIN_MOVE_SPEED, 0)
## API comment

SMH my head, `window.position` *is also broken under direct wayland*

Nothing moves when I press the arrow keys. :cry: 

All these "direct wayland" issues are fine/ignorable for now because these issues don't happen under XWayland which SDL2 picks by default, but this could be a problem in the SDL3 era if SDL3 devs decide to do wayland-default.

2023-12-23 12:15 UTC, ankith26 reviewed
This example also reveals memory leaks :sweat: 

Open task manager while this example is running and play around with this example. Every time a new window is spawned the memory usage goes up as expected, but closing the window does not reduce the memory consumption

Similarly everytime the window is resized memory usage increases, even when downsizing.

These memory leaks are not insignificant, I believe entire window surfaces are being leaked, so depending on the window size and display resolutions we may be leaking a lot.

2023-12-23 14:24 UTC, robertpfeiffer commented on examples/window.py
> +                    win.position += pygame.Vector2(WIN_MOVE_SPEED, 0)
This is by design. Wayland does not want applications to know this for API design and security reasons. There is nothing SDL3 can do about it short of sending patches to KDE and GNOME and sway

2023-12-23 22:14 UTC, Starbuck5 commented on examples/window.py
> +                windows_and_surfaces.append((win, win.get_surface()))
Well I think I could be calling get_surface() every time I need a surface. I'm just not sure how that works SDL-side.

2023-12-23 22:19 UTC, Starbuck5 commented on examples/window.py
> +                    win.size -= pygame.Vector2(WIN_GROW_SPEED, WIN_GROW_SPEED)
It's unclear reading your comment whether you see the `minimum_size` of the window is explicitly set to contain the instruction text.

It would happen to the main window if it was ever told to do a negative size there. Which it can't because the minimum size dimensions are higher than WIN_GROW_SPEED.

I agree it shouldn't be possible to crash the example by messing around with it, but I'm not sure what the best solution would be.

2023-12-23 22:22 UTC, Starbuck5 commented on examples/window.py
> +                    win.position += pygame.Vector2(WIN_MOVE_SPEED, 0)
Do I need to add try/except pygame.error blocks around them then? I did it for opacity given your previous report.

I'm also unsure if we really want to raise an exception if the operation is not supported. We could return True/False about success?

2023-12-23 22:34 UTC, Starbuck5 commented on examples/window.py
> +                windows_and_surfaces.append((win, win.get_surface()))
This is also why I thought of subclassing window, issue raised as #2625. In this demo it would be nice to store the color of the window with the window. (Store arbitrary things in instance of class, subclass)

2023-12-23 22:37 UTC, Starbuck5 commented on examples/window.py
> +main_window = pygame.Window("demo window", (500, 500), resizable=True)
At least on Windows, the spawned windows spawn in the center of the main window (I'm not controlling the spawn point). So if the main window was always_on_top it would seem like the spawn window command does nothing, because the other windows would not be visible unless you move the main window with the mouse.

I was looking around the examples data folder for art to use for this, (icons, backgrounds), and none of it spoke to me. I don't feel the need to set an icon in this example.

2023-12-23 22:40 UTC, Starbuck5 commented on docs/reST/ref/window.rst
> +   https://github.com/pygame-community/pygame-ce/blob/main/examples/window.py
I'll update the import. I'll leave the example in the docs, I think we should have more "snippet" style examples in our documentation in general.

2023-12-24 04:23 UTC, ankith26 commented on examples/window.py
> +                    win.position += pygame.Vector2(WIN_MOVE_SPEED, 0)
In this case the position is silently ignored by SDL, like `always_on_top`. Only opacity explicitly errors.

I think for this example, we should not have this position-moving thing as a highlight, and make it more low-key somehow?

2023-12-24 04:26 UTC, ankith26 commented on examples/window.py
> +                windows_and_surfaces.append((win, win.get_surface()))
So, SDL stores the surface in the window struct (both in SDL2 and SDL3), and if the surface needs updating it updates the surface, so for most of the calls to this function it is just a cheap struct member access.

On the python side, we could basically the change this `get_surface` to a property.

2023-12-24 04:50 UTC, ankith26 commented on examples/window.py
> +                windows_and_surfaces.append((win, win.get_surface()))
Here is a commit on a branch I made on top of yours, implementing my idea: https://github.com/pygame-community/pygame-ce/commit/6b620f18b3a37eab5a0147508aa5b2da00ea384b

I also updated this example to see/test the property in action

2025-05-11 02:41 UTC, Starbuck5 commented
This PR is too old, I'm going to close.

2025-05-11 02:41 UTC, closed without merging