Test function for pygame.draw.arc (resolves #2636)
pygame-community/pygame-ce pull request #2638
Opened 2023-12-28 13:47 UTC by Houda222

### This pull request resolves issue #2636
I added a test function `test_arc__correct_drawing` that replaced the `todo_test_arc` function in the `DrawArcMixin` class. It ensures that `pygame.draw.arc` works correctly, by checking whether the drawn arc matches the ellipse defined by the bounding rectangle. The comparison is done by measuring the difference between the ellipse's points and the arc's point and making sure it's less than a certain threshold. 
The test is done on different bounding rectangles.

2023-12-28 18:42 UTC, ankith26 commented
The circleci fail on this PR is not this PRs fault, don't worry. It's being resolved in another PR

2024-01-06 13:50 UTC, ankith26 commented on test/draw_test.py
> +            )
this check can more simply be written as `self.assertEqual(number_of_invalid_arc_points, 0)`.

Additionally, we should probably test for `number_of_valid_arc_points` being correct somehow?

2024-02-12 15:11 UTC, MyreMylar commented on test/draw_test.py
> +        stop = 2
I feel like we should probably test a broader range of arcs than just 0 to 2 radians, probably stuff like: pi, pi/2, pi/4, 2 * pi.

2024-02-12 15:11 UTC, MyreMylar commented on test/draw_test.py
> +                "width": 1,
Probably should also test on wider range of widths than just 1.

2024-02-12 15:12 UTC, MyreMylar commented on test/draw_test.py
> +            )
```suggestion
            self.assertEqual(number_of_invalid_arc_points, 0)
```

2024-02-12 15:13 UTC, MyreMylar requested changes
What is here is nice, but I think this test should test more angles and more widths to fully test out draw arc.

2024-05-31 10:58 UTC, MyreMylar commented
Hi @Houda222, do you think you will make any of the changes asked for? Or should we pass this PR over to someone else to finish off?

2024-12-01 17:09 UTC, closed without merging