``invlerp`` and ``remap`` implementation
pygame-community/pygame-ce pull request #2654
Opened 2024-01-04 10:16 UTC by bilhox

Implementation of #2649
Docs will come in a short time.

2024-01-04 14:45 UTC, Matiiss requested changes
Thanks for the PR, I left a couple of notes:

I don't think you should change anything about `math.lerp` in this PR, you can submit a separate PR for that (that includes both the implementation and the docs).

Also this needs tests too.

2024-01-04 14:48 UTC, bilhox commented on buildconfig/stubs/pygame/math.pyi
Ah, I thought I added it

2024-01-04 14:48 UTC, Matiiss commented on buildconfig/stubs/pygame/math.pyi
> +def invlerp(a: float, b: float, weight: float /) -> float: ...
CI is failing because you forgot a comma here, after `weight: float`

2024-01-04 14:50 UTC, bilhox commented
> I don't think you should change anything about math.lerp in this PR, you can submit a separate PR for that (that includes both the implementation and the docs).

It's because I had to use ``lerp`` and ``invlerp`` in ``remap``, So I updated it. Should I point it out btw ?

2024-01-04 17:43 UTC, bilhox commented on src_c/math.c
> +    double t = PyFloat_AsDouble(value);
It's also present in ``pygame.math.lerp``, I'll fix it in another PR.

2024-01-05 22:58 UTC, Matiiss reviewed
This also needs unit tests

2024-01-05 22:58 UTC, Matiiss commented on buildconfig/stubs/pygame/math.pyi
> +def remap(i_min : float, i_max : float, o_min : float, o_max : float, value : float , /) -> float: ...
Was it formatted with those spaces before `:`s using `python setup.py format`?

2024-01-05 22:58 UTC, Matiiss commented on src_c/math.c
> +
Could maybe `inline` both of these functions

2024-01-05 22:58 UTC, Matiiss commented on src_c/math.c
For consistency all of the error messages should begin with a lowercase letter (well, unless it's reasonable not to, like abbreviations or something) and end without a period

2024-01-05 22:58 UTC, Matiiss commented on src_c/math.c
> +                     "Invalid argument values passed to invlerp.");
I think it's reasonable to at least mention to the user here that their input value might be too small or too large

2024-01-05 22:58 UTC, Matiiss commented on src_c/math.c
> +                     "Invalid argument values passed to remap.");
I think it's reasonable to at least mention to the user here that their input value might be too small or too large

2024-01-06 13:37 UTC, bilhox commented on buildconfig/stubs/pygame/math.pyi
> +def remap(i_min : float, i_max : float, o_min : float, o_max : float, value : float , /) -> float: ...
I think it's just me, let me fix it

2024-01-06 14:45 UTC, Matiiss commented on buildconfig/stubs/pygame/math.pyi
> +def remap(i_min: float, i_max: float, o_min: float, o_max: float, value: float , /) -> float: ...
There's space before that last comma

2024-01-06 14:59 UTC, bilhox commented on buildconfig/stubs/pygame/math.pyi
> +def remap(i_min: float, i_max: float, o_min: float, o_max: float, value: float , /) -> float: ...
fixed

2024-01-07 11:39 UTC, durkisneer1 commented on test/math_test.py
> +            c = "durk"
I approve.

2024-01-13 17:35 UTC, ankith26 commented on src_c/math.c
> +                     "invlerp requires all the arguments to be numbers");
improvement suggestion: instead of checking this explicitly, we can instead call `PyFloat_AsDouble` directly, and then handle the error on a per-argument basis? That we can also tell which of the arguments is incorrect

2024-01-13 17:35 UTC, ankith26 commented on src_c/math.c
> +                     "the result of b - a needs to be different from zero");
Instead of a zero division error, how about raising something else, like maybe a `ValueError`

2024-01-13 17:35 UTC, ankith26 commented on src_c/math.c
> +}
Nice addition! To take things further, this could also be called from the implementation of `math_lerp`

2024-01-13 17:45 UTC, bilhox commented on src_c/math.c
> +}
yup, @Matiiss asked me to make a different PR so I can change ``pygame.math.lerp`` code, just to difference new api and enhancement.

2024-01-20 11:06 UTC, bilhox commented on src_c/math.c
> +                     "invlerp requires all the arguments to be numbers");
So If I understood, I should write something like this ? :
```c
double v = PyFloat_AsDouble(value);
if (PyErr_Occurred())
    return RAISE(PyExc_ValueError,
                 "invalid `arg` values passed to remap, the value might "
                 "be too small or too big");
double a = PyFloat_AsDouble(i_min);
// same here
double b = PyFloat_AsDouble(i_max);
// same here
double c = PyFloat_AsDouble(o_min);
// same here
double d = PyFloat_AsDouble(o_max);
// same here
```

2024-01-29 16:43 UTC, ankith26 commented on src_c/math.c
> +                     "invlerp requires all the arguments to be numbers");
Well, we could do a simple `return NULL` as the error is already set. But the error won't be really specific

2024-02-11 12:24 UTC, MyreMylar requested changes
At the minute the float version of the inverse lerp implementation doesn't work how I would expect. It does not reverse a `lerp()` operation - except if the result is between 0 and 1.

the `remap()` seems ok 👍

2024-02-11 12:24 UTC, MyreMylar commented on src_c/math.c
> +        t = 1.0;
This check breaks the implementation of inverse lerp. You need to be able to reverse the interploatation of results larger than 1. e.g:

```
inv_lerp_result = pygame.math.invlerp(0, 10, 5)
```

Currently this will return 0.1, It should return 0.5. You need to expand your test cases with third parameters with a magnitude larger than 1. See this page on the inverse lerp function:

https://www.gamedev.net/articles/programming/general-and-gameplay-programming/inverse-lerp-a-super-useful-yet-often-overlooked-function-r5230/

2024-02-11 12:25 UTC, MyreMylar commented on test/math_test.py
> +
```suggestion
        a = 0.0
        b = 10.0
        self.assertEqual(pygame.math.invlerp(a, b, 5.0), 0.5)

```

2024-02-11 12:25 UTC, MyreMylar commented on test/math_test.py
> +
Changing a test to show how the implementation is not working.

2024-02-11 12:28 UTC, MyreMylar commented on test/math_test.py
> +        self.assertEqual(pygame.math.invlerp(a, b, 1.5), 0.55)
```suggestion
        a = -10.0
        b = 10.0
        self.assertEqual(pygame.math.invlerp(a, b, 1.0), 0.55)
```

2024-02-11 12:28 UTC, MyreMylar commented on test/math_test.py
> +        self.assertEqual(pygame.math.invlerp(a, b, 1.5), 0.55)
Correcting test.

2024-02-11 12:30 UTC, MyreMylar commented on test/math_test.py
> +        self.assertEqual(pygame.math.invlerp(a, b, 1.0), 0.55)
```suggestion
        self.assertEqual(pygame.math.invlerp(a, b, 1.5), 0.575)
```
Better correction.

2024-02-11 12:31 UTC, bilhox commented on src_c/math.c
> +        t = 1.0;
technically, I just have to remove the value limit and it's okay

2024-02-12 13:46 UTC, MyreMylar approved these changes
LGTM 👍 works as described now.

2024-02-25 13:40 UTC, Matiiss approved these changes
LGTM 🎉
If you want to, you can implement Ankith's suggestions, but otherwise it seems to be functionally fine. It is failing one of the CI runs though and as far as I can tell, you'd just need to rebase this branch on top of main and that should fix that I hope.

2024-02-25 16:22 UTC, Matiiss commented
> There is one thing I didn't understand from what ankith asked me to do, and with my exams I didn't have time sorry. Anyways, if you can explain me how to specificly now which variable is incorrect, rather than copy/pasting the error condition.

Good question, one approach would of course be a macro that does that, just add it after every double conversion and give it the argument number or name or whatever and make it just add the error message with that name in that place using the macro (make sure you undef it after usage). I guess another approach is a function, but that seems somewhat unnecessary for this. So yeah, probably a macro if you want to do that.

2024-05-30 16:29 UTC, ankith26 commented on src_c/math.c
> +    }
```suggestion
#define RAISE_ARG_TYPE_ERROR(var)                                     \
    if (PyErr_Occurred()) {                                           \
        return RAISE(PyExc_TypeError,                                 \
                     "The argument '" var "' must be a real number"); \
    }
```

2024-05-30 16:29 UTC, ankith26 commented on src_c/math.c
> +    double b = PyFloat_AsDouble(max);
```suggestion
    double a = PyFloat_AsDouble(args[0]);
    RAISE_ARG_TYPE_ERROR("min")
    double b = PyFloat_AsDouble(args[1])
    RAISE_ARG_TYPE_ERROR("max")
    double t = PyFloat_AsDouble(args[2]);
    RAISE_ARG_TYPE_ERROR("value")
```
We check if `PyFloat_AsDouble` raises an error, and if it does, it means that the input is incorrect and therefore raise our custom error that tells which argument exactly is incorrect.

Sorry for the back and forth about the reviews, but if this is resolved I don't think I will have any other issues with this PR. You can also apply a similar patch for the other function being added

2024-05-31 06:24 UTC, ankith26 commented on src_c/math.c
> +                     "might be too small or too big");
this check is redundant now

2024-05-31 06:24 UTC, ankith26 commented on src_c/math.c
> +    double d = PyFloat_AsDouble(o_max);
same macro and changes as above have to be applied here too

2024-05-31 06:56 UTC, Starbuck5 commented
Why is this implemented in C?

2024-05-31 07:02 UTC, MyreMylar commented
> Why is this implemented in C?

Why not? I think for this current PR it would be a bit awkward & somewhat confusing to have 90% of the current math library in C and just two functions not written in C. It is a worthwhile question to ask though and I would like more of pygame's code to be written in python.

If you are pondering re-implementing the _whole_ of `pygame.math` in python then that would be interesting to see how the current speed of python 3.12 stacks up against C implementations.

2024-05-31 07:08 UTC, Starbuck5 commented
> Why not?

Because bigwhoop's feature request had the functions written in Python. It would be trivial to just monkey patch them in in `__init__.py`.

Less code on our end, might even be more performant.

2024-05-31 07:16 UTC, MyreMylar commented
> > Why not?
> 
> Because bigwhoop's feature request had the functions written in Python. It would be trivial to just monkey patch them in in `__init__.py`.
> 
> Less code on our end, might even be more performant.

I'd like to see a pull request like this - both to see how it looks as an example case, and to see some performance testing. I think performance is definitely relevant for a math function like this that could be called repeatedly in tight loop drawing code.

2024-05-31 07:32 UTC, ankith26 commented
Here is a simple performance test script for testing the `invlerp` implemented here
```py
import pygame
import random
import time


use_python = False

objs = [
    (
        random.uniform(-100, 100),
        random.uniform(-100, 100),
        random.uniform(0, 1),
    )
    for _ in range(5000)
]

def py_invlerp(a, b, v, /):
    return (v - a) / (b - a)


start = time.time()

if use_python:
    for arg in objs:
        py_invlerp(*arg)


else:
    for arg in objs:
        pygame.math.invlerp(*arg)


print(time.time() - start)
```
I'm on python 3.12 and the C version implemented in this PR is more performant than the python version. However, at the rate at which the language is evolving (with the jit compiler and stuff), the difference is only going to lessen over the years, seems like.

On this specific case, I still would support the C implementation because it is simple enough, and if we ever decide to do a python re-implementation: it's a one-liner.

2024-05-31 07:34 UTC, bilhox commented
I highly believe that at this stage of implementation, and because the rest of math lib is written in C, that we keep this implementation.

2024-05-31 08:04 UTC, Starbuck5 commented on docs/reST/ref/math.rst
> +   | :sg:`invlerp(a, b, value, /) -> float`
Why is a, b, value here and a, b, weight in the stubs?

2024-05-31 08:11 UTC, Starbuck5 commented on docs/reST/ref/math.rst
> +   If ``b - a`` is equal to 0, it raises a ``ZeroDivisionError``.
This was very confusing to me when I was trying to figure out this function.

It takes 2 endpoints and a value, it returns the lerp amount of the value relative to the endpoints.

I think an example in this doc could help.

```py
>>> a = 10
>>> b = 20
>>> pygame.math.invlerp(10, 20, 11.5)
0.15
>>> pygame.math.lerp(10, 20, 0.15)
11.5
```

2024-05-31 08:12 UTC, Starbuck5 commented on docs/reST/ref/math.rst
> +   If ``b - a`` is equal to 0, it raises a ``ZeroDivisionError``.
I tried to look up "inverse interpolation" and got completely unhelpful results like this: https://en.wikipedia.org/wiki/Inverse_quadratic_interpolation.

2024-06-01 18:38 UTC, bilhox commented on docs/reST/ref/math.rst
> +   | :sg:`invlerp(a, b, value, /) -> float`
small mistake

2024-06-01 19:09 UTC, bilhox commented on docs/reST/ref/math.rst
> +   If ``b - a`` is equal to 0, it raises a ``ZeroDivisionError``.
Added an example and re explained the purpose of the function in the docs.

2024-06-02 07:33 UTC, MyreMylar commented on src_c/math.c
> +    RAISE_ARG_TYPE_ERROR("min")
```suggestion
    RAISE_ARG_TYPE_ERROR("a")
```

2024-06-02 07:33 UTC, MyreMylar commented on src_c/math.c
> +    RAISE_ARG_TYPE_ERROR("max")
```suggestion
    RAISE_ARG_TYPE_ERROR("b")
```

2024-06-02 10:47 UTC, merged