Rect() and FRect() initialization with no arguments
pygame-community/pygame-ce pull request #2655
Opened 2024-01-04 14:11 UTC by Damus666

I've added 3 lines of code to the C src to allow `Rect` and `FRect` to be made by passing no arguments to them, which will result in a zero rect (x, y, w, h = 0).
The check is so little it should not impact performance at all.

Why did i do this?
- Code speed and quantity: this is an insignificant point but it takes less time/you type less to do `pygame.Rect()` rather than `pygame.Rect(0, 0, 0, 0)`
- It feels like it should be possible + prettier to see
- Consistency: the main point: why can i do `pygame.Vector2()` and i can't do `pygame.Rect()`? Well, now you do
- Same performace. I am very confident a little sequence length check on the args won't impact performance at all

Other than the C code i modified:
- The `_GenericRect` class in the `rect.pyi` stub to include parameterless `__init__`
- Added some lines of documentation to explain the new behaviour (i'm not the best at documenting, if you'd prefer something different tell me)
- Added a test in `rect_test.py` to verify the correct initialization of the rect

2024-01-04 14:46 UTC, itzpr3d4t0r commented on src_c/rect_impl.h
> +    }
This could just be `PyTuple_GET_SIZE` since `args` is guaranteed to be a tuple.

2024-01-04 14:50 UTC, Damus666 commented on src_c/rect_impl.h
> +    }
You're right. I'll correct this in a commit, thanks

2024-01-04 14:53 UTC, Matiiss commented on src_c/rect_impl.h
> +    }
Should also maybe move this check to after that InnerRect declaration line

2024-01-04 16:28 UTC, novialriptide commented
The code looks fine, but is there any use case for this?

2024-01-05 09:04 UTC, Damus666 commented
> The code looks fine, but is there any use case for this? (@novialriptide)

There are some, i think. Maybe you want to create a rectangle and assign it's values later, just like you'd do with a `Vector2`.
In my UI library you could benefit from this alot. Each element requires a `Rect` for positioning and sizing, but very often you just want for the element to resize automatically to fill the parent (specified in the style) so you pass an empty rectangle. I use this so much i even made the `guiscript.ZeroR()` function. Having it built in would be nice, and it would be also consistent as i can do that with `pygame.Vector2` as mentioned above. temporary rects, dummy rects, rects made in the `__init__`/setup and then changed later etc could all be created without parameters. And since the check i'm adding is a simple tuple size check, i'm confident it won't impact performance so it also raises the question "why not?".

2024-01-06 13:44 UTC, ankith26 commented on src_c/rect_impl.h
> +        return 0;
we should probably explicitly set all the fields of `self->r` to 0 here. I dunno the internals of python memory management but relying on it to be 0 initialised sounds like a bad idea anyways

2024-01-07 10:33 UTC, Damus666 commented on src_c/rect_impl.h
> +        return 0;
That's true, thanks. We don't want our rect to have random values from existing memory (it happened at the previous attempt at this). I'll be updating it now.

2024-01-07 10:40 UTC, itzpr3d4t0r commented on src_c/rect_impl.h
> +        return 0;
This is weird, since we already do that in `RectExport_new`, in theory we shouldn't do this again...

2024-01-07 12:26 UTC, Damus666 commented on src_c/rect_impl.h
> +        return 0;
When I said it happened at the previous attempt, I meant it happened when I tried to achieve the same result a few months ago when I was editing another function. Tell me if you think the change is still needed, and if yes, I posted a weird failure on the discord channel #contributing, maybe you know why

2024-01-07 12:34 UTC, itzpr3d4t0r requested changes

2024-01-07 12:34 UTC, itzpr3d4t0r commented on src_c/rect_impl.h
> +        self->weakreflist = NULL;
Yeah I don't think this is necessary. rect_new already sets all fields to zero. To check this is true, just run this program for an arbitrary number of times:
```Py
from pygame import Rect

r_zero = Rect(0, 0, 0, 0)

l = [r_zero == Rect.__new__(Rect) for _ in range(10_000_000)]
print(all(l))
```

2024-01-07 13:31 UTC, Damus666 commented on src_c/rect_impl.h
> +        self->weakreflist = NULL;
Yeah, exactly. I removed those in the newest commit, thanks

2024-01-07 13:37 UTC, itzpr3d4t0r commented on test/rect_test.py
> +
A test for FRect is still missing.

2024-01-07 13:37 UTC, itzpr3d4t0r commented on docs/reST/ref/rect.rst
> +   If no arguments are given, a zero Rect will be created (x, y, w, h = 0).
I don't really like the format of `(x, y, w, h = 0)`, it looks like only the h is set to zero that way. Maybe something like `(x=0, y=0, w=0, h=0)` or `(x, y, w, h) = (0, 0, 0, 0)` would be more clear?

2024-01-07 13:37 UTC, itzpr3d4t0r commented on buildconfig/stubs/pygame/rect.pyi
> +    def __init__(self) -> None: ...
This should return a `Rect`/`Frect`, not `None` no?

2024-01-07 13:39 UTC, itzpr3d4t0r commented on test/rect_test.py
> +
You should also add tests for Rect/Frect subclasses.

2024-01-07 13:47 UTC, Damus666 commented on test/rect_test.py
> +
The FRect test unit inherits from the normal rect test, so it should have that already. Please correct me if i'm wrong

2024-01-07 13:48 UTC, Damus666 commented on docs/reST/ref/rect.rst
> +   If no arguments are given, a zero Rect will be created (x, y, w, h = 0).
Good idea, I'll change that for the next commit (i'll commit once all the code change requests are resolved)

2024-01-07 18:28 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada: 

I agree with the reasoning to add this API, might not be a huge deal, but does no harm so why not.

I also see that `__new__` inits the fields to 0 already, so there's no issue of uninitialised memory at any point

2024-01-28 10:15 UTC, MyreMylar approved these changes
LGTM, and the API makes sense. 👍

2024-01-28 10:39 UTC, itzpr3d4t0r approved these changes

2024-01-28 10:41 UTC, merged