Add Circle `collideswith()`
pygame-community/pygame-ce pull request #2661
Opened 2024-01-07 11:40 UTC by itzpr3d4t0r

This PR adds the much awaited Circle.collideswith function.

## Credits

**Geometry Project:**
For code, docs and tests:
@novialriptide @Emc2356 @itzpr3d4t0r @ScriptLineStudios @avaxar @Matiiss @newpaxonian @maqa41 @blankRiot96
Also thanks to @Starbuck5 for kickstarting the idea and the occasional help!

**Functionality added in this PR**
- `circle.c`
https://github.com/pygame-community/pygame-geometry/blame/main/src_c/circle.c
Credits to @Emc2356 @itzpr3d4t0r @novialriptide
- `geometry.pyi`
https://github.com/pygame-community/pygame-geometry/blame/main/geometry.pyi
Credits to @Emc2356 @itzpr3d4t0r @novialriptide @ScriptLineStudios @avaxar 
- `geometry_test.py`
https://github.com/pygame-community/pygame-geometry/blame/main/test/test_circle.py
Credits to @itzpr3d4t0r @novialriptide
- `geometry.rst`
https://github.com/pygame-community/pygame-geometry/blame/main/docs/circle.rst
Credits to @itzpr3d4t0r

2024-01-23 00:29 UTC, Matiiss requested changes

2024-01-23 00:29 UTC, Matiiss commented on buildconfig/stubs/pygame/geometry.pyi
> +    def collideswith(self, other: _CanBeCollided) -> bool: ...
The stub needs `/` because the arg is positional-only

2024-01-23 00:29 UTC, Matiiss commented on docs/reST/ref/geometry.rst
> +         | :sg:`contains(Vector2) -> bool`
All of these signatures need a forward slash [`/`] added to signify that they are positional-only argument.
The names need to be in `snake_case` (i.e., lowercased (the `FRect` signature can be omitted since `rect` would cover it as well)), this is because `ClassName` notation in doc signatures was used to signify that the argument was positional-only, now that's done with `/`.

Basically it should be
```
         | :sg:`collideswith(circle, /) -> bool`
         | :sg:`collideswith(rect, /) -> bool`
         | :sg:`collideswith((x, y), /) -> bool`
         | :sg:`contains(vector2, /) -> bool`
```

2024-01-28 11:53 UTC, itzpr3d4t0r commented on docs/reST/ref/geometry.rst
> +         | :sg:`contains(Vector2) -> bool`
Thanks!

2024-02-12 13:31 UTC, MyreMylar approved these changes
LGTM 👍 

All works locally. Tested with:

```python
import pygame

from pygame import Color, Rect, Vector2
from pygame.geometry import Circle

pygame.init()
screen = pygame.display.set_mode((640, 480), 0)

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

circle_1 = Circle((50, 50), 30)
circle_col = Color("red")

circle_2 = Circle((250, 250), 30)
circle_2_col = Color("blue")

rect_3 = Rect(40, 40, 30, 30)
rect_3_col = Color("blue")

point_4_col = Color("blue")
point_4 = Vector2(100, 150)

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    circle_1.center = pygame.mouse.get_pos()

    if circle_1.collideswith(circle_2):
        circle_col = Color("blue")
        circle_2_col = Color("green")
    elif circle_1.collideswith(point_4):
        circle_col = Color("blue")
        point_4_col = Color("green")
    elif circle_1.collideswith(rect_3):
        circle_col = Color("blue")
        rect_3_col = Color("green")
    else:
        circle_col = Color("red")
        circle_2_col = Color("blue")
        rect_3_col = Color("blue")

    screen.blit(white_background, (0, 0))

    pygame.draw.circle(screen, circle_col, (circle_1.x, circle_1.y), circle_1.r)
    pygame.draw.circle(screen, circle_2_col, (circle_2.x, circle_2.y), circle_2.r)
    pygame.draw.rect(screen, rect_3_col, rect_3)
    pygame.draw.line(screen, point_4_col, point_4, point_4)

    pygame.display.flip()


pygame.quit()

```

2024-02-25 13:31 UTC, Matiiss commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Coordinate, Vector2]
Probably no need to include Vector2 in this if we got Coordinate in there, but it probably doesn't hurt anyway, so, probably can stay

2024-02-25 17:17 UTC, itzpr3d4t0r commented on test/geometry_test.py
> +            """tests if the function correctly handles incorrect types as parameters"""
Yes it is xD, might've happened because of the merge with main.

2024-02-25 17:18 UTC, itzpr3d4t0r commented on src_c/circle.c
> +                     "LineType, PolygonType or a sequence of 2 numbers");
Thanks, I changed it a bit. I've removed mentions of Line and Poly as well.

2024-02-25 18:04 UTC, Matiiss commented on src_c/circle.c
> +                     "LineType, PolygonType or a sequence of 2 numbers");
not sure Coordinate should've been used instead of a sequence of two points since we don't really have a Coordinate object, it only appears in type stubs, maybe you can change that back, as for the other shapes, maybe those could stay in the message since otherwise they'd have to be added later and that could be forgotten.

2024-02-25 19:47 UTC, itzpr3d4t0r commented on src_c/circle.c
> +                     "LineType, PolygonType or a sequence of 2 numbers");
Alright.

2024-02-25 20:56 UTC, Matiiss approved these changes

2024-02-25 20:56 UTC, merged