Add Circle `rotate()` / `rotate_ip()`
pygame-community/pygame-ce pull request #2662
Opened 2024-01-07 13:18 UTC by itzpr3d4t0r

This PR adds the circle.rotate and circle.rotate_ip functions.

## Credits

**Geometry Project:**
For code, docs and tests:
@novialriptide @Emc2356 @itzpr3d4t0r @ScriptLineStudios @avaxar @Matiiss @newpaxonian @maqa41 @blankRiot96
Also thanks to @Starbuck5 for kickstarting the idea and the occasional help!

**Functionality added in this PR**
- `circle.c`
https://github.com/pygame-community/pygame-geometry/blame/main/src_c/circle.c
Credits to @Emc2356 @itzpr3d4t0r @novialriptide
- `geometry.pyi`
https://github.com/pygame-community/pygame-geometry/blame/main/geometry.pyi
Credits to @Emc2356 @itzpr3d4t0r @novialriptide @ScriptLineStudios @avaxar 
- `geometry_test.py`
https://github.com/pygame-community/pygame-geometry/blame/main/test/test_circle.py
Credits to @itzpr3d4t0r @novialriptide
- `geometry.rst`
https://github.com/pygame-community/pygame-geometry/blame/main/docs/circle.rst
Credits to @itzpr3d4t0r
- `geometry.h`
https://github.com/pygame-community/pygame-geometry/blame/main/src_c/include/geometry.h
Credits to @Emc2356 @itzpr3d4t0r @maqa41

2024-01-22 23:33 UTC, Matiiss commented
Should `rotation_point` have a default value (`None`) for rotation around the center? Kind of useless for a circle since we can just shortcut it to return self, but it would be consistent with the rest of the geometry API (at least polygons have a default value).

2024-01-22 23:52 UTC, Matiiss requested changes
A really minor thing, but also the error messages have inconsistencies in first letter cases, they should all be lowercase, i.e., `Invalid` -> `invalid`

2024-01-22 23:52 UTC, Matiiss commented on buildconfig/stubs/pygame/geometry.pyi
> +    def rotate_ip(self, angle: float, rotation_point: Coordinate) -> None: ...
These both need overloads for when only the angle is supplied, since there is no default value for `rotation_point`. Also need to add `/` to indicate that they are positional-only arguments (this applies to the rest of the stubs as well).

2024-01-22 23:52 UTC, Matiiss commented on docs/reST/ref/geometry.rst
> +         | :sg:`rotate(angle, rotation_point=Circle.center) -> None`
Same thing as with stubs, probably should show two method signatures and need to add `/` to indicate that they are positional-only args.

2024-01-22 23:52 UTC, Matiiss commented on docs/reST/ref/geometry.rst
> +         | :sg:`rotate_ip(angle, rotation_point=Circle.center) -> None`
Same as with `rotate`

2024-01-22 23:52 UTC, Matiiss commented on src_c/doc/geometry_doc.h
> +#define DOC_CIRCLE_ROTATE ""
The generated docstring is empty, likely because there needs to be a blank line between
```
   .. method:: rotate
```
and
```
         | :sl:`rotates the circle`
```
in `geometry.rst` (see `rotate_ip` docs, because they are generated)

2024-02-11 16:27 UTC, MyreMylar commented on test/geometry_test.py
> +        """Ensures that the rotate method always returns a Line."""
```suggestion
        """Ensures that the rotate method always returns a Circle."""
```

2024-02-11 16:47 UTC, MyreMylar commented on docs/reST/ref/geometry.rst
> +         The rotation point can be a `tuple`, `list`, or `Vector2`.
```suggestion
         A positive angle rotates the circle clockwise, while a negative angle rotates it counter-clockwise. Angles are in degrees.
         The rotation point can be a `tuple`, `list`, or `Vector2`.
```

2024-02-11 16:48 UTC, MyreMylar commented on docs/reST/ref/geometry.rst
> +         A positive angle rotates the circle clockwise, while a negative angle rotates it counter-clockwise.
```suggestion
         A positive angle rotates the circle clockwise, while a negative angle rotates it counter-clockwise.  Angles should be specified in degrees.
```

2024-02-11 16:51 UTC, MyreMylar approved these changes
LGTM 👍  Does what it says, and there is documentation and tests.

I used the following cisual test program to tinker around with it:

```python
import pygame

from pygame import Color
from pygame.geometry import Circle

pygame.init()
screen = pygame.display.set_mode((640, 480), 0)

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

circle_1 = Circle((50, 50), 30)
circle_col = Color("red")

circle_2 = Circle((250, 250), 30)
circle_2_col = Color("blue")

clock = pygame.time.Clock()

running = True
curr_angle = 2.0
rotate_time = 0.005
rotate_acc = 0.0
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.MOUSEBUTTONDOWN and event.button == pygame.BUTTON_LEFT:
            circle_1.center = (
                pygame.mouse.get_pos()[0],
                pygame.mouse.get_pos()[1] - 60,
            )

        if event.type == pygame.MOUSEBUTTONDOWN and event.button == pygame.BUTTON_RIGHT:
            circle_2 = circle_2.rotate(90, pygame.mouse.get_pos())

    dt = clock.tick() / 1000.0

    rotate_acc += dt
    if rotate_acc >= rotate_time:
        rotate_acc = 0.0
        circle_1.rotate_ip(curr_angle, pygame.mouse.get_pos())

    if circle_1.collidecircle(circle_2.x, circle_2.y, circle_2.radius):
        circle_col = Color("blue")
        circle_2_col = Color("green")
    else:
        circle_col = Color("red")
        circle_2_col = Color("blue")

    screen.blit(white_background, (0, 0))

    pygame.draw.circle(screen, circle_col, (circle_1.x, circle_1.y), circle_1.r)
    pygame.draw.circle(screen, circle_2_col, (circle_2.x, circle_2.y), circle_2.r)

    pygame.display.flip()


pygame.quit()

```

I left a couple of minor suggestions on the documentation and spotted one copy and paste typo in the tests.

2024-02-12 13:05 UTC, MyreMylar commented
You'll need to merge with main again to pick up that CircleCI fix I guess.

2024-02-25 13:36 UTC, Matiiss commented on src_c/circle.c
> +    if (angle == 0.0 || fmod(angle, 360.0) == 0.0) {
is this `angle == 0.0` check necessary if we check for the remainder anyway?

2024-02-25 15:40 UTC, itzpr3d4t0r commented on src_c/circle.c
> +    if (angle == 0.0 || fmod(angle, 360.0) == 0.0) {
we avoid doing the fmod in that way, but it could be removed.

2024-02-25 16:18 UTC, Matiiss commented on src_c/circle.c
> +    if (angle == 0.0 || fmod(angle, 360.0) == 0.0) {
I don't think we avoid it because this is C, it doesn't do any short-circuiting like Python that I'm aware of.

2024-02-25 16:52 UTC, Matiiss commented on src_c/circle.c
> +    if (angle == 0.0 || fmod(angle, 360.0) == 0.0) {
Nevermind, apparently it does short-circuit

2024-02-25 16:52 UTC, Matiiss approved these changes
Thanks for the PR 🎉

2024-02-25 16:53 UTC, merged