added from_normalized() and get and set normalized methods for pygame.Color
pygame-community/pygame-ce pull request #2693
Opened 2024-01-23 19:38 UTC by XFajk

this should add the feature requested in #2645 
I added the `from_normalized()` method to `pygame.Color` also I added the getter and setter methods for the `normalized` parameter so you can change it

2024-01-24 04:54 UTC, ankith26 submitted a review, later dismissed
For backward compatibility reasons, we cannot remove the `normalize()` method. However, we can definitely add a new `from_normalized()` class method, and a new `normalized` property

2024-01-24 06:41 UTC, XFajk commented
Added it back

2024-01-24 21:13 UTC, Matiiss requested changes
Thanks a lot for the PR!

The implementation looks great!

A couple of things that need to be added:
- docs (see the comment about the color_doc.h file)
- tests, need to add those for the new property and classmethods, test file is `test/color_test.py`, just follow the existing tests for these properties and methods
- type stubs, need to add those in `buildconfig/stubs/pygame/color.pyi`, again, just see how it is already done and follow that example

2024-01-24 21:13 UTC, Matiiss commented on src_c/color.c
> +        PyErr_SetString(PyExc_ValueError, "invalid CMY value");
The error message here says "CMY", should be "normalized"

2024-01-24 21:13 UTC, Matiiss commented on src_c/color.c
> +/** deprecated
I don't think this comment is necessary and the method is not really deprecated yet

2024-01-24 23:13 UTC, XFajk commented on src_c/doc/color_doc.h
should I add the .. versionadded:: x.y.z to the docs and if yes what version

2024-01-25 01:38 UTC, Matiiss commented on src_c/doc/color_doc.h
Yep, 2.5.0

2024-01-25 01:51 UTC, Matiiss commented on docs/reST/ref/color.rst
> +      in the ranges specified ``r`` = [0, 1], ``g`` = [0, 1], ``b`` = [0, 1]
> The ``Normalized``` components of are

Something is missing in that sentence there

2024-01-25 01:57 UTC, Matiiss commented on src_c/color.c
> +    color->data[3] = (Uint8)round(frgba[3]*255.0)-1;
The CI is failing (https://github.com/pygame-community/pygame-ce/actions/runs/7647698984/job/20841798096?pr=2693#step:3:2200) because your test is failing and your test is failing mostly because you are subtracting 1 from the rounded value, I'd suggest removing that `-1` subtraction here because if given 1 the result should obviously be 255 not 254
And also because with 0 it will be 0 but then you subtract 1 and it goes up to 255 which also doesn't really make sense.

2024-01-25 01:57 UTC, Matiiss commented on test/color_test.py
> +        expected_normal = (255, 255, 255)
This should be
```
expected_normal = (255, 255, 255, 255)
```

2024-01-25 01:58 UTC, Matiiss commented
Also make sure you run `python setup.py format`, otherwise the linter is failing as well.

2024-01-26 10:15 UTC, XFajk commented
ok I have changed the docs a bit though I am not sure if this is how you wanteded it. So check it out again and tell me if it can be that way. Hopefully, I copied/made all the tests for the normalized representation if I have missed any pls tell me I am not sure I double checked but I may have missed one or two

2024-01-26 23:51 UTC, XFajk commented
> LGTM 👍 I assume those other random files were formatted by `python setup.py format`, since the changes are tiny, I assume it's fine to leave them in.

yeah exactly

2024-02-04 17:55 UTC, MyreMylar approved these changes
LGTM 👍

2024-02-04 17:57 UTC, merged