PixelArray raise error assigning sequence to pixel
pygame-community/pygame-ce pull request #2742
Opened 2024-03-07 19:29 UTC by ankith26

fixes https://github.com/pygame-community/pygame-ce/issues/2740

- In the pixelarray module, any sequence (except tuple and `pygame.Color`) isn't considered a "color", but rather a pixel sequence
- The segfault happens because the code expects a pixelarray upon subscripting for assignment, but receives an "integer color"

I am open to suggestions on how to improve the error message, can't think of something descriptive enough ATM.

2024-03-27 02:23 UTC, oddbookworm requested changes
I take it the segfault is reproducible? If so, I'd like to see a regression test

2024-03-27 04:59 UTC, ankith26 commented
Have added the regression test, thanks for pointing it out

2024-04-26 15:52 UTC, oddbookworm approved these changes
LGTM!

2024-04-27 13:21 UTC, narilee2006 commented
Why not convert the `PyList` to a `PyTuple`?
```c
static int
_pxarray_ass_item(pgPixelArrayObject *array, Py_ssize_t index, PyObject *value)
{
    // Shortened code...

    if (PyList_Check(value))
        value = PyList_AsTuple(value);
```

2024-04-27 13:26 UTC, ankith26 commented
That is a behaviour change that deviates from the specification of the pixelarray module. According to the docs:
> For assignment, a tuple can only be a color. Any other sequence type is a sequence of colors.

2024-05-11 10:19 UTC, MyreMylar approved these changes
LGTM 👍

2024-05-11 10:19 UTC, merged