Remove pygame.threads
pygame-community/pygame-ce pull request #2762
Opened 2024-03-21 07:51 UTC by Starbuck5

The source file doesn't seem to have had a non-linting related update in the past 7 years, it's not documented, and a scour of Google for mentions saw no one using it. I think this is safe to remove.

2024-03-21 07:54 UTC, Starbuck5 commented on test/test_utils/run_tests.py
These run_tests changes only impact the "use subprocess" mode, which we don't use. And regardless, the use subprocess mode doesn't work. I have a patch locally that gets it working but I am not seeing much improvement in runtime by multithreading this.

2024-03-22 04:48 UTC, ankith26 requested changes
I think we could deprecate it but not remove it just yet.
On a quick search I found atleast one github repo that uses it: https://github.com/pmtkachev/TMNT-Fight-NES/blob/c297f8aa9d802dc3fdbfc4b1b8726ccc95eeff97/src/game_func.py#L2

2024-03-22 06:39 UTC, Starbuck5 commented
> I think we could deprecate it but not remove it just yet.
On a quick search I found atleast one github repo that uses it: https://github.com/pmtkachev/TMNT-Fight-NES/blob/c297f8aa9d802dc3fdbfc4b1b8726ccc95eeff97/src/game_func.py#L2

But they're not using the functionality! pygame.threads.Thread is a weird import of threading.Thread. They must've written thread and clicked "fix imports" and picked something from a list. No human would've written that unaided.

This is an undocumented module that hasn't made any progress towards being a real thing since pygame 1.8.1, and has never been documented anywhere. The functionality is available in the standard library now.

I don't see an undocumented experimental module that no one is actually using as being covered by any backwards compatibility concerns.

2024-03-27 02:38 UTC, oddbookworm commented
> But they're not using the functionality! pygame.threads.Thread is a weird import of threading.Thread. They must've written thread and clicked "fix imports" and picked something from a list. No human would've written that unaided.

Side note:
I created a [pull request](https://github.com/pmtkachev/TMNT-Fight-NES/pull/2) there to get rid of the weird alias and just use the real thing lol

2024-03-27 02:41 UTC, oddbookworm approved these changes
LGTM!

2024-03-27 05:25 UTC, ankith26 requested changes

2024-03-27 05:25 UTC, ankith26 commented on test/image_test.py
> +            with ThreadPoolExecutor(max_workers=20) as executor:
shouldn't the loop be inside the context block?

The current code is still going to sequentially load stuff because a new executor instance is created for each loop?

2024-03-27 05:38 UTC, Starbuck5 commented on test/image_test.py
> +            with ThreadPoolExecutor(max_workers=20) as executor:
This does what the previous code does. It loads all images in parallel, 10 times.

2024-03-27 05:44 UTC, ankith26 approved these changes
Okay sure, let's remove this. Thanks for the PR :tada:

2024-03-28 07:19 UTC, merged