Minor optimizations by using comprehensions
pygame-community/pygame-ce pull request #2771
Opened 2024-03-25 18:35 UTC by cclauss

% `pipx install ruff`
% `ruff check --select=C4,PERF --statistics`
```
30	C408   	[*] Unnecessary `dict` call (rewrite as a literal)
10	C406   	[*] Unnecessary `tuple` literal (rewrite as a `dict` literal)
10	C417   	[*] Unnecessary `map` usage (rewrite using a generator expression)
 9	PERF401	[ ] Use a list comprehension to create a transformed list
 2	C419   	[*] Unnecessary list comprehension
 2	PERF203	[ ] `try`-`except` within a loop incurs performance overhead
 2	PERF402	[ ] Use `list` or `list.copy` to create a copy of a list
```
% `ruff rule C408`
# unnecessary-collection-call (C408)

Derived from the **flake8-comprehensions** linter.

Fix is always available.

## What it does
Checks for unnecessary `dict`, `list` or `tuple` calls that can be
rewritten as empty literals.

## Why is this bad?
It's unnecessary to call, e.g., `dict()` as opposed to using an empty
literal (`{}`). The former is slower because the name `dict` must be
looked up in the global scope in case it has been rebound.

## Examples
```python
dict()
dict(a=1, b=2)
list()
tuple()
```

Use instead:
```python
{}
{"a": 1, "b": 2}
[]
()
```

## Fix safety
This rule's fix is marked as unsafe, as it may occasionally drop comments
when rewriting the call. In most cases, though, comments will be preserved.

## Options
- `lint.flake8-comprehensions.allow-dict-calls-with-keyword-arguments`

2024-03-26 05:35 UTC, ankith26 commented on buildconfig/config.py
> +            lids.extend(LPREFIX+dir[startind:]for dir in dep.lib_dir)
```suggestion
            lids.extend(LPREFIX+dir[startind:] for dir in dep.lib_dir)
```
formatting issue, must have space before `for`

2024-03-26 13:52 UTC, ankith26 requested changes
The lint job seems to have failed with other errors on this PR, so a commit fixing all those will also be needed

2024-03-26 13:55 UTC, cclauss commented
Are you talking about #2773 or something else?
* #2773

2024-03-26 13:57 UTC, ankith26 commented
I'm talking about this fail: https://github.com/pygame-community/pygame-ce/actions/runs/8425378679/job/23088593026

2024-03-27 05:51 UTC, ankith26 approved these changes
LGTM, thanks for the PR :partying_face:

2024-03-29 06:17 UTC, Starbuck5 commented
This PR now has merge conflicts.

2024-03-29 08:41 UTC, cclauss commented
Git conflicts fixed.

2024-04-26 07:55 UTC, zoldalma999 approved these changes
LGTM, thanks!

2024-04-26 07:55 UTC, merged