PEP572 Use Python's assignment expression
pygame-community/pygame-ce pull request #2782
Opened 2024-03-29 21:18 UTC by cclauss

As discussed at https://github.com/pygame-community/pygame-ce/pull/2770#pullrequestreview-1962131646
* https://peps.python.org/pep-0572

2024-03-30 23:38 UTC, oddbookworm requested changes
Just one small change I'd like to see, but overall looks good!

2024-03-31 04:47 UTC, cclauss commented on test/mixer_test.py
> +        if (lshift := abs(format) - 8 * a.itemsize) >= 0:
```suggestion
        lshift = abs(format) - 8 * a.itemsize
        if lshift >= 0:
```

2024-03-31 07:48 UTC, cclauss commented
Failing test is fixed in
* #2783

2024-04-02 13:32 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada:

2024-04-09 15:39 UTC, merged