draw.aacircle()
pygame-community/pygame-ce pull request #2800
Opened 2024-04-14 02:05 UTC by mzivic7

Pygame-ce has only `gfxdraw.aacircle` function for drawing antialiased circles, but it has several problems:
- It's arguments are different from draw.circle
- It does not accept float as input
- It can't draw circle quadrants
- There is no line thickness option
   Related issue: #2463
- Draws incorrect lines when radius is larger than about 1000
   Related issue: #2450

and it is intended to be deprecated/removed in future.

All these problems are fixed in `draw.aacircle`, that is implemented in this commit.

Changes:
- Added `draw.aacircle` function that has same inputs and outputs as `draw.circle`
- Added algorithms for drawing thin and thick antialiased circles, adapted from:
https://cgg.mff.cuni.cz/~pepca/ref/WU.pdf
- Added to documentation
- Added to code_examples
- Added to tests

2024-04-14 02:08 UTC, oddbookworm commented
Looks like you need to run `python setup.py format`

2024-04-14 02:26 UTC, oddbookworm reviewed
Just a few comments, looking good so far!

2024-04-14 02:26 UTC, oddbookworm commented on buildconfig/stubs/pygame/draw.pyi
> +) -> Rect: ...
I think it would actually be better to have two signatures here. One without the bools, and one with

2024-04-14 02:26 UTC, oddbookworm commented on src_c/draw.c
> +    int posx, posy, radius;
Here you list radius as an int, but in the stub you put float

2024-04-14 02:26 UTC, oddbookworm commented on src_c/draw.c
> +        pixel_color = get_antialiased_color(surf, x0 + x, y0 - y, color, opacity);
CI is complaining about an implicit conversion from double to float here, either use a float for opacity or explicitly cast. I would be careful casting from double to float though because of the chance that the original might be outside the range of the destination type without validation

2024-04-14 02:26 UTC, oddbookworm commented on src_c/draw.c
> +eight_pixels(SDL_Surface *surf, int x0, int y0, Uint32 color, int x, int y,
What does `eight_pixels` mean? I recommend making the name more clear

2024-04-14 02:26 UTC, oddbookworm commented on src_c/draw.c
> +                x++;
Some people might complain about post-increment/decrement being used instead of pre-increment/decrement due to the post version making a copy yadda yadda yadda. I don't personally think it matters because of modern compiler optimization, but feel free to performance test it lol

2024-04-14 02:26 UTC, oddbookworm commented on test/draw_test.py
> +### AACircle Testing ############################################################
nitpick:
all the method names and the docstrings used `circle` and not `aacircle`

2024-04-14 03:06 UTC, mzivic7 commented on src_c/draw.c
> +    int posx, posy, radius;
but draw.circle does exactly same thing, this is because algorithms must use integer values for position and radius, but function still accepts floats

2024-04-14 09:52 UTC, mzivic7 commented on src_c/draw.c
> +    int posx, posy, radius;
`pg_IntFromObj` [here](https://github.com/pygame-community/pygame-ce/pull/2800/files/fb9ea0e7cb43297701a2fd4cb129f938cb9836eb#diff-d40ef6601363eeb9acdc38f0d143fc5a577b6c98f702eb13f68116af0b1ad7d6R783) converts python float object to integer and  stores it in radius variable.

2024-04-15 00:46 UTC, oddbookworm requested changes

2024-04-15 00:46 UTC, oddbookworm commented on buildconfig/stubs/pygame/draw.pyi
> +def aacircle(
I suspect that your stub check is failing due to the lack of `@overload` from `typing`

[docs](https://docs.python.org/3/library/typing.html#overload)

2024-04-15 00:46 UTC, oddbookworm commented on src_c/draw.c
> +                x++;
you changed where this is from my last review, is there a reason for that?

2024-04-15 00:46 UTC, oddbookworm commented on src_c/SDL_gfx/SDL_gfxPrimitives.c
> +__declspec(naked) long int lrint(double flt)
what version of `clang-format` do you have installed in your environment? There are a bunch of files here that you didn't modify, but got formatted. I want to make sure that we're using the correct version

2024-04-15 01:15 UTC, mzivic7 commented on src_c/SDL_gfx/SDL_gfxPrimitives.c
> +__declspec(naked) long int lrint(double flt)
clang-format version 17.0.6
clang is up-to-date with Arch repos

2024-04-15 01:27 UTC, mzivic7 commented on src_c/draw.c
> +                x++;
I changed from post-increment to pre-increment, as you said [here](https://github.com/pygame-community/pygame-ce/pull/2800#discussion_r1564392476)

2024-04-15 01:45 UTC, oddbookworm commented on src_c/draw.c
> +                x++;
Ah, I see the misunderstanding. By pre-increment, I meant `++x` instead of `x++` (post-increment)

2024-04-15 15:49 UTC, mzivic7 commented on src_c/SDL_gfx/SDL_gfxPrimitives.c
> +__declspec(naked) long int lrint(double flt)
black was missing

2024-04-15 16:14 UTC, mzivic7 commented on src_c/SDL_gfx/SDL_gfxPrimitives.c
> +__declspec(naked) long int lrint(double flt)
I installed clang-format 18.1.3 with pipenv, its all good now

2024-04-21 07:01 UTC, Starbuck5 commented on buildconfig/stubs/pygame/draw.pyi
> +) -> Rect: ...
Why? circle above just has one signature.

2024-04-21 07:02 UTC, Starbuck5 commented on src_c/draw.c
> +    }
Check out the `RAISE` macro we use for a lot of these"set error and return" cases.

2024-04-26 15:57 UTC, oddbookworm requested changes

2024-04-26 15:57 UTC, oddbookworm commented on src_c/draw.c
> +                                   255 - (float)opacity, top_right, top_left,
```suggestion
                                   255.0f - (float)opacity, top_right, top_left,
```

2024-04-26 15:57 UTC, oddbookworm commented on src_c/draw.c
> +                                   255 - (float)opacity, top_right, top_left,
The reason I suggest that is to be more explicit that we're subtracting floats specifically

2024-04-26 15:57 UTC, oddbookworm commented on src_c/draw.c
> +    double prev_opacity = 0;
```suggestion
    double prev_opacity = 0.0;
```

2024-04-26 16:38 UTC, mzivic7 commented on src_c/draw.c
> +    double prev_opacity = 0;
should I do the same for multiplications? 
I thought that in C basic math operations, when given an operand of type float and int, the int is converted to float first.

2024-04-26 16:39 UTC, mzivic7 commented on src_c/draw.c
> +                                   255 - (float)opacity, top_right, top_left,
should I do the same for multiplications?
I thought that in C basic math operations, when given an operand of type float and int, the int is converted to float first.

2024-04-26 16:42 UTC, oddbookworm commented on src_c/draw.c
> +                                   255 - (float)opacity, top_right, top_left,
I don't like implicit conversions in C. I prefer to be explicit whenever possible, especially when I'm mixing floating point and integral types

2024-05-20 18:45 UTC, oddbookworm approved these changes
I got a couple small comments, but this looks good!

2024-05-20 18:45 UTC, oddbookworm commented on src_c/draw.c
> +        double opacity = 255.0f * (ceil(height) - height);
nitpick: `255.0f` is a 32-bit float, not a 64-bit double. C would interpret `255.0` as a double

2024-05-20 18:45 UTC, oddbookworm commented on src_c/draw.c
> +    for (int radius_ = radius - thickness; radius_ <= radius; radius_++) {
I think maybe a better name for `radius_` would be preferred because it's too close to `radius`

2024-05-25 19:42 UTC, MyreMylar approved these changes
This looks really good to me! 👍 

Will enable us to shim the old gfxdraw version completely at some point and has features on top of that that make it consistent with draw.circle.

No notes! 🥇

2024-05-25 22:49 UTC, merged