Add pygame.display.get/set_window_pos() functions, tests, stubs and documentation
pygame-community/pygame-ce pull request #2816
Opened 2024-04-22 19:59 UTC by Damus666

I implemented what is said in the title of the pull request, I tested locally the functions.

Why?
- The window API should not have this feature restricted to it, without it seems incomplete
- The SDL code to achieve this is minimal so I see no reason to exclude this functionality
- The environment variable won't allow position changes after initialization and is nor pythonic nor clear
- The window API currently doesn't support OpenGL among the many features, so adding this feature to the display API is important
- Really, why not? It's not bloating nor complicating rather implementing existing and important functions provided by SDL

I'm very open to feedback and critics, I got inspired by the rest of `display.c` to write the implementation :)
Sorry for the double pull request, I messed up the previous branch.

2024-04-22 22:43 UTC, oddbookworm requested changes

2024-04-22 22:43 UTC, oddbookworm commented on src_c/display.c
> +    if (!PyArg_ParseTuple(arg, "i|i", &x, &y))
Why is the y coordinate optional?

2024-04-22 22:43 UTC, oddbookworm commented on buildconfig/stubs/pygame/display.pyi
> +def set_window_pos(x: int, y: int) -> None:...
I think this should be generalized to also accept any sequence of two integers as a single argument

2024-04-22 22:43 UTC, oddbookworm commented on src_c/display.c
> +        SDL_SetWindowPosition(win, x, y);
In SDL3, this will return something based on whether it was successful or not ([SDL3 docs](https://wiki.libsdl.org/SDL3/SDL_SetWindowPosition)). @Starbuck5 @ankith26 @MyreMylar what do y'all think about this? Should there be some version checks built into new code that can support SDL3 more directly in the future, or should that be added in with other SDL3-compat stuff?

The same also applies to `SDL_GetWindowPosition`

2024-04-22 22:43 UTC, oddbookworm commented on docs/reST/ref/display.rst
> +
What about multi-monitor setups? Is that relative to the primary monitor? Relative to the top left corner of the leftmost monitor?

2024-04-23 06:09 UTC, Damus666 commented on src_c/display.c
> +    if (!PyArg_ParseTuple(arg, "i|i", &x, &y))
I copied the parse tuple from set_caption, without realizing in there the second argument was optional!

2024-04-23 06:11 UTC, Damus666 commented on docs/reST/ref/display.rst
> +
I already noticed a way to improve the docs, and the position for me is relative to my only monitor, how can I test it with multiple monitors if I don't have them?

2024-04-24 10:50 UTC, Damus666 commented
Would re-running checks magically fix the Pypy exception (which was not raised by code edited by me)? I remember that happening with another pull request of mine. (how would I do that?)

2024-04-26 02:53 UTC, oddbookworm commented
> Would re-running checks magically fix the Pypy exception (which was not raised by code edited by me)? I remember that happening with another pull request of mine. (how would I do that?)

Potentially, a rerun would have worked. Sometimes the fails are intermittent and unrelated to the changes. A member can rerun (most) failed checks (I haven't figured out how to rerun circleci yet). You can force rerun all CI by closing and reopening the PR, but I don't like doing that if I don't have to

2024-04-26 15:02 UTC, oddbookworm commented on docs/reST/ref/display.rst
> +
I'll test it for you

2024-04-26 15:07 UTC, Damus666 commented on docs/reST/ref/display.rst
> +
Thank you very much :)

2024-04-26 15:29 UTC, oddbookworm commented on docs/reST/ref/display.rst
> +
On windows 11, looks like it's relative to the primary monitor's top-left corner. On my setup, that's my middle monitor, and moving the window to my left monitor gives me `(-1512, 397)`. There's some weirdness when the window crosses monitor boundaries (at least for me, where I have mismatched resolutions and framerates between monitors), but it seems to be working fine otherwise

2024-04-26 16:25 UTC, Damus666 commented on docs/reST/ref/display.rst
> +
Okay, thank you!

2024-04-27 13:12 UTC, oddbookworm requested changes

2024-04-27 13:12 UTC, oddbookworm commented on docs/reST/ref/display.rst
> +   The position is relative to the topleft of the monitor the window is contained in and the y coordinate ignores the window frame.
Primary monitor*

2024-04-27 13:17 UTC, Damus666 commented on docs/reST/ref/display.rst
> +   The position is relative to the topleft of the monitor the window is contained in and the y coordinate ignores the window frame.
I just pushed a commit about that, those docs were created before your tests :)

2024-04-27 13:20 UTC, oddbookworm approved these changes
LGTM! Tested locally on windows 11, and it works.

2024-05-12 13:33 UTC, ankith26 reviewed
I'm not strongly in favour or strongly against this PR, but I have left a few reviews for your consideration.

2024-05-12 13:33 UTC, ankith26 commented on buildconfig/stubs/pygame/display.pyi
> +def set_window_pos(pos: Sequence[int]) -> None:...
```suggestion
def set_window_pos(pos: Coordinate) -> None:...
```
typing it as a `Coordinate` is more generic and accurate

2024-05-12 13:33 UTC, ankith26 commented on docs/reST/ref/display.rst
> +   The user will still be able to move the window after this call. See also :func:`pygame.display.get_window_pos()`.
I'd like to have it noted here that there is a chance that this function can just fail on some platforms/configurations (example: direct wayland on linux)
So we shouldn't encourage users to rely on this function.

2024-05-12 13:33 UTC, ankith26 commented on src_c/display.c
> +        SDL_SetWindowPosition(win, x, y);
I think we should just put a comment here for now saying that this function will start raising errors, and deal with it during the porting

2024-05-12 13:48 UTC, Damus666 commented
@ankith26 I know it makes no sense, but I could be against my pull request. I made it because I knew the display API was gonna stay and I didn't understand why it was missing those functions. But then we started talking quite a lot about the window module.

From what I understood, the window API will be THE way of making the window. The display module will *only* contain monitor/screen related functions, meaning that `set_mode`, `get_window_size`, `get_surface` (I might be missing something) will be deprecated and only available with the Window object.
Feel free to correct me if what I understood is not planned, but *if* it was, having `get/set_window_pos` added and then *immediately* deprecated doesn't feel like a good move.

I use this comment as an occasion to ask you what's the future of the display/window API. If display will always remain as an option to create a singleton window, then I'm strongly in favor of my pull request (who would have guessed) but otherwise, then we should finish the window API and deprecate display functions related to the window.

NOTE: I'm still gonna modify it like you suggested as it makes a lot of sense, but I think this are important considerations.

2024-05-12 13:52 UTC, ankith26 commented
> I use this comment as an occasion to ask you what's the future of the display/window API. If display will always remain as an option to create a singleton window, then I'm strongly in favor of my pull request (who would have guessed) but otherwise, then we should finish the window API and deprecate display functions related to the window.

The display module will probably never be removed. Almost all pygame code written relies on it. What we will most likely do once the window API is finalized and published, is recommend users to write any new code in it. The old code that uses display will continue to work.

2024-05-12 13:58 UTC, Damus666 commented
> The display module will probably never be removed. Almost all pygame code written relies on it. What we will most likely do once the window API is finalized and published, is recommend users to write any new code in it. The old code that uses display will continue to work.

Thanks for the information.

2024-05-12 14:12 UTC, Damus666 commented on docs/reST/ref/display.rst
> +   The user will still be able to move the window after this call. See also :func:`pygame.display.get_window_pos()`.
I saw that the similar functions in window.c call the same SDL functions, doesn't that mean that they could also fail on those platforms/configurations?

2024-05-18 02:09 UTC, novialriptide commented on buildconfig/stubs/pygame/display.pyi
> +def get_window_pos() -> Tuple[int, int]:...
Why `window_pos` instead `window_position`?

2024-05-18 05:09 UTC, Damus666 commented on buildconfig/stubs/pygame/display.pyi
> +def get_window_pos() -> Tuple[int, int]:...
When I wrote it I gave it that name because it was shorter but Window has the position attribute and not pos so it makes sense to have position. I'll edit this when I'm back in Italy in 14 hours

2024-05-19 00:20 UTC, novialriptide commented on src_c/display.c
> +            return RAISE(PyExc_TypeError, "pos must be two numbers");
Please change this as well.

2024-05-19 06:54 UTC, Damus666 commented on src_c/display.c
> +            return RAISE(PyExc_TypeError, "pos must be two numbers");
My bad I didn't see it thanks

2024-05-20 19:11 UTC, oddbookworm approved these changes
Still looks good

2024-05-24 15:29 UTC, MyreMylar approved these changes
OK, I don't mind this going in. 

It doesn't really create more work for the eventual plan of  Window supplanting display because Window already supports this functionality. I guess it slightly takes a little shine of Window for having features that display doesn't. But eh, that's not a great reason not to do it at the minute.

If display eventually becomes a python shim around the new Window module then this will only add a tiny bit more code to that shim.

2024-05-25 18:37 UTC, merged