Outlineee
pygame-community/pygame-ce pull request #2828
Opened 2024-04-26 21:11 UTC by narilee2006

Hello! I tried doing https://github.com/pygame-community/pygame-ce/issues/2452. Let me know if there are any issues.

2024-04-27 04:43 UTC, oddbookworm requested changes

2024-04-27 04:43 UTC, oddbookworm commented on src_c/font.c
> +    val = PyLong_AsLong(value);
One note is that [`PyLong_AsLong`](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong) returns `-1` on failure, so you should probably do what those docs say and check if an error occurred, and return -1 if one did. Something like this should work. Note that no additional exception needs to be set because it's already set by PyLong_AsLong
```c
if ((val == -1) && (PyErr_Occurred() != NULL))
{
    return -1;
}
```

2024-04-27 04:43 UTC, oddbookworm commented on buildconfig/stubs/pygame/font.pyi
> +    def outline(self) -> int: ...
You also need to stub the setter
```python3
@outline.setter
def outline(self, value: int) -> None: ...
````

2024-04-27 04:43 UTC, oddbookworm commented on src_c/font.c
> +    return PyLong_FromLong(TTF_GetFontOutline(PyFont_AsFont(self)));
I don't really like this chain like this, but I don't think it's technically wrong. Neither inner function call returns something specific on failure to check, so I guess it's fine

2024-04-27 04:43 UTC, oddbookworm commented on test/font_test.py
> +                skip_properties.add("outline")
Don't do it like this lol. Add it back as a property in the list, but only for the shorter list. It won't work for ftfont because ftfont inherits from _freetype.Font, not font.Font

2024-04-27 04:49 UTC, oddbookworm commented on test/font_test.py
> +                skip_properties.add("outline")
The reason you don't need to do it like this IMO is that we support TTF 2.20.0 or something like that, well past 2.0.12

2024-04-27 12:07 UTC, oddbookworm reviewed
I have just a couple comments

2024-04-27 12:07 UTC, oddbookworm commented on test/font_test.py
> +        outline=False,
Isn't outline an int, not a bool?

2024-04-27 12:07 UTC, oddbookworm commented on test/font_test.py
> +                ("outline", 2006),
2006? That's both oddly specific and very high. Why not something reasonable, like 1 or 2?

2024-04-27 12:11 UTC, narilee2006 commented on test/font_test.py
> +                ("outline", 2006),
I tried sneaking in an easteregg of myself. It's the year I am born.

2024-04-27 13:01 UTC, oddbookworm approved these changes
LGTM!

2024-04-27 15:53 UTC, Starbuck5 requested changes
The challenge of #2452 is to design a good API for this, and this PR doesn’t accomplish that in my opinion.

- Outline color isn’t supported
- Looking at my notes from before (haven’t run this yet), doesn’t this PR mean that people have to call font.render twice? Once for the text, then once for the outline. That seems inconvenient for users.

2024-04-27 16:07 UTC, narilee2006 commented
> Outline color isn’t supported

It actually is, you need to call it in the font.render() method.

> Looking at my notes from before (haven’t run this yet), doesn’t this PR mean that people have to call font.render twice? Once for the text, then once for the outline. That seems inconvenient for users.

Yep, that's how SDL2 implemented it.

2024-04-27 16:19 UTC, narilee2006 commented
Perhaps `outline` as a kwarg so the developer doesn't need to use two lines to create the font?

2024-04-27 16:23 UTC, oddbookworm commented
Maybe perhaps
```
pygame.font.Font(filename=None, size=20, outline=0)
```
for the font constructor and
```
pygame.font.Font.render(text, antialias, color, bgcolor=None, wraplength=0, outline_color=None)
```
for the render call?

But I'm not sure what to do if `outline_color` defaults when `outline` was set to something nonzero

2024-04-27 16:27 UTC, Starbuck5 commented
> Perhaps outline as a kwarg so the developer doesn't need to use two lines to create the font?

Well then how do you do the color? Another kwarg? Kwargs are expensive to parse in functions that get called all the time, too.

I think my second proposal in the issue would work well (minus the render outline only thing, I think that’s unnecessary now)

‘’’
font.outline_width (attribute, get/set with TTF_ outline)
font.outline_color (attribute, defaults to black)

Render with an outline:
font.render
‘’’

2024-04-27 16:28 UTC, narilee2006 commented
I'm personally against the outline_color parameter as existing draw methods have the `width` parameter to determine their border size; if the `width` parameter is greater than 0 it won't fill the shape and only draw the borders.

https://pyga.me/docs/ref/draw.html

2024-04-27 16:50 UTC, narilee2006 commented
> Well then how do you do the color? Another kwarg? Kwargs are expensive to parse in functions that get called all the time, too.

@Starbuck5, sorry I meant the `outline` kwarg in the constructor of the Font object.

2024-04-28 13:48 UTC, MyreMylar commented
I agree with @Starbuck that this should be implemented as a styling attribute to Font - similar to the current styling attributes bold, italic & underline. The current `.render()` function is already overlong with parameters like the 'antialias' parameter that definitely should have been an attribute defaulting to the most common usage (true). 

Proposed test program:

```python
import pygame
from pygame import Color, Font, QUIT

pygame.init()
window_surf = pygame.display.set_mode((400, 200))

impact_font = Font(filename="fonts/impact.ttf", size=64)

impact_font.outline_width = 2  # defaults to 0
impact_font.outline_color = Color("red")  # defaults to black

text_with_outline = impact_font.render(
    text="Hello World", antialias=True, color=Color("white")
)

running = True
while running:
    for event in pygame.event.get():
        if event.type == QUIT:
            running = False

    window_surf.fill(Color("black"))

    window_surf.blit(text_with_outline, (50, 50))

    pygame.display.update()


```

font.render can just check if outline_width is greater than 0 or not - and if so draw the outline before or after the main font rendering code - whichever looks better.

As an aside maybe we could make color and antialias into arguments with default values. We almost certainly would have already converted 'antialias' if it was on the other side of 'color' in the argument list. At least that way you could do:

```
font.render("Hello World", color=Color("white"))
```

Which isn't a typing saving over:

```
font.render("Hello World", True, Color("white"))
```

But probably clearer to read.

Might also open up:

```
font.default_color = Color("red")

hw_text_surf = font.render("Hello World in red")
other_text_surf = font.render("Other text, also in red")
```

2024-04-28 14:08 UTC, MyreMylar requested changes
I think 80% of the time when people use this they are going to want to draw an outline around actual visible text. 

A possible upgrade to `font.render()` that might be nice in concert with this is to allow it to set alpha pixels on the produced surface. I believe at the minute text surfaces come out  of render in a slightly odd format that looks like normal 32 bit 'ARGB' - but is subtly not that. You can see this by doing:
```
text_surf  = font.render("Hello World", True, Color("white"))
# text_surf = text_surf.convert_alpha()
text_surf = text_surf.premul_alpha() 

running = True
while running:
    for event in pygame.event.get():
        if event.type == QUIT:
            running = False

    window_surf.fill(Color("grey"))

    window_surf.blit(text_surf, (50, 50), special_flags=BLEND_PREMULTIPLIED)

    pygame.display.update()
```
and seeing the difference after uncommenting the `.convert_alpha()` line. I expect at some point it was marginally cheaper to blit whatever, not-quite-full-transparency format comes out of font.render() but I doubt it still is. Anyway, if we could render semi- and full transparency text then you would get the benefits of outline only text without having to change the API.

2024-04-28 14:50 UTC, narilee2006 commented
Okay... I'll get to work on this.

2024-05-04 06:20 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +   .. attribute:: outline_size
I'd rather do outline_width

2024-05-04 06:21 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      Returns the size of the outline.
But it doesn't just return it, it can be set here too. What units is the outline size/width in? What does setting an outline size/width do?

2024-05-04 06:22 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      Returns the color of the outline.
Ditto this doesn't just return it, it can be set here too. What does this default to?

Plus one of these attributes should have a small example of how to use this, with an image of what the output looks like.

2024-05-04 06:22 UTC, Starbuck5 commented on src_c/font.c
> +                "Invalid font (font module quit since font created)", r);
Why change this?

2024-05-04 06:23 UTC, Starbuck5 commented on src_c/font.c
> +    // 글꼴 생성
Comments should be in English

2024-05-04 06:25 UTC, Starbuck5 commented on src_c/font.c
> +            return 0;
Why do these changes exist?

2024-05-04 06:28 UTC, Starbuck5 commented on src_c/include/pygame_font.h
> +
The spaces around these two are jarring with the lack of space between the other ones.

2024-05-04 06:28 UTC, Starbuck5 commented on test/font_test.py
> +            self.f = pygame_font.Font(None, 96)
Why?

2024-05-04 06:36 UTC, Starbuck5 commented on src_c/font.c
> +                     int wraplength, SDL_Surface **dst_surf)
I'm skeptical of the division of effort between font_render and this function.

I haven't dived much into it yet, but it seems like it would be simpler to have more of the argument parsing and error checking in font_render. Like why does this function need to parse the C string out of the Pyobject, or check the wraplength.

In fact, if the text has an outline, this code has to parse the C string out of the PyObject twice because it calls this function twice, rather than extracting it in font_render and then passing it in.

Also, it would be nice from an organizational perspective to have the "Python API level function" that deals with Python, and then have this function be C-only. It's something I want to do more in our code.

2024-05-04 08:58 UTC, robertpfeiffer commented on src_c/font.c
> +                "Invalid font (font module quit since font created)", r);
Is this a clang-format version mismatch?

2024-05-04 09:16 UTC, robertpfeiffer requested changes

2024-05-04 09:16 UTC, robertpfeiffer commented on src_c/font.c
> +    SDL_Color backg = {0, 0, 0, SDL_ALPHA_OPAQUE};
should we warn here when outline colour is the same as background or foreground?

2024-05-04 09:16 UTC, robertpfeiffer commented on src_c/font.c
> +    if (!PyArg_ParseTupleAndKeywords(args, kwds, "OpO|Oi", kwlist, &text,
having foreground colour and background colour as params, but outline colour as a property feels inconsistent. I would like to request some feedback from the maintainers on this. Maybe we should fix this now, maybe we need to make an issue for this after merge.

2024-05-04 09:16 UTC, robertpfeiffer commented on src_c/font.c
> +    SDL_Color foreg = {rgba[0], rgba[1], rgba[2], SDL_ALPHA_OPAQUE};
I don't understand the API here, shouldn't the background be transparent by default? I know this matches the old behaviour, but this probably warrants a comment.

2024-05-04 09:16 UTC, robertpfeiffer commented on src_c/font.c
> +    if (outline_size > 0) {
Does the order of operations matter here? Would the drawn pixels look different if you rendered the outline first, and blitted the letters onto that (except surface size)

2024-05-04 09:17 UTC, robertpfeiffer commented
Overall, this is promising.

2024-05-04 09:17 UTC, narilee2006 commented on docs/reST/ref/font.rst
> +      Returns the color of the outline.
Example as in the examples directory? Or an example as an example image in the documentation?

2024-05-04 09:18 UTC, narilee2006 commented on src_c/font.c
> +                "Invalid font (font module quit since font created)", r);
During my time learning the code I accidentally deleted those ;s.

2024-05-04 09:20 UTC, narilee2006 commented on src_c/font.c
> +            return 0;
Return type is no longer a `PyObject *`.

2024-05-04 09:21 UTC, narilee2006 commented on src_c/include/pygame_font.h
> +
Could you explain further? I don't understand.

2024-05-04 09:21 UTC, narilee2006 commented on test/font_test.py
> +            self.f = pygame_font.Font(None, 96)
It's hard to see the outline when the font is small.

2024-05-04 09:22 UTC, narilee2006 commented on docs/reST/ref/font.rst
> +      | :sg:`outline_size -> int`
Nope, it defaults to 0. I'll add this to the docs.

2024-05-04 09:23 UTC, narilee2006 commented on src_c/font.c
> +    if (outline_size > 0) {
Yes, the order matters as the size of the outline will increase inward and outward of the text's outlines.

2024-05-04 09:25 UTC, narilee2006 commented on src_c/font.c
> +    SDL_Color foreg = {rgba[0], rgba[1], rgba[2], SDL_ALPHA_OPAQUE};
I learned from my professor that you cannot assign `NULL` to `typedef struct`s. Correct me if she's wrong.

2024-05-04 09:29 UTC, narilee2006 commented on src_c/font.c
> +                     int wraplength, SDL_Surface **dst_surf)
I'll eventually touch on this and refactor the code.

2024-05-04 09:32 UTC, narilee2006 commented on src_c/font.c
> +    SDL_Color backg = {0, 0, 0, SDL_ALPHA_OPAQUE};
I don't think that'll be necessary as printing content to the console is already a controversial topic.

https://github.com/pygame/pygame/issues/1468

2024-05-04 10:10 UTC, robertpfeiffer commented on src_c/font.c
> +    if (outline_size > 0) {
This should probably be a comment here then.

/* order of operations matters. \*/
/* blitting foreground over outline results in smaller outline than otherwise \*/

something like that

2024-05-04 10:10 UTC, robertpfeiffer commented on src_c/font.c
> +    SDL_Color foreg = {rgba[0], rgba[1], rgba[2], SDL_ALPHA_OPAQUE};
No, I meant I don't understand why the alpha isn't 0. It was like that before, but this part of the code is unclear to me.

2024-05-07 08:02 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      Returns the color of the outline.
Example as in a code block in the docs showing how it works, with a picture of the rendered output.

2024-05-07 08:04 UTC, Starbuck5 commented on src_c/font.c
> +            return 0;
RAISE doesn't return a PyObject, it returns NULL. And NULL is 0, so this is the same code?

2024-05-07 08:05 UTC, Starbuck5 commented on src_c/include/pygame_font.h
> +
```
PyObject *weakreflist;
int ptsize;
*SPACE*
SDL_Color outline_color;
int outline_size;
*SPACE*
unsigned int ttf_init_generation;
```
There aren't any other spaces in the struct definition.

2024-05-07 08:25 UTC, Starbuck5 commented on docs/reST/ref/font.rst
> +      Gets or sets the size of the outline in pixels defaulting to 0.
I tested this with Arial, and I saw that it actually added 2 pixels of outline with width=1, and 4 pixels of outline with width=2.

`Gets or sets the size of the outline in pixels defaulting to 0.`
Size still?
Grammatically it should be `Gets or sets the size of the outline in pixels, defaulting to 0.`

You could also mention details like it has to be a positive number or zero, zero means no outline.

2024-05-07 08:27 UTC, Starbuck5 commented on src_c/font.c
> +font_setter_outline_width(PyFontObject *self, PyObject *value, void *closure)
When I try to set a float it gives me this:

```
C:\Users\charl\Desktop\testr.py:8: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  arial.outline_width = 1.5
```

2024-05-14 09:14 UTC, narilee2006 commented on src_c/font.c
> +    SDL_Color foreg = {rgba[0], rgba[1], rgba[2], SDL_ALPHA_OPAQUE};
It was originally `SDL_ALPHA_OPAQUE` before. https://github.com/pygame-community/pygame-ce/pull/2828/files#diff-75538c02a9bfe6511e8b72324ec5736b4d22aae6c5a99c52a83cef0dc70df300L575

2024-05-14 09:42 UTC, narilee2006 commented on src_c/font.c
> +font_setter_outline_width(PyFontObject *self, PyObject *value, void *closure)
This does not happen on my machine.
```
======================================================================
ERROR: test_set_outline_width_as_float (__main__.FontTypeTest.test_set_outline_width_as_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nari/Documents/pygame-ce/test/font_test.py", line 392, in test_set_outline_width_as_float
    f.outline_width = 20.06
    ^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

----------------------------------------------------------------------
Ran 72 tests in 13.958s
```

2024-05-14 09:44 UTC, narilee2006 commented on docs/reST/ref/font.rst
> +      Gets or sets the size of the outline in pixels defaulting to 0.
> I tested this with Arial, and I saw that it actually added 2 pixels of outline with width=1, and 4 pixels of outline with width=2.

The unit is actually radius, not pixels.

2024-05-18 01:52 UTC, novialriptide commented on docs/reST/ref/font.rst
> +   .. attribute:: outline_width
`outline_radius` is a better name if you're already going to mention radius in the docs description.

2024-05-18 01:52 UTC, novialriptide commented on docs/reST/ref/font.rst
> +      | :sg:`outline_width -> RGB`
You say (0, 0, 0, 255), but that's RGBA.

2024-05-18 01:52 UTC, novialriptide commented on src_c/font.c
> +    return PyLong_FromLong(TTF_GetFontOutline(PyFont_AsFont(self)));
Resolving as this code no longer exists.

2026-08-30 20:37 UTC, damusss commented
I'm taking the liberty to close this pull request as a different approach has already been merged and published. Still grateful it has been worked on though!

2026-08-30 20:37 UTC, closed without merging