fix typos
pygame-community/pygame-ce pull request #2847
Opened 2024-05-12 01:51 UTC by RainRat

fix typos

2024-05-12 02:00 UTC, oddbookworm approved these changes
Thanks! This looks great. I'm not going to miss `fronzensets` lol

2024-05-12 02:01 UTC, oddbookworm commented
Oh yeah, you should make sure to run `python setup format` to get the lint check passing. You can install pre-commit to catch any outstanding linter errors before your commit happens
I'll go update the contributing wiki now...

2024-05-12 21:21 UTC, gresm commented on docs/reST/c_api/color.rst
> +   Return a new :py:class:`pygame.Color` instance for the four element array *rgba*.
```suggestion
   Returns a new :py:class:`pygame.Color` instance from the four element array *rgba*.
```

2024-05-12 21:23 UTC, gresm commented on docs/reST/c_api/color.rst
> +   Return a new :py:class:`pygame.Color` instance for the four element array *rgba*.
Otherwise looks good to me.

2024-05-13 23:56 UTC, oddbookworm requested changes
The circleCI fail from the most recent run isn't your fault, it's a freetype download issue that's been intermittently cropping up. But, the lint fail needs to be addressed before this can be merged

2024-05-13 23:56 UTC, oddbookworm commented on src_c/mask.c
> +        /* last pixel of the row, if it's not also the first pixel of the row */
Lint is complaining about this line being ever so slightly too long. Run `python setup format` to update the formatting. You'll need clang-format and ruff installed

2024-05-14 18:40 UTC, ankith26 commented on src_c/mask.c
> +        /* last pixel of the row, if it's not also the first pixel of the row */
`setup.py` has been removed. What you need to run now is `pre-commit run -a`. You don't need clang-format and ruff installed manually, it is handled automatically for you

2024-05-18 11:40 UTC, ankith26 approved these changes
LGTM, thanks for contributing! :tada:

2024-05-18 11:40 UTC, ankith26 commented
PS: ignore the new failing test, it is unrelated to your PR

2024-05-18 12:28 UTC, oddbookworm approved these changes
LGTM!

2024-05-18 12:30 UTC, merged