Remove artifacts on pygame.Surface.scroll and add repeat argument
pygame-community/pygame-ce pull request #2855
Opened 2024-05-14 22:16 UTC by Damus666

The shifting was incorrect, not setting the space created by the shifted pixels to black. Now it does that, but most importantly I think I implemented this feature idea: https://github.com/pygame-community/pygame-ce/issues/2159 implementing a way to allow for repeated shifting. The video proof is here: https://discord.com/channels/772505616680878080/772940667231928360/1240055647584911443

I would love feedback about the C code as I did quite a lot of pointer operations.
Why?
- The fix to the shifting was necessary and the repeat functionality gives to this function some reason to exist
- It's cool

Question: how can I add a test for it?

You can use the following code with my request to test locally:

```python
import pygame
pygame.init()
win = pygame.Window(size=(700, 700))
win.get_surface()
clock = pygame.Clock()

surf = pygame.image.load("B:/py/contributing/test.png").convert_alpha() # your image
surf = surf.subsurface(surf.get_bounding_rect())

main = pygame.Surface((600, 600))
main.blit(surf, surf.get_rect(center = (main.get_width()/2, main.get_height()/2)))
#main.set_clip(pygame.Rect(50, 50, 400, 400))

REPEAT = True
SPEED = 4

while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
            exit()
            
    win.get_surface().fill("black")
    screen = win.get_surface()    
    
    keys = pygame.key.get_pressed()
    dir = [0, 0]
    if keys[pygame.K_LEFT]:
        dir[0] -= SPEED
    if keys[pygame.K_RIGHT]:
        dir[0] += SPEED
    if keys[pygame.K_UP]:
        dir[1] -= SPEED
    if keys[pygame.K_DOWN]:
        dir[1] += SPEED
    main.scroll(dir[0], dir[1])
    
    screen.blit(main, main.get_rect(center=(win.size[0]/2, win.size[1]/2)))
    
    win.flip()
    dt = clock.tick(60)/1000
    win.title = str(clock.get_fps())
    
```

2024-05-19 10:42 UTC, Damus666 commented
Could the 2 faulty tests be rerun?

2024-05-25 17:34 UTC, MyreMylar commented
> The shifting was incorrect, not setting the space created by the shifted pixels to black.

Why do you think this is incorrect? The docs currently say:

> Move the image by dx pixels right and dy pixels down. dx and dy may be negative for left and up scrolls respectively. **Areas of the surface that are not overwritten retain their original pixel values.**

Which looks to me like what the current behaviour is.

e.g.

Current main branch scroll a 200pixel wide surface right by 100 pixels:

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/a4ba455e-8a4b-480b-9b62-095e5c0abfcd)


After this PR:

![image](https://github.com/pygame-community/pygame-ce/assets/13382426/566a7a99-6d65-4798-affc-e13efa9d48ad)

I think we should retain the current behaviour as the default, and if we want the original pixels not overwritten by scrolled pixels cleared to a colour (and why specifically black?) that should be an option/parameter. Otherwise we will probably accidentally break somebody's code.

----

As an addendum - do we think this function is likely to be a performance sensitive one like blit, or one used less frequently? I'm wondering whether it should support keyword arguments or not, now it has 3 params (possibly 4 after the above).

2024-05-25 17:37 UTC, MyreMylar requested changes
See comment above.

2024-05-25 17:48 UTC, Damus666 commented
@MyreMylar yeah that was a misunderstanding on my side. I don't think 4 arguments are too much. If they are, what do you suggest? Another function for repeat? only positional?

2024-06-07 16:01 UTC, bilhox commented
Looking at how you implemented it, I believe the best option would be to use the same system used for flags on surfaces and window. Like that we can a fair amount of arguments for this function.

2024-06-07 16:06 UTC, Damus666 commented
> Looking at how you implemented it, I believe the best option would be to use the same system used for flags on surfaces and window. Like that we can a fair amount of arguments for this function.

That would require 2 new constants pygame.SCROLL_REPEAT and pygame.SCROLL_ERASE i believe. the new arguments would go from 2 to 1, i guess

2024-06-07 16:08 UTC, bilhox commented
> > Looking at how you implemented it, I believe the best option would be to use the same system used for flags on surfaces and window. Like that we can a fair amount of arguments for this function.
> 
> That would require 2 new constants pygame.SCROLL_REPEAT and pygame.SCROLL_ERASE i believe. the new arguments would go from 2 to 1, i guess

I prefer this approach.

2024-06-21 12:32 UTC, bilhox commented
I think there were separate functions for the actual process of scrolling and the function definition, what about doing this to keep some kind of readability ?

2024-06-21 12:38 UTC, damusss commented on src_c/surface.c
> +    }
It's not necessary. When dx or dy are >= w or h, and there is no repeat, that function returns early, so that code is never reached.

2024-06-22 21:28 UTC, bilhox commented
Code example so you understand how it simplifies the life a lot : https://gist.github.com/bilhox/ce024b994e536338a750a760024b5939

2024-10-05 18:11 UTC, MyreMylar approved these changes

2024-10-05 18:12 UTC, MyreMylar commented on docs/reST/ref/surface.rst
> +      .. versionchanged:: 2.5.1 Add repeating scroll and allow erasing pixels
```suggestion
      .. versionchanged:: 2.5.2 Add repeating scroll and allow erasing pixels
```

2024-10-05 18:15 UTC, MyreMylar commented
All looks good to me now, the three modes work as I expect and add some nice functionality to this function which I expect is not often used in it's current form.

Perhaps it will see a resurgence? 👍

2024-10-17 11:28 UTC, bilhox requested changes
except what I mentionned, nice, it works correctly now !

2024-10-17 11:28 UTC, bilhox commented on src_c/surface.c
> +scroll(SDL_Surface *surf, int dx, int dy, int x, int y, int w, int h,
I had loved if there was two distinct function ``scroll_repeat`` and ``scroll_erase``. I believe it's much more understandable than all in a single function. If you're not convinced, check ``pg_set_mode`` code 💀 .

2024-10-17 17:46 UTC, damusss commented on src_c/surface.c
> +scroll(SDL_Surface *surf, int dx, int dy, int x, int y, int w, int h,
UH I'll try

2024-10-17 18:11 UTC, damusss commented on docs/reST/ref/surface.rst
> +      The scroll flag can be ``0`` (normal behavior) or:
You really don't need to request changes when some requested changes are already in action you know that right 😭 

does this satisfy you?

2024-10-17 18:14 UTC, bilhox approved these changes
LGTM !

2024-10-17 18:15 UTC, damusss commented
btw I really suggest squash and merge, 32 commits are not worth this change!!

2024-10-17 18:55 UTC, bilhox commented
except myremylar, we're only 2 who contributed to this PR, so I'm waiting tomorrow before merging it.

2024-10-18 09:50 UTC, merged