Add SSE2, AVX2 & NEON support to `pygame.print_debug_info()`
pygame-community/pygame-ce pull request #2897
Opened 2024-06-01 13:18 UTC by MyreMylar

These are the most common instruction sets we support paths for and could assist us in detecting bugs. There are more instruction sets listed in `system.get_cpu_instuction_sets()` but currently we don't make much use of them in pygame-ce.

Suggested by @Starbuck5

2024-06-01 13:21 UTC, Damus666 approved these changes
Great idea, will help detect bugs like the recent segfaults more easily

2024-06-01 15:27 UTC, oddbookworm approved these changes
LGTM!

2024-06-01 19:01 UTC, Starbuck5 approved these changes
Thanks!

2024-06-01 19:08 UTC, Starbuck5 requested changes
Ankith wanted to review this so slapping down a request changes to hold it until he can take a look.

2024-06-05 17:34 UTC, ankith26 requested changes
I don't have a problem with this PR per se, but my opinion is that we should probably have a centralized way to get and set the SIMD level at runtime.

Everytime someone has to test a lower SIMD level they have to mess with either the buildconfig or the source code itself, and this is not ideal. Especially if we want a user to test out something.

One approach is to have env variables `PG_ENABLE_[AVX2|SSE2|NEON]` that can be configured before pygame init. On init, these variables are read, and along with runtime detection, we set the corresponding runtime check values.

Another approach is to have some API, probably in `pygame.system`, to pythonically get/set this

2024-06-07 06:30 UTC, Starbuck5 commented
> I don't have a problem with this PR per se, but my opinion is that we should probably have a centralized way to get and set the SIMD level at runtime.

You should open an issue about that. It shouldn't block this PR.

We will get this for free when SDL3 comes out, btw. SDL_HINT_CPU_FEATURE_MASK.

2024-06-07 07:10 UTC, ankith26 approved these changes
True, I'm opening a separate issue for it, as it is independent of this PR.

Thanks for the PR :tada:

2024-06-08 01:47 UTC, merged