Contribution Section Added to README.rst
pygame-community/pygame-ce pull request #2910
Opened 2024-06-05 17:20 UTC by MrF1ow

### Why Change was Made
As previously stated, sifting through all the project docs to figure out how to contribute was a bit of a maze. It took some digging and hopping between wiki pages to find what I needed. After some good discussion, it was clear that the addition of another file such as `Contribution.md` would be unnecessary and not for the pygame GitHub. However, even though the addition of a whole other file was not the right call, the need for a place that will guide new and existing contributors to the documentation in the wiki pages related to contributing was still there. 

### Why pygame CE should accept changes
If pygame CE accepts these changes, I know that it will speed-up the onboarding process for contributors, making it more inviting for new folks to jump in and for seasoned contributors to navigate with ease. Additionally, it will lessen the amount of questions people have about how to get started or where to find essential information. It is a win-win all around!

### What I did
A small "How to Contribute" section was added to the `README.rst`. It provides a short and concise summary of where to find the documentation in the wiki pages about contributing to pygame-ce. 

This pull request addresses the following:

- Changes requested in PR #2892 
- Issue #2883

2024-06-08 01:26 UTC, oddbookworm requested changes
Overall, this looks like a good addition IMO. I'm in favor of it, but I do have one gripe that I would like to see corrected before I approve. Great job! 👏

2024-06-08 01:26 UTC, oddbookworm commented on README.rst
> +If you have any questions, please feel free to ask in the `pygame Discord server`_ or open an issue.
This is nitpicky, but as we are *technically* a hostile fork of upstream pygame, I think it would be better to use the more official name of the Discord server : the Pygame Community Discord server. Pygame Community is an organization completely unrelated from upstream pygame itself (and pygame-ce isn't actually run by the Pygame Community org, but is supported by it), and I don't want any inadvertent implications that could lead to trouble in the future, either for us or the Discord server

2024-06-09 23:32 UTC, MrF1ow commented on README.rst
> +If you have any questions, please feel free to ask in the `pygame Discord server`_ or open an issue.
I changed it, let me know if there is anything else you would like changed

2024-06-10 19:20 UTC, MyreMylar approved these changes
OK, LGTM 👍 

Thanks for bearing with all the feedback!

2024-06-14 15:46 UTC, ankith26 approved these changes
LGTM, thanks for contributing! :tada: 

There are README rewrite ideas floating around, but I don't think that should stop this PR from getting merged for now. It's a good addition that the README mentions the wiki now, and the rewrite should keep that aspect in.

2024-06-14 15:47 UTC, merged