Fix aalines overlap
pygame-community/pygame-ce pull request #2912
Opened 2024-06-06 00:53 UTC by mzivic7

As seen on the picture bellow, there is a problem with draw.aalines.
![bad](https://github.com/pygame-community/pygame-ce/assets/92328096/6b32de08-7ea9-4b13-b40b-985a452d211c)
This is happening because draw.aalines require each aaline to be drawn 1px shorter (in some cases 2px - see bellow), so two connected draw_aaline are not overlapping.

<details>
  <summary>What is changed and how it works:</summary>

draw_aaline has 2 endpoints that needs to be disabled for draw.aalines only:
First endpoint is disabled when it is first line when aalines is open.
And when `from_x` value is not decimal (if it is, then line is 2px shorter).
Second endpoint is disabled when it is last line when aalines is open.
 
As a result of disabling first endpoint, now there is special case where 1px is missing between two lines, where one is steep and other line is not.
This is detected in draw.aalines.
And resolved in draw_aaline by drawing one px at place where end point should be.
At what end point will be drawn pixel: first point when line is not inverted, second point when line is inverted.
</details>

Here are some results (might need to zoom to see the difference better):
![results](https://github.com/pygame-community/pygame-ce/assets/92328096/4d1d1c21-31c7-4fea-b45c-15f531e1d779)
Top line is modified.
Middle line is original.
Bottom line is difference.
<details>
  <summary>Code used to draw this:</summary>

  ```py
  import pygame
  import numpy as np

  def curve_points(a, b, pea, t):
      sin_p = np.sin(pea)
      cos_p = np.cos(pea)
      x = a * np.cos(t)
      y = b * np.sin(t)
      x_rot = x * cos_p - y * sin_p
      y_rot = y * cos_p + x * sin_p
      return np.stack((x_rot, y_rot), axis=1)

  points1 = [[200.1, 300],
             [220.1, 300.1],
             [240.1, 300.2],
             [260.1, 300.4],
             [280.1, 300.6],
             [300.1, 300.8]]

  points2 = [[400.7, 300.1],
             [420.3, 300.5],
             [440.6, 305.1],
             [460.4, 315.2],
             [480.2, 330.5],
             [500.1, 360.7],
             [550.4, 360.5],
             [550.8, 400.2]]

  points_num = 150
  t = np.linspace(-np.pi, np.pi, points_num)
  points3 = curve_points(250, 150, 0.3, t) + np.array([350, 350])

  pygame.init()
  screen = pygame.display.set_mode((700, 700))
  clock = pygame.time.Clock()

  run = True
  while run:
      for event in pygame.event.get():
          if event.type == pygame.QUIT:
              run = False
      screen.fill("black")
      pygame.draw.aalines(screen, (150, 150, 150), False, points1)
      pygame.draw.aalines(screen, (150, 150, 150), False, points2)
      pygame.draw.aalines(screen, (150, 150, 150), False, points3)
      pygame.display.flip()
      clock.tick(60)
  pygame.quit()
  ```
Results were merged for comparison in gimp.
</details>

2024-06-08 01:30 UTC, oddbookworm commented on src_c/draw.c
> +                    x = (int)y_endpoint - 1;
Here and on other lines around here, I'm kinda sketched out by the cast from float to int. I get that it's pre-existing, but it's screaming at me that the range a float can represent is just so much larger than what an int can represent. Personally, I'd like to see some range checking to ensure that the cast won't cause us to overflow/underflow the bounds of int.

2024-06-08 01:32 UTC, oddbookworm requested changes
I know this is asking for something that won't be fun, but I'd like to see some regression test(s) put in place that demonstrate this change, and will flag if the change gets broken by a future commit

2024-06-09 13:15 UTC, mzivic7 commented on src_c/draw.c
> +                    x = (int)y_endpoint - 1;
y_endpoint is calculated as `from_y + something_small` (something_small < 1)
Take a look after line [1385](https://github.com/mzivic7/pygame-ce/blob/fix_aalines_overlap/src_c/draw.c#L1385), it is culling and cutting lines not on surface, `from_y` and `to_y` are there.
Now, if I try to create surface larger than int size, I get `Invalid resolution for Surface`.
And if I try to create: `pygame.Surface((2147483647, 2147483647))`, I get `pygame.error: Out of memory`.
I don't know what memory is actually needed, but surely nobody will ever need that huge surface, and operate with it in reasonable time.

2024-06-20 00:59 UTC, oddbookworm approved these changes
One small nitpick (that applies to both tests), but otherwise this looks good to me!

2024-06-20 00:59 UTC, oddbookworm commented on test/draw_test.py
> +        See: #2912
nitpick, but I'd rather see a full url here instead of just a reference number, that way it's easier just to ctrl-click from an IDE or other rich text environment

2024-06-20 01:53 UTC, mzivic7 commented on test/draw_test.py
> +        See: #2912
Oh, I saw some other tests have reference numbers, so I used it too.

2024-07-14 23:47 UTC, oddbookworm approved these changes
This still looks good to me

2024-09-14 12:01 UTC, bilhox commented
So I tried to understand how the algorithm works, but even after a lot of doliprane, I couldn't understand the algorithm because of lack of graphical explanations. I believe it would be better if @mzivic7 or anyone who understood the algorithm, make a video that explains step by step the algorithm for the sake of others mental health. Like that we can push this PR faster to its merge.

2024-10-03 20:08 UTC, MyreMylar approved these changes
OK, LGTM 👍 

Output looks a lot better (Once I zoomed in, my old eyes couldn't see shit at normal resolution) and the changes make sense to me to reduce the overlapping in the original algorithm.

2024-10-03 20:08 UTC, merged