Update OpenGL Viewport when Window resizes
pygame-community/pygame-ce pull request #2915
Opened 2024-06-07 21:09 UTC by Damus666

Fixes https://github.com/pygame-community/pygame-ce/issues/2877
The documentation has been updated by MyreMylar already.

As stated in the issue, the newly functional OpenGL `Window`s, unlike the display windows, would not resize the OpenGL viewport causing bugs and inconsistencies.

With the addition of a function, used both in the event watch and in the `set_size` function, the OpenGl viewport is now correctly updated. I tested locally, it works for fullscreen/maximization/autoresize/manualresize.

If it works for you too (should, it's identical to the display's one), I think this should be added not later than 2.5.1

2024-06-07 23:33 UTC, oddbookworm commented on src_c/window.c
> +        (GL_glViewport_Func)SDL_GL_GetProcAddress("glViewport");
I'm not a fan of making this a local on the stack every time this function gets called. Can this either be made static or otherwise moved out of here?

2024-06-07 23:45 UTC, oddbookworm requested changes

2024-06-07 23:45 UTC, oddbookworm commented on src_c/window.c
> +        (GL_glViewport_Func)SDL_GL_GetProcAddress("glViewport");
In the [docs](https://wiki.libsdl.org/SDL2/SDL_GL_GetProcAddress), this function ***can*** return `NULL`, so please check for that before trying to call the resulting function to be defensive and not cause segfaults on some weird system with a potentially bugged driver

2024-06-07 23:45 UTC, oddbookworm commented on src_c/window.c
> +    if (self->context) {
On line 246, you compare to `NULL`, but not here. Personally, I prefer the explicit comparison, but I don't care which way you go. I would like to see it be consistent though

2024-06-07 23:45 UTC, oddbookworm commented on src_c/window.c
> +    SDL_GL_MakeCurrent(window, context);
I suggest checking the return here and getting the error from SDL when this function fails, and throwing an exception (`pygame.error` probably)

[docs](https://wiki.libsdl.org/SDL2/SDL_GL_MakeCurrent)

2024-06-07 23:53 UTC, oddbookworm commented
I suspect the circleCI failure is unrelated to your changes, looks like it's unable to download the SDL2 dependency. I'm going to wait a while before rerunning it

2024-06-08 08:07 UTC, Starbuck5 commented on src_c/window.c
> +        (GL_glViewport_Func)SDL_GL_GetProcAddress("glViewport");
Static references to things are sort of discouraged now that the Python ecosystem is trying to move towards free threading.

2024-06-08 08:11 UTC, Damus666 commented
@oddbookworm Alright, I managed to make `glViewport` static and I added exceptions to my new function. To note that the window is still resized even if there are problems with opengl, so you could do something like
![image](https://github.com/pygame-community/pygame-ce/assets/97639432/7a9892f4-d0d0-444f-9420-68c798362362)
On the event watch, I cleared the errors as I don't know how to stop the python execution with an exception from there. It also seems that another check (for the surface) is returning early without an exception aswell, so I followed the same trend.
Tell me what you think :)

2024-06-08 08:15 UTC, Damus666 commented on src_c/window.c
> +        (GL_glViewport_Func)SDL_GL_GetProcAddress("glViewport");
> Static references to things are sort of discouraged now that the Python ecosystem is trying to move towards free threading.

So should I revert that specific change and get the `glViewport` within the function?

2024-06-08 12:51 UTC, oddbookworm requested changes

2024-06-08 12:51 UTC, oddbookworm commented on src_c/window.c
> +            PyErr_Clear();
All you'll do here is clear the error you set inside the function, which isn't what you want to do, I'll look into this in a little while to see how it could be handled better

2024-06-08 12:53 UTC, Damus666 commented on src_c/window.c
> +            PyErr_Clear();
> All you'll do here is clear the error you set inside the function, which isn't what you want to do, I'll look into this in a little while to see how it could be handled better

As I said in the latest comment, I don't know how to hook up some sort of exception inside a function which is called by SDL. I've handled the exception correctly on the `set_size` function as that's called by CPython.

2024-06-08 16:52 UTC, oddbookworm commented on src_c/window.c
> +            PyErr_Clear();
I think the best we can do here is issue a warning. Ideally, it'll never get to do that and an actual exception will be raised, but at least there will be something in the event that doesn't happen. So I'm suggesting replacing `PyErr_Clear()` here with
```
return PyErr_WarnEx(PyExc_RuntimeWarning, "Failed to set opengl viewport", 0);
```
I chose runtime warning because it made the most sense to me of the builtin warnings, but if you can justify something else, I'm fine with that too

2024-06-20 00:55 UTC, oddbookworm approved these changes
LGTM!

2024-07-25 16:16 UTC, MyreMylar commented
Hi,

What test code are you using for this? When I try it with a resizable Window using the code from the last PR the context doesn't appear to resize and I get some refcount errors popping up. Here is the original PR code:

<details>
<summary>Open GL triangle code</summary>

```python
import pygame
import zengl

window_size = (1280, 720)

pygame.init()

window = pygame.Window(size=window_size, opengl=True)
window.resizable = True

ctx = zengl.context()

image = ctx.image(window_size, "rgba8unorm", samples=4)

pipeline = ctx.pipeline(
    vertex_shader="""
        #version 330 core

        out vec3 v_color;

        vec2 vertices[3] = vec2[](
            vec2(0.0, 0.8),
            vec2(-0.6, -0.8),
            vec2(0.6, -0.8)
        );

        vec3 colors[3] = vec3[](
            vec3(1.0, 0.0, 0.0),
            vec3(0.0, 1.0, 0.0),
            vec3(0.0, 0.0, 1.0)
        );

        void main() {
            gl_Position = vec4(vertices[gl_VertexID], 0.0, 1.0);
            v_color = colors[gl_VertexID];
        }
    """,
    fragment_shader="""
        #version 330 core

        in vec3 v_color;

        layout (location = 0) out vec4 out_color;

        void main() {
            out_color = vec4(v_color, 1.0);
            out_color.rgb = pow(out_color.rgb, vec3(1.0 / 2.2));
        }
    """,
    framebuffer=[image],
    topology="triangles",
    vertex_count=3,
)

clock = pygame.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()

    ctx.new_frame()
    image.clear()
    pipeline.render()
    image.blit()
    ctx.end_frame()

    window.flip()
    clock.tick(60)
```

</details>

After resizing a few times and hitting the close button I have received this on more than one occasion:

```
Fatal Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension
Python runtime state: finalizing (tstate=0x00007ff9364f6960)

Current thread 0x0000e614 (most recent call first):
  Garbage-collecting
  <no Python frame>
```

After resizing the window smaller I sort of expected the triangle to resize to the size of the window:

![image](https://github.com/user-attachments/assets/23519354-af86-4a1a-bd3a-30edad590f00)

This could be a zenGL issue though I'm not sure.

2024-07-25 16:24 UTC, MyreMylar commented
After some fiddling this is what I came up with as test code:

```python
import pygame
import zengl

window_size = (1280, 720)

pygame.init()

window = pygame.Window(size=window_size, opengl=True)
window.resizable = True

ctx = zengl.context()

image = ctx.image(window_size, "rgba8unorm", samples=4)
vert_shader = """
        #version 330 core

        out vec3 v_color;

        vec2 vertices[3] = vec2[](
            vec2(0.0, 0.8),
            vec2(-0.6, -0.8),
            vec2(0.6, -0.8)
        );

        vec3 colors[3] = vec3[](
            vec3(1.0, 0.0, 0.0),
            vec3(0.0, 1.0, 0.0),
            vec3(0.0, 0.0, 1.0)
        );

        void main() {
            gl_Position = vec4(vertices[gl_VertexID], 0.0, 1.0);
            v_color = colors[gl_VertexID];
        }
    """
frag_shader = """
        #version 330 core

        in vec3 v_color;

        layout (location = 0) out vec4 out_color;

        void main() {
            out_color = vec4(v_color, 1.0);
            out_color.rgb = pow(out_color.rgb, vec3(1.0 / 2.2));
        }
    """
pipeline = ctx.pipeline(
    vertex_shader=vert_shader,
    fragment_shader=frag_shader,
    framebuffer=[image],
    topology="triangles",
    vertex_count=3,
)

clock = pygame.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()

        if event.type == pygame.WINDOWRESIZED:
            image = ctx.image((event.x, event.y), "rgba8unorm", samples=4)
            pipeline = ctx.pipeline(
                vertex_shader=vert_shader,
                fragment_shader=frag_shader,
                framebuffer=[image],
                topology="triangles",
                vertex_count=3,
            )

    ctx.new_frame()
    image.clear()
    pipeline.render()
    image.blit()
    ctx.end_frame()

    window.flip()
    clock.tick(60)
```

Which seems to work. Does that seem correct for testing this issue?

2024-07-25 16:25 UTC, damusss commented
@MyreMylar zengl is different from moderngl, so when the window resizes you are required to remake the framebuffer image and threfore the pipeline that uses it. The "correct" version of your code is this:
(failed to make collapsable header)
NOTE: this makes this code work with OR without my PR. You should try with moderngl. hold on while I provide a moderngl example that is impacted by this PR.

```python
import pygame
  import zengl
  
  window_size = (1280, 720)
  
  pygame.init()
  
  window = pygame.Window(size=window_size, opengl=True)
  window.resizable = True
  
  ctx = zengl.context()
  
  image = ctx.image(window_size, "rgba8unorm", samples=4)
  
  def make_pipeline():
      global pipeline
      pipeline = ctx.pipeline(
          vertex_shader="""
              #version 330 core
  
              out vec3 v_color;
  
              vec2 vertices[3] = vec2[](
                  vec2(0.0, 0.8),
                  vec2(-0.6, -0.8),
                  vec2(0.6, -0.8)
              );
  
              vec3 colors[3] = vec3[](
                  vec3(1.0, 0.0, 0.0),
                  vec3(0.0, 1.0, 0.0),
                  vec3(0.0, 0.0, 1.0)
              );
  
              void main() {
                  gl_Position = vec4(vertices[gl_VertexID], 0.0, 1.0);
                  v_color = colors[gl_VertexID];
              }
          """,
          fragment_shader="""
              #version 330 core
  
              in vec3 v_color;
  
              layout (location = 0) out vec4 out_color;
  
              void main() {
                  out_color = vec4(v_color, 1.0);
                  out_color.rgb = pow(out_color.rgb, vec3(1.0 / 2.2));
              }
          """,
          framebuffer=[image],
          topology="triangles",
          vertex_count=3,
      )
  make_pipeline()
  
  clock = pygame.Clock()
  
  while True:
      for event in pygame.event.get():
          if event.type == pygame.QUIT:
              pygame.quit()
              quit()
          if event.type == pygame.VIDEORESIZE:
              window_size = event.size
              image = ctx.image(window_size, "rgba8unorm", samples=4)
              make_pipeline()
  
      ctx.new_frame()
      image.clear()
      pipeline.render()
      image.blit()
      ctx.end_frame()
  
      window.flip()
      clock.tick(60)
```

2024-07-25 16:26 UTC, MyreMylar commented
OK, looks like the refcount error on window close is also fixed by updating zenGL - so I guess that was on their side not us.

2024-07-25 16:32 UTC, MyreMylar approved these changes
Approving, assuming I'm testing this correctly - please let me know if I am not.

2024-07-25 18:58 UTC, merged