Add new official logos for pygame - Community Edition
pygame-community/pygame-ce pull request #2965
Opened 2024-07-01 18:02 UTC by Mega-JC

Upon request by some contributors, other community members (#2234) and in order to have a better distinction between [upstream pygame](https://github.com/pygame/pygame) and pygame-ce, @kadir014 and I came up with a new logo for the pygame-ce project. The first concepts were created mid-October 2023, eventually leading to the current set of changes in this PR.

I've stayed conservative with stylistic changes to the pygame snake to preserve familiarity. The pupily are slightly larger and positioned in a more friendly way.

Logo  |  LoFi | Powered 
:-------------------------:|:-------------------------:|:-------------------------:
![image](https://github.com/pygame-community/pygame-ce/assets/65417594/1a332d28-9dc9-49e7-911d-a999463e8baf) | ![image](https://github.com/pygame-community/pygame-ce/assets/65417594/61543307-9e67-4b85-9e3a-de8bb3e40561) | ![image](https://github.com/pygame-community/pygame-ce/assets/65417594/89d9b3b1-2cfc-405e-81e1-90f04abc00b9)

Docs: Light Theme  |  Docs: Dark Theme
:-------------------------:|:-------------------------:
![image](https://github.com/pygame-community/pygame-ce/assets/65417594/7cde9bfe-08e4-41e4-aad7-622acf115bb9)  |  ![image](https://github.com/pygame-community/pygame-ce/assets/65417594/1da79ab4-abc8-4362-8816-4168c550d523)
![image](https://github.com/pygame-community/pygame-ce/assets/65417594/1829da1b-fa22-463d-948c-cebcae8a5ef1)  |  ![image](https://github.com/pygame-community/pygame-ce/assets/65417594/1b462a29-629b-44ae-b932-1934eb6bd954)

### Approximate README.rst preview
![image](https://github.com/pygame-community/pygame-ce/assets/65417594/c40a9b51-d38e-4146-8a35-cf94676e37cf)

2024-07-01 18:21 UTC, damusss commented
I love this new logo :)

2024-07-01 22:28 UTC, novialriptide commented
I think the "ce" part of the logo should be smaller and should pronounce "community edition".

2024-07-02 05:44 UTC, Starbuck5 commented
> I think the "ce" part of the logo should be smaller and should pronounce "community edition".

I'd rather leave it as "ce".

"community edition" is a lot of text for a logo, even as banner-like as it is.

2024-07-02 06:21 UTC, Starbuck5 commented on docs/reST/logos.rst
>  .. container:: fullwidth
I get a warning about this from Sphinx.

`C:\Users\charl\Desktop\pygame-ce\docs\reST\logos.rst:43: ERROR: Content block expected for the "container" directive; none found.`

2024-07-02 11:48 UTC, Mega-JC commented on docs/reST/logos.rst
>  .. container:: fullwidth
Fixed.

2024-07-03 06:22 UTC, Starbuck5 approved these changes
Thank you for pushing this forward Mega, and thanks to Lucy for the original design concept.

I like these new logos.

2024-07-06 12:02 UTC, gresm requested changes
Please update 
https://github.com/pygame-community/pygame-ce/blob/6f7aeea6e4ef9f9fd6f67e56bf63ea77e9a1d961/src_py/meson.build#L30-L33 
```meson
data_files = files( 
    'freesansbold.ttf', 
    'pygame_icon.bmp', 
    'pygame_ce_logo.png',
    'pygame_ce_powered.png',
) 
```
(and include copies of bundled images in ``src_py/`` - likely moving those files to a different folder will be needed in the future), so the code could access these images:
```py
import pygame

pygame.init()
powered_splash = pygame.image.load(pygame.pkgdata.getResource("pygame_ce_powered.png"))
```

Otherwise LGTM :+1:

2024-07-06 18:11 UTC, Mega-JC commented
The sole goal behind this PR was to replace the previous logos by providing drop-in replacements, while making file name and link adjustments at all the places necessary.

Anything else feels out of scope.

2024-07-07 07:59 UTC, MyreMylar approved these changes
LGTM, well done to everyone who worked on these. Let's get them in I say 👍 

I do think we should consider - at some point - having a second style of logo that is more subdued and 'serious' looking. This is just because videogames is a broad category and while many have the same cheery, fun colourful ambience of the traditional pygame style  there are also plenty that are sadgames in a grim future of only war where another style of logo might blend in more easily.

Plenty of precedent for long running media organisations to have many logos, and logo variants.

As an example of something we could try adding as a variant that might suit many users - a monochrome variant, something that can be easily colourized to fit an app/game's colour scheme:

![pygame_ce_monochrome](https://github.com/pygame-community/pygame-ce/assets/13382426/82e9b4fe-a079-44ec-bb43-3d0ab75bcd40)

Colourized example:
![pygame_ce_colorized_example](https://github.com/pygame-community/pygame-ce/assets/13382426/117c6bc1-b0b3-4949-9e5f-83b4b8e85a60)

2024-07-07 08:02 UTC, MyreMylar commented
> Please update
> 
> https://github.com/pygame-community/pygame-ce/blob/6f7aeea6e4ef9f9fd6f67e56bf63ea77e9a1d961/src_py/meson.build#L30-L33
> 
> ```meson
> data_files = files( 
>     'freesansbold.ttf', 
>     'pygame_icon.bmp', 
>     'pygame_ce_logo.png',
>     'pygame_ce_powered.png',
> ) 
> ```
> 
> (and include copies of bundled images in `src_py/` - likely moving those files to a different folder will be needed in the future), so the code could access these images:
> 
> ```python
> import pygame
> 
> pygame.init()
> powered_splash = pygame.image.load(pygame.pkgdata.getResource("pygame_ce_powered.png"))
> ```
> 
> Otherwise LGTM 👍

Let's move this idea to a new issue/PR so we can resolve the long-running logo switchover issue.

2024-07-07 09:09 UTC, merged