Condense SDL_PixelFormat copy code
pygame-community/pygame-ce pull request #2979
Opened 2024-07-07 21:29 UTC by itzpr3d4t0r

This PR tries to make code more compact, legible and not dependant on SDL versions.

2024-07-08 01:58 UTC, oddbookworm commented on src_c/surface.c
> +            memcpy(&newfmt, src->format, sizeof(SDL_PixelFormat));
I'm not 100% sold that `memcpy` is more readable than what's already there. Especially since we still have to go set specific fields after this. There are actually other fields too that may need to be specially handled. According to https://wiki.libsdl.org/SDL2/SDL_PixelFormat, shouldn't we also ensure that
* `refcount` gets zeroed out on the new one
* `next` gets set to `NULL` (is that right?)
* Currently we don't handle the `padding` or `format` fields. What should we actually do with them?

2024-07-08 02:00 UTC, oddbookworm commented on src_c/surface.c
> -#endif
If we end up not going with this PR and keeping things the way they currently are, looks like in SDL3, the `*loss* fields get renamed to `*bits` https://wiki.libsdl.org/SDL3/SDL_PixelFormat

2024-07-08 14:04 UTC, ankith26 commented on src_c/surface.c
> +            memcpy(&newfmt, src->format, sizeof(SDL_PixelFormat));
I believe in the current code, those values are garbage anyways.

2024-07-09 02:38 UTC, oddbookworm commented on src_c/surface.c
> +            memcpy(&newfmt, src->format, sizeof(SDL_PixelFormat));
> I believe in the current code, those values are garbage anyways.

And that spooks me somewhat. We really should be ensuring that all fields are set to at least a default value if not copied from the source IMO. Seems like a good way to get weird segfaults because of something internal to SDL

2024-07-09 11:30 UTC, itzpr3d4t0r commented on src_c/surface.c
> +            memcpy(&newfmt, src->format, sizeof(SDL_PixelFormat));
Yeah i concour with that, actually funnily enough those attributes were uninitialized before, so yeah unless we check SDL's internals we can't assure weird things won't happen.

2024-07-14 23:44 UTC, oddbookworm commented
@itzpr3d4t0r that recent commit confuses me in context of all the rest of the changes here. Am I missing something, or is this incomplete for now?

2024-07-15 06:05 UTC, itzpr3d4t0r commented
> @itzpr3d4t0r that recent commit confuses me in context of all the rest of the changes here. Am I missing something, or is this incomplete for now?

You can shallow copy a struct without memcpy, so i did just that, it's not incomplete.

2024-07-16 04:08 UTC, oddbookworm requested changes

2024-07-16 04:08 UTC, oddbookworm commented on src_c/surface.c
>              newfmt.palette = 0; /* Set NULL (or SDL gets confused) */
I would like to see two changes here:
- `newfmt.palette = NULL` for clarity that it's a pointer type
- Addressing `newfmt.next`, which is also a pointer. I don't want to end up copying a pointer to memory that ends up being garbage later because we copied a pointer to memory this object doesn't own

2024-07-16 04:08 UTC, oddbookworm commented on src_c/surface.c
> -#endif
Update:
[this entire struct got renamed in SDL3 as of like a week ago](https://wiki.libsdl.org/SDL3/SDL_PixelFormatDetails)

2024-10-04 20:00 UTC, MyreMylar approved these changes
LGTM 👍  Though, as the comments point out, a bunch of this will need to be changed again in the near future to manage the renaming and internal changes for SDL 3.

Still I think it'll be easier to change this code chunk once it is fewer lines.

2025-02-28 09:03 UTC, closed without merging