Polish stubs with deprecated decorator
pygame-community/pygame-ce pull request #2984
Opened 2024-07-11 12:44 UTC by damusss

After the discussion in this PR the focus of it has changed. This can be considered stubs polish.
- I changed the `_to/from_string_format` name to `_to/from_bytes_format` as the previous was referring to deprecated functions
- I removed the `final` import from `window.pyi` as `Window` is not a final class anymore
- Most relevant, I've added the new 3.13 (using `typing_extension`) `@deprecated` decorator to note deprecated functions and classes. This makes the stubs stay up to date with the python type systems and add useful messages (and visual effects like a strikethrough in VSCode) about deprecated features so users don't confuse them with the correct ones and are able to know if something is deprecated without documentation/running the code.

2024-07-11 12:56 UTC, damusss commented
I realized later that some checks check if the stubs are present, so I'll convert to draft, get some feedback and decide what to do with the PR

2024-07-11 13:34 UTC, ankith26 reviewed
If you are doing this change, you need to add the removed API to the stubtest ignore file.

2024-07-11 14:27 UTC, damusss commented
Alright, thanks, I didn't know that was possible, the checks are passing now.

2024-07-12 05:52 UTC, Starbuck5 commented
I would like to not do this.

Deprecations are now part of the type system in 3.13: https://peps.python.org/pep-0702/

In my VS code deprecations show up like this:
![image](https://github.com/user-attachments/assets/60dd0277-9ea4-40de-a07f-357b9cb90573)

And it's backed by a pyi file that has the feature:
![image](https://github.com/user-attachments/assets/a7f85ff9-c389-4614-ba1a-0137478745d5)

(Using typing_extensions since I'm on 3.9)

2024-07-12 06:27 UTC, damusss commented
do we have some sort of access to @deprecated in the lower python supported version of pygame?

2024-07-12 11:14 UTC, ankith26 commented
You can import `@deprecated` from `typing_extensions` which should serve as a backport of the feature for older python versions

2024-07-14 23:58 UTC, oddbookworm requested changes
I've just got a few clarifying suggestions

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/math.pyi
>  def disable_swizzling() -> None: ...
Empty strings?

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead, which only requires display init")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead, which doesn't require scrap init")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead: `pygame.scrap.get_text`")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead, which only supports strings")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead: `pygame.scrap.put_text`")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead: `pygame.scrap.has_text`")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead, which uses system clipboard")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/scrap.pyi
> +@deprecated("since 2.2.0. Use the new API instead")
```suggestion
@deprecated("since 2.2.0. Use the new API instead, which only supports strings")
```

2024-07-14 23:58 UTC, oddbookworm commented on buildconfig/stubs/pygame/window.pyi
> +    @deprecated("since 2.4.0. Use the display module or the Window class with get_surface and flip")
```suggestion
    @deprecated("since 2.4.0. Use either the display module or the Window class with get_surface and flip. Try not to mix display and Window")
```

2024-07-15 09:31 UTC, damusss commented on buildconfig/stubs/pygame/math.pyi
>  def disable_swizzling() -> None: ...
Replaced with "Functionality is removed" which I found in the emitted warning

2024-07-16 03:56 UTC, oddbookworm approved these changes
LGTM!

2024-07-16 08:54 UTC, damusss commented on buildconfig/stubs/pygame/scrap.pyi
> +put
I was testing my ide response to deprecation I forgot it there LOL sorry

2024-07-16 09:01 UTC, damusss commented on buildconfig/stubs/pygame/sprite.pyi
>  class OrderedUpdates(RenderUpdates[_TSprite]): ...
I added it now, thanks

2024-07-16 09:08 UTC, bilhox commented
> You missed the deprecation of `mouse.set_system_cursor` too

Thanks, going to add it in #2943 .

2024-07-16 09:11 UTC, damusss commented
> > You missed the deprecation of `mouse.set_system_cursor` too
> 
> Thanks, going to add it in #2943 .

hold on, I didn't know it was deprecated, I need to add it here aswell!

2024-07-16 11:16 UTC, ankith26 approved these changes
LGTM, thanks for the PR :partying_face:

2024-07-16 11:16 UTC, merged