Add 9-patch to examples
pygame-community/pygame-ce pull request #2985
Opened 2024-07-11 21:01 UTC by damusss

After a short discussion with @Starbuck5 9-patch scaling is a recipe like process that doesn't involve algorithmic pixel manipulation so an example is probably good enough for it.

This is a good place to come every time you need your own 9-patch function and good to teach for GUI purposes. It's also existing in every other game engine so at least an example is needed.

I made the 9-patch code behave like a transform function would, adding comments and type hinting.

2024-07-12 09:13 UTC, damusss commented
Attaching a preview of the example for ease of review
![image](https://github.com/user-attachments/assets/2bd86e2c-f27b-4307-baba-7a3223661fd7)

2024-08-26 16:47 UTC, bilhox requested changes
Overall the example is really cool. I would apprecate since you mentionned it works for any custom surface to actually use a custom surface, like an image with the necessary properties to make it work.

Anyways, good job :)

2024-08-26 16:47 UTC, bilhox commented on examples/ninepatch.py
> +        )
Can this part be simplified using ``pygame.Vector2`` operations ?

2024-08-27 07:51 UTC, damusss commented on examples/ninepatch.py
> +        )
No, I don't think so. It's the most compact and understandable I could. I can't even see where to insert vector2s, all I'm doing is subsurfacing, scaling and blitting.

2024-08-27 08:08 UTC, damusss commented
With my las commit I
- used pygame.Vector2.elementwise
- changed the while True
- added a real image on top of the rect

2024-08-28 17:16 UTC, bilhox requested changes
LGTM, I left some requested changes.

2024-08-28 17:16 UTC, bilhox commented on examples/ninepatch.py
> +    src_y_side, ret_y_side = src_h - c * 2, ret_h - c * 2
```suggestion
    dest_size = size  # non-sequence argument catched by python
    src_size = surface.size
    c = corner_size
    scale_func = pygame.transform.smoothscale if smooth else pygame.transform.scale
    subsurface = surface.subsurface  # alias for performance/clarity

    if not 0 < corner_size < min(dest_size):
        raise ValueError(
            "Corner size must be positive and less than the smallest between destination width and destination height"
        )
    if corner_size == 0:  # default to normal scaling
        return scale_func(surface, size)
        
    ret_x_side, ret_y_side = src_size - pygame.Vector2(c) * 2
    src_x_side, src_y_side = ret_size - pygame.Vector2(c) * 2    
```
For these 2 lines : 
```py
    ret_x_side, ret_y_side = src_size - pygame.Vector2(c) * 2
    src_x_side, src_y_side = ret_size - pygame.Vector2(c) * 2  
```
It might be not beautiful, but this is because you are not currently supporting custom x and y corners. I would like to recommend this additional feature.

For beginners mental health, you should comment what the variable you created are used for.

2024-08-28 17:16 UTC, bilhox commented on examples/ninepatch.py
> +    ninepatch_center = SCREEN_SIZE.elementwise() / (2, (4 / 3))
What about turning ``(2, (4, 3))`` into ``pygame.Vector2(2, 4 / 3)`` ?

2024-08-28 17:30 UTC, damusss commented on examples/ninepatch.py
> +    src_y_side, ret_y_side = src_h - c * 2, ret_h - c * 2
bro wants me to suffer even more 😭 I'm about to take back the idea of adding this in the examples 😭

2024-08-28 17:31 UTC, damusss commented on examples/ninepatch.py
> +    ninepatch_center = SCREEN_SIZE.elementwise() / (2, (4 / 3))
OK

2024-08-28 17:49 UTC, bilhox commented on examples/ninepatch.py
> +    src_y_side, ret_y_side = src_h - c * 2, ret_h - c * 2
After a small discussion on discord, I agree it's not necessary.

2024-08-28 17:49 UTC, damusss commented on examples/ninepatch.py
> +    src_y_side, ret_y_side = src_h - c * 2, ret_h - c * 2
I will improve what you said to improve in this review comment tho

2024-10-05 08:09 UTC, MyreMylar approved these changes
OK, LGTM 👍

2024-10-05 09:17 UTC, bilhox approved these changes
LGTM!

2024-10-05 09:22 UTC, merged