[WIP] Add pygame.typing module
pygame-community/pygame-ce pull request #3002
Opened 2024-07-16 17:32 UTC by damusss

[description WIP]

2024-07-16 20:21 UTC, damusss commented on buildconfig/stubs/gen_stubs.py
> +shutil.copyfile("src_py/typing.py", "buildconfig/stubs/pygame/typing.pyi")
Alright I updated that and I added typing to __init__ otherwise you could not actually use it :kekw:

2024-07-17 21:59 UTC, Matiiss requested changes

2024-07-17 21:59 UTC, Matiiss commented on src_py/typing.py
There should be a
```py
del sys, IO, Callable, Tuple, Union, TypeVar, Protocol, SupportsIndex
```
at the end of the file so that this module doesn't contain any of those names

2024-07-18 06:33 UTC, Starbuck5 commented
So before we add a whole new module for this, we should think about some things.

How do other libraries do this?

Does this need to be a module or can type variables be scattered where they are relevant? Like pygame.rect.RectLike?

How can we keep this stable? This exposes more stuff that we need to keep stable, are we okay with that?

2024-07-18 06:50 UTC, damusss commented
> So before we add a whole new module for this, we should think about some things.
> 
> How do other libraries do this?
> 
> Does this need to be a module or can type variables be scattered where they are relevant? Like pygame.rect.RectLike?
> 
> How can we keep this stable? This exposes more stuff that we need to keep stable, are we okay with that?

2) you could realistically only scatter rect, color and maybe rgba, maybe path and file to rwobject, but those are all implemented in C and they would require some injection.

3) what non stable things are we exposing?

2024-07-21 17:40 UTC, ankith26 approved these changes
Overall, I really like where this PR is going! I am approving the code changes from my side. I left a few reviews for improving the test file. 

As this is a significant change, I would like for this PR to have 3 approving reviews.

2024-07-21 17:40 UTC, ankith26 commented on buildconfig/stubs/typing_sample_app.py
> +
I would like to see `pathlib` stuff tested here.

2024-07-21 17:40 UTC, ankith26 commented on buildconfig/stubs/typing_sample_app.py
> +validator_SequenceLike("1234567890")
I would also like to have type specific tests here. For example `SequenceLike[float]`

2024-07-21 17:47 UTC, ankith26 commented on buildconfig/stubs/stubcheck.py
> +        returncode = subprocess.run([*mypy_args]).returncode
If this is anything other than 0, an error must be raised here/

2024-07-21 17:47 UTC, ankith26 commented on src_py/typing.py
> +import sys
I would like a header docstring here, and also a comment explaining that this file and typing.pyi are meant to be kept duplicated

2024-07-21 17:59 UTC, ankith26 commented
Addressing some of Starbuck's points (in favour of this PR) from my POV

> How do other libraries do this?
> Does this need to be a module or can type variables be scattered where they are relevant? Like pygame.rect.RectLike?

As Matt already pointed out, `numpy` already has a dedicated submodule for typing stuff. In the future, if needed, we can make aliases in scattered places, but I'd like all the implementation to be in one file.

> How can we keep this stable? This exposes more stuff that we need to keep stable, are we okay with that?

This PR already adds a test file, that should help with maintaining stability. OFC, the file could be expanded in future iterations.
If this makes approval more comfortable: we can always slap an "experimental" notice on the docs, and allow for more drastic changes here for a few releases.

2024-07-22 20:10 UTC, Matiiss commented on buildconfig/stubs/pygame/typing.pyi
> +    # that returns a rect confirms to the rect protocol
confirms -> conforms
lol

2024-07-22 20:12 UTC, damusss commented on buildconfig/stubs/pygame/typing.pyi
> +    # that returns a rect confirms to the rect protocol
On my defense, this typo has been there since forever lol, I just copy pasted

2024-07-22 20:12 UTC, Matiiss approved these changes
LGTM, I sense this will be a great addition to `pygame-ce`

Maybe the type aliases could be hinted as `TypeAlias`es, but if type checkers don't complain then it's probably that important.

I suppose sometime in the future we could restructure this a bit so that there's no need to literally copy-paste code from `typing.py` to `typing.pyi`, but I suppose it should be fine for now.

Thanks! 🚀

2024-07-31 17:05 UTC, bilhox requested changes
Overall LGTM, I left some requested changes for the documentation part.
I feel like for people reading the docs, a list of structure for each type in ``pygame.type`` is a lot better for the user. Even though it's abstract and can technically handles an infinite number of type as long as it respects the structure, making a list of the most common types used feels essential for the user.

2024-08-02 16:12 UTC, bilhox requested changes
``pygame.gfxdraw`` does not handle string colors and mapped color, only sequences of 3 or 4 values are accepted (RGB and RGBA).

2024-08-02 16:12 UTC, bilhox commented on docs/reST/ref/typing.rst
> +      are supported by every function accepting a rect as argument. i.e.:
```suggestion
      or an object with a rect attribute or a method returning a rect. This type
      is supported by every function accepting a rect as argument. i.e.:
```

2024-08-02 16:14 UTC, damusss commented on docs/reST/ref/typing.rst
> +      are supported by every function accepting a rect as argument. i.e.:
why should it be singular? i listed multiple types in the sentence.

2024-08-02 16:16 UTC, bilhox commented on docs/reST/ref/typing.rst
> +      are supported by every function accepting a rect as argument. i.e.:
Then it would be ``These`` and not ``This`` . I thought you were talking about ``Rectlike``.

2024-08-02 16:18 UTC, damusss commented on docs/reST/ref/typing.rst
> +      are supported by every function accepting a rect as argument. i.e.:
ah that's just some silly grammar mistake of mine

2024-08-02 16:20 UTC, damusss commented
> ``pygame.gfxdraw`` does not handle string colors and mapped color, only sequences of 3 or 4 values are accepted (RGB and RGBA).

so should i say supported by "almost" all pygame functions or do you want me to edit gfxdraw.pyi? the typehints were there already and they were wrong before this PR.

2024-08-12 13:53 UTC, ankith26 commented on docs/reST/ref/typing.rst
> +.. versionadded:: 2.5.1
needs updating now

2024-08-12 23:40 UTC, Matiiss reviewed
None of the `sprite.pyi` types seem to be exposed, is this intended? I find it would be greatly beneficial to expose those types as well. It would help with some testing I plan to do regarding those types and thus it would require access to concrete objects.

2024-08-13 03:43 UTC, damusss commented
> None of the `sprite.pyi` types seem to be exposed, is this intended? I find it would be greatly beneficial to expose those types as well. It would help with some testing I plan to do regarding those types and thus it would require access to concrete objects.

Do you mean types such as _SuportsSprite and _SupportsDirtySprite? It is kinda intended. This PR only implements the contents of common.pyi to keep the scope simple. extra typings can be added later with other PRs based on their need (at the start of the PR I added a lot more types but keeping it small is better). @ankith26 might have a say in the matter.

2024-08-14 20:07 UTC, Matiiss commented
> > None of the `sprite.pyi` types seem to be exposed, is this intended? I find it would be greatly beneficial to expose those types as well. It would help with some testing I plan to do regarding those types and thus it would require access to concrete objects.
> 
> Do you mean types such as _SuportsSprite and _SupportsDirtySprite? It is kinda intended. This PR only implements the contents of common.pyi to keep the scope simple. extra typings can be added later with other PRs based on their need (at the start of the PR I added a lot more types but keeping it small is better). @ankith26 might have a say in the matter.

Fair enough, it can be handled in a later PR then 👍

2024-08-18 10:49 UTC, ankith26 approved these changes
This PR still has my approval. This has been some nice work, thanks again for working on this! :sunglasses: 

I think we can just merge it in for now (as it is a pretty safe change that wouldn't break any code) and see how it goes. If needed we can also mark this as experimental before the next release.

2024-08-18 10:49 UTC, merged