Fix segfault with antialiased draw functions with a depth different than 32bits
pygame-community/pygame-ce pull request #3008
Opened 2024-07-19 18:54 UTC by bilhox

Closes #586 

*Needs some tests from other users*

2024-07-19 21:10 UTC, bilhox commented
edit : It doesn't fix ``gfxdraw`` side as it's meant to be deprecated and be redirected to ``pygame.draw`` for all antialiasing functions.

2024-07-22 14:59 UTC, damusss approved these changes
I tested locally. The segfault existed before, now it's gone. Visually it was broken before, now it's perfect.

LGTM, thanks for the fix! :)

2024-07-23 08:09 UTC, ankith26 requested changes
I left a few reviews. I'm a bit sceptical of the 24-bit codepath, which is also why I'm suggesting the tests to be stricter here.

2024-07-23 08:09 UTC, ankith26 commented on test/draw_test.py
> +            )
I'd like this test to take a few random pixels (atleast 5 or so) on the surface and assert that the color matches exactly.

2024-07-23 08:09 UTC, ankith26 commented on src_c/draw.c
> +    }
This block can be refactored to reduce some duplication. I would suggest having a `Uint32 pixel` variable declared first, then set on the case-wise basis, so that the below part can be done outside the switch statement.
```c
SDL_GetRGB(pixel, surf->format, &background_color[0],
    &background_color[1], &background_color[2]);
```

2024-07-24 21:46 UTC, bilhox commented on src_c/draw.c
> +    }
Should be fixed now.

2024-07-24 22:25 UTC, bilhox commented on test/draw_test.py
> +            )
Should be fixed. I took pixels at edges since the problem concerns antialiased mode.

2024-07-26 05:55 UTC, Starbuck5 commented
This whole thing is a mess.

Firstly, I would expect in a PR like this to see an explanation of what is actually being fixed, why it is segfaulting. Not just that it's fixed and needs tests from other users.

You want to use SDL_GetRGBA correctly? See https://github.com/libsdl-org/SDL/issues/8320 and https://github.com/libsdl-org/SDL/commit/f8dfee01bb4fdca3d7f77d4d2a30ed58c63e869c#diff-ec00a797fe34913f3e553761506783ef6b4cd0050704665615c93392ac7360e6R1557-R1618

They mention the performance is terrible "meant only for unittests", so that gets me thinking about performance:

So get_antialiased_color is a performance sensitive function, why is it being called over and over decoding the value of original_color every single time?

And so then this function produces a result to use in set_at, but set_at also calls SDL_GetRGB, but only on 24 bit! So in set_at it's taking a mapped color, unmapping it with SDL_GetRGB, then manually remapping it with bit shifting. Am I reading that right?

2024-07-26 18:27 UTC, bilhox commented
> This whole thing is a mess.
> 
> Firstly, I would expect in a PR like this to see an explanation of what is actually being fixed, why it is segfaulting. Not just that it's fixed and needs tests from other users.
> 
> You want to use SDL_GetRGBA correctly? See [libsdl-org/SDL#8320](https://github.com/libsdl-org/SDL/issues/8320) and [libsdl-org/SDL@f8dfee0#diff-ec00a797fe34913f3e553761506783ef6b4cd0050704665615c93392ac7360e6R1557-R1618](https://github.com/libsdl-org/SDL/commit/f8dfee01bb4fdca3d7f77d4d2a30ed58c63e869c#diff-ec00a797fe34913f3e553761506783ef6b4cd0050704665615c93392ac7360e6R1557-R1618)
> 
> They mention the performance is terrible "meant only for unittests", so that gets me thinking about performance:
> 
> So get_antialiased_color is a performance sensitive function, why is it being called over and over decoding the value of original_color every single time?
> 
> And so then this function produces a result to use in set_at, but set_at also calls SDL_GetRGB, but only on 24 bit! So in set_at it's taking a mapped color, unmapping it with SDL_GetRGB, then manually remapping it with bit shifting. Am I reading that right? (EDIT: PR to fix set_at to not call SDL_GetRGB every pixel: #3021)
> 
> P.S. maybe we can do our version of SDL_GetRGBA "manually inlined" into our source by grabbing it from the SDL source.

Hello, first, thank you for the constructive review !

Sorry, I forgot to mention what was the culprit behind this segfault. As you guessed, the problem resided on how we were extracting pixels in ``get_antialiased_color`` in ``draw.c`` (extracted as a ``Uint32`` array), leading to read at pixels out of the range of the array.

You suggested me to look at how SDL does the same work with ``SDL_ReadSurfacePixel``, are you specifically talking about 24bit path ?

2024-07-27 06:26 UTC, Starbuck5 commented
> You suggested me to look at how SDL does the same work with SDL_ReadSurfacePixel, are you specifically talking about 24bit path ?

So I see you checked out the SDL implementation and put it in, nice! The big endian build is failing though since you have a discrepancy in variable names.

I found another way to get around this problem that may be better. When I looked through draw.c I saw that this is the only location that does any pixel reading, everything else is just doing pixel writing. But there are places in pygame-ce doing pixel reading, how are they doing it? I found in surface.h there's a macro `GET_PIXEL` that works for all bit depths, that could be a good solution here. Might even be faster, as it doesn't need a memcpy-- although the memcpy might be compiler-optimized-away.

Anyways, I'd be interested in seeing you check it out.

2024-07-27 10:29 UTC, bilhox commented
I checked how it's done on other files, and I saw that they all used a switch case, and manually shift bits for 3 bytes case, and ultimately call ``GET_PIXELVAL`` which is a hidden ``SDL_GetRGBA``.

2024-08-04 06:16 UTC, Starbuck5 commented
> I checked how it's done on other files, and I saw that they all used a switch case, and manually shift bits for 3 bytes case, and ultimately call GET_PIXELVAL which is a hidden SDL_GetRGBA.

Yes, I wasn't saying it avoided calling that function? Just saying that we already have an implementation strategy for calling that function properly, maybe that's the way to go here as well.

2024-08-06 07:00 UTC, bilhox commented
What about adding a new C API function called ``pg_getPixelValue`` ? Everywhere they have their own macros.

2024-08-23 21:31 UTC, bilhox commented
To move this fix as close as possible to being merged. I'm doing some performance tests (just a little skeptical about the perf behind a lot of ``memcpy`` calls) which I'll be posting here tomorrow. This will determine if we keep the switch case impl or the memcpy impl.

2024-08-24 09:30 UTC, bilhox commented
My tests on ``aaline`` showed me this : 
![graph_get_pixel_value](https://github.com/user-attachments/assets/0a0b53a7-5da6-4fdb-9d40-ec7753e59f4b)

red is the switch case implementation and green is the ``memcpy`` implementation.
As you can see switch case implementation is faster than ``memcpy``. So I'll be reverting to switch case. (The results for other bpp show the same difference of performance)

2024-09-01 09:08 UTC, MightyJosip commented on src_c/draw.c
> +#include <string.h>
Is there a reason for this?

2024-09-01 09:09 UTC, MightyJosip reviewed
Just a question

2024-09-01 09:12 UTC, bilhox commented on src_c/draw.c
> +#include <string.h>
I have no idea when I included this, maybe I wrote this in the wrong branch, I'll remove it.

2024-09-16 04:42 UTC, Starbuck5 commented on src_c/draw.c
> +#include <string.h>
string.h is needed for memcpy.

2024-09-16 04:45 UTC, Starbuck5 commented on src_c/draw.c
> +    size_t bpp = surf->format->BytesPerPixel;
`bpp = PG_SURF_BytesPerPixel(surf);` for SDL3 compatibility.

Why is this a size_t?

2024-09-16 04:49 UTC, Starbuck5 commented on src_c/draw.c
> +    size_t bpp = surf->format->BytesPerPixel;
Nice work changing surf->w to surf->pitch.

2024-09-18 20:21 UTC, bilhox commented on src_c/draw.c
> +    size_t bpp = surf->format->BytesPerPixel;
> Why is this a size_t?

Good question, I can't remember what i was thinking about when I used ``size_t``. Switching to ``int``.

2024-09-23 02:43 UTC, Starbuck5 approved these changes
Thanks!

2024-09-23 02:44 UTC, Starbuck5 commented on src_c/draw.c
> +    size_t bpp = surf->format->BytesPerPixel;
I approved and all, but just for the record you didn't switch to int.

2024-09-24 18:09 UTC, bilhox commented on src_c/draw.c
> +    size_t bpp = surf->format->BytesPerPixel;
Sorry I forgot, now It's updated.

2024-09-24 18:45 UTC, ankith26 approved these changes
LGTM, thanks for the PT :sunglasses:

2024-09-24 18:46 UTC, merged