Make `pygame.typing.PathLike` internal/private
pygame-community/pygame-ce pull request #3086
Opened 2024-08-30 01:05 UTC by aatle

Closes #3085

Renames all occurrences from `PathLike` to `_PathLike`, and removes it from docs and `__all__` list.

2024-08-30 05:31 UTC, damusss requested changes
This isn't particularly important, the rest looks good!

2024-08-30 05:31 UTC, damusss commented on docs/reST/ref/typing.rst
> +      An object representing a file. This includes any path-like objects such as
I think it would be best if you used the same docs style as PathLike for FileLike, listing each possible type 
- "mypath"
- pathlib.Path
- b"mybytespath"
- anything supporting the file protocol 
- file buffers (IO of str and bytes) such as the return value of open

something like this (this is just for the idea, the list item text should be better, I'm on phone now)

2024-08-30 09:15 UTC, MyreMylar approved these changes
This seems reasonable I agree that the the `os.PathLike` vs `pygame.typing.PathLike` is likely to be confusing.

2024-08-31 01:54 UTC, aatle commented on docs/reST/ref/typing.rst
> +      An object representing a file. This includes any path-like objects such as
Okay, I listed 6 possible types. Let me know if you'd like any changes to the items I put in.

2024-08-31 09:09 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada:

2024-08-31 09:19 UTC, damusss approved these changes
LGTM, Thank you!

2024-08-31 09:19 UTC, merged