Fix test_inflate_ip__larger.
pygame-community/pygame-ce pull request #3098
Opened 2024-09-11 14:57 UTC by avpai-dinosaur

This test case was not checking what it was supposed to check (duplicate code of test_inflate_ip__smaller).

Fixes #3096

2024-09-11 19:25 UTC, bilhox requested changes
LGTM, thanks for the contribution ! I left a comment for you.

2024-09-11 19:25 UTC, bilhox commented on test/rect_test.py
> +        """The inflate_ip method inflates around the center of the rectangle"""
While you are editing the docstring, it's better if you actually say what does the test do brievly. Same for ``test_inflate_ip__larger``

2024-09-12 00:56 UTC, avpai-dinosaur commented on test/rect_test.py
> +        """The inflate_ip method inflates around the center of the rectangle"""
Took a stab at a more descriptive docstring, lmk what you think

2024-09-12 09:17 UTC, bilhox approved these changes
LGTM 🥳

2024-09-13 11:52 UTC, gresm approved these changes
LGTM. The docstrings for tests of ``pygame.Rect.scale_by`` could also benefit from updating them, but it's probably out of scope of this PR.

2024-09-13 13:37 UTC, bilhox commented
> LGTM. The docstrings for tests of `pygame.Rect.scale_by` could also benefit from updating them, but it's probably out of scope of this PR.

Indeed I can see that for certain tests. I think it's something a bit linked to the topic of this PR. So I would suggest a change there as gresm mentionned it. Otherwise it will not be fixed in a near future.

2024-09-13 16:22 UTC, MyreMylar approved these changes
LGTM 👍

2024-09-13 16:22 UTC, merged