Clarify how Rect and positions relate in the intro tutorial
pygame-community/pygame-ce pull request #3111
Opened 2024-09-23 04:37 UTC by datapythonista

The introduction to PyGame tutorial is a bit confusing for very beginners about the `Rect` object.

I think for beginners talking about a rectangular area it sounds like a rectangle will be printed on the screen. I think it's better to be more specific and mention that rectangular areas are the way to manage an object position.

2024-09-23 08:05 UTC, ankith26 approved these changes
LGTM, thanks for contributing! :balloon:

2024-09-24 21:32 UTC, bilhox requested changes

2024-09-24 21:32 UTC, bilhox commented on docs/reST/tutorials/en/intro-to-pygame.rst
> +to copy from, and a :class:`Rect <pygame.Rect>` object, representing
I would suggest here to stay with the old sentence. It feels more logical and intuitive to pass a destination position (which is even more used than Rects based on datas I don't have), rather than making a rect.

2024-10-01 18:58 UTC, MyreMylar commented on docs/reST/tutorials/en/intro-to-pygame.rst
> +the position to place the source onto the destination.
```suggestion
to copy from, and a position (which can be a :class:`Rect <pygame.Rect>` object or a pair of numbers e.g. (50.0, 25.0) ), to place the source onto the destination.
```

2024-10-01 18:59 UTC, MyreMylar commented on docs/reST/tutorials/en/intro-to-pygame.rst
> +object in the screen).
```suggestion
which represents a rectangular area (which can be used to manage the position of an
object in the screen).
```

2024-10-01 19:03 UTC, bilhox approved these changes
LGTM now! Thanks for the contribution!

2024-10-01 20:09 UTC, merged