Document event.peek() behavior, minor doc and stub fixes
pygame-community/pygame-ce pull request #3122
Opened 2024-09-25 20:12 UTC by zoldalma999

Fixes #1196 by documenting the behavior of pygame.event.peek if nothing is passed in.

Also marks `event.type` and `event.dict` readonly in the stubs, adds runtime docs to them, and makes the pump argument more accurate in the stubs.

2024-09-25 20:48 UTC, bilhox requested changes
LGTM, thanks for the PR!
Worth to mention that @gresm also proposed a fix for this issue in his latest PR.
Otherwise, I left little changes.

2024-09-28 14:10 UTC, ankith26 reviewed
If this is becoming public, a test or two for it would also be good

2024-09-28 14:10 UTC, ankith26 commented on buildconfig/stubs/pygame/event.pyi
> +def peek(eventtype: Optional[_EventTypes] = None, pump: bool = True) -> bool: ...
The return value probably needs to be updated here to be consistent with the docs.

Also, the reason it was typed as `Any` in the first place is because almost any object in python is acceptable as a bool, as you probably already know

2024-09-28 15:00 UTC, zoldalma999 commented
> If this is becoming public, a test or two for it would also be good

Wanted to write one for it, but got a segfault with this code:
```python
import pygame

pygame.init()
pygame.event.clear()

e = pygame.Event(pygame.KEYDOWN, key=pygame.K_SPACE)
pygame.event.post(e)

print("1")
assert e == pygame.event.peek(pump=False)
print("2")
assert e == pygame.event.peek(None, False)
print("3") # This one never gets printed
```
Debugging it a bit more, seems like the dict proxy on this line is already freed
https://github.com/pygame-community/pygame-ce/blob/ddc900edc037552763f390fdfb0cc612581a17c3/src_c/event.c#L930

2024-09-28 15:48 UTC, ankith26 commented
After giving it a bit of thought, my current opinion is that we should remove this functionality all together now.
- If it is segfaulting right now and no one has reported it yet, no one knows or cares about this behaviour.
- For whatever reason if we want to document it down the line, it can be readded and fixed then.

2024-12-09 17:21 UTC, ankith26 reviewed
I think there is a bit of confusion here, what I actually wanted to convey was "make the return value a bool regardless of the input, just remove the behaviour of returning an event type". I would still like to retain the `None`/optional-arg case

2024-12-31 16:05 UTC, MyreMylar commented on buildconfig/stubs/pygame/event.pyi
> +def peek(eventtype: _EventTypes, pump: bool = True) -> bool: ...
```suggestion
def peek(eventtype: Optional[_EventTypes] = None, pump: bool = True) -> bool: ...
```

2024-12-31 16:06 UTC, MyreMylar commented on docs/reST/ref/event.rst
> +   | :sg:`peek(eventtype, pump=True) -> bool`
```suggestion
   | :sg:`peek(eventtype=None) -> bool`
   | :sg:`peek(eventtype=None, pump=True) -> bool`
```

2024-12-31 16:08 UTC, MyreMylar commented on src_c/doc/event_doc.h
> +#define DOC_EVENT_PEEK "peek(eventtype, pump=True) -> bool\ntest if event types are waiting on the queue"
```suggestion
#define DOC_EVENT_PEEK "peek(eventtype=None) -> bool\npeek(eventtype=None, pump=True) -> bool\ntest if event types are waiting on the queue"
```

2024-12-31 16:08 UTC, MyreMylar commented on docs/reST/ref/event.rst
> +
```suggestion
   .. versionchanged:: 2.5.3 no longer mistakenly returns an event when ``eventtype`` is None or not passed.

```

2024-12-31 16:09 UTC, MyreMylar commented on src_c/event.c
> +    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "O|p", kwids, &obj,
```suggestion
    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "|Op", kwids, &obj,
```

2024-12-31 16:12 UTC, MyreMylar commented on src_c/event.c
> +            return NULL;
```suggestion
            return Py_RETURN_FALSE;
```

2024-12-31 16:12 UTC, MyreMylar commented on src_c/event.c
> +        return NULL;
```suggestion
        return Py_RETURN_FALSE;
```

2024-12-31 16:15 UTC, MyreMylar commented on test/event_test.py
>          pygame.event.peek(eventtype=[pygame.KEYUP, pygame.KEYDOWN])
```suggestion
        pygame.event.peek()
        pygame.event.peek(None)
        pygame.event.peek(None, True)

        pygame.event.peek(pump=False)
        pygame.event.peek(pump=True)
        pygame.event.peek(eventtype=None)
        pygame.event.peek(eventtype=[pygame.KEYUP, pygame.KEYDOWN])
```

2024-12-31 16:16 UTC, MyreMylar commented on test/event_test.py
>          # Ensure events can be checked individually.
```suggestion
        # Ensure all events can be checked.
        peeked = pygame.event.peek()

        self.assertFalse(peeked)

        # Ensure events can be checked individually.
```

2024-12-31 16:19 UTC, MyreMylar commented on src_c/event.c
> +        return Py_RETURN_FALSE;
```suggestion
        Py_RETURN_FALSE;
```

2024-12-31 16:20 UTC, MyreMylar commented on src_c/event.c
> +            return Py_RETURN_FALSE;
```suggestion
            Py_RETURN_FALSE;
```

2024-12-31 16:35 UTC, MyreMylar commented
Hmm, well I tried to match what @ankith26 was asking for but it now seems to be segfaulting in the CI. No idea why.

2025-01-05 13:57 UTC, ankith26 commented
I made my own attempt at resolving this PR, and it's now in a new PR here: #3283

I have taken some work done in this PR onto the new one, so thanks for working on this! So, I am closing this one.

2025-01-05 13:57 UTC, closed without merging