Added `geometry.Line` base
pygame-community/pygame-ce pull request #3131
Opened 2024-09-29 10:14 UTC by itzpr3d4t0r

This pull request adds the `Line` class to the `pygame.geometry` module.

It also adds the xa, ya, xb, yb, a, b attributes, str functionality (for printing), and the copy method. It also adds their associated docs and tests.

## Credits

**Geometry Project:**
For code, docs and tests:
@novialriptide @Emc2356 @itzpr3d4t0r @ScriptLineStudios @avaxar @Matiiss @newpaxonian @maqa41 @blankRiot96
Also thanks to @Starbuck5 for kickstarting the idea and the occasional help!

**Functionality added in this PR**
- `geometry.pyi`
https://github.com/pygame-community/pygame-geometry/blame/main/geometry.pyi
Credits to @Emc2356 @itzpr3d4t0r @novialriptide @ScriptLineStudios @avaxar

- `geometry.rst`
https://github.com/pygame-community/pygame-geometry/blame/main/docs/line.rst
Credits to @Emc2356 @itzpr3d4t0r @ScriptLineStudios @avaxar

- `line.c`
https://github.com/pygame-community/pygame-geometry/blame/main/src_c/line.c
Credits to @Emc2356 @itzpr3d4t0r @novialriptide @ScriptLineStudios @avaxar

- `geometry.h`
https://github.com/pygame-community/pygame-geometry/blame/main/src_c/include/geometry.h
Credits to @Emc2356 @itzpr3d4t0r @maqa41

- `geometry.c`
https://github.com/pygame-community/pygame-geometry/blame/main/src_c/geometry.c
Credits to @Emc2356 @itzpr3d4t0r @novialriptide @ScriptLineStudios @avaxar

- `geometry_test.py`
https://github.com/pygame-community/pygame-geometry/blame/main/test/test_line.py
Credits to @Emc2356 @itzpr3d4t0r @novialriptide @ScriptLineStudios @avaxar

2024-09-29 10:15 UTC, damusss commented
_woah_

2024-09-29 10:20 UTC, damusss requested changes
In addition, is it really necessary to add a `..versionadded::` tag for every method and attribute? if the object was added in 2.5.2, it's kind of obvious that everything inside it was also added in the same version.

2024-09-29 10:20 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +    Sequence[Coordinate],
Unless you have another reasons, this should probably be `SequenceLike` from `pygame.typing`

2024-09-29 10:26 UTC, itzpr3d4t0r commented on buildconfig/stubs/pygame/geometry.pyi
> +    Sequence[Coordinate],
> In addition, is it really necessary to add a ..versionadded:: tag for every method and attribute? if the object was added in 2.5.2, it's kind of obvious that everything inside it was also added in the same version.

I don't believe this is accurate. 
It's unclear to state the object was added in 2.5.2 without specifying when each attribute was introduced. We, as developers, know exactly what was added through changelogs, but regular users rely solely on the documentation to see what they can use. How can someone be certain the attribute they want was added in 2.5.2 if it's not specified? In that case, they would only know the object was added in that version, not the attributes.

2024-09-29 10:27 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +    Sequence[Coordinate],
Fair enough I guess, sure

2024-09-29 10:47 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +    def __init__(self, first: Coordinate, second: Coordinate) -> None: ...
Minor nitpick which could just be related to the porting, but it makes more sense to me to call "first" and "second" "a" and "b", which is more consistent with the other init overload

2024-09-29 10:47 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +    def __init__(self, first: Coordinate, second: Coordinate) -> None: ...
BRO I sent while you committed that exact change, no way

2024-09-29 10:48 UTC, itzpr3d4t0r commented on buildconfig/stubs/pygame/geometry.pyi
> +    def __init__(self, first: Coordinate, second: Coordinate) -> None: ...
Just did that.

2024-09-29 10:49 UTC, damusss approved these changes
Nothing else comes to mind, LGTM, thanks :)

2024-10-05 09:07 UTC, MyreMylar commented on buildconfig/stubs/pygame/geometry.pyi
> +class _HasLineAttribute(Protocol):
```suggestion
_CircleValue = Union[_CanBeCircle, _HasCirclettribute]

class _HasLineAttribute(Protocol):
```

2024-10-05 09:08 UTC, MyreMylar commented on buildconfig/stubs/pygame/geometry.pyi
> +    copy = __copy__
```suggestion
```

2024-10-05 09:08 UTC, MyreMylar commented on buildconfig/stubs/pygame/geometry.pyi
> +
```suggestion
```

2024-10-06 09:11 UTC, MyreMylar commented on src_c/geometry.h
> -#define pgCircle_GETR(self) (pgCircle_CAST(self)->circle.r)
are these deletions intentional?

2024-10-06 09:12 UTC, MyreMylar commented on src_c/geometry.h
> -#define pgCircle_GETR(self) (pgCircle_CAST(self)->circle.r)
could be a merge error...

2024-10-06 09:14 UTC, itzpr3d4t0r commented on src_c/geometry.h
> -#define pgCircle_GETR(self) (pgCircle_CAST(self)->circle.r)
Yes, they're intentional. Better keep unused stuff to a minimum.

2024-10-06 09:22 UTC, MyreMylar approved these changes
OK, LGTM 👍 

Tests, docs & code seem fine and it all works locally. Good work! 💯

2024-10-08 12:51 UTC, damusss requested changes

2024-10-08 12:51 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeLine = Union[
This is just me being confused, would a tuple `(xa, ya, xb, yb)` be ok for a line? because it doesn't seem to get covered. also how can a `Rect` and `FRect` be considered lines? is it just because they are iterable, which will result in the line weirdly inheriting `xa=x, ya=y, xb=width, yb=height`? (if yes, perhaps it can be omitted in this union as already covered by `SequenceLike[float]` to avoid confusion).
Ok maybe it does get covered by `Point`, but I think you should actually be explicit with `SequenceLike[float]` because point is intended to be used as `(x, y)`, not a sequence with arbitrary length. If it was possible it would be annotated in the type itself but python doesn't allow it.

2024-10-08 19:26 UTC, itzpr3d4t0r commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeLine = Union[
Idk, I just wanted to be explicit about what you can pass and can be interpreted as a Line. Without that Rect/Frect people could randomly discover that and think it wasn't expected when infact it was a known thing all the time.

2024-10-08 19:34 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeLine = Union[
Alright then I'm only concerned about Point, because logically it doesn't make sense to create a line from a single Point, while SequenceLike[float] makes sense. I know Point and SequenceLike[float] are exactly the same, but their names convey different meanings, and Point isn't suited for this job.

About the degenerate thing, rather than removing it you could explicit the fact that is allowed but that some operations might not be available in that case. Not required of course, just my 2 cents about it!

2024-10-09 02:19 UTC, aatle commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeLine = Union[
It is best to remove `Rect` and `FRect` from the union (and give a warning in docs to prevent surprises).
Redundantly putting `Rect` in the union may mislead users into thinking that `Rect` is intuitively or specially supported, when this is not the case.

I agree that `SequenceLike[float]` should be used rather than `Point`. This construct is already being used for `RectLike`.

2024-10-09 02:21 UTC, aatle commented on buildconfig/stubs/pygame/geometry.pyi
> +    copy = __copy__
In accordance with a recent PR, the `copy` method should have the full type annotation for explicitness.

2024-10-09 02:30 UTC, aatle commented
Is there any specific reason why the coordinates are named with `xa`, `yb` instead of `ax`, `by`?
The current is annoying for me to parse mentally, as it looks backwards and the 'subscript' appears in front of the point.

2024-10-12 09:49 UTC, itzpr3d4t0r commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeLine = Union[
Alright, fixed that I suppose.

2024-10-12 09:53 UTC, damusss approved these changes
Alright thanks, changes LGTM

2024-10-12 10:11 UTC, merged