A simple implementation of `import pygame.debug`
pygame-community/pygame-ce pull request #3148
Opened 2024-10-06 16:10 UTC by MyreMylar

Was reading through PR #2944 and after seeing 43 files changed and looking over the original issue #2894 I thought perhaps it would be better to start with a smaller PR before building up to bigger systemic changes to warnings.

This PR does two things:

1. a python file called `debug.py` that imports pygame, prints the old support prompt and the output of `.print_debug_info()` and sets the python warning filter level to `default` which is what it is at the moment in pygame.
2. removes the support prompt printing from `import pygame` and sets the default python warnings filter level for python to "ignore".

I'm not sure this is exactly what we want, but has the benefit of being small and an easier place to start a point of discussion.

Test programs:

1. Produces no console output.
```python
# without debug information - "normal mode"
import pygame

pygame.init()

red_colour = pygame.Color("#FF0000")
red_colour.set_length(2)
```

2. Produces 19 lines of output.
```python
# with debug information - "debug mode"
import pygame.debug

pygame.init()

red_colour = pygame.Color("#FF0000")
red_colour.set_length(2)
```

Output of 2.
```
pygame-ce 2.5.2.dev1 (SDL 2.30.7, Python 3.11.1)
Platform:		Windows-10-10.0.22631-SP0
System:			Windows
System Version:		10.0.22631
Processor:		AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD	SSE2: Yes	AVX2: Yes	NEON: No
Architecture:		Bits: 64bit	Linkage: WindowsPE

Python:			CPython 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
pygame version:		2.5.2.dev1
SDL versions:		Linked: 2.30.7	Compiled: 2.30.7
SDL Mixer versions:	Linked: 2.8.0	Compiled: 2.8.0
SDL Font versions:	Linked: 2.22.0	Compiled: 2.22.0
SDL Image versions:	Linked: 2.8.2	Compiled: 2.8.2
Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1

Display Driver:		Display Not Initialized
Mixer Driver:		Mixer Not Initialized
C:\Users\dan\Programming\scrap\circles_testing.py:6: DeprecationWarning: pygame.Color.set_length deprecated since 2.1.3
  red_colour.set_length(2)
```

2024-10-06 17:18 UTC, MyreMylar commented on src_py/__init__.py
> +warnings.filterwarnings("ignore")
I'd like to only ignore/filter warnings generated somewhere in pygame code here but that is impossible to do with warnings from C code that populate up to users as they don't have a module attribute attached.

This is where a custom pygame warning system would come in as it would enable us to filter out/filter in warnings from pygame C code.

2024-10-06 17:46 UTC, MyreMylar commented
Tinkered around with supressing deprecation warnings as part of this - but it is difficult to do in a sensible way as you can only supress python warnings by where the offending code originates, and deprecation warnings come, generally, from users using deprecated code.

2024-10-06 18:07 UTC, MyreMylar commented
What we might be able to do fairly easily is add a specific custom python warning category that we can then filter in, or filter out by default using `PyErr_NewException("pygame.PygameWarning", PyExc_Warning, NULL)` without messing with warnings from other modules.

See an example here: https://github.com/danos/pygobject/blob/6372b569b1a9b6499ba73775350c8420017a1992/gi/gimodule.c#L684

2024-10-06 19:00 UTC, MyreMylar commented
I added a new warning type that is only active when pygame.debug is imported. Currently nothing uses it.

2024-10-06 19:03 UTC, damusss commented
not too sold on the name. `pygame.error` isn't named `pygame.PygameError`, perhaps this should be called `pygame.DebugWarning`?

2024-10-06 19:11 UTC, MyreMylar commented
> not too sold on the name. `pygame.error` isn't named `pygame.PygameError`, perhaps this should be called `pygame.DebugWarning`?

I thought that initially, but only the second part on the string actually prints to the console if you create one, the first part is just the module name and in this case we actually want it to be clear it is a pygame only type of warning not a generic one that may collide or overlap with warnings from other modules.

2024-10-09 09:40 UTC, gresm requested changes
Besides minor notes, it would be nice if ``pygame.debug`` was documented and not a private, obscure submodule. You can just copy the changes from my PR (requires alteration), but otherwise I like this solution.

2024-10-09 09:40 UTC, gresm commented on buildconfig/stubs/mypy_allow_list.txt
> +pygame\.debug
My guess that this change is here is that there's no ``debug.pyi`` stub, correct?

2024-10-09 09:40 UTC, gresm commented on src_py/debug.py
As of currently, using:
```py
import pygame.debug
pygame.do_stuff()
```
Works, as also:
```py
import pygame.debug
import pygame as pg
from pygame import do_stuff

pg.do_stuff()
do_stuff()
```
But not:
```py
import pygame.debug as pg
from pygame.debug import do_stuff

pg.do_stuff()
do_stuff()
```
What's your stance on this? If the last behavio(u)r is desired, adding
```py
from pygame import *
```
Or
```py
def __getattr__(name):
    return getattr(pygame, name)

def __dir__():
    return dir(pygame)
```
Should suffice, but if doing so, the ``debug.pyi`` stub should be created (edit ``buildconfig/stubs/gen_stubs.py`` to copy ``__init__.pyi`` stub).

2025-08-26 15:49 UTC, closed without merging