Minor fixes and changes to `geometry.pyi` stub file
pygame-community/pygame-ce pull request #3172
Opened 2024-10-13 06:49 UTC by aatle

Improved some stuff.
- Change has-attribute protocols to use properties (to fix typing problems)
- Remove type unions `_CanBeCircle`, `_CanBeLine`. These internal types provide little benefit, and a similar union `_CanBeRect` was removed previously.
  - This has one minor effect: the circle attribute can now be another object with a circle attribute, recursively (which reflects actual implementation)
- Rename `_CircleValue` -> `_CircleLike`, `_LineValue` -> `_LineLike`, to be consistent with `RectLike`, adhere to naming scheme.
- Fix name typo `_HasCirclettribute` -> `_HasCircleAttribute`
- Remove redundant `Vector2` type from `_CanBeCollided`. `Vector2` is clearly implied by `Point`.
- Mark `Circle.contains(shape)` parameter positional-only
- Format

2024-10-13 07:05 UTC, damusss requested changes

2024-10-13 07:05 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
I am not sold on this removal. I know Vector2 is covered by Point but leaving it here even if redundant could be nice to remind users that vectors are allowed and perhaps suggest them to use them. Not too many people are aware that a Vector2 is a compatible sequence so they might convert it to a list out of habit without trying to pass it to any function if they don't see it there.

2024-10-13 16:33 UTC, aatle commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
If `Vector2` would have to be included in this type union along with `Point` for clarity, then every use of `Point` should also be annotated with `Vector2` by that logic.

I think we can trust that typing users (mostly intermediate to advanced) already understand usage of `Point`/`SequenceLike[float]` (a very common type that is documented to include `Vector2`).

2024-10-13 16:36 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
Alright, I'm 51% convinced so I'm going to approve it.

2024-10-13 16:36 UTC, damusss approved these changes
LGTM, thanks

2024-10-14 05:34 UTC, ankith26 commented on buildconfig/stubs/pygame/geometry.pyi
> +    def circle(self) -> Union[_CircleLike, Callable[[], _CircleLike]]: ...
This is forward referencing `_CircleLike`. I believe this could be problematic on older python versions. But I'm not sure if this is problematic only on source files and if this won't be a problem on stubs.

2024-10-14 05:34 UTC, ankith26 commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
```suggestion
_CanBeCollided = Union[_CircleLike, RectLike, Point]
```
I haven't really checked the code, but I think this typing is more accurate

2024-10-14 23:52 UTC, aatle commented on buildconfig/stubs/pygame/geometry.pyi
> +    def circle(self) -> Union[_CircleLike, Callable[[], _CircleLike]]: ...
I've already checked and raw forward references are used liberally in the type stubs (except `typing.pyi`).
The most common forward reference use is for methods that return an instance of their own class.

(*All* python versions would raise an error when encountering a raw forward reference at runtime.)

2024-10-14 23:53 UTC, aatle commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
The collide methods that use this type union want only concrete types according to the docs, in order to be able to distinguish between different shape types.

2024-10-16 10:04 UTC, ankith26 commented on buildconfig/stubs/pygame/geometry.pyi
> +    def circle(self) -> Union[_CircleLike, Callable[[], _CircleLike]]: ...
Yeah that makes sense

2024-10-16 10:08 UTC, ankith26 commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
Maybe the docs are wrong as well. The code uses API like `pgFRect_FromObject` and `pgCircle_FromObject` to all input which don't expect concrete types. Though it would be nice if any geometry authors review this PR.

2024-10-16 12:16 UTC, damusss commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
> Maybe the docs are wrong as well. The code uses API like `pgFRect_FromObject` and `pgCircle_FromObject` to all input which don't expect concrete types. Though it would be nice if any geometry authors review this PR.

![image](https://github.com/user-attachments/assets/fb7ba29d-a6cb-4dce-b532-af23d857b4bf)

I have to disagree as the collision methods for circle actually use `pgRect_Check` and `pgCircle_Check`. Which makes sense, because a random sequence of 4 or 3 numbers cannot be mapped to the right shape arbitrarly, so the stubs are actually correct.

2024-10-17 05:04 UTC, ankith26 commented on buildconfig/stubs/pygame/geometry.pyi
> +_CanBeCollided = Union[Circle, Rect, FRect, Point]
True, I was looking at `colliderect` when I made my previous comment and that handles any rect-ey argument. And that is already typed as `RectLike` in the stubs, so that's all good.

I still think `_CanBeCollided` should be made more general but then that is definitely out of scope for this PR as it would require code, docs, test changes.

2024-10-17 05:06 UTC, ankith26 approved these changes
LGTM, thanks for the PR :partying_face:

2024-10-17 05:06 UTC, merged