Fix grammar in window.rst
pygame-community/pygame-ce pull request #3194
Opened 2024-10-26 13:38 UTC by gavinmorrow

2024-10-26 13:48 UTC, bilhox requested changes

2024-10-26 13:48 UTC, bilhox commented on docs/reST/ref/window.rst
> +   the window. Note that the event ``QUIT`` will only be sent if all Windows
if it's plurial, then it should not be capitalized as well.

2024-10-26 14:01 UTC, oddbookworm commented on docs/reST/ref/window.rst
> +   the window. Note that the event ``QUIT`` will only be sent if all Windows
I would actually suggest doing something like this instead
```rst
\`\`Window\`\`s
```

2024-10-26 15:27 UTC, gavinmorrow commented on docs/reST/ref/window.rst
> +   the window. Note that the event ``QUIT`` will only be sent if all Windows
I was trying to follow the example of the rest of the file, where Window is capitalized (including plurals). In the [`Surface`](https://pyga.me/docs/ref/surface.html#:~:text=Normal%20Surfaces%20should%20not%20require%20the%20masks%20argument) docs, the same convention is followed.

2024-10-29 10:53 UTC, gavinmorrow commented on docs/reST/ref/window.rst
> +   the window. Note that the event ``QUIT`` will only be sent if all Windows
@bilhox @oddbookworm what do you think?

2024-10-30 15:16 UTC, bilhox commented on docs/reST/ref/window.rst
> +   the window. Note that the event ``QUIT`` will only be sent if all Windows
@gavinmorrow I would follow what oddbookworm suggested.

2024-10-31 06:18 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada:

2024-10-31 18:00 UTC, zoldalma999 approved these changes
LGTM, Thanks!

2024-10-31 18:01 UTC, merged

2024-11-02 23:18 UTC, gavinmorrow commented
It looks completely wrong, does anyone know why? I'm not familiar with `.rst`.

<img width="660" alt="Screenshot 2024-11-02 at 19 16 25" src="https://github.com/user-attachments/assets/d41cf2ad-4acc-45bc-b170-d14ee71ec2e8">

2024-11-02 23:18 UTC, gavinmorrow commented
oh yeah didn't see #3205