New functions :  Vector2.angle and Vector2.angle_rad and the tests and documentation needed
pygame-community/pygame-ce pull request #3216
Opened 2024-11-07 13:06 UTC by AntoineMamou

As explains in this issue : https://github.com/pygame-community/pygame-ce/issues/3195, I added the two functions `angle` and `angle_rad` in the module Vector2. 
`angle_rad`: Returns the vector’s angle in radians relative to the positive x-axis.
`angle`: Returns the angle in degrees, normalized to (180,180].

I also created tests and documentation for these two functions

2024-11-07 13:29 UTC, oddbookworm requested changes
I’d rather see these implemented as attributes vs methods. There’s also a discussion to be had about how it should work for `Vector3` because we should have parity in features between the two as much as possible

2024-11-07 14:12 UTC, AntoineMamou commented
Ok, I'll try to modify my code and create attributes and not methods and wait for how the Vector3 features should work.

2024-11-07 14:18 UTC, damusss commented on src_c/math.c
> +    return Py_BuildValue("d", angle_deg);
Why have you used Py_BuildValue here and PyFloat_FromDouble in the other function? I feel like they should both use the latter. also, I feel like there are a few unnecessary declarations that could be avoided reducing a bit the lines, if that doesn't decrease readability too much (but formatting the code might bring it back)

2024-11-07 15:19 UTC, AntoineMamou commented on src_c/doc/math_doc.h
> +#define DOC_MATH_VECTOR2_ANGLERAD "angle_rad() -> float\nreturns the angle of the vector in radians relative to the positive X-axis."
Sorry, I'm new so I didn't know that. I'm going to fix that. But I don't understand what this macros is doing if it's not to create a doc.

2024-11-07 15:26 UTC, AntoineMamou commented on src_c/math.c
> +    return Py_BuildValue("d", angle_deg);
Yes you are right. Because I begin in this project, I saw that there is these two function and I try it both. Since it works, I didn't see the problem but if both should use PyFloat_FromDouble, it's ok.

2024-11-07 17:00 UTC, oddbookworm commented on src_c/doc/math_doc.h
> +#define DOC_MATH_VECTOR2_ANGLERAD "angle_rad() -> float\nreturns the angle of the vector in radians relative to the positive X-axis."
@AntoineMamou for the docs header, did you not read the first line of the file? Where it says it's autogenerated from the actual docs?

2024-11-07 17:01 UTC, oddbookworm commented on src_c/doc/math_doc.h
> +#define DOC_MATH_VECTOR2_ANGLERAD "angle_rad() -> float\nreturns the angle of the vector in radians relative to the positive X-axis."
Which part of my comment do you want to push off to another PR?

2024-11-11 14:39 UTC, AntoineMamou commented on src_c/doc/math_doc.h
> +#define DOC_MATH_VECTOR2_ANGLERAD "angle_rad() -> float\nreturns the angle of the vector in radians relative to the positive X-axis."
I was just thinking about the attributes `angle` and `angle_rad`

2024-11-27 10:21 UTC, AntoineMamou commented on test/rect_test.py
Hello,

No, not at all. This was a mistake I made because I was working on an other issue at that time. By the way, this PR should be close I think because it's this PR that is link to the issue of `.angle` and `.angle_rad` : https://github.com/pygame-community/pygame-ce/pull/3222

2024-11-27 11:57 UTC, closed without merging

2024-11-27 11:57 UTC, ankith26 commented
Closing this PR in favour of the newer PR #3222 made by OP