Add `Window.wm_info`
pygame-community/pygame-ce pull request #3219
Opened 2024-11-10 15:17 UTC by damusss

Window manager information and especially the window handle were only accessible to the display module. I feel like you should know the window handle of any window, so I added the property. The return value almost perfectly mimics the display one, but it can change of course since this would be new api.

MRE:
```py
import pygame

D = True
if D:
    screen = pygame.display.set_mode((300, 300))
else:
    win = pygame.Window("test", (300, 300))

while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit

        if e.type == pygame.KEYDOWN:
            if D:
                print(pygame.display.get_wm_info())
            else:
                print(win.wm_info)

    if D:
        screen.fill(0)
        pygame.display.flip()
    else:
        win.get_surface().fill(0)
        win.flip()

```

2024-11-10 15:52 UTC, ankith26 requested changes
`SDL_syswm.h` header is removed in SDL3. The way to access the wm info has also changed, and I believe that also changes what values are exported by the SDL side.

I think that going forward any new API added should be SDL3 style, and any thing in the grey area should not be exported at all.

2024-11-10 15:54 UTC, damusss commented
> `SDL_syswm.h` header is removed in SDL3. The way to access the wm info has also changed, and I believe that also changes what values are exported by the SDL side.
> 
> I think that going forward any new API added should be SDL3 style, and any thing in the grey area should not be exported at all.

Alright, good to know. I'll study the new system that SDL3 uses and adjust the Window code for it. I believe I should keep the SDL2 version (unless it has more dictionary keys than sdl3 will support) so it can be added before pygame 3.

2024-11-10 16:50 UTC, damusss commented
@ankith26 @Starbuck5 
the most recent commit adds a codepath for SDL3. I removed the dictionary keys from the SDL2 codepath that weren't accessible in SDL3. My only limitations:
- I have no idea on how to test the SDL3 codepath
- I got confused sometimes. because I tried to be close to the sdl2 codepath, but sometimes` PyLong_FromLong` was used when the returned value was a pointer, instead of using `PyCapsule_New`. So I'd like to know if what I did is correct, as I assume the checks won't tell me anything

2024-11-18 17:15 UTC, ankith26 commented
Perhaps this PR should wait for the "port window to SDL3" PR to be made and merged first

2024-11-18 17:17 UTC, damusss commented
> Perhaps this PR should wait for the "port window to SDL3" PR to be made and merged first

I suppose that makes sense. Do you need special competence to pull off one of those PRs, or is it just about following the migration guide (and making different codepaths/creating compat macros)? (if so, I could even try to make it, otherwise I'll wait for you or starbuck). :)

2024-11-22 16:41 UTC, ankith26 commented
We do test that the patch compiles on SDL3. It can be done locally, but you have to compile SDL3 from source if you are gonna go the WSL way (don't worry, it's not that hard). BTW, we also have SDL3 CI now that can do the testing on windows+mac+linux.

Basically the thing is we are yet to figure how to properly deal with the pixelformat changes uniformly, once that is done we can apply the same strategy everywhere and port the next wave of modules

2024-11-22 17:33 UTC, ankith26 commented
Well actually, `Window` is not blocked by pixelformat changes, I am working on porting it to SDL3 rn

2024-11-22 18:00 UTC, damusss commented
Alright then, nice, thanks

2024-12-19 07:17 UTC, Starbuck5 commented
So even if this code works great on SDL3, why should we expose new API in the SDL2 style?

2024-12-20 06:28 UTC, damusss commented
> So even if this code works great on SDL3, why should we expose new API in the SDL2 style?

We don't have to expose it in a SDL2 style, but the window manager information is very dependent on the os so how would you provide the info without a dictionary?

2024-12-20 08:10 UTC, Starbuck5 commented
Having something called "wm info" is clearly an SDL2 construction. Well, looking at the SDL code you have it looks like they expose it now as properties on the window object itself.

2024-12-20 08:31 UTC, Starbuck5 commented
I have marked as a draft, because with uncertainty about API as well as merge conflicts this is not ready to merge.

2024-12-20 09:07 UTC, damusss commented
> Having something called "wm info" is clearly an SDL2 construction. Well, looking at the SDL code you have it looks like they expose it now as properties on the window object itself.

That's true, but each property is going to exist or not based on the OS and window manager. they are not generic properties that belong to almost every window like a position and a size. The dictionary reflects how uncertain the attributes are to exist. plus they are all very low lever, so putting them besides common attributes would look "ugly" imo.

2025-01-05 13:45 UTC, damusss commented
Ok, this API was kinda ugly so I replaced it with `Window.handle`. it's always an integer, casting pointers to `size_t`. 0 on error. This brings more freedom of Window from display. The rest of the display info can still use the old display function, the handle is the only real thing that needs to be added to Window. New MRE:
```py
import pygame

DISPLAY = True
if DISPLAY:
    screen = pygame.display.set_mode((500, 500))
else:
    win = pygame.Window(size=(500, 500))
    screen = win.get_surface()
clock = pygame.Clock()
while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT or e.type == pygame.WINDOWCLOSE:
            pygame.quit()
            raise SystemExit
        if e.type == pygame.KEYDOWN:
            if DISPLAY:
                print(pygame.display.get_wm_info()["window"])
            else:
                print(win.handle)
    clock.tick(60)
    if DISPLAY:
        pygame.display.flip()
    else:
        win.flip()

```

2025-03-15 11:39 UTC, damusss commented
I fixed the merge conflict and I also made sure that Window.handle compiles with SDL3 and returns the proper window handle (I modified window.c to be able to create a window with SDL3 so I could call the property). This is now ready to review.

2025-06-07 11:49 UTC, ankith26 commented
Is there any other usecase for this apart from diagnostics? We probably discussed this already but just so that it's on github - these handle numbers could potentially be useful for embedding foreign windows in pygame-ce or vice-versa. It is probably going to be very platform/configuration specific though. 
`pygame.display` windows currently support `SDL_WINDOWID` based embedding already but there is no equivalent in the `Window` constructor.

2025-06-07 11:51 UTC, damusss commented
@ankith26 I would say the usecase is using low level functionality of the OS that can do something if they know the window pointer. If you want, I can rename this to `_handle`, similar to `Surface._pixels_address`. How does that sound?

2025-07-06 03:03 UTC, damusss commented
Looks like there are people that desire the handle:
https://discord.com/channels/772505616680878080/822265298085347368/1391179936311803965
and from my questions it looks like you can't achieve the same result by not using the handle.

2025-08-25 13:27 UTC, MyreMylar approved these changes
This seems to make sense to me based on long ago fiddling with window embedding. I'm happy to allow it and then see if there is demand for any other platform specific window properties with defined use cases as we go along.

The way windows are handled is very platform specific in the details and each platform has it's own selection of identifiers that we are unlikely to be able to abstract perfectly to interface with other library code. You can see SDLs `SDL_GetWindowProperties()` just returns a group of identifiers that differ per platform.

Anyway, approved. 👍

2025-10-16 12:37 UTC, zoldalma999 approved these changes
Added a small comment, but apart from that both API-wise and implementation wise it looks good to me. However I would maybe wait for one or two more approvals, because it is new API.

2025-10-16 12:37 UTC, zoldalma999 commented on buildconfig/stubs/pygame/window.pyi
> +        .. versionaddedold:: 2.5.4
This should be normal versionadded, and version should be 2.5.7.

2025-10-16 12:39 UTC, damusss commented on buildconfig/stubs/pygame/window.pyi
> +        .. versionaddedold:: 2.5.4
Good catch! I'll commit as soon as I can

2025-10-17 08:16 UTC, damusss commented on src_c/window.c
> +    }
Crazy catch

2025-10-17 08:49 UTC, damusss commented on src_c/window.c
> +
Each union access is guarded by a directive check. The system info struct is defined using the same directives, so checking subsystem seems redundant.

2025-10-17 08:52 UTC, damusss commented on src_c/window.c
> +#endif
I will fix it, but the first stable release of SDL3 is 3.2.0, meaning SDL 3.1.0 isn't really a thing.

2026-03-07 21:33 UTC, zoldalma999 approved these changes
Still looks good to me (apart from the now outdated versionadded note in the docs).

2026-03-29 23:44 UTC, oddbookworm approved these changes
LGTM! Assuming @ankith26 is happy with the changes, I would like to get this merged

2026-04-02 07:16 UTC, ankith26 approved these changes
Yeah, I'm fine with this PR. Thanks! 🍰

2026-04-02 07:16 UTC, merged