new angle and angle_rad property in vector2
pygame-community/pygame-ce pull request #3222
Opened 2024-11-12 17:43 UTC by AntoineMamou

This PR follows this one : https://github.com/pygame-community/pygame-ce/pull/3216

I make the changes needed and add two properties : 
`angle_rad` : Returns the vector’s angle in radians relative to the positive x-axis.
`angle` : Returns the angle in degrees, normalized to (180,180].

2024-11-12 18:20 UTC, oddbookworm requested changes
Needs documentation, and there are a few issues I see offhand

2024-11-12 18:20 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
I’d rather an exception get raised here. The zero vector is special and getting it’s angle makes no sense

2024-11-12 18:20 UTC, oddbookworm commented on src_c/math.c
> +    pgVector *vec = (pgVector *)self;
Why this cast to the type it already is?

2024-11-12 18:20 UTC, oddbookworm commented on src_c/math.c
> +    if (angle > 180.0) {
Make constants instead of reusing the same hardcoded numbers

2024-11-12 18:20 UTC, oddbookworm commented on src_c/math.c
> +vector_get_angle_rad(pgVector *self, void *closure)
Just reuse the function you already have instead of writing the same code twice. Since you already got the output in a form you like, just convert it from degrees to radians

2024-11-12 18:20 UTC, oddbookworm commented on src_c/math.c
> +    {"angle", (getter)vector_get_angle, NULL, NULL, NULL},
Missing the docs component of these structs, which should be generated in the docs header, which is generated from the documentation updates you need to make

2024-11-13 07:31 UTC, AntoineMamou commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
ok, I thought it should be 0 because of the initial issue https://github.com/pygame-community/pygame-ce/issues/3195, but I can change and raise an exception

2024-11-13 10:08 UTC, oddbookworm commented on src_c/math.c
> +    {"angle", (getter)vector_get_angle, NULL, NULL, NULL},
No, you need to add to math.rst

2024-11-13 10:09 UTC, oddbookworm commented on src_c/math.c
> +    {"angle", (getter)vector_get_angle, NULL, NULL, NULL},
Yes

2024-11-13 17:24 UTC, AntoineMamou commented on src_c/math.c
> +    {"angle", (getter)vector_get_angle, NULL, NULL, NULL},
Hello @oddbookworm, I have a question about the building of the docs. When I try to build the docs I add in math.rst, I get two new lines in math_doc.h, which is what I want. However I get this : 
```
#define DOC_MATH_VECTOR2_ANGLE ""
#define DOC_MATH_VECTOR2_ANGLERAD "" 
```

However, I try to add a short descriptive sentence like this : 
```
| :sl: `Gives the angle of the vector in degrees, relative to the X-axis, normalized to the interval (-180, 180].`
```
Is this normal ?

2024-11-14 01:44 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
@oddbookworm 
I strongly think the angle properties should be consistent with the existing behavior of `.as_polar()`, `.angle_to()`, `.rotate()` and more importantly [python `math.atan2()`](https://github.com/python/cpython/blob/9a3ffc0492d1310ead9ce8f5ee678c26b20a338d/Modules/mathmodule.c#L591) (which is based off the a C standard) and polar coordinates.
These functions don't raise errors and (for not `nan` args) don't return `nan`, and most actually do not document this special case.

2024-11-14 01:54 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
I still don't agree that we should silently just say the angle of the zero vector is zero. I don't like those functions treating that special case in the way they do either. And actually, the C standard **does not** guarantee that `atan2(0, 0)` returns 0. Here's a snippet from the C standard
![image](https://github.com/user-attachments/assets/5710923f-92bd-4ab6-9e99-9d13fa8a758f)

2024-11-14 02:02 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
One reason I hate that behavior is because it can lead to very confusing behavior. Consider the case where you're just continuously scaling down a vector without changing it's direction. At some point, you'll go from a constant angle to 0, regardless of what the starting angle is.

2024-11-14 02:07 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
From what I gathered from my sources including [this](https://stackoverflow.com/questions/55037585/is-it-safe-to-assume-that-atan20-0-returns-0) and [this](https://stackoverflow.com/questions/47909048/what-will-be-atan2-output-for-both-x-and-y-as-0) and [this](https://en.wikipedia.org/wiki/Atan2#Realizations_of_the_function_in_common_computer_languages), at least some sort of standard.
Silently saying the angle of the zero vector is zero (or even `pi` or `-pi` as is in some of the functions' behavior) is not really that bad because if the magnitude is 0, then the angle practically doesn't even matter (in contrast with `scale_to_length` which actually needs it). The polar coordinates `(0.0, x)` represent the origin for all x.
I think an error (or `nan`) is worse, for reasons which I will explain.

2024-11-14 02:13 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
> At some point, you'll go from a constant angle to 0, regardless of what the starting angle is.

Setting the length to 0 (or continuously scaling down, in which case using `scale_to_length` must be special cased anyway) inevitably loses the angle data, and an undocumented angle is as valid to use as an error.
Most of the time, when a zero vector is involved, the angle does not matter so it is better to *not* raise an error and instead give a valid value. Since the magnitude is 0, any finite value including 0.0 is a valid angle to represent the zero vector.
For practicality reasons and consistency, the angle getter and setter shouldn't raise an error.

2024-11-14 02:39 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
I disagree. If literally any answer makes as much sense as any other, we should not assert any answer IMO. As for implementing per Annex F as your sources indicate, the second one in particular actually shows the relevant content of that annex, which is more complex than just "return 0". It actually can return +0, -0, +pi, -pi technically per that annex (but of course, annexes are just suggestions, they're not a mandatory part of the spec). But it's ultimately implementation-specific. You also don't need to use `scale_to_length` either to scale a vector down. It has the `*` and `/` operators defined on it. I can create this behavior with a bit of fiddling with the boundaries of what doubles will allow (on my system with my installed python)
![image](https://github.com/user-attachments/assets/0ec10030-473b-4e9f-afa0-744b68bbfc5b)

2024-11-14 02:39 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
```python3
import pygame

pygame.init()

window = pygame.Window()
screen = window.get_surface()

my_vector = pygame.Vector2(30, 43)
print(f"Starting angle: {my_vector.angle}")

SCALE_FACTOR = 0.1

running = True
shrinking = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    if shrinking and my_vector.x > 5e-324:
        my_vector *= SCALE_FACTOR
        print(f"New angle (shrinking): {my_vector.angle}, {my_vector}")
    elif my_vector.length() < 100:
        shrinking = False
        my_vector /= SCALE_FACTOR
        print(f"New angle (growing): {my_vector.angle}, {my_vector}")
```

2024-11-14 02:44 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
And it's not even 100% consistent with itself. This came from the same code
![image](https://github.com/user-attachments/assets/cc2d01c6-00b8-475a-a856-59605e9ac82d)

2024-11-14 02:57 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
I believe your example (of using the angle of a scaled vector instead of other way around) is uncommon and already bad to implement by itself because of floating point limits. The zero vector itself does not have to be reached for the angle to change because the design of the code encounters imprecision. If one were to actually hit the zero vector and face the special behavior, they wouldn't even be able to grow it back.

We do not have to assert any answer. Like python `atan2`, it can be left undocumented but still give a value instead of an error, even if its implementation specific (which we can prevent).
The point is, using an error is worse than an arbitrary but valid angle, for various reasons. Mathematically, this isn't even really bad.

2024-11-14 02:59 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
How is raising an error worse than giving an undocumented result? At least an error gives the user some kind of feedback that maybe something went wrong rather than just silently accept that the user knows what they're doing (which is never a given)

2024-11-14 03:16 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
First, mathematically it is okay to give e.g. 0.0 for the angle. All vectors with a magnitude of 0 are equivalent regardless of their direction, and polar coordinates needs the origin anyway. Imagine if the vector were to be implemented with magnitude + direction internally instead of components.

Having a possible error for getting or setting an `angle` is *very* annoying and would create *rare* crashes, cases that would most likely be better off having a defined and even undocumented angle for the zero vector.
One thing is that the angle is a property and is essentially an attribute. Nobody likes it when their attribute accesses raise a `ValueError` depending on the contents of the object.

Second, using a valid angle for it is superior as default behavior than raising an error. Imagine an unknowing user, implementing something that requires the angle between two points. When the two points are equivalent which is very rare, 99% of cases you want it to give any angle instead of blowing up and necessitating extra code checks.
My pymunk code would be exploding if its `Vec2d` gave an error for the angle of the zero vector, and much more error-prone.

2024-11-14 03:31 UTC, oddbookworm commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
Mathematically, ***anything*** is acceptable because it's undefined. 0 is just as valid as 180 degrees/pi radians. That doesn't mean we ***should***. All polar vectors of magnitude 0 are equivalent, regardless of their angle. If you have a vector defined with `r=0`, then `theta` does not matter at all. There's absolutely no rule in math that it ***must*** be 0, because that's nonsense. It doesn't make sense at all to even talk about the angle of the zero vector.

No, I 100% disagree that having an undocumented return in one special case is better than actually requiring the user to be responsible. We are a graphics library (plus other stuff). That's not our job. If we were an actual game engine that abstracted that away, then sure. But we're not. Our own opinions should not make it into the library. Be explicit. Make the user validate that their thing makes sense. Also, I will not support setting angle using these methods. Read-only attribute. If you need to set the angle, do it properly using the components or one of the rotate methods.

"Superior" is subjective. IMO the superior thing to do would be to check if the two points are the same before even thinking about getting the angle between them. Give me one good use-case where not checking that beforehand is overly burdensome to the user. I think in most cases, it would actually allow for short-circuits in code. Location and destination are the same? Don't do anything then. Easy. Fast. Error-free.

2024-11-14 03:55 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
Continuing the discussion on discord

2024-11-16 13:17 UTC, AntoineMamou commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
Hello @aatle and @oddbookworm, 
I saw on discord that there is many vision for what should be done for the zero vector. And I wanted to know if people agree on one of these in order to maybe change my code

2024-11-16 13:18 UTC, AntoineMamou commented
I see that two checks were not successful but I don't understand why. Can someone help me ?

2024-11-17 00:43 UTC, aatle commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
Hi @AntoineMamou, it has been settled that we will imitate python's `math.atan2()` function behavior. (Returns certain value depending on sign of zeroes, for zero vector.)
See https://github.com/python/cpython/blob/ed81971e6b26c34445f06850192b34458b029337/Lib/test/test_math.py#L327 for the relevant test cases.
Here's the old CPython 3.7.2 implementation for special cases (I can't find the most recent implementation): https://github.com/python/cpython/blob/v3.7.2/Modules/mathmodule.c#L566-L600

2024-11-17 13:35 UTC, AntoineMamou commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
Hi @aatle, so if we want to imitate math.atan2(), for the case where x=y=0, it should return 0, right ?

2024-11-17 13:38 UTC, AntoineMamou commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
And I'm using atan2 to find the angle, so basically I can skip the if  statement ?

2024-11-17 13:38 UTC, AntoineMamou commented on src_c/math.c
> +        return PyFloat_FromDouble(0.0);
Maybe I'm missing something here

2024-11-22 06:58 UTC, aatle commented on buildconfig/stubs/pygame/math.pyi
> +    angle_rad: float
```suggestion
    @property
    def angle(self) -> float: ...
    @property
    def angle_rad(self) -> float: ...
```
These are properties and they are read-only.

2024-11-22 07:05 UTC, aatle commented on docs/reST/ref/math.rst
> +      the interval (-180, 180].
My mistake, the interval is actually inclusive of -180. So, `[-180, 180]`

2024-11-22 07:07 UTC, aatle commented on docs/reST/ref/math.rst
> +      Usage: Accessing `angle` provides the current angle of the vector in degrees within the specified range.
Reword "specified range". The word 'specified' implies that the user provides it.

2024-11-22 07:24 UTC, aatle commented on src_c/math.c
> +    }
Seems unnecessary. The radians is within `[-pi, pi]`, so the degrees will be within `[-180, 180]`.

2024-11-22 07:56 UTC, aatle commented on src_c/math.c
> +vector_get_angle_rad(pgVector *self, void *closure)
I would suggest creating a helper function `_pg_atan2` that takes doubles and returns double. That way, one doesn't have to convert back to double and then to pyobject when doing more operations on it.

2024-11-22 09:02 UTC, AntoineMamou commented on buildconfig/stubs/pygame/math.pyi
> +    angle_rad: float
`@property` doesn't say that it's a read-only attribute, right ?

2024-11-22 09:46 UTC, AntoineMamou commented on src_c/math.c
> +vector_get_angle_rad(pgVector *self, void *closure)
Where I should make the documentations for `_pg_atan2` ?

2024-11-30 00:30 UTC, aatle approved these changes
LGTM.
Thanks for implementing my feature request.

2025-01-12 05:32 UTC, aatle commented on docs/reST/ref/math.rst
> +
need to document `versionadded` e.g.
```reST
.. versionadded:: 2.5.x
```

2025-01-15 17:18 UTC, damusss commented on docs/reST/ref/math.rst
> +
> Should this be `.. versionadded:: 2.5.3` ? I'm not sure about which version I should put.

yes 👍

2025-01-27 13:03 UTC, LittleBread69 approved these changes
Legitimate.
Had no issues running it on MacOS 15.1 with python3.12 and python3.10 .

2025-03-23 18:05 UTC, ankith26 reviewed
Hi, sorry for taking a while to get to this proposal.

Personally I really like the overall idea. Definitely +1 for keeping it as a property. A couple of things to discuss
- Do we really need both `angle` and `angle_rad`? Yes, I can understand why it was done (consistency with other vector methods), but because this is a new property, we can consider dropping one of these. I'm just putting this idea up for discussion, personally have no opinion here
- Why restrict it to read only property? I can imagine that setting an angle without changing magnitude would be a useful feature as well. Though that could be a separate follow up PR too.

Again, thanks for taking up this proposal and contributing to pygame-ce

2025-04-24 01:12 UTC, aatle commented
To answer those questions,
Yes, we need both `angle` and `angle_rad`. Degrees is not droppable. Radians is very useful with many mathematical properties and a relation to trigonometric functions. Because of this, radians is often used instead of degrees in many places: physics engines, math/science, etc.
It has been implemented as a read-only property at @oddbookworm's [request](https://github.com/pygame-community/pygame-ce/pull/3216#pullrequestreview-2420984544), the reasoning given on Discord as:
> If you want to change the vector, you do it component-wise or use the other methods available.

I guess since it is a property, it may be appropriate to allow setting; however, there should be a non-inplace equivalent. This functionality can be always be added in a later PR though.

2025-05-21 06:45 UTC, ankith26 commented on docs/reST/ref/math.rst
> +      the interval (-180, 180].
For what case would it return -180? Shouldn't it just return 180 in that case because essentially they are the same thing?

2025-05-21 17:37 UTC, aatle commented on docs/reST/ref/math.rst
> +      the interval (-180, 180].
The case of `math.atan2(-0.0, -1.0)` returns `-pi` due to special edge cases: the sign of y is copied to the result here.

2025-05-21 19:19 UTC, ankith26 commented on docs/reST/ref/math.rst
> +      the interval (-180, 180].
oh okay. Yeah just another float quirk IG. Not exactly ideal but if the standard atan2 behaviour is this then who are we to judge

2025-05-21 19:23 UTC, ankith26 approved these changes
LGTM, thanks for the PR :sunglasses:

2025-05-24 05:40 UTC, ankith26 commented
Requesting a re-review from @oddbookworm here as they had previously reviewed it.

2025-05-24 13:45 UTC, oddbookworm commented on docs/reST/ref/math.rst
> +      .. versionadded:: 2.5.4
Unfortunately, it took me too long to get back to this before they decided to release a dev version of 2.5.4 (I was asleep). This needs to be updated to 2.5.5
```suggestion
      .. versionadded:: 2.5.5
```

2025-05-24 13:48 UTC, oddbookworm approved these changes
LGTM! 🥳
Sorry it took me so long to get back to this, I've been super busy irl 😢

2025-05-24 13:48 UTC, oddbookworm commented
As soon as everything passes, I'll merge it

2025-05-24 18:47 UTC, merged