Batch and error check allocations
pygame-community/pygame-ce pull request #3224
Opened 2024-11-17 10:48 UTC by Starbuck5

I was looking into optimization opportunities and found some allocation requests (mallocs and PyMem_News) right next to each other, and I thought surely calling the function once will be faster than calling it twice. It is also simpler to check if one buffer failed to allocate, and simpler to free one buffer at the end, rather than 2 or 3.

Looking through the code I also saw that the malloc statements in the blur routines weren't error checked at all, so I fixed that.

Running very favorable microbenchmarks I saw very small performance increases, like 1-3%, or no impact. I'm unsure if running a tight loop over identical calls reduces the execution time burden of malloc / PyMem_New, so maybe performance would be affected differently in a more realistic scenario?

Anyways since this is a small thing I'm not trying to pitch this as a performance PR, instead this is a code quality PR. We want our code to be the best it can be, and I think that reducing the number of allocation calls helps that goal.

2024-11-18 04:49 UTC, ankith26 commented on src_c/transform.c
> +        PyErr_NoMemory();
This function is called within `Py_BEGIN_ALLOW_THREADS`/`Py_END_ALLOW_THREADS` so I don't think we are allowed to call this here as it is python API.

2024-11-18 05:34 UTC, Starbuck5 commented on src_c/transform.c
> +        PyErr_NoMemory();
Good catch! Fixed.

2024-11-18 05:35 UTC, ankith26 approved these changes
LGTM, thanks for the PR :tada:

2024-11-18 09:38 UTC, bilhox requested changes
LGTM, just a little thing to fix, but otherwise it seems fair.

2024-11-19 22:19 UTC, bilhox approved these changes
LGTM

2024-11-19 22:19 UTC, merged