Utility Window implementation.
pygame-community/pygame-ce pull request #3226
Opened 2024-11-19 12:01 UTC by gresm

Adds ``pygame.window.Window(utility=True)`` which makes the window not appear in the taskbar (+``pygame.window.Window.utility`` to get if this option is enabled for the window).
Note: SDL might not support this for all platforms (macOS?).

2024-11-19 12:24 UTC, damusss requested changes

2024-11-19 12:24 UTC, damusss commented on docs/reST/ref/window.rst
> +      ``True`` if the window doesn't appear in the task bar, ``False`` otherwise
If it's true it's not guaranteed to work on all platforms then it should be noted somehow I think.

2024-11-19 14:47 UTC, gresm commented on docs/reST/ref/window.rst
> +      ``True`` if the window doesn't appear in the task bar, ``False`` otherwise
On some platforms this will fail silently. It's a good idea to write about that, but I don't have a comprehensive list for which platforms will this work.

2024-11-19 15:00 UTC, damusss commented on docs/reST/ref/window.rst
> +      ``True`` if the window doesn't appear in the task bar, ``False`` otherwise
You should just say it's not guaranteed to behave as expected on all platforms. This will stop people from coming to us if it's not actually hidden in the taskbar (or if they do, we can point out that it was written all along)

2024-11-19 15:01 UTC, gresm commented on docs/reST/ref/window.rst
> +      ``True`` if the window doesn't appear in the task bar, ``False`` otherwise
Okay, this seems to work only for X11 and Windows.

2024-11-19 15:03 UTC, damusss commented on docs/reST/ref/window.rst
> +   :param bool utility: Create a window that doesn't appear in the task-bar .
```suggestion
   :param bool utility: Create a window that doesn't appear in the task-bar.
```
(it bugs me lmao)

2024-11-19 15:07 UTC, gresm commented on docs/reST/ref/window.rst
> +   :param bool utility: Create a window that doesn't appear in the task-bar .
Weird that this happened, but fixed it.

2024-11-19 15:09 UTC, damusss commented on docs/reST/ref/window.rst
> +      | :sl:`Get if the windos is an utility window`
Other (except for opengl, for no reason) read-only properties of Window append `(**read-only**)` to the :sl:, I believe this could do the same

2024-11-20 02:33 UTC, yunline commented
Since SDL3 uses `SDL_WINDOW_SKIP_TASKBAR` as the flag, is it better to use `skip_taskbar` instead of `utility` as the name of the argument?
I think `skip_taskbar`  is more clear than `utility`

2024-11-20 06:05 UTC, Starbuck5 commented
> Since SDL3 uses `SDL_WINDOW_SKIP_TASKBAR` as the flag, is it better to use `skip_taskbar` instead of `utility` as the name of the argument? I think `skip_taskbar` is more clear than `utility`

I love the way you're thinking but I think it's the other way around. SDL3 is utility, SDL2 is skip taskbar.

2024-11-20 14:11 UTC, gresm commented
@yunline @Starbuck5 So, what's the decision?

2024-11-20 14:20 UTC, damusss commented
> So, what's the decision?

I wasn't asked, but I think it's best to follow sdl3. plus, `utility` is a bit more generic leaving "freedom of conceptual behaviour" to the OS. it just means the window is an utility, which usually results in no taskbar, but the OS can decide what utility means. I vote for utility. Btw you forgot to run `py dev.py all`

2024-11-20 16:29 UTC, ankith26 commented
I also vote for leaving it as `utility` for reasons damus already mentioned, and also the fact that it the name SDL3 picked. Some setups don't have the taskbar at all, and SDL may still do something differently if `utility` is passed.

2024-11-20 16:32 UTC, yunline commented
> So, what's the decision? 

SDL docs said: "window should be treated as a utility window, not showing in the **task bar** and **window list**". 

From the docs we can see "utility window" is a broader concept than "skip taskbar window". They are not the same.

Some window environments don't have a task bar, they use window list

![window list picture copied from somewhere of the internet](https://github.com/user-attachments/assets/3eb77795-18e9-4b31-85e9-6693a567e80b)

Some window environments use dock

![macos-big-sur-dock.jpg](https://github.com/user-attachments/assets/842b79be-0979-4fd8-a4e3-28714e9e1d1d)

Although "skip_task_bar" could be more clear for Windows users, "utility" is more universal on all platforms.

So I vote for "utility".

2024-11-20 17:24 UTC, gresm commented
Then it's ``utility``.

2024-11-21 12:52 UTC, yunline commented on docs/reST/ref/window.rst
> +      .. versionadded:: TBD
```suggestion
      .. versionadded:: 2.5.0
```

2024-11-22 16:35 UTC, ankith26 approved these changes
Normally I would complain about adding new API that isn't cross platform, but in the case of `Window` I guess we already have enough API that isn't cross platform so it shouldn't be out of place.

Thanks for the PR! :tada:

2024-11-22 18:07 UTC, merged